{{{conj[Sd], Fd, Cp[Glu[{gO1}], conj[Sd[{gI1}]], Fd[{gI2}]], FFS, 1/2, 1/2}, 
  {conj[Su], Fu, Cp[Glu[{gO1}], conj[Su[{gI1}]], Fu[{gI2}]], FFS, 1/2, 1/2}, 
  {VG, Glu, Cp[Glu[{gO1}], VG, Glu[{gI2}]], FFV, 3, 1/2}, 
  {bar[Fd], Sd, Cp[Glu[{gO1}], bar[Fd[{gI1}]], Sd[{gI2}]], FFS, 1/2, 1/2}, 
  {bar[Fu], Su, Cp[Glu[{gO1}], bar[Fu[{gI1}]], Su[{gI2}]], FFS, 1/2, 1/2}}, 
 {{bar[Fd], Fd, Cp[VG, bar[Fd[{gI1}]], Fd[{gI2}]], FFV, 1/2, 1/2}, 
  {bar[Fu], Fu, Cp[VG, bar[Fu[{gI1}]], Fu[{gI2}]], FFV, 1/2, 1/2}, 
  {bar[gG], gG, Cp[VG, bar[gG], gG], GGV, 3, 1/2}, 
  {Glu, Glu, Cp[VG, Glu[{gI1}], Glu[{gI2}]], FFV, 3, 1/4}, 
  {conj[Sd], Sd, Cp[VG, conj[Sd[{gI1}]], Sd[{gI2}]], SSV, 1/2, 1/2}, 
  {conj[Su], Su, Cp[VG, conj[Su[{gI1}]], Su[{gI2}]], SSV, 1/2, 1/2}, 
  {VG, VG, Cp[VG, VG, VG], VVV, 3, 1/4}, 
  {conj[Sd], Sd, Cp[VG, VG, conj[Sd[{gI1}]], Sd[{gI1}]], SSVV, 999, 1}, 
  {conj[Su], Su, Cp[VG, VG, conj[Su[{gI1}]], Su[{gI1}]], SSVV, 999, 1}, 
  {VG, VG, Cp[VG, VG, VG, VG], VVVV, 1, 1/2}}, 
 {{bar[Cha], Cha, Cp[VP, bar[Cha[{gI1}]], Cha[{gI2}]], FFV, 1, 1/2}, 
  {bar[Fd], Fd, Cp[VP, bar[Fd[{gI1}]], Fd[{gI2}]], FFV, 3, 1/2}, 
  {bar[Fe], Fe, Cp[VP, bar[Fe[{gI1}]], Fe[{gI2}]], FFV, 1, 1/2}, 
  {bar[Fu], Fu, Cp[VP, bar[Fu[{gI1}]], Fu[{gI2}]], FFV, 3, 1/2}, 
  {bar[gWm], gWm, Cp[VP, bar[gWm], gWm], GGV, 1, 1/2}, 
  {bar[gWmC], gWmC, Cp[VP, bar[gWmC], gWmC], GGV, 1, 1/2}, 
  {conj[Hpm], Hpm, Cp[VP, conj[Hpm[{gI1}]], Hpm[{gI2}]], SSV, 1, 1/2}, 
  {conj[VWm], Hpm, Cp[VP, conj[VWm], Hpm[{gI2}]], SVV, 1, 1}, 
  {conj[Sd], Sd, Cp[VP, conj[Sd[{gI1}]], Sd[{gI2}]], SSV, 3, 1/2}, 
  {conj[Se], Se, Cp[VP, conj[Se[{gI1}]], Se[{gI2}]], SSV, 1, 1/2}, 
  {conj[Su], Su, Cp[VP, conj[Su[{gI1}]], Su[{gI2}]], SSV, 3, 1/2}, 
  {conj[VWm], VWm, Cp[VP, conj[VWm], VWm], VVV, 1, 1/2}, 
  {conj[Hpm], Hpm, Cp[VP, VP, conj[Hpm[{gI1}]], Hpm[{gI1}]], SSVV, 1, 1}, 
  {conj[Sd], Sd, Cp[VP, VP, conj[Sd[{gI1}]], Sd[{gI1}]], SSVV, 3, 1}, 
  {conj[Se], Se, Cp[VP, VP, conj[Se[{gI1}]], Se[{gI1}]], SSVV, 1, 1}, 
  {conj[Su], Su, Cp[VP, VP, conj[Su[{gI1}]], Su[{gI1}]], SSVV, 3, 1}, 
  {conj[VWm], VWm, Cp[VP, VP, conj[VWm], VWm], VVVV, 1, 1}}, 
 {{hh, Ah, Cp[VZ, hh[{gI1}], Ah[{gI2}]], SSV, 1, 1/2}, 
  {bar[Cha], Cha, Cp[VZ, bar[Cha[{gI1}]], Cha[{gI2}]], FFV, 1, 1/2}, 
  {Chi, Chi, Cp[VZ, Chi[{gI1}], Chi[{gI2}]], FFV, 1, 1/4}, 
  {bar[Fd], Fd, Cp[VZ, bar[Fd[{gI1}]], Fd[{gI2}]], FFV, 3, 1/2}, 
  {bar[Fe], Fe, Cp[VZ, bar[Fe[{gI1}]], Fe[{gI2}]], FFV, 1, 1/2}, 
  {bar[Fu], Fu, Cp[VZ, bar[Fu[{gI1}]], Fu[{gI2}]], FFV, 3, 1/2}, 
  {bar[Fv], Fv, Cp[VZ, bar[Fv[{gI1}]], Fv[{gI2}]], FFV, 1, 1/2}, 
  {bar[gWm], gWm, Cp[VZ, bar[gWm], gWm], GGV, 1, 1/2}, 
  {bar[gWmC], gWmC, Cp[VZ, bar[gWmC], gWmC], GGV, 1, 1/2}, 
  {VZ, hh, Cp[VZ, VZ, hh[{gI2}]], SVV, 1, 1/2}, 
  {VZp, hh, Cp[VZ, VZp, hh[{gI2}]], SVV, 1, 1/2}, 
  {conj[Hpm], Hpm, Cp[VZ, conj[Hpm[{gI1}]], Hpm[{gI2}]], SSV, 1, 1/2}, 
  {conj[VWm], Hpm, Cp[VZ, conj[VWm], Hpm[{gI2}]], SVV, 1, 1}, 
  {conj[Sd], Sd, Cp[VZ, conj[Sd[{gI1}]], Sd[{gI2}]], SSV, 3, 1/2}, 
  {conj[Se], Se, Cp[VZ, conj[Se[{gI1}]], Se[{gI2}]], SSV, 1, 1/2}, 
  {conj[Su], Su, Cp[VZ, conj[Su[{gI1}]], Su[{gI2}]], SSV, 3, 1/2}, 
  {conj[Sv], Sv, Cp[VZ, conj[Sv[{gI1}]], Sv[{gI2}]], SSV, 1, 1/2}, 
  {conj[VWm], VWm, Cp[VZ, conj[VWm], VWm], VVV, 1, 1/2}, 
  {Ah, Ah, Cp[VZ, VZ, Ah[{gI1}], Ah[{gI1}]], SSVV, 1, 1/2}, 
  {hh, hh, Cp[VZ, VZ, hh[{gI1}], hh[{gI1}]], SSVV, 1, 1/2}, 
  {conj[Hpm], Hpm, Cp[VZ, VZ, conj[Hpm[{gI1}]], Hpm[{gI1}]], SSVV, 1, 1}, 
  {conj[Sd], Sd, Cp[VZ, VZ, conj[Sd[{gI1}]], Sd[{gI1}]], SSVV, 3, 1}, 
  {conj[Se], Se, Cp[VZ, VZ, conj[Se[{gI1}]], Se[{gI1}]], SSVV, 1, 1}, 
  {conj[Su], Su, Cp[VZ, VZ, conj[Su[{gI1}]], Su[{gI1}]], SSVV, 3, 1}, 
  {conj[Sv], Sv, Cp[VZ, VZ, conj[Sv[{gI1}]], Sv[{gI1}]], SSVV, 1, 1}, 
  {conj[VWm], VWm, Cp[VZ, VZ, conj[VWm], VWm], VVVV, 1, 1}}, 
 {{hh, Ah, Cp[VZp, hh[{gI1}], Ah[{gI2}]], SSV, 1, 1/2}, 
  {bar[Cha], Cha, Cp[VZp, bar[Cha[{gI1}]], Cha[{gI2}]], FFV, 1, 1/2}, 
  {Chi, Chi, Cp[VZp, Chi[{gI1}], Chi[{gI2}]], FFV, 1, 1/4}, 
  {bar[Fd], Fd, Cp[VZp, bar[Fd[{gI1}]], Fd[{gI2}]], FFV, 3, 1/2}, 
  {bar[Fe], Fe, Cp[VZp, bar[Fe[{gI1}]], Fe[{gI2}]], FFV, 1, 1/2}, 
  {bar[Fu], Fu, Cp[VZp, bar[Fu[{gI1}]], Fu[{gI2}]], FFV, 3, 1/2}, 
  {bar[Fv], Fv, Cp[VZp, bar[Fv[{gI1}]], Fv[{gI2}]], FFV, 1, 1/2}, 
  {bar[gWm], gWm, Cp[VZp, bar[gWm], gWm], GGV, 1, 1/2}, 
  {bar[gWmC], gWmC, Cp[VZp, bar[gWmC], gWmC], GGV, 1, 1/2}, 
  {VZ, hh, Cp[VZp, VZ, hh[{gI2}]], SVV, 1, 1/2}, 
  {VZp, hh, Cp[VZp, VZp, hh[{gI2}]], SVV, 1, 1/2}, 
  {conj[Hpm], Hpm, Cp[VZp, conj[Hpm[{gI1}]], Hpm[{gI2}]], SSV, 1, 1/2}, 
  {conj[VWm], Hpm, Cp[VZp, conj[VWm], Hpm[{gI2}]], SVV, 1, 1}, 
  {conj[Sd], Sd, Cp[VZp, conj[Sd[{gI1}]], Sd[{gI2}]], SSV, 3, 1/2}, 
  {conj[Se], Se, Cp[VZp, conj[Se[{gI1}]], Se[{gI2}]], SSV, 1, 1/2}, 
  {conj[Su], Su, Cp[VZp, conj[Su[{gI1}]], Su[{gI2}]], SSV, 3, 1/2}, 
  {conj[Sv], Sv, Cp[VZp, conj[Sv[{gI1}]], Sv[{gI2}]], SSV, 1, 1/2}, 
  {conj[VWm], VWm, Cp[VZp, conj[VWm], VWm], VVV, 1, 1/2}, 
  {Ah, Ah, Cp[VZp, VZp, Ah[{gI1}], Ah[{gI1}]], SSVV, 1, 1/2}, 
  {hh, hh, Cp[VZp, VZp, hh[{gI1}], hh[{gI1}]], SSVV, 1, 1/2}, 
  {conj[Hpm], Hpm, Cp[VZp, VZp, conj[Hpm[{gI1}]], Hpm[{gI1}]], SSVV, 1, 1}, 
  {conj[Sd], Sd, Cp[VZp, VZp, conj[Sd[{gI1}]], Sd[{gI1}]], SSVV, 3, 1}, 
  {conj[Se], Se, Cp[VZp, VZp, conj[Se[{gI1}]], Se[{gI1}]], SSVV, 1, 1}, 
  {conj[Su], Su, Cp[VZp, VZp, conj[Su[{gI1}]], Su[{gI1}]], SSVV, 3, 1}, 
  {conj[Sv], Sv, Cp[VZp, VZp, conj[Sv[{gI1}]], Sv[{gI1}]], SSVV, 1, 1}, 
  {conj[VWm], VWm, Cp[VZp, VZp, conj[VWm], VWm], VVVV, 1, 1}}, 
 {{Hpm, Ah, Cp[conj[VWm], Hpm[{gI1}], Ah[{gI2}]], SSV, 1, 1}, 
  {Chi, Cha, Cp[conj[VWm], Chi[{gI1}], Cha[{gI2}]], FFV, 1, 1}, 
  {bar[Fu], Fd, Cp[conj[VWm], bar[Fu[{gI1}]], Fd[{gI2}]], FFV, 3, 1}, 
  {bar[Fv], Fe, Cp[conj[VWm], bar[Fv[{gI1}]], Fe[{gI2}]], FFV, 1, 1}, 
  {bar[gWmC], gP, Cp[conj[VWm], bar[gWmC], gP], GGV, 1, 1}, 
  {bar[gP], gWm, Cp[conj[VWm], bar[gP], gWm], GGV, 1, 1}, 
  {bar[gZ], gWm, Cp[conj[VWm], bar[gZ], gWm], GGV, 1, 1}, 
  {bar[gZp], gWm, Cp[conj[VWm], bar[gZp], gWm], GGV, 1, 1}, 
  {bar[gWmC], gZ, Cp[conj[VWm], bar[gWmC], gZ], GGV, 1, 1}, 
  {bar[gWmC], gZp, Cp[conj[VWm], bar[gWmC], gZp], GGV, 1, 1}, 
  {Hpm, hh, Cp[conj[VWm], Hpm[{gI1}], hh[{gI2}]], SSV, 1, 1}, 
  {VWm, hh, Cp[conj[VWm], VWm, hh[{gI2}]], SVV, 1, 1}, 
  {VP, Hpm, Cp[conj[VWm], VP, Hpm[{gI2}]], SVV, 1, 1}, 
  {VZ, Hpm, Cp[conj[VWm], VZ, Hpm[{gI2}]], SVV, 1, 1}, 
  {VZp, Hpm, Cp[conj[VWm], VZp, Hpm[{gI2}]], SVV, 1, 1}, 
  {conj[Su], Sd, Cp[conj[VWm], conj[Su[{gI1}]], Sd[{gI2}]], SSV, 3, 1}, 
  {conj[Sv], Se, Cp[conj[VWm], conj[Sv[{gI1}]], Se[{gI2}]], SSV, 1, 1}, 
  {VWm, VP, Cp[conj[VWm], VWm, VP], VVV, 1, 1}, 
  {VZ, VWm, Cp[conj[VWm], VZ, VWm], VVV, 1, 1}, 
  {VZp, VWm, Cp[conj[VWm], VZp, VWm], VVV, 1, 1}, 
  {Ah, Ah, Cp[VWm, conj[VWm], Ah[{gI1}], Ah[{gI1}]], SSVV, 1, 1/2}, 
  {hh, hh, Cp[VWm, conj[VWm], hh[{gI1}], hh[{gI1}]], SSVV, 1, 1/2}, 
  {conj[Hpm], Hpm, Cp[VWm, conj[VWm], conj[Hpm[{gI1}]], Hpm[{gI1}]], SSVV, 1, 
   1}, {conj[Sd], Sd, Cp[VWm, conj[VWm], conj[Sd[{gI1}]], Sd[{gI1}]], SSVV, 
   3, 1}, {conj[Se], Se, Cp[VWm, conj[VWm], conj[Se[{gI1}]], Se[{gI1}]], 
   SSVV, 1, 1}, {conj[Su], Su, Cp[VWm, conj[VWm], conj[Su[{gI1}]], 
    Su[{gI1}]], SSVV, 3, 1}, {conj[Sv], Sv, Cp[VWm, conj[VWm], 
    conj[Sv[{gI1}]], Sv[{gI1}]], SSVV, 1, 1}, 
  {VP, VP, Cp[VWm, conj[VWm], VP, VP], VVVV, 1, 1/2}, 
  {conj[VWm], VWm, Cp[VWm, conj[VWm], conj[VWm], VWm], VVVV, 1, 1}, 
  {VZ, VZ, Cp[VWm, conj[VWm], VZ, VZ], VVVV, 1, 1/2}, 
  {VZp, VZp, Cp[VWm, conj[VWm], VZp, VZp], VVVV, 1, 1/2}}}
