(* ::Package:: *)

ParameterDefinitions = { 

{g1,        { Description -> "Hypercharge-Coupling"}},
{g2,        { Description -> "Left-Coupling"}},
{g3,        { Description -> "Strong-Coupling"}},    
{AlphaS,    {Description -> "Alpha Strong"}},	
{Gf,        { Description -> "Fermi's constant"}},
{aEWinv,    { Description -> "inverse weak coupling constant at mZ"}},

{e,         { Description -> "electric charge"}}, 

{\[Mu],     { Description -> "Mu-parameter"}}, 
{B[\[Mu]],  { Description -> "Bmu-parameter"}}, 

{Qq,        { LaTeX -> "Q_q}",
              Real -> True,
	      OutputName -> Qq,
	      LesHouches -> {XCharge, 1}}}, 
{Ql1,        { LaTeX -> "Q_{l_1}",
              Real -> True,
              OutputName -> Ql1,
	      LesHouches -> {XCharge, 4}}},
{Ql2,        { LaTeX -> "Q_{l_2}",
              Real -> True,
              OutputName -> Ql2,
	      LesHouches -> {XCharge, 5}}},
{Ql3,        { LaTeX -> "Q_{l_3}",
              Real -> True,
              OutputName -> Ql3,
	      LesHouches -> {XCharge, 6}}},
{QHu,        { LaTeX -> "Q_{H_u}",
              Real -> True,
		OutputName -> QHu,
			  LesHouches -> {XCharge, 7}}},
{QHd,        { LaTeX -> "Q_{H_d}",
              Real -> True,
		OutputName -> QHd,
			  LesHouches -> {XCharge, 8}}},
{Qd,        { LaTeX -> "Q_{d}",
              Real -> True,
		OutputName -> Qd,
			  LesHouches -> {XCharge, 9}}},
{Qu,        { LaTeX -> "Q_{u}",
              Real -> True,
		OutputName -> Qu,
			  LesHouches -> {XCharge, 12}}},            
{Qe1,        { LaTeX -> "Q_{e_{1}}",
              Real -> True,
		OutputName -> Qe1,
			  LesHouches -> {XCharge, 15}}},
{Qe2,        { LaTeX -> "Q_{e_{2}}",
              Real -> True,
		OutputName -> Qe2,
			  LesHouches -> {XCharge, 16}}},
{Qe3,        { LaTeX -> "Q_{e_3}",
              Real -> True,
		OutputName -> Qe3,
			  LesHouches -> {XCharge, 17}}},
{Qv1,        { LaTeX -> "Q_{v_1}",        
             Real -> True,          
		OutputName -> Qv1,    
			  LesHouches -> {XCharge, 18}}},
{Qv2,        { LaTeX -> "Q_{v_2}",        
             Real -> True,          
		OutputName -> Qv2,    
			  LesHouches -> {XCharge, 19}}},
{Qv3,        { LaTeX -> "Q_{v_3}",        
             Real -> True,          
		OutputName -> Qv3,    
			  LesHouches -> {XCharge, 20}}},			  
{Qs,        { LaTeX -> "Q_s",
              Real -> True,
		OutputName -> Qs,
			  LesHouches -> {XCharge, 21}}},
{QDx,        { LaTeX -> "Q_{Dx}",        
             Real -> True,          
		OutputName -> QDx,    
			  LesHouches -> {XCharge, 22}}},			  
{QDxbar,        { LaTeX -> "Q_{Dxbar}",
              Real -> True,
		OutputName -> QDxbar,
			  LesHouches -> {XCharge, 23}}},

 
{Ye11,        { Real -> False,
                LesHouches -> Ye11,
                LaTeX -> "Ye11",
                OutputName -> Ye11   }}, 
{Ye22,        { Real -> False,
                LesHouches -> Ye22,
                LaTeX -> "Ye22",
                OutputName -> Ye22   }}, 
{Ye33,        {Real -> False,
              LesHouches -> Ye33,
              LaTeX -> "Ye33",
              OutputName -> Ye33 }}, 
{Yv11,        { Real -> False,
                LesHouches -> Yv11,
                LaTeX -> "Yv11",
                OutputName -> Yv11   }}, 
{Yv22,        { Real -> False,
                LesHouches -> Yv22,
                LaTeX -> "Yv22",
                OutputName -> Yv22   }}, 
{Yv33,        {Real -> False,
              LesHouches -> Yv33,
              LaTeX -> "Yv33",
              OutputName -> Yv33 }},
{Yu,        { Description -> "Up-Yukawa-Coupling"   }}, 
{Yd,        { Description -> "Down-Yukawa-Coupling"   }}, 


{T[Ye11],     { LesHouches -> TYe11,
               LaTeX -> "TYe11",
               OutputName -> TYe11}}, 
{T[Ye22],     { LesHouches -> TYe22,
               LaTeX -> "TYe22",
               OutputName -> TYe22}},
{T[Ye33],     { LesHouches -> TYe33,
               LaTeX -> "TYe33",
               OutputName -> TYe33}},  
{T[Yv11],     { LesHouches -> TYv11,
               LaTeX -> "TYv11",
               OutputName -> TYv11}},  
{T[Yv22],     { LesHouches -> TYv22,
               LaTeX -> "TYv22",
               OutputName -> TYv22}},
{T[Yv33],     { LesHouches -> TYv33,
               LaTeX -> "TYv33",
               OutputName -> TYv33}}, 
{T[Yu],     { Description -> "Trilinear-Up-Coupling"}}, 
{T[Yd],     { Description -> "Trilinear-Down-Coupling"}}, 

{me012,       { LaTeX -> "m^2_{e01}",
                LesHouches -> ME012,
                OutputName -> me012}},
{me022,       { LaTeX -> "m^2_{e02}",
                LesHouches -> ME022,
                OutputName -> me022}},
{me032,       { LaTeX -> "m^2_{e03}",
                LesHouches -> ME032,
                OutputName -> me032}},
{mvR012,       { LaTeX -> "m^2_{vR01}",
                LesHouches -> MVR012,
                OutputName -> mvR012}},
{mvR022,       { LaTeX -> "m^2_{vR02}",
                LesHouches -> MVR022,
                OutputName -> mvR022}},
{mvR032,       { LaTeX -> "m^2_{vR03}",
                LesHouches -> MVR032,
                OutputName -> mvR032}},
{mu2,       { Description -> "Softbreaking right Up-Squark Mass"}},
{md2,       { Description -> "Softbreaking right Down-Squark Mass"}},
{mq2,       { Description -> "Softbreaking left Squark Mass"}},
{ml012,       { LaTeX -> "m^2_{l01}",
                LesHouches -> ML012,
                OutputName -> ml012}},
{ml022,       { LaTeX -> "m^2_{l02}",
                LesHouches -> ML022,
                OutputName -> ml022}},
{ml032,       { LaTeX -> "m^2_{l03}",
                LesHouches -> ML032,
                OutputName -> ml032}},


{mHd2,      { Description -> "Softbreaking Down-Higgs Mass"}}, 
{mHu2,      { Description -> "Softbreaking Up-Higgs Mass"}}, 

{MassB,     { Description -> "Bino Mass parameter"}},
{MassWB,    { Description -> "Wino Mass parameter"}},
{MassG,     { Description -> "Gluino Mass parameter"}},
                           
{vd,        { Description -> "Down-VEV"}}, 
{vu,        { Description -> "Up-VEV"}},       
{v,         { Description -> "EW-VEV"}},
             
{\[Beta],   { Description -> "Pseudo Scalar mixing angle"  }},             
{TanBeta,   { Description -> "Tan Beta" }},              
{\[Alpha],  { Description -> "Scalar mixing angle" }},                          
             
    
{ZD,        { Description -> "Down-Squark-Mixing-Matrix" }},
{ZDX,           { Description -> "Exotics S Mixing-Matrix",
                 LaTeX -> "Z^{DX}",
                 Value -> None,
                 Dependence -> None,
		 OutputName -> ZDX,
	         LesHouches -> ZDX}},

{ZDXL,           { Description -> "Exotics L Mixing-Matrix",
                 LaTeX -> "Z^{DXL}",
                 Value -> None,
                 Dependence -> None,
		 OutputName -> ZDXL,
	         LesHouches -> ZDXL}},
{ZDXR,           { Description -> "Exotics R Mixing-Matrix",
                 LaTeX -> "Z^{DXR}",
                 Value -> None,
                 Dependence -> None,
		 OutputName -> ZDXR,
	         LesHouches -> ZDXR}},             
{ZU,        { Description -> "Up-Squark-Mixing-Matrix"}},             
{ZE,        { Description -> "Slepton-Mixing-Matrix"}}, 
{ZV,        { Description->"Sneutrino Mixing-Matrix"}},   
{ZH,        { Description->"Scalar-Mixing-Matrix", 
              Real -> False, 
              Dependence -> None,
              DependenceNum -> None,
              DependenceOptional -> None,
              LesHouches -> NMHMIX      }},
{ZA,        { Description->"Pseudo-Scalar-Mixing-Matrix", 
               Real ->False,
               Dependence -> None,
              DependenceNum -> None,
              DependenceOptional -> None,
               LesHouches -> NMAMIX     }},
{ZP,        { Description->"Charged-Mixing-Matrix"}},                      
                                          
 
{ZN,        { Description->"Neutralino Mixing-Matrix",
              LesHouches -> NMNMIX   }}, 

{UP,        { Description->"Chargino-plus Mixing-Matrix"}}, 
{UM,        { Description->"Chargino-minus Mixing-Matrix"}}, 

{ZEL,       { Description ->"Left-Lepton-Mixing-Matrix"}},
{ZVL,	    {Description -> "Neutrino-Mixing-Matrix",
             LaTeX->"Z^{V_L}", 
             LesHouches ->  SNULMIX,
             OutputName-> ZVL             
             }},
{ZVR,	    {LaTeX -> "Z^{V_R}",
             LesHouches ->  SNURMIX,
             OutputName-> ZVR }}, 
{ZER,       { Description ->"Right-Lepton-Mixing-Matrix" }},                          
{ZDL,       { Description ->"Left-Down-Mixing-Matrix"}},                       
{ZDR,       { Description ->"Right-Down-Mixing-Matrix"}},              
{ZUL,       { Description ->"Left-Up-Mixing-Matrix"}},                        
{ZUR,       { Description ->"Right-Up-Mixing-Matrix"}},           


{ThetaW,    { Description -> "Weinberg-Angle"}},              

                         
{PhaseGlu,  { Description -> "Gluino-Phase" }},   
                                                                      
{\[Lambda],   { Description -> "Singlet-Higgs-Interaction"   }}, 
{\[Kappa],     { Description -> "Singlet-Exotic-Interaction",
                 LaTeX -> "\\kappa",
		 OutputName -> kap,
		 LesHouches -> ESIXKAPPA}},                              
{T[\[Lambda]],  {Description -> "Softbreaking Singlet-Higgs-Interaction"}},  
{T[\[Kappa]],  { Description -> "Softbreaking Singlet-Exotic-Interaction",
                 LaTeX -> "T_{\\kappa}",
                 Real -> False,
	         Dependence -> None,
                 Value -> None,
		 OutputName -> Tkap,
		 LesHouches -> ESIXTKAPPA}},     
             
{vS,        { LaTeX -> "v_S",
              LesHouches -> {NP, 3},
              OutputName -> vS}},
  
{ms2,       {  LaTeX -> "m^2_{s}",
               LesHouches -> {NP, 4},
               OutputName -> ms2 }},
{mDx2,          { Description -> "Softbreaking Exotics1 Mass",
	         LaTeX -> "m_{X}^2",
		 Real -> False,
                 Dependence -> None,
		 LesHouches -> mDx2,
		 OutputName -> mDx2}},
{mDxbar2,       { Description -> "Softbreaking BarExotics1 Mass",
	         LaTeX -> "m_{\\bar{X}}^2",
		 Real -> False,
		 LesHouches -> mDxBar2,
		 OutputName -> mDxB2}},

(* ------------------------------------------- *)
(* Expression for ThetaWp has to be added!     *)
(* ------------------------------------------- *)

{ZZ, {Description ->   "Photon-Z-Z' Mixing Matrix"}},
{ZW, {Description -> "W Mixing Matrix" }},
{ZfW, {Description ->    "Wino Mixing Matrix"}},

{ThetaWp,  { Description -> "Theta'",
             LaTeX -> "\\Theta_W^{\\prime}",
              DependenceNum -> None  }},
              
              
{gp,       {Description -> "U(1)' Gauge Coupling"}},


{ThetaZ,    { LaTeX -> "\\Theta_Z",
			  OutputName -> ThZ}},

{MassU,    { LaTeX -> "M_U",
             Form -> Scalar,
             OutputName -> M4,
             LesHouches -> {MSOFT,4} }},

{Tep, {LaTeX ->"T^{\\prime}_e",	
       OutputName-> Tep,		
       LesHouches -> TEP}},		

{Tmup, {LaTeX ->"T^{\\prime}_mu",
      OutputName-> Tmup,		
       LesHouches -> TMUP}}		

 }; 
 


