
ParticleDefinitions[GaugeES] = {
      {SdL,  { Description -> "Left Down-Squarks",
                 LaTeX -> "SdL" }},
      {SdR,  { Description -> "Right Down-Squarks",
                 LaTeX -> "SdR" }},
      {SuL,  { Description -> "Left Up-Squarks",
                 LaTeX -> "SuL" }},
      {SuR,  { Description -> "Right Up-Squarks",
                 LaTeX -> "SuR" }},
      {Se01L,  {LaTeX -> "Se01L" }},
      {Se02L,  {LaTeX -> "Se02L" }},
      {Se03L,  {LaTeX -> "Se03L" }}, 
      {Se01R,  { LaTeX -> "Se01R"}},
      {Se02R,  { LaTeX -> "Se02R"}},                          
      {Se03R,  { LaTeX -> "Se03R"}},                         
      {Sv01L,  {LaTeX -> "Sv01L" }},
      {Sv02L,  {LaTeX -> "Sv02L" }},                         
      {Sv03L,  {LaTeX -> "Sv03L" }},
      {Sv01R,  {LaTeX -> "Sv01R" }},
      {Sv02R,  {LaTeX -> "Sv02R" }},                         
      {Sv03R,  {LaTeX -> "Sv03R" }},   
      {SDx1L,        {Description -> "Left SExotics",
                     FeynArtsNr -> 666,
	             LaTeX -> "\\tilde{Dx1}_L",
                     OutputName -> "SDx1L"}},
      {SDxbar1R,     {Description -> "Right SExotics",
	             FeynArtsNr -> 667,
	             LaTeX -> "\\tilde{Dx1}_R",
                     OutputName -> "SDx1R"}},
      {SDx2L,        {Description -> "Left SExotics",
                     FeynArtsNr -> 676,
	             LaTeX -> "\\tilde{Dx2}_L",
                     OutputName -> "SDx2L"}},
      {SDxbar2R,     {Description -> "Right SExotics",
	             FeynArtsNr -> 677,
	             LaTeX -> "\\tilde{Dx2}_R",
                     OutputName -> "SDx2R"}},	     
      {SDx3L,        {Description -> "Left SExotics",
                     FeynArtsNr -> 686,
	             LaTeX -> "\\tilde{Dx3}_L",
                     OutputName -> "SDx3L"}},
      {SDxbar3R,     {Description -> "Right SExotics",
	             FeynArtsNr -> 687,
	             LaTeX -> "\\tilde{Dx3}_R",
                     OutputName -> "SDx3R"}},                      
      {SHd0, { Description -> "Neutral Down-Higgs"}},                         
      {SHdm, { Description -> "Charged Down-Higgs"}}, 
      {SHu0, { Description -> "Neutral Up-Higgs"}},                         
      {SHup, { Description -> "Charged Up-Higgs"}},                                                   
      {VB,   { Description -> "B-Boson"}},                                                   
      {VG,   { Description -> "Gluon"}},          
      {VWB,  { Description -> "W-Bosons"}},          
      {gB,   { Description -> "B-Boson Ghost"}},                                                   
      {gG,   { Description -> "Gluon Ghost" }},          
      {gWB,  { Description -> "W-Boson Ghost"}},    
      {Glu,  { Description -> "Gluino"}},
      {Wino, { Description -> "Wino"}},
      {Bino, { Description -> "Bino"}},                                                                                           
      {H0,   { Description -> "Neutral Higgsinos"}},
      {HC,   { Description -> "Charged Higgsinos"}},  

      {SsR,  { Description -> "Singlet"}},                     
      {FS,   { Description -> "Singlino" }},
      (*  {FDX,        { Description -> "Dirac Exotics",
        	     LaTeX -> "x_1",
		     FeynArtsNr -> 660,
                         OutputName -> "FDx"}}, *)
      {FDx11,        { Description -> "Dirac Left Exotics1",
        	     LaTeX -> "Dx_{11}",
		     FeynArtsNr -> 660,
		     OutputName -> "Dx11"}},
      {FDx12,        { Description -> "Dirac Right Exotics1",
        	     LaTeX -> "Dx_{12}",
		     FeynArtsNr -> 661,
		     OutputName -> "Dx12"}},
      {FDx21,        { Description -> "Dirac Left Exotics2",
        	     LaTeX -> "Dx_{21}",
		     FeynArtsNr -> 670,
		     OutputName -> "Dx21"}},
      {FDx22,        { Description -> "Dirac Right Exotics2",
        	     LaTeX -> "Dx_{22}",
		     FeynArtsNr -> 671,
		     OutputName -> "Dx22"}},
      {FDx31,        { Description -> "Dirac Left Exotics3",
        	     LaTeX -> "Dx_{31}",
		     FeynArtsNr -> 680,
		     OutputName -> "Dx31"}},
      {FDx32,        { Description -> "Dirac Right Exotics3",
        	     LaTeX -> "Dx_{32}",
		     FeynArtsNr -> 681,
		     OutputName -> "Dx32"}},
      {Fd1,  { Description -> "Dirac Left Down-Quark"}},
      {Fd2,  { Description -> "Dirac Right Down-Quark"}},
      {Fu1,  { Description -> "Dirac Left Up-Quark"}},
      {Fu2,  { Description -> "Dirac Right Up-Quark"}},
      {Fe1,  { Description -> "Dirac Left Electron"}},
      {Fe2,  { Description -> "Dirac Right Electron"}},
      {Fv,   { Description -> "Neutrinos" }},
      {VU,   { LaTeX -> "U",
               OutputName -> VU,
               FeynArtsNr -> 10 }},

      {gU,   { LaTeX -> "g_U",
               OutputName -> gU,
               FeynArtsNr -> 10 }},
  
      {FU,  { LaTeX -> "\\tilde{u}_1",
               FeynArtsNr -> 10,
               OutputName -> FU}}
      };
      
      
  ParticleDefinitions[TEMP] = {
    {VZ,   { Description -> "Z-Boson" }}, 
    {gZ,   { Description -> "Z-Boson Ghost" }}
    };
      
      
  ParticleDefinitions[EWSB] = {

     {Sd ,  { Description -> "Down-Squarks"}},
     {Su ,  { Description -> "Up-Squarks"}},   
     {Se ,  { Description -> "Sleptons"}}, 
     {Sv ,  { Description -> "Sneutrinos",
     PDG->{1000012,1000014,1000016,2000012,2000014,2000016} }},   
     {SDX,   { Description -> "SExotics1",
              PDG -> {1000051,2000051,1000052,2000052,1000053,2000053},
              Mass -> Automatic,
              ElectricCharge -> -1/3,
              FeynArtsNr -> 666,
              LaTeX -> "\\tilde{D}_X",
              OutputName -> "SDX"}},                                
     {hh   ,  {  Description -> "Higgs", 
                 PDG -> {25, 35,45},
                 PDG.IX ->{101000001,101000002,101000003} }}, 
     {Ah   ,  {    Description -> "Pseudo-Scalar Higgs",
                 PDG -> {0, 36, 46},
                 PDG.IX ->{0,102000001, 102000002} }},                       
      {Hpm,  { Description -> "Charged Higgs"}},                                                   
      {VP,   { Description -> "Photon"}},
 
      {VZp,    { Description -> "Z'-Boson"}},  
      {gZp,    { Description -> "Z'-Ghost" }},  
      {VZ,   { Description -> "Z-Boson" }}, 
      {gZ,   { Description -> "Z-Boson Ghost" }},  
      {VG,   { Description -> "Gluon" }},          
      {VWm,  { Description -> "W-Boson" }},         
      {gP,   { Description -> "Photon Ghost"}},                                                   
      {gWm,  { Description -> "Negative W-Boson Ghost"}}, 
      {gWmC, { Description -> "Positive W-Boson Ghost" }}, 
      {gG,   { Description -> "Gluon Ghost" }},                 
      {Fd,   { Description -> "Down-Quarks"}},   
      {Fu,   { Description -> "Up-Quarks"}},   
      {Fe,   { Description -> "Leptons" }},
      {Fv,   { Description -> "Neutrinos" }}, 
      {FDX,  { Description->"Exotics1",
    		   PDG -> {51,52,53},
    		   Width -> 0,
    		   Mass -> Automatic,
		   ElectricCharge -> -1/3,
    		   FeynArtsNr -> 666,
    		   LaTeX -> "D_X",
    		   OutputName -> "FDX"}},                                                                    
      {Glu,  { Description -> "Gluino" }},
                 
      {Chi,    {   Description -> "Neutralinos",
                 PDG -> {1000022,1000023,1000025,1000035,1000045,1000055},
                 PDG.IX ->{211000001,211000002,211000003,211000004,211000005,211000006} }},
                 
      {Cha,  { Description -> "Charginos"}}                                                                                          
     
        };    
        
        
        
 WeylFermionAndIndermediate = {
       {FHd0, { Description -> "Neutral Down-Higgsino"}},      
       {FHu0, { Description -> "Neutral Up-Higgsino" }}, 
       {FHdm, { Description -> "Charged Down-Higgsino"}}, 
       {FHup, { Description -> "Charged Up-Higgsino"}},
       {L0,   { Description -> "Neutralino Weyl-Spinor"}},
       {Lm,   { Description -> "Negative Chargino Weyl-Spinor"}},
       {Lp,   { Description -> "Positive Chargino Weyl-Spinor"}}, 
       {fG,   { Description ->"Gluino Weyl-Spinor"}},
       {fWB,  { Description ->"Wino Weyl-Spinor"}},
       {fW0,  { Description ->"Neutral Wino" }},
       {fWm,  { Description ->"Negative Wino"}},                 
       {fWp,  { Description ->"Positive Wino"}},                 
       {fB,   { Description ->"Bino Weyl-Spinor"}},    
       {phid, { Description -> "Scalar Down"}},                                                                       
       {phiu, { Description -> "Scalar Up"}}, 
       {sigmad,   { Description -> "Pseudo Scalar Down"}},                                                                                        
       {sigmau,   { Description -> "Pseudo Scalar Up" }},
       {SHd,  { Description -> "Down-Higgs"}},
       {SHu,  { Description -> "Up-Higgs"}},
       {Sl,   { Description -> "Left Slepton" }},
       {Sq,   { Description -> "Left Squark" }},
       {FeL,  { Description -> "Left Electron" }},
       {Fe01R,  { LaTeX -> "Fe01R" }},
       {Fe02R,  { LaTeX -> "Fe02R" }},
       {Fe03R,  { LaTeX -> "Fe03R" }},
       {Fe01L,  { LaTeX -> "Fe01L" }},
       {Fe02L,  { LaTeX -> "Fe02L" }},
       {Fe03L,  { LaTeX -> "Fe03L" }},
       {FdL,  { Description -> "Left Down-Quark" }},
       {FdR,  { Description -> "Right Down-Quark" }},              
       {FuL,  { Description -> "Left Up-Quark" }},
       {FuR,  { Description -> "Right Up-Quark" }},
       {FDx1L, {Description -> "Dx1-fermion component"}},
       {FDx2L, {Description -> "Dx2-fermion component"}},
       {FDx3L, {Description -> "Dx3-fermion component"}},
       {FDxbar1R, {Description -> "Dxbar1-fermion component"}},
       {FDxbar2R, {Description -> "Dxbar2-fermion component"}},
       {FDxbar3R, {Description -> "Dxbar3-fermion component"}},
       {FEL,  { Description -> "Rotated Left Electron" }},
       {FEL,  { Description -> "Rotated Left Electron" }},
       {FER,  { Description -> "Rotated Right Electron" }} ,
       {FDL,  { Description -> "Rotated Left Up-Quark" }},
       {FDR,  { Description -> "Rotated Right Up-Quark" }},              
       {FL,  { Description -> "Rotated Left Down-Quark"}},
       {FUR,  { Description -> "Rotated Right Down-Quark" }},  
       {FDX1L,   { Description -> "Rotated Left Exotics",
                 LaTeX -> "X1_L"}},
       {FDX1R,   { Description->"Rotated Right Exotics",
                 LaTeX -> "X1_L"}},
       {FDX2L,   { Description -> "Rotated Left Exotics2",
                 LaTeX -> "X2_L"}},
       {FDX2R,   { Description->"Rotated Right Exotics2",
                 LaTeX -> "X2_L"}},
       {FDX3L,   { Description -> "Rotated Left Exotics3",
                 LaTeX -> "X3_L"}},
       {FDX3R,   { Description->"Rotated Right Exotics3",
                 LaTeX -> "X3_L"}},                 
       {FHd,  { Description -> "Down-Higgsino" }},
       {FHu,  { Description -> "Up-Higgsino" }},
       {Fl,   { Description -> "Left Leptons"}},
       {Fq,   { Description -> "Left Quarks"}}, 
       {Fv01L,  { LaTeX -> "Fv01L"}},
       {Fv02L,  { LaTeX -> "Fv02L"}}, 
       {Fv03L,  { LaTeX -> "Fv03L"}},
       {Fv01R,  { LaTeX -> "Fv01R"}},
       {Fv02R,  { LaTeX -> "Fv02R"}}, 
       {Fv03R,  { LaTeX -> "Fv03R" }},  
       {FsR,   { Description -> "Weyl Spinor of Singlino"}}, 
       
       {fU,   { LaTeX -> "\\lambda_U" }},
                 
 {phiS,      {Description -> "Scalar Singlet" }}  ,
                 
 {sigmaS,      { Description -> "Pseudo Scalar Singlet"}},


       {e01,    { LaTeX -> "e01" }},
       {e02,    { LaTeX -> "e02" }},
       {e03,    { LaTeX -> "e03" }},
       {vR01,    { LaTeX -> "vR01" }},
       {vR02,    { LaTeX -> "vR02" }},
       {vR03,    { LaTeX -> "vR03" }},
       {d,    { Description -> "Right Down-Quark Superfield" }},                 
       {q,    { Description -> "Left Quark Superfield" }},                 
       {u,    { Description -> "Right Up-Quark Superfield" }},                 
       {l01,    { LaTeX -> "l01" }},  
       {l02,    { LaTeX -> "l02" }}, 
       {l03,    { LaTeX -> "l03" }}, 
       {Dx1,          { Description -> "Left Exotics Superfield",
 		      LaTeX -> "\\hat{Dx1}"}},
       {Dx1bar,       { Description -> "Right Exotics Superfield",
 		      LaTeX -> "\\hat{\\bar{Dx1}}"}},
       {Dx2,          { Description -> "Left Exotics Superfield",
 		      LaTeX -> "\\hat{Dx2}"}},
       {Dx2bar,       { Description -> "Right Exotics Superfield",
  		      LaTeX -> "\\hat{\\bar{Dx2}}"}},
       {Dx3,          { Description -> "Left Exotics Superfield",
		      LaTeX -> "\\hat{Dx3}"}},
       {Dx3bar,       { Description -> "Right Exotics Superfield",
		      LaTeX -> "\\hat{\\bar{Dx3}}"}}, 
       {Hd,   { Description -> "Down-Higgs Superfield"}},                                         
       {Hu,   { Description -> "Up-Higgs Superfield" }},                 
       {s,    { Description -> "Singlet Superfield" }}, 
       {G,    { Description -> "Gluon Superfield" }},                 
       {B,    { Description -> "B Superfield" }},                 
       {WB,   { Description -> "W Superfield" }},
       
       {U,    { LaTeX -> "\\hat{U}"}},
       
       {MassU,    { LaTeX -> "M_Z",
                    Form -> Scalar }},
       {Qq,       {LaTeX -> "Q_q}",
                    Real -> True}},            
       {Ql1,        {LaTeX -> "Q_{l_1}",
                     Real -> True}},
       {Ql2,        {LaTeX -> "Q_{l_2}",
                     Real -> True}},
       {Ql3,        {LaTeX -> "Q_{l_3}",
                     Real -> True}},
       {QHu,        {LaTeX -> "Q_{H_u}",
                     Real -> True}},
       {QHd,        {LaTeX -> "Q_{H_d}",
                     Real -> True}},
       {Qd,        {LaTeX -> "Q_{d}",
                     Real -> True}},
       {Qu,        {LaTeX -> "Q_{u}",
                     Real -> True}},            
       {Qe1,        {LaTeX -> "Q_{e_{1}}",
                     Real -> True}},
       {Qe2,        {LaTeX -> "Q_{e_{2}}",
                     Real -> True}},
       {Qe3,        {LaTeX -> "Q_{e_3}",
                     Real -> True}},
       {Qv1,         {LaTeX -> "Q_{v_1}",
                     Real -> True}},
       {Qv2,         {LaTeX -> "Q_{v_2}",
                     Real -> True}},
       {Qv3,         {LaTeX -> "Q_{v_3}",
                     Real -> True}},
			  

       {Qs,        {LaTeX -> "Q_s",
                    Real -> True}},

       {QDx,         {LaTeX -> "Q_{Dx}",
                     Real -> True}},
			  

       {QDxbar,        {LaTeX -> "Q_{Dxbar}",
                    Real -> True}}
   
      
        };       


