! --------------------------------------------------------------------------------
! Autogenerated by the happy scrappy WHIZARD model file generator on 2/10/2021 , 0:41:44
! WHIZARD interface svn revision info: $Id: WOMathematicaInterface.m 3666 2012-01-14 17:03:09Z cnspeckn $
! Code generated for WHIZARD / O'Mega version 2.4.0
! Model name: nonumssm_sarah
! Gauge: Unitarity
! Maximum number of couplings per FORTRAN module: 150
! --------------------------------------------------------------------------------
! 
! --------------------------------------------------------------------------------

module parameters_nonumssm_sarah_cpl14
use parameters_nonumssm_sarah_global
use parameters_nonumssm_sarah_local
implicit none

contains

subroutine calc_cpl14
   G_sv1_se3c_a_1_wm_1 = (0,-1)*(((0,-1)*g1*g2*ZE31*conjg(ZV11)*Cos(TW))/Sqrt ( &
      2._default) - ((0,1)*g1*g2*ZE32*conjg(ZV12)*Cos(TW))/Sqrt (2._default) - ((0,1)*g1*g2*ZE33 &
      *conjg(ZV13)*Cos(TW))/Sqrt (2._default))
   G_sv1_se4c_a_1_wm_1 = (0,-1)*(((0,-1)*g1*g2*ZE41*conjg(ZV11)*Cos(TW))/Sqrt ( &
      2._default) - ((0,1)*g1*g2*ZE42*conjg(ZV12)*Cos(TW))/Sqrt (2._default) - ((0,1)*g1*g2*ZE43 &
      *conjg(ZV13)*Cos(TW))/Sqrt (2._default))
   G_sv1_se5c_a_1_wm_1 = (0,-1)*(((0,-1)*g1*g2*ZE51*conjg(ZV11)*Cos(TW))/Sqrt ( &
      2._default) - ((0,1)*g1*g2*ZE52*conjg(ZV12)*Cos(TW))/Sqrt (2._default) - ((0,1)*g1*g2*ZE53 &
      *conjg(ZV13)*Cos(TW))/Sqrt (2._default))
   G_sv1_se6c_a_1_wm_1 = (0,-1)*(((0,-1)*g1*g2*ZE61*conjg(ZV11)*Cos(TW))/Sqrt ( &
      2._default) - ((0,1)*g1*g2*ZE62*conjg(ZV12)*Cos(TW))/Sqrt (2._default) - ((0,1)*g1*g2*ZE63 &
      *conjg(ZV13)*Cos(TW))/Sqrt (2._default))
   G_sv2_se1c_a_1_wm_1 = (0,-1)*(((0,-1)*g1*g2*ZE11*conjg(ZV21)*Cos(TW))/Sqrt ( &
      2._default) - ((0,1)*g1*g2*ZE12*conjg(ZV22)*Cos(TW))/Sqrt (2._default) - ((0,1)*g1*g2*ZE13 &
      *conjg(ZV23)*Cos(TW))/Sqrt (2._default))
   G_sv2_se2c_a_1_wm_1 = (0,-1)*(((0,-1)*g1*g2*ZE21*conjg(ZV21)*Cos(TW))/Sqrt ( &
      2._default) - ((0,1)*g1*g2*ZE22*conjg(ZV22)*Cos(TW))/Sqrt (2._default) - ((0,1)*g1*g2*ZE23 &
      *conjg(ZV23)*Cos(TW))/Sqrt (2._default))
   G_sv2_se3c_a_1_wm_1 = (0,-1)*(((0,-1)*g1*g2*ZE31*conjg(ZV21)*Cos(TW))/Sqrt ( &
      2._default) - ((0,1)*g1*g2*ZE32*conjg(ZV22)*Cos(TW))/Sqrt (2._default) - ((0,1)*g1*g2*ZE33 &
      *conjg(ZV23)*Cos(TW))/Sqrt (2._default))
   G_sv2_se4c_a_1_wm_1 = (0,-1)*(((0,-1)*g1*g2*ZE41*conjg(ZV21)*Cos(TW))/Sqrt ( &
      2._default) - ((0,1)*g1*g2*ZE42*conjg(ZV22)*Cos(TW))/Sqrt (2._default) - ((0,1)*g1*g2*ZE43 &
      *conjg(ZV23)*Cos(TW))/Sqrt (2._default))
   G_sv2_se5c_a_1_wm_1 = (0,-1)*(((0,-1)*g1*g2*ZE51*conjg(ZV21)*Cos(TW))/Sqrt ( &
      2._default) - ((0,1)*g1*g2*ZE52*conjg(ZV22)*Cos(TW))/Sqrt (2._default) - ((0,1)*g1*g2*ZE53 &
      *conjg(ZV23)*Cos(TW))/Sqrt (2._default))
   G_sv2_se6c_a_1_wm_1 = (0,-1)*(((0,-1)*g1*g2*ZE61*conjg(ZV21)*Cos(TW))/Sqrt ( &
      2._default) - ((0,1)*g1*g2*ZE62*conjg(ZV22)*Cos(TW))/Sqrt (2._default) - ((0,1)*g1*g2*ZE63 &
      *conjg(ZV23)*Cos(TW))/Sqrt (2._default))
   G_sv3_se1c_a_1_wm_1 = (0,-1)*(((0,-1)*g1*g2*ZE11*conjg(ZV31)*Cos(TW))/Sqrt ( &
      2._default) - ((0,1)*g1*g2*ZE12*conjg(ZV32)*Cos(TW))/Sqrt (2._default) - ((0,1)*g1*g2*ZE13 &
      *conjg(ZV33)*Cos(TW))/Sqrt (2._default))
   G_sv3_se2c_a_1_wm_1 = (0,-1)*(((0,-1)*g1*g2*ZE21*conjg(ZV31)*Cos(TW))/Sqrt ( &
      2._default) - ((0,1)*g1*g2*ZE22*conjg(ZV32)*Cos(TW))/Sqrt (2._default) - ((0,1)*g1*g2*ZE23 &
      *conjg(ZV33)*Cos(TW))/Sqrt (2._default))
   G_sv3_se3c_a_1_wm_1 = (0,-1)*(((0,-1)*g1*g2*ZE31*conjg(ZV31)*Cos(TW))/Sqrt ( &
      2._default) - ((0,1)*g1*g2*ZE32*conjg(ZV32)*Cos(TW))/Sqrt (2._default) - ((0,1)*g1*g2*ZE33 &
      *conjg(ZV33)*Cos(TW))/Sqrt (2._default))
   G_sv3_se4c_a_1_wm_1 = (0,-1)*(((0,-1)*g1*g2*ZE41*conjg(ZV31)*Cos(TW))/Sqrt ( &
      2._default) - ((0,1)*g1*g2*ZE42*conjg(ZV32)*Cos(TW))/Sqrt (2._default) - ((0,1)*g1*g2*ZE43 &
      *conjg(ZV33)*Cos(TW))/Sqrt (2._default))
   G_sv3_se5c_a_1_wm_1 = (0,-1)*(((0,-1)*g1*g2*ZE51*conjg(ZV31)*Cos(TW))/Sqrt ( &
      2._default) - ((0,1)*g1*g2*ZE52*conjg(ZV32)*Cos(TW))/Sqrt (2._default) - ((0,1)*g1*g2*ZE53 &
      *conjg(ZV33)*Cos(TW))/Sqrt (2._default))
   G_sv3_se6c_a_1_wm_1 = (0,-1)*(((0,-1)*g1*g2*ZE61*conjg(ZV31)*Cos(TW))/Sqrt ( &
      2._default) - ((0,1)*g1*g2*ZE62*conjg(ZV32)*Cos(TW))/Sqrt (2._default) - ((0,1)*g1*g2*ZE63 &
      *conjg(ZV33)*Cos(TW))/Sqrt (2._default))
   G_sv1_se1c_wm_1_z_1 = (0,-1)*(((0,1)*g1*g2*ZE11*conjg(ZV11)*Cos(TWp)*Sin(TW))/ &
      Sqrt (2._default) + ((0,1)*g1*g2*ZE12*conjg(ZV12)*Cos(TWp)*Sin(TW))/Sqrt (2._default &
      ) + ((0,1)*g1*g2*ZE13*conjg(ZV13)*Cos(TWp)*Sin(TW))/Sqrt (2._default) + (0,1)*Sqrt ( &
      2._default)*g2*gp*Ql1*ZE11*conjg(ZV11)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE12* &
      conjg(ZV12)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql3*ZE13*conjg(ZV13)*Sin(TWp))
   G_sv1_se2c_wm_1_z_1 = (0,-1)*(((0,1)*g1*g2*ZE21*conjg(ZV11)*Cos(TWp)*Sin(TW))/ &
      Sqrt (2._default) + ((0,1)*g1*g2*ZE22*conjg(ZV12)*Cos(TWp)*Sin(TW))/Sqrt (2._default &
      ) + ((0,1)*g1*g2*ZE23*conjg(ZV13)*Cos(TWp)*Sin(TW))/Sqrt (2._default) + (0,1)*Sqrt ( &
      2._default)*g2*gp*Ql1*ZE21*conjg(ZV11)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE22* &
      conjg(ZV12)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql3*ZE23*conjg(ZV13)*Sin(TWp))
   G_sv1_se3c_wm_1_z_1 = (0,-1)*(((0,1)*g1*g2*ZE31*conjg(ZV11)*Cos(TWp)*Sin(TW))/ &
      Sqrt (2._default) + ((0,1)*g1*g2*ZE32*conjg(ZV12)*Cos(TWp)*Sin(TW))/Sqrt (2._default &
      ) + ((0,1)*g1*g2*ZE33*conjg(ZV13)*Cos(TWp)*Sin(TW))/Sqrt (2._default) + (0,1)*Sqrt ( &
      2._default)*g2*gp*Ql1*ZE31*conjg(ZV11)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE32* &
      conjg(ZV12)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql3*ZE33*conjg(ZV13)*Sin(TWp))
   G_sv1_se4c_wm_1_z_1 = (0,-1)*(((0,1)*g1*g2*ZE41*conjg(ZV11)*Cos(TWp)*Sin(TW))/ &
      Sqrt (2._default) + ((0,1)*g1*g2*ZE42*conjg(ZV12)*Cos(TWp)*Sin(TW))/Sqrt (2._default &
      ) + ((0,1)*g1*g2*ZE43*conjg(ZV13)*Cos(TWp)*Sin(TW))/Sqrt (2._default) + (0,1)*Sqrt ( &
      2._default)*g2*gp*Ql1*ZE41*conjg(ZV11)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE42* &
      conjg(ZV12)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql3*ZE43*conjg(ZV13)*Sin(TWp))
   G_sv1_se5c_wm_1_z_1 = (0,-1)*(((0,1)*g1*g2*ZE51*conjg(ZV11)*Cos(TWp)*Sin(TW))/ &
      Sqrt (2._default) + ((0,1)*g1*g2*ZE52*conjg(ZV12)*Cos(TWp)*Sin(TW))/Sqrt (2._default &
      ) + ((0,1)*g1*g2*ZE53*conjg(ZV13)*Cos(TWp)*Sin(TW))/Sqrt (2._default) + (0,1)*Sqrt ( &
      2._default)*g2*gp*Ql1*ZE51*conjg(ZV11)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE52* &
      conjg(ZV12)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql3*ZE53*conjg(ZV13)*Sin(TWp))
   G_sv1_se6c_wm_1_z_1 = (0,-1)*(((0,1)*g1*g2*ZE61*conjg(ZV11)*Cos(TWp)*Sin(TW))/ &
      Sqrt (2._default) + ((0,1)*g1*g2*ZE62*conjg(ZV12)*Cos(TWp)*Sin(TW))/Sqrt (2._default &
      ) + ((0,1)*g1*g2*ZE63*conjg(ZV13)*Cos(TWp)*Sin(TW))/Sqrt (2._default) + (0,1)*Sqrt ( &
      2._default)*g2*gp*Ql1*ZE61*conjg(ZV11)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE62* &
      conjg(ZV12)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql3*ZE63*conjg(ZV13)*Sin(TWp))
   G_sv2_se1c_wm_1_z_1 = (0,-1)*(((0,1)*g1*g2*ZE11*conjg(ZV21)*Cos(TWp)*Sin(TW))/ &
      Sqrt (2._default) + ((0,1)*g1*g2*ZE12*conjg(ZV22)*Cos(TWp)*Sin(TW))/Sqrt (2._default &
      ) + ((0,1)*g1*g2*ZE13*conjg(ZV23)*Cos(TWp)*Sin(TW))/Sqrt (2._default) + (0,1)*Sqrt ( &
      2._default)*g2*gp*Ql1*ZE11*conjg(ZV21)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE12* &
      conjg(ZV22)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql3*ZE13*conjg(ZV23)*Sin(TWp))
   G_sv2_se2c_wm_1_z_1 = (0,-1)*(((0,1)*g1*g2*ZE21*conjg(ZV21)*Cos(TWp)*Sin(TW))/ &
      Sqrt (2._default) + ((0,1)*g1*g2*ZE22*conjg(ZV22)*Cos(TWp)*Sin(TW))/Sqrt (2._default &
      ) + ((0,1)*g1*g2*ZE23*conjg(ZV23)*Cos(TWp)*Sin(TW))/Sqrt (2._default) + (0,1)*Sqrt ( &
      2._default)*g2*gp*Ql1*ZE21*conjg(ZV21)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE22* &
      conjg(ZV22)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql3*ZE23*conjg(ZV23)*Sin(TWp))
   G_sv2_se3c_wm_1_z_1 = (0,-1)*(((0,1)*g1*g2*ZE31*conjg(ZV21)*Cos(TWp)*Sin(TW))/ &
      Sqrt (2._default) + ((0,1)*g1*g2*ZE32*conjg(ZV22)*Cos(TWp)*Sin(TW))/Sqrt (2._default &
      ) + ((0,1)*g1*g2*ZE33*conjg(ZV23)*Cos(TWp)*Sin(TW))/Sqrt (2._default) + (0,1)*Sqrt ( &
      2._default)*g2*gp*Ql1*ZE31*conjg(ZV21)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE32* &
      conjg(ZV22)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql3*ZE33*conjg(ZV23)*Sin(TWp))
   G_sv2_se4c_wm_1_z_1 = (0,-1)*(((0,1)*g1*g2*ZE41*conjg(ZV21)*Cos(TWp)*Sin(TW))/ &
      Sqrt (2._default) + ((0,1)*g1*g2*ZE42*conjg(ZV22)*Cos(TWp)*Sin(TW))/Sqrt (2._default &
      ) + ((0,1)*g1*g2*ZE43*conjg(ZV23)*Cos(TWp)*Sin(TW))/Sqrt (2._default) + (0,1)*Sqrt ( &
      2._default)*g2*gp*Ql1*ZE41*conjg(ZV21)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE42* &
      conjg(ZV22)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql3*ZE43*conjg(ZV23)*Sin(TWp))
   G_sv2_se5c_wm_1_z_1 = (0,-1)*(((0,1)*g1*g2*ZE51*conjg(ZV21)*Cos(TWp)*Sin(TW))/ &
      Sqrt (2._default) + ((0,1)*g1*g2*ZE52*conjg(ZV22)*Cos(TWp)*Sin(TW))/Sqrt (2._default &
      ) + ((0,1)*g1*g2*ZE53*conjg(ZV23)*Cos(TWp)*Sin(TW))/Sqrt (2._default) + (0,1)*Sqrt ( &
      2._default)*g2*gp*Ql1*ZE51*conjg(ZV21)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE52* &
      conjg(ZV22)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql3*ZE53*conjg(ZV23)*Sin(TWp))
   G_sv2_se6c_wm_1_z_1 = (0,-1)*(((0,1)*g1*g2*ZE61*conjg(ZV21)*Cos(TWp)*Sin(TW))/ &
      Sqrt (2._default) + ((0,1)*g1*g2*ZE62*conjg(ZV22)*Cos(TWp)*Sin(TW))/Sqrt (2._default &
      ) + ((0,1)*g1*g2*ZE63*conjg(ZV23)*Cos(TWp)*Sin(TW))/Sqrt (2._default) + (0,1)*Sqrt ( &
      2._default)*g2*gp*Ql1*ZE61*conjg(ZV21)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE62* &
      conjg(ZV22)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql3*ZE63*conjg(ZV23)*Sin(TWp))
   G_sv3_se1c_wm_1_z_1 = (0,-1)*(((0,1)*g1*g2*ZE11*conjg(ZV31)*Cos(TWp)*Sin(TW))/ &
      Sqrt (2._default) + ((0,1)*g1*g2*ZE12*conjg(ZV32)*Cos(TWp)*Sin(TW))/Sqrt (2._default &
      ) + ((0,1)*g1*g2*ZE13*conjg(ZV33)*Cos(TWp)*Sin(TW))/Sqrt (2._default) + (0,1)*Sqrt ( &
      2._default)*g2*gp*Ql1*ZE11*conjg(ZV31)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE12* &
      conjg(ZV32)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql3*ZE13*conjg(ZV33)*Sin(TWp))
   G_sv3_se2c_wm_1_z_1 = (0,-1)*(((0,1)*g1*g2*ZE21*conjg(ZV31)*Cos(TWp)*Sin(TW))/ &
      Sqrt (2._default) + ((0,1)*g1*g2*ZE22*conjg(ZV32)*Cos(TWp)*Sin(TW))/Sqrt (2._default &
      ) + ((0,1)*g1*g2*ZE23*conjg(ZV33)*Cos(TWp)*Sin(TW))/Sqrt (2._default) + (0,1)*Sqrt ( &
      2._default)*g2*gp*Ql1*ZE21*conjg(ZV31)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE22* &
      conjg(ZV32)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql3*ZE23*conjg(ZV33)*Sin(TWp))
   G_sv3_se3c_wm_1_z_1 = (0,-1)*(((0,1)*g1*g2*ZE31*conjg(ZV31)*Cos(TWp)*Sin(TW))/ &
      Sqrt (2._default) + ((0,1)*g1*g2*ZE32*conjg(ZV32)*Cos(TWp)*Sin(TW))/Sqrt (2._default &
      ) + ((0,1)*g1*g2*ZE33*conjg(ZV33)*Cos(TWp)*Sin(TW))/Sqrt (2._default) + (0,1)*Sqrt ( &
      2._default)*g2*gp*Ql1*ZE31*conjg(ZV31)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE32* &
      conjg(ZV32)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql3*ZE33*conjg(ZV33)*Sin(TWp))
   G_sv3_se4c_wm_1_z_1 = (0,-1)*(((0,1)*g1*g2*ZE41*conjg(ZV31)*Cos(TWp)*Sin(TW))/ &
      Sqrt (2._default) + ((0,1)*g1*g2*ZE42*conjg(ZV32)*Cos(TWp)*Sin(TW))/Sqrt (2._default &
      ) + ((0,1)*g1*g2*ZE43*conjg(ZV33)*Cos(TWp)*Sin(TW))/Sqrt (2._default) + (0,1)*Sqrt ( &
      2._default)*g2*gp*Ql1*ZE41*conjg(ZV31)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE42* &
      conjg(ZV32)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql3*ZE43*conjg(ZV33)*Sin(TWp))
   G_sv3_se5c_wm_1_z_1 = (0,-1)*(((0,1)*g1*g2*ZE51*conjg(ZV31)*Cos(TWp)*Sin(TW))/ &
      Sqrt (2._default) + ((0,1)*g1*g2*ZE52*conjg(ZV32)*Cos(TWp)*Sin(TW))/Sqrt (2._default &
      ) + ((0,1)*g1*g2*ZE53*conjg(ZV33)*Cos(TWp)*Sin(TW))/Sqrt (2._default) + (0,1)*Sqrt ( &
      2._default)*g2*gp*Ql1*ZE51*conjg(ZV31)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE52* &
      conjg(ZV32)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql3*ZE53*conjg(ZV33)*Sin(TWp))
   G_sv3_se6c_wm_1_z_1 = (0,-1)*(((0,1)*g1*g2*ZE61*conjg(ZV31)*Cos(TWp)*Sin(TW))/ &
      Sqrt (2._default) + ((0,1)*g1*g2*ZE62*conjg(ZV32)*Cos(TWp)*Sin(TW))/Sqrt (2._default &
      ) + ((0,1)*g1*g2*ZE63*conjg(ZV33)*Cos(TWp)*Sin(TW))/Sqrt (2._default) + (0,1)*Sqrt ( &
      2._default)*g2*gp*Ql1*ZE61*conjg(ZV31)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE62* &
      conjg(ZV32)*Sin(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql3*ZE63*conjg(ZV33)*Sin(TWp))
   G_sv1_se1c_wm_1_zp_1 = (0,-1)*((0,1)*Sqrt (2._default)*g2*gp*Ql1*ZE11*conjg(ZV11 &
      )*Cos(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE12*conjg(ZV12)*Cos(TWp) + (0,1)* &
      Sqrt (2._default)*g2*gp*Ql3*ZE13*conjg(ZV13)*Cos(TWp) - ((0,1)*g1*g2*ZE11*conjg(ZV11 &
      )*Sin(TW)*Sin(TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE12*conjg(ZV12)*Sin(TW)*Sin( &
      TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE13*conjg(ZV13)*Sin(TW)*Sin(TWp))/Sqrt ( &
      2._default))
   G_sv1_se2c_wm_1_zp_1 = (0,-1)*((0,1)*Sqrt (2._default)*g2*gp*Ql1*ZE21*conjg(ZV11 &
      )*Cos(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE22*conjg(ZV12)*Cos(TWp) + (0,1)* &
      Sqrt (2._default)*g2*gp*Ql3*ZE23*conjg(ZV13)*Cos(TWp) - ((0,1)*g1*g2*ZE21*conjg(ZV11 &
      )*Sin(TW)*Sin(TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE22*conjg(ZV12)*Sin(TW)*Sin( &
      TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE23*conjg(ZV13)*Sin(TW)*Sin(TWp))/Sqrt ( &
      2._default))
   G_sv1_se3c_wm_1_zp_1 = (0,-1)*((0,1)*Sqrt (2._default)*g2*gp*Ql1*ZE31*conjg(ZV11 &
      )*Cos(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE32*conjg(ZV12)*Cos(TWp) + (0,1)* &
      Sqrt (2._default)*g2*gp*Ql3*ZE33*conjg(ZV13)*Cos(TWp) - ((0,1)*g1*g2*ZE31*conjg(ZV11 &
      )*Sin(TW)*Sin(TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE32*conjg(ZV12)*Sin(TW)*Sin( &
      TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE33*conjg(ZV13)*Sin(TW)*Sin(TWp))/Sqrt ( &
      2._default))
   G_sv1_se4c_wm_1_zp_1 = (0,-1)*((0,1)*Sqrt (2._default)*g2*gp*Ql1*ZE41*conjg(ZV11 &
      )*Cos(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE42*conjg(ZV12)*Cos(TWp) + (0,1)* &
      Sqrt (2._default)*g2*gp*Ql3*ZE43*conjg(ZV13)*Cos(TWp) - ((0,1)*g1*g2*ZE41*conjg(ZV11 &
      )*Sin(TW)*Sin(TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE42*conjg(ZV12)*Sin(TW)*Sin( &
      TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE43*conjg(ZV13)*Sin(TW)*Sin(TWp))/Sqrt ( &
      2._default))
   G_sv1_se5c_wm_1_zp_1 = (0,-1)*((0,1)*Sqrt (2._default)*g2*gp*Ql1*ZE51*conjg(ZV11 &
      )*Cos(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE52*conjg(ZV12)*Cos(TWp) + (0,1)* &
      Sqrt (2._default)*g2*gp*Ql3*ZE53*conjg(ZV13)*Cos(TWp) - ((0,1)*g1*g2*ZE51*conjg(ZV11 &
      )*Sin(TW)*Sin(TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE52*conjg(ZV12)*Sin(TW)*Sin( &
      TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE53*conjg(ZV13)*Sin(TW)*Sin(TWp))/Sqrt ( &
      2._default))
   G_sv1_se6c_wm_1_zp_1 = (0,-1)*((0,1)*Sqrt (2._default)*g2*gp*Ql1*ZE61*conjg(ZV11 &
      )*Cos(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE62*conjg(ZV12)*Cos(TWp) + (0,1)* &
      Sqrt (2._default)*g2*gp*Ql3*ZE63*conjg(ZV13)*Cos(TWp) - ((0,1)*g1*g2*ZE61*conjg(ZV11 &
      )*Sin(TW)*Sin(TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE62*conjg(ZV12)*Sin(TW)*Sin( &
      TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE63*conjg(ZV13)*Sin(TW)*Sin(TWp))/Sqrt ( &
      2._default))
   G_sv2_se1c_wm_1_zp_1 = (0,-1)*((0,1)*Sqrt (2._default)*g2*gp*Ql1*ZE11*conjg(ZV21 &
      )*Cos(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE12*conjg(ZV22)*Cos(TWp) + (0,1)* &
      Sqrt (2._default)*g2*gp*Ql3*ZE13*conjg(ZV23)*Cos(TWp) - ((0,1)*g1*g2*ZE11*conjg(ZV21 &
      )*Sin(TW)*Sin(TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE12*conjg(ZV22)*Sin(TW)*Sin( &
      TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE13*conjg(ZV23)*Sin(TW)*Sin(TWp))/Sqrt ( &
      2._default))
   G_sv2_se2c_wm_1_zp_1 = (0,-1)*((0,1)*Sqrt (2._default)*g2*gp*Ql1*ZE21*conjg(ZV21 &
      )*Cos(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE22*conjg(ZV22)*Cos(TWp) + (0,1)* &
      Sqrt (2._default)*g2*gp*Ql3*ZE23*conjg(ZV23)*Cos(TWp) - ((0,1)*g1*g2*ZE21*conjg(ZV21 &
      )*Sin(TW)*Sin(TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE22*conjg(ZV22)*Sin(TW)*Sin( &
      TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE23*conjg(ZV23)*Sin(TW)*Sin(TWp))/Sqrt ( &
      2._default))
   G_sv2_se3c_wm_1_zp_1 = (0,-1)*((0,1)*Sqrt (2._default)*g2*gp*Ql1*ZE31*conjg(ZV21 &
      )*Cos(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE32*conjg(ZV22)*Cos(TWp) + (0,1)* &
      Sqrt (2._default)*g2*gp*Ql3*ZE33*conjg(ZV23)*Cos(TWp) - ((0,1)*g1*g2*ZE31*conjg(ZV21 &
      )*Sin(TW)*Sin(TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE32*conjg(ZV22)*Sin(TW)*Sin( &
      TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE33*conjg(ZV23)*Sin(TW)*Sin(TWp))/Sqrt ( &
      2._default))
   G_sv2_se4c_wm_1_zp_1 = (0,-1)*((0,1)*Sqrt (2._default)*g2*gp*Ql1*ZE41*conjg(ZV21 &
      )*Cos(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE42*conjg(ZV22)*Cos(TWp) + (0,1)* &
      Sqrt (2._default)*g2*gp*Ql3*ZE43*conjg(ZV23)*Cos(TWp) - ((0,1)*g1*g2*ZE41*conjg(ZV21 &
      )*Sin(TW)*Sin(TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE42*conjg(ZV22)*Sin(TW)*Sin( &
      TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE43*conjg(ZV23)*Sin(TW)*Sin(TWp))/Sqrt ( &
      2._default))
   G_sv2_se5c_wm_1_zp_1 = (0,-1)*((0,1)*Sqrt (2._default)*g2*gp*Ql1*ZE51*conjg(ZV21 &
      )*Cos(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE52*conjg(ZV22)*Cos(TWp) + (0,1)* &
      Sqrt (2._default)*g2*gp*Ql3*ZE53*conjg(ZV23)*Cos(TWp) - ((0,1)*g1*g2*ZE51*conjg(ZV21 &
      )*Sin(TW)*Sin(TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE52*conjg(ZV22)*Sin(TW)*Sin( &
      TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE53*conjg(ZV23)*Sin(TW)*Sin(TWp))/Sqrt ( &
      2._default))
   G_sv2_se6c_wm_1_zp_1 = (0,-1)*((0,1)*Sqrt (2._default)*g2*gp*Ql1*ZE61*conjg(ZV21 &
      )*Cos(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE62*conjg(ZV22)*Cos(TWp) + (0,1)* &
      Sqrt (2._default)*g2*gp*Ql3*ZE63*conjg(ZV23)*Cos(TWp) - ((0,1)*g1*g2*ZE61*conjg(ZV21 &
      )*Sin(TW)*Sin(TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE62*conjg(ZV22)*Sin(TW)*Sin( &
      TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE63*conjg(ZV23)*Sin(TW)*Sin(TWp))/Sqrt ( &
      2._default))
   G_sv3_se1c_wm_1_zp_1 = (0,-1)*((0,1)*Sqrt (2._default)*g2*gp*Ql1*ZE11*conjg(ZV31 &
      )*Cos(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE12*conjg(ZV32)*Cos(TWp) + (0,1)* &
      Sqrt (2._default)*g2*gp*Ql3*ZE13*conjg(ZV33)*Cos(TWp) - ((0,1)*g1*g2*ZE11*conjg(ZV31 &
      )*Sin(TW)*Sin(TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE12*conjg(ZV32)*Sin(TW)*Sin( &
      TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE13*conjg(ZV33)*Sin(TW)*Sin(TWp))/Sqrt ( &
      2._default))
   G_sv3_se2c_wm_1_zp_1 = (0,-1)*((0,1)*Sqrt (2._default)*g2*gp*Ql1*ZE21*conjg(ZV31 &
      )*Cos(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE22*conjg(ZV32)*Cos(TWp) + (0,1)* &
      Sqrt (2._default)*g2*gp*Ql3*ZE23*conjg(ZV33)*Cos(TWp) - ((0,1)*g1*g2*ZE21*conjg(ZV31 &
      )*Sin(TW)*Sin(TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE22*conjg(ZV32)*Sin(TW)*Sin( &
      TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE23*conjg(ZV33)*Sin(TW)*Sin(TWp))/Sqrt ( &
      2._default))
   G_sv3_se3c_wm_1_zp_1 = (0,-1)*((0,1)*Sqrt (2._default)*g2*gp*Ql1*ZE31*conjg(ZV31 &
      )*Cos(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE32*conjg(ZV32)*Cos(TWp) + (0,1)* &
      Sqrt (2._default)*g2*gp*Ql3*ZE33*conjg(ZV33)*Cos(TWp) - ((0,1)*g1*g2*ZE31*conjg(ZV31 &
      )*Sin(TW)*Sin(TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE32*conjg(ZV32)*Sin(TW)*Sin( &
      TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE33*conjg(ZV33)*Sin(TW)*Sin(TWp))/Sqrt ( &
      2._default))
   G_sv3_se4c_wm_1_zp_1 = (0,-1)*((0,1)*Sqrt (2._default)*g2*gp*Ql1*ZE41*conjg(ZV31 &
      )*Cos(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE42*conjg(ZV32)*Cos(TWp) + (0,1)* &
      Sqrt (2._default)*g2*gp*Ql3*ZE43*conjg(ZV33)*Cos(TWp) - ((0,1)*g1*g2*ZE41*conjg(ZV31 &
      )*Sin(TW)*Sin(TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE42*conjg(ZV32)*Sin(TW)*Sin( &
      TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE43*conjg(ZV33)*Sin(TW)*Sin(TWp))/Sqrt ( &
      2._default))
   G_sv3_se5c_wm_1_zp_1 = (0,-1)*((0,1)*Sqrt (2._default)*g2*gp*Ql1*ZE51*conjg(ZV31 &
      )*Cos(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE52*conjg(ZV32)*Cos(TWp) + (0,1)* &
      Sqrt (2._default)*g2*gp*Ql3*ZE53*conjg(ZV33)*Cos(TWp) - ((0,1)*g1*g2*ZE51*conjg(ZV31 &
      )*Sin(TW)*Sin(TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE52*conjg(ZV32)*Sin(TW)*Sin( &
      TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE53*conjg(ZV33)*Sin(TW)*Sin(TWp))/Sqrt ( &
      2._default))
   G_sv3_se6c_wm_1_zp_1 = (0,-1)*((0,1)*Sqrt (2._default)*g2*gp*Ql1*ZE61*conjg(ZV31 &
      )*Cos(TWp) + (0,1)*Sqrt (2._default)*g2*gp*Ql2*ZE62*conjg(ZV32)*Cos(TWp) + (0,1)* &
      Sqrt (2._default)*g2*gp*Ql3*ZE63*conjg(ZV33)*Cos(TWp) - ((0,1)*g1*g2*ZE61*conjg(ZV31 &
      )*Sin(TW)*Sin(TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE62*conjg(ZV32)*Sin(TW)*Sin( &
      TWp))/Sqrt (2._default) - ((0,1)*g1*g2*ZE63*conjg(ZV33)*Sin(TW)*Sin(TWp))/Sqrt ( &
      2._default))
   G_sv1_sv1c_wmc_wm_1 = (0,-1)*((0,0.5_default)*g2**2*ZV11*conjg(ZV11) + (0, &
      0.5_default)*g2**2*ZV12*conjg(ZV12) + (0,0.5_default)*g2**2*ZV13*conjg(ZV13))
   G_sv1_sv2c_wmc_wm_1 = (0,-1)*((0,0.5_default)*g2**2*ZV21*conjg(ZV11) + (0, &
      0.5_default)*g2**2*ZV22*conjg(ZV12) + (0,0.5_default)*g2**2*ZV23*conjg(ZV13))
   G_sv1_sv3c_wmc_wm_1 = (0,-1)*((0,0.5_default)*g2**2*ZV31*conjg(ZV11) + (0, &
      0.5_default)*g2**2*ZV32*conjg(ZV12) + (0,0.5_default)*g2**2*ZV33*conjg(ZV13))
   G_sv2_sv1c_wmc_wm_1 = (0,-1)*((0,0.5_default)*g2**2*ZV11*conjg(ZV21) + (0, &
      0.5_default)*g2**2*ZV12*conjg(ZV22) + (0,0.5_default)*g2**2*ZV13*conjg(ZV23))
   G_sv2_sv2c_wmc_wm_1 = (0,-1)*((0,0.5_default)*g2**2*ZV21*conjg(ZV21) + (0, &
      0.5_default)*g2**2*ZV22*conjg(ZV22) + (0,0.5_default)*g2**2*ZV23*conjg(ZV23))
   G_sv2_sv3c_wmc_wm_1 = (0,-1)*((0,0.5_default)*g2**2*ZV31*conjg(ZV21) + (0, &
      0.5_default)*g2**2*ZV32*conjg(ZV22) + (0,0.5_default)*g2**2*ZV33*conjg(ZV23))
   G_sv3_sv1c_wmc_wm_1 = (0,-1)*((0,0.5_default)*g2**2*ZV11*conjg(ZV31) + (0, &
      0.5_default)*g2**2*ZV12*conjg(ZV32) + (0,0.5_default)*g2**2*ZV13*conjg(ZV33))
   G_sv3_sv2c_wmc_wm_1 = (0,-1)*((0,0.5_default)*g2**2*ZV21*conjg(ZV31) + (0, &
      0.5_default)*g2**2*ZV22*conjg(ZV32) + (0,0.5_default)*g2**2*ZV23*conjg(ZV33))
   G_sv3_sv3c_wmc_wm_1 = (0,-1)*((0,0.5_default)*g2**2*ZV31*conjg(ZV31) + (0, &
      0.5_default)*g2**2*ZV32*conjg(ZV32) + (0,0.5_default)*g2**2*ZV33*conjg(ZV33))
   G_sv1_sv1c_z_1_z_1 = (0,-1)*((0,0.5_default)*g2**2*ZV11*conjg(ZV11)*Cos(TW)**2* &
      Cos(TWp)**2 + (0,0.5_default)*g2**2*ZV12*conjg(ZV12)*Cos(TW)**2*Cos(TWp)**2 + (0, &
      0.5_default)*g2**2*ZV13*conjg(ZV13)*Cos(TW)**2*Cos(TWp)**2 + (0,1)*g1*g2*ZV11*conjg(ZV11)* &
      Cos(TW)*Cos(TWp)**2*Sin(TW) + (0,1)*g1*g2*ZV12*conjg(ZV12)*Cos(TW)*Cos(TWp)**2*Sin( &
      TW) + (0,1)*g1*g2*ZV13*conjg(ZV13)*Cos(TW)*Cos(TWp)**2*Sin(TW) + (0,0.5_default)* &
      g1**2*ZV11*conjg(ZV11)*Cos(TWp)**2*Sin(TW)**2 + (0,0.5_default)*g1**2*ZV12*conjg( &
      ZV12)*Cos(TWp)**2*Sin(TW)**2 + (0,0.5_default)*g1**2*ZV13*conjg(ZV13)*Cos(TWp)**2* &
      Sin(TW)**2 + (0,2)*g2*gp*Ql1*ZV11*conjg(ZV11)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g2* &
      gp*Ql2*ZV12*conjg(ZV12)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g2*gp*Ql3*ZV13*conjg( &
      ZV13)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g1*gp*Ql1*ZV11*conjg(ZV11)*Cos(TWp)*Sin(TW)* &
      Sin(TWp) + (0,2)*g1*gp*Ql2*ZV12*conjg(ZV12)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,2)*g1*gp &
      *Ql3*ZV13*conjg(ZV13)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,2)*gp**2*Ql1**2*ZV11*conjg( &
      ZV11)*Sin(TWp)**2 + (0,2)*gp**2*Ql2**2*ZV12*conjg(ZV12)*Sin(TWp)**2 + (0,2)*gp**2* &
      Ql3**2*ZV13*conjg(ZV13)*Sin(TWp)**2)
   G_sv1_sv2c_z_1_z_1 = (0,-1)*((0,0.5_default)*g2**2*ZV21*conjg(ZV11)*Cos(TW)**2* &
      Cos(TWp)**2 + (0,0.5_default)*g2**2*ZV22*conjg(ZV12)*Cos(TW)**2*Cos(TWp)**2 + (0, &
      0.5_default)*g2**2*ZV23*conjg(ZV13)*Cos(TW)**2*Cos(TWp)**2 + (0,1)*g1*g2*ZV21*conjg(ZV11)* &
      Cos(TW)*Cos(TWp)**2*Sin(TW) + (0,1)*g1*g2*ZV22*conjg(ZV12)*Cos(TW)*Cos(TWp)**2*Sin( &
      TW) + (0,1)*g1*g2*ZV23*conjg(ZV13)*Cos(TW)*Cos(TWp)**2*Sin(TW) + (0,0.5_default)* &
      g1**2*ZV21*conjg(ZV11)*Cos(TWp)**2*Sin(TW)**2 + (0,0.5_default)*g1**2*ZV22*conjg( &
      ZV12)*Cos(TWp)**2*Sin(TW)**2 + (0,0.5_default)*g1**2*ZV23*conjg(ZV13)*Cos(TWp)**2* &
      Sin(TW)**2 + (0,2)*g2*gp*Ql1*ZV21*conjg(ZV11)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g2* &
      gp*Ql2*ZV22*conjg(ZV12)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g2*gp*Ql3*ZV23*conjg( &
      ZV13)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g1*gp*Ql1*ZV21*conjg(ZV11)*Cos(TWp)*Sin(TW)* &
      Sin(TWp) + (0,2)*g1*gp*Ql2*ZV22*conjg(ZV12)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,2)*g1*gp &
      *Ql3*ZV23*conjg(ZV13)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,2)*gp**2*Ql1**2*ZV21*conjg( &
      ZV11)*Sin(TWp)**2 + (0,2)*gp**2*Ql2**2*ZV22*conjg(ZV12)*Sin(TWp)**2 + (0,2)*gp**2* &
      Ql3**2*ZV23*conjg(ZV13)*Sin(TWp)**2)
   G_sv1_sv3c_z_1_z_1 = (0,-1)*((0,0.5_default)*g2**2*ZV31*conjg(ZV11)*Cos(TW)**2* &
      Cos(TWp)**2 + (0,0.5_default)*g2**2*ZV32*conjg(ZV12)*Cos(TW)**2*Cos(TWp)**2 + (0, &
      0.5_default)*g2**2*ZV33*conjg(ZV13)*Cos(TW)**2*Cos(TWp)**2 + (0,1)*g1*g2*ZV31*conjg(ZV11)* &
      Cos(TW)*Cos(TWp)**2*Sin(TW) + (0,1)*g1*g2*ZV32*conjg(ZV12)*Cos(TW)*Cos(TWp)**2*Sin( &
      TW) + (0,1)*g1*g2*ZV33*conjg(ZV13)*Cos(TW)*Cos(TWp)**2*Sin(TW) + (0,0.5_default)* &
      g1**2*ZV31*conjg(ZV11)*Cos(TWp)**2*Sin(TW)**2 + (0,0.5_default)*g1**2*ZV32*conjg( &
      ZV12)*Cos(TWp)**2*Sin(TW)**2 + (0,0.5_default)*g1**2*ZV33*conjg(ZV13)*Cos(TWp)**2* &
      Sin(TW)**2 + (0,2)*g2*gp*Ql1*ZV31*conjg(ZV11)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g2* &
      gp*Ql2*ZV32*conjg(ZV12)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g2*gp*Ql3*ZV33*conjg( &
      ZV13)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g1*gp*Ql1*ZV31*conjg(ZV11)*Cos(TWp)*Sin(TW)* &
      Sin(TWp) + (0,2)*g1*gp*Ql2*ZV32*conjg(ZV12)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,2)*g1*gp &
      *Ql3*ZV33*conjg(ZV13)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,2)*gp**2*Ql1**2*ZV31*conjg( &
      ZV11)*Sin(TWp)**2 + (0,2)*gp**2*Ql2**2*ZV32*conjg(ZV12)*Sin(TWp)**2 + (0,2)*gp**2* &
      Ql3**2*ZV33*conjg(ZV13)*Sin(TWp)**2)
   G_sv2_sv1c_z_1_z_1 = (0,-1)*((0,0.5_default)*g2**2*ZV11*conjg(ZV21)*Cos(TW)**2* &
      Cos(TWp)**2 + (0,0.5_default)*g2**2*ZV12*conjg(ZV22)*Cos(TW)**2*Cos(TWp)**2 + (0, &
      0.5_default)*g2**2*ZV13*conjg(ZV23)*Cos(TW)**2*Cos(TWp)**2 + (0,1)*g1*g2*ZV11*conjg(ZV21)* &
      Cos(TW)*Cos(TWp)**2*Sin(TW) + (0,1)*g1*g2*ZV12*conjg(ZV22)*Cos(TW)*Cos(TWp)**2*Sin( &
      TW) + (0,1)*g1*g2*ZV13*conjg(ZV23)*Cos(TW)*Cos(TWp)**2*Sin(TW) + (0,0.5_default)* &
      g1**2*ZV11*conjg(ZV21)*Cos(TWp)**2*Sin(TW)**2 + (0,0.5_default)*g1**2*ZV12*conjg( &
      ZV22)*Cos(TWp)**2*Sin(TW)**2 + (0,0.5_default)*g1**2*ZV13*conjg(ZV23)*Cos(TWp)**2* &
      Sin(TW)**2 + (0,2)*g2*gp*Ql1*ZV11*conjg(ZV21)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g2* &
      gp*Ql2*ZV12*conjg(ZV22)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g2*gp*Ql3*ZV13*conjg( &
      ZV23)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g1*gp*Ql1*ZV11*conjg(ZV21)*Cos(TWp)*Sin(TW)* &
      Sin(TWp) + (0,2)*g1*gp*Ql2*ZV12*conjg(ZV22)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,2)*g1*gp &
      *Ql3*ZV13*conjg(ZV23)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,2)*gp**2*Ql1**2*ZV11*conjg( &
      ZV21)*Sin(TWp)**2 + (0,2)*gp**2*Ql2**2*ZV12*conjg(ZV22)*Sin(TWp)**2 + (0,2)*gp**2* &
      Ql3**2*ZV13*conjg(ZV23)*Sin(TWp)**2)
   G_sv2_sv2c_z_1_z_1 = (0,-1)*((0,0.5_default)*g2**2*ZV21*conjg(ZV21)*Cos(TW)**2* &
      Cos(TWp)**2 + (0,0.5_default)*g2**2*ZV22*conjg(ZV22)*Cos(TW)**2*Cos(TWp)**2 + (0, &
      0.5_default)*g2**2*ZV23*conjg(ZV23)*Cos(TW)**2*Cos(TWp)**2 + (0,1)*g1*g2*ZV21*conjg(ZV21)* &
      Cos(TW)*Cos(TWp)**2*Sin(TW) + (0,1)*g1*g2*ZV22*conjg(ZV22)*Cos(TW)*Cos(TWp)**2*Sin( &
      TW) + (0,1)*g1*g2*ZV23*conjg(ZV23)*Cos(TW)*Cos(TWp)**2*Sin(TW) + (0,0.5_default)* &
      g1**2*ZV21*conjg(ZV21)*Cos(TWp)**2*Sin(TW)**2 + (0,0.5_default)*g1**2*ZV22*conjg( &
      ZV22)*Cos(TWp)**2*Sin(TW)**2 + (0,0.5_default)*g1**2*ZV23*conjg(ZV23)*Cos(TWp)**2* &
      Sin(TW)**2 + (0,2)*g2*gp*Ql1*ZV21*conjg(ZV21)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g2* &
      gp*Ql2*ZV22*conjg(ZV22)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g2*gp*Ql3*ZV23*conjg( &
      ZV23)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g1*gp*Ql1*ZV21*conjg(ZV21)*Cos(TWp)*Sin(TW)* &
      Sin(TWp) + (0,2)*g1*gp*Ql2*ZV22*conjg(ZV22)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,2)*g1*gp &
      *Ql3*ZV23*conjg(ZV23)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,2)*gp**2*Ql1**2*ZV21*conjg( &
      ZV21)*Sin(TWp)**2 + (0,2)*gp**2*Ql2**2*ZV22*conjg(ZV22)*Sin(TWp)**2 + (0,2)*gp**2* &
      Ql3**2*ZV23*conjg(ZV23)*Sin(TWp)**2)
   G_sv2_sv3c_z_1_z_1 = (0,-1)*((0,0.5_default)*g2**2*ZV31*conjg(ZV21)*Cos(TW)**2* &
      Cos(TWp)**2 + (0,0.5_default)*g2**2*ZV32*conjg(ZV22)*Cos(TW)**2*Cos(TWp)**2 + (0, &
      0.5_default)*g2**2*ZV33*conjg(ZV23)*Cos(TW)**2*Cos(TWp)**2 + (0,1)*g1*g2*ZV31*conjg(ZV21)* &
      Cos(TW)*Cos(TWp)**2*Sin(TW) + (0,1)*g1*g2*ZV32*conjg(ZV22)*Cos(TW)*Cos(TWp)**2*Sin( &
      TW) + (0,1)*g1*g2*ZV33*conjg(ZV23)*Cos(TW)*Cos(TWp)**2*Sin(TW) + (0,0.5_default)* &
      g1**2*ZV31*conjg(ZV21)*Cos(TWp)**2*Sin(TW)**2 + (0,0.5_default)*g1**2*ZV32*conjg( &
      ZV22)*Cos(TWp)**2*Sin(TW)**2 + (0,0.5_default)*g1**2*ZV33*conjg(ZV23)*Cos(TWp)**2* &
      Sin(TW)**2 + (0,2)*g2*gp*Ql1*ZV31*conjg(ZV21)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g2* &
      gp*Ql2*ZV32*conjg(ZV22)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g2*gp*Ql3*ZV33*conjg( &
      ZV23)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g1*gp*Ql1*ZV31*conjg(ZV21)*Cos(TWp)*Sin(TW)* &
      Sin(TWp) + (0,2)*g1*gp*Ql2*ZV32*conjg(ZV22)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,2)*g1*gp &
      *Ql3*ZV33*conjg(ZV23)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,2)*gp**2*Ql1**2*ZV31*conjg( &
      ZV21)*Sin(TWp)**2 + (0,2)*gp**2*Ql2**2*ZV32*conjg(ZV22)*Sin(TWp)**2 + (0,2)*gp**2* &
      Ql3**2*ZV33*conjg(ZV23)*Sin(TWp)**2)
   G_sv3_sv1c_z_1_z_1 = (0,-1)*((0,0.5_default)*g2**2*ZV11*conjg(ZV31)*Cos(TW)**2* &
      Cos(TWp)**2 + (0,0.5_default)*g2**2*ZV12*conjg(ZV32)*Cos(TW)**2*Cos(TWp)**2 + (0, &
      0.5_default)*g2**2*ZV13*conjg(ZV33)*Cos(TW)**2*Cos(TWp)**2 + (0,1)*g1*g2*ZV11*conjg(ZV31)* &
      Cos(TW)*Cos(TWp)**2*Sin(TW) + (0,1)*g1*g2*ZV12*conjg(ZV32)*Cos(TW)*Cos(TWp)**2*Sin( &
      TW) + (0,1)*g1*g2*ZV13*conjg(ZV33)*Cos(TW)*Cos(TWp)**2*Sin(TW) + (0,0.5_default)* &
      g1**2*ZV11*conjg(ZV31)*Cos(TWp)**2*Sin(TW)**2 + (0,0.5_default)*g1**2*ZV12*conjg( &
      ZV32)*Cos(TWp)**2*Sin(TW)**2 + (0,0.5_default)*g1**2*ZV13*conjg(ZV33)*Cos(TWp)**2* &
      Sin(TW)**2 + (0,2)*g2*gp*Ql1*ZV11*conjg(ZV31)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g2* &
      gp*Ql2*ZV12*conjg(ZV32)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g2*gp*Ql3*ZV13*conjg( &
      ZV33)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g1*gp*Ql1*ZV11*conjg(ZV31)*Cos(TWp)*Sin(TW)* &
      Sin(TWp) + (0,2)*g1*gp*Ql2*ZV12*conjg(ZV32)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,2)*g1*gp &
      *Ql3*ZV13*conjg(ZV33)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,2)*gp**2*Ql1**2*ZV11*conjg( &
      ZV31)*Sin(TWp)**2 + (0,2)*gp**2*Ql2**2*ZV12*conjg(ZV32)*Sin(TWp)**2 + (0,2)*gp**2* &
      Ql3**2*ZV13*conjg(ZV33)*Sin(TWp)**2)
   G_sv3_sv2c_z_1_z_1 = (0,-1)*((0,0.5_default)*g2**2*ZV21*conjg(ZV31)*Cos(TW)**2* &
      Cos(TWp)**2 + (0,0.5_default)*g2**2*ZV22*conjg(ZV32)*Cos(TW)**2*Cos(TWp)**2 + (0, &
      0.5_default)*g2**2*ZV23*conjg(ZV33)*Cos(TW)**2*Cos(TWp)**2 + (0,1)*g1*g2*ZV21*conjg(ZV31)* &
      Cos(TW)*Cos(TWp)**2*Sin(TW) + (0,1)*g1*g2*ZV22*conjg(ZV32)*Cos(TW)*Cos(TWp)**2*Sin( &
      TW) + (0,1)*g1*g2*ZV23*conjg(ZV33)*Cos(TW)*Cos(TWp)**2*Sin(TW) + (0,0.5_default)* &
      g1**2*ZV21*conjg(ZV31)*Cos(TWp)**2*Sin(TW)**2 + (0,0.5_default)*g1**2*ZV22*conjg( &
      ZV32)*Cos(TWp)**2*Sin(TW)**2 + (0,0.5_default)*g1**2*ZV23*conjg(ZV33)*Cos(TWp)**2* &
      Sin(TW)**2 + (0,2)*g2*gp*Ql1*ZV21*conjg(ZV31)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g2* &
      gp*Ql2*ZV22*conjg(ZV32)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g2*gp*Ql3*ZV23*conjg( &
      ZV33)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g1*gp*Ql1*ZV21*conjg(ZV31)*Cos(TWp)*Sin(TW)* &
      Sin(TWp) + (0,2)*g1*gp*Ql2*ZV22*conjg(ZV32)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,2)*g1*gp &
      *Ql3*ZV23*conjg(ZV33)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,2)*gp**2*Ql1**2*ZV21*conjg( &
      ZV31)*Sin(TWp)**2 + (0,2)*gp**2*Ql2**2*ZV22*conjg(ZV32)*Sin(TWp)**2 + (0,2)*gp**2* &
      Ql3**2*ZV23*conjg(ZV33)*Sin(TWp)**2)
   G_sv3_sv3c_z_1_z_1 = (0,-1)*((0,0.5_default)*g2**2*ZV31*conjg(ZV31)*Cos(TW)**2* &
      Cos(TWp)**2 + (0,0.5_default)*g2**2*ZV32*conjg(ZV32)*Cos(TW)**2*Cos(TWp)**2 + (0, &
      0.5_default)*g2**2*ZV33*conjg(ZV33)*Cos(TW)**2*Cos(TWp)**2 + (0,1)*g1*g2*ZV31*conjg(ZV31)* &
      Cos(TW)*Cos(TWp)**2*Sin(TW) + (0,1)*g1*g2*ZV32*conjg(ZV32)*Cos(TW)*Cos(TWp)**2*Sin( &
      TW) + (0,1)*g1*g2*ZV33*conjg(ZV33)*Cos(TW)*Cos(TWp)**2*Sin(TW) + (0,0.5_default)* &
      g1**2*ZV31*conjg(ZV31)*Cos(TWp)**2*Sin(TW)**2 + (0,0.5_default)*g1**2*ZV32*conjg( &
      ZV32)*Cos(TWp)**2*Sin(TW)**2 + (0,0.5_default)*g1**2*ZV33*conjg(ZV33)*Cos(TWp)**2* &
      Sin(TW)**2 + (0,2)*g2*gp*Ql1*ZV31*conjg(ZV31)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g2* &
      gp*Ql2*ZV32*conjg(ZV32)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g2*gp*Ql3*ZV33*conjg( &
      ZV33)*Cos(TW)*Cos(TWp)*Sin(TWp) + (0,2)*g1*gp*Ql1*ZV31*conjg(ZV31)*Cos(TWp)*Sin(TW)* &
      Sin(TWp) + (0,2)*g1*gp*Ql2*ZV32*conjg(ZV32)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,2)*g1*gp &
      *Ql3*ZV33*conjg(ZV33)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,2)*gp**2*Ql1**2*ZV31*conjg( &
      ZV31)*Sin(TWp)**2 + (0,2)*gp**2*Ql2**2*ZV32*conjg(ZV32)*Sin(TWp)**2 + (0,2)*gp**2* &
      Ql3**2*ZV33*conjg(ZV33)*Sin(TWp)**2)
   G_sv1_sv1c_z_1_zp_1 = (0,-1)*((0,1)*g2*gp*Ql1*ZV11*conjg(ZV11)*Cos(TW)*Cos(TWp &
      )**2 + (0,1)*g2*gp*Ql2*ZV12*conjg(ZV12)*Cos(TW)*Cos(TWp)**2 + (0,1)*g2*gp*Ql3*ZV13* &
      conjg(ZV13)*Cos(TW)*Cos(TWp)**2 + (0,1)*g1*gp*Ql1*ZV11*conjg(ZV11)*Cos(TWp)**2*Sin(TW &
      ) + (0,1)*g1*gp*Ql2*ZV12*conjg(ZV12)*Cos(TWp)**2*Sin(TW) + (0,1)*g1*gp*Ql3*ZV13*conjg &
      (ZV13)*Cos(TWp)**2*Sin(TW) + (0,2)*gp**2*Ql1**2*ZV11*conjg(ZV11)*Cos(TWp)*Sin(TWp &
      ) + (0,2)*gp**2*Ql2**2*ZV12*conjg(ZV12)*Cos(TWp)*Sin(TWp) + (0,2)*gp**2*Ql3**2*ZV13* &
      conjg(ZV13)*Cos(TWp)*Sin(TWp) - (0,0.5_default)*g2**2*ZV11*conjg(ZV11)*Cos(TW)**2*Cos &
      (TWp)*Sin(TWp) - (0,0.5_default)*g2**2*ZV12*conjg(ZV12)*Cos(TW)**2*Cos(TWp)*Sin( &
      TWp) - (0,0.5_default)*g2**2*ZV13*conjg(ZV13)*Cos(TW)**2*Cos(TWp)*Sin(TWp) - (0,1)* &
      g1*g2*ZV11*conjg(ZV11)*Cos(TW)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,1)*g1*g2*ZV12*conjg( &
      ZV12)*Cos(TW)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,1)*g1*g2*ZV13*conjg(ZV13)*Cos(TW)*Cos( &
      TWp)*Sin(TW)*Sin(TWp) - (0,0.5_default)*g1**2*ZV11*conjg(ZV11)*Cos(TWp)*Sin(TW)**2* &
      Sin(TWp) - (0,0.5_default)*g1**2*ZV12*conjg(ZV12)*Cos(TWp)*Sin(TW)**2*Sin(TWp) - (0 &
      ,0.5_default)*g1**2*ZV13*conjg(ZV13)*Cos(TWp)*Sin(TW)**2*Sin(TWp) - (0,1)*g2*gp* &
      Ql1*ZV11*conjg(ZV11)*Cos(TW)*Sin(TWp)**2 - (0,1)*g2*gp*Ql2*ZV12*conjg(ZV12)*Cos(TW &
      )*Sin(TWp)**2 - (0,1)*g2*gp*Ql3*ZV13*conjg(ZV13)*Cos(TW)*Sin(TWp)**2 - (0,1)*g1*gp &
      *Ql1*ZV11*conjg(ZV11)*Sin(TW)*Sin(TWp)**2 - (0,1)*g1*gp*Ql2*ZV12*conjg(ZV12)*Sin( &
      TW)*Sin(TWp)**2 - (0,1)*g1*gp*Ql3*ZV13*conjg(ZV13)*Sin(TW)*Sin(TWp)**2)
   G_sv1_sv2c_z_1_zp_1 = (0,-1)*((0,1)*g2*gp*Ql1*ZV21*conjg(ZV11)*Cos(TW)*Cos(TWp &
      )**2 + (0,1)*g2*gp*Ql2*ZV22*conjg(ZV12)*Cos(TW)*Cos(TWp)**2 + (0,1)*g2*gp*Ql3*ZV23* &
      conjg(ZV13)*Cos(TW)*Cos(TWp)**2 + (0,1)*g1*gp*Ql1*ZV21*conjg(ZV11)*Cos(TWp)**2*Sin(TW &
      ) + (0,1)*g1*gp*Ql2*ZV22*conjg(ZV12)*Cos(TWp)**2*Sin(TW) + (0,1)*g1*gp*Ql3*ZV23*conjg &
      (ZV13)*Cos(TWp)**2*Sin(TW) + (0,2)*gp**2*Ql1**2*ZV21*conjg(ZV11)*Cos(TWp)*Sin(TWp &
      ) + (0,2)*gp**2*Ql2**2*ZV22*conjg(ZV12)*Cos(TWp)*Sin(TWp) + (0,2)*gp**2*Ql3**2*ZV23* &
      conjg(ZV13)*Cos(TWp)*Sin(TWp) - (0,0.5_default)*g2**2*ZV21*conjg(ZV11)*Cos(TW)**2*Cos &
      (TWp)*Sin(TWp) - (0,0.5_default)*g2**2*ZV22*conjg(ZV12)*Cos(TW)**2*Cos(TWp)*Sin( &
      TWp) - (0,0.5_default)*g2**2*ZV23*conjg(ZV13)*Cos(TW)**2*Cos(TWp)*Sin(TWp) - (0,1)* &
      g1*g2*ZV21*conjg(ZV11)*Cos(TW)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,1)*g1*g2*ZV22*conjg( &
      ZV12)*Cos(TW)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,1)*g1*g2*ZV23*conjg(ZV13)*Cos(TW)*Cos( &
      TWp)*Sin(TW)*Sin(TWp) - (0,0.5_default)*g1**2*ZV21*conjg(ZV11)*Cos(TWp)*Sin(TW)**2* &
      Sin(TWp) - (0,0.5_default)*g1**2*ZV22*conjg(ZV12)*Cos(TWp)*Sin(TW)**2*Sin(TWp) - (0 &
      ,0.5_default)*g1**2*ZV23*conjg(ZV13)*Cos(TWp)*Sin(TW)**2*Sin(TWp) - (0,1)*g2*gp* &
      Ql1*ZV21*conjg(ZV11)*Cos(TW)*Sin(TWp)**2 - (0,1)*g2*gp*Ql2*ZV22*conjg(ZV12)*Cos(TW &
      )*Sin(TWp)**2 - (0,1)*g2*gp*Ql3*ZV23*conjg(ZV13)*Cos(TW)*Sin(TWp)**2 - (0,1)*g1*gp &
      *Ql1*ZV21*conjg(ZV11)*Sin(TW)*Sin(TWp)**2 - (0,1)*g1*gp*Ql2*ZV22*conjg(ZV12)*Sin( &
      TW)*Sin(TWp)**2 - (0,1)*g1*gp*Ql3*ZV23*conjg(ZV13)*Sin(TW)*Sin(TWp)**2)
   G_sv1_sv3c_z_1_zp_1 = (0,-1)*((0,1)*g2*gp*Ql1*ZV31*conjg(ZV11)*Cos(TW)*Cos(TWp &
      )**2 + (0,1)*g2*gp*Ql2*ZV32*conjg(ZV12)*Cos(TW)*Cos(TWp)**2 + (0,1)*g2*gp*Ql3*ZV33* &
      conjg(ZV13)*Cos(TW)*Cos(TWp)**2 + (0,1)*g1*gp*Ql1*ZV31*conjg(ZV11)*Cos(TWp)**2*Sin(TW &
      ) + (0,1)*g1*gp*Ql2*ZV32*conjg(ZV12)*Cos(TWp)**2*Sin(TW) + (0,1)*g1*gp*Ql3*ZV33*conjg &
      (ZV13)*Cos(TWp)**2*Sin(TW) + (0,2)*gp**2*Ql1**2*ZV31*conjg(ZV11)*Cos(TWp)*Sin(TWp &
      ) + (0,2)*gp**2*Ql2**2*ZV32*conjg(ZV12)*Cos(TWp)*Sin(TWp) + (0,2)*gp**2*Ql3**2*ZV33* &
      conjg(ZV13)*Cos(TWp)*Sin(TWp) - (0,0.5_default)*g2**2*ZV31*conjg(ZV11)*Cos(TW)**2*Cos &
      (TWp)*Sin(TWp) - (0,0.5_default)*g2**2*ZV32*conjg(ZV12)*Cos(TW)**2*Cos(TWp)*Sin( &
      TWp) - (0,0.5_default)*g2**2*ZV33*conjg(ZV13)*Cos(TW)**2*Cos(TWp)*Sin(TWp) - (0,1)* &
      g1*g2*ZV31*conjg(ZV11)*Cos(TW)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,1)*g1*g2*ZV32*conjg( &
      ZV12)*Cos(TW)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,1)*g1*g2*ZV33*conjg(ZV13)*Cos(TW)*Cos( &
      TWp)*Sin(TW)*Sin(TWp) - (0,0.5_default)*g1**2*ZV31*conjg(ZV11)*Cos(TWp)*Sin(TW)**2* &
      Sin(TWp) - (0,0.5_default)*g1**2*ZV32*conjg(ZV12)*Cos(TWp)*Sin(TW)**2*Sin(TWp) - (0 &
      ,0.5_default)*g1**2*ZV33*conjg(ZV13)*Cos(TWp)*Sin(TW)**2*Sin(TWp) - (0,1)*g2*gp* &
      Ql1*ZV31*conjg(ZV11)*Cos(TW)*Sin(TWp)**2 - (0,1)*g2*gp*Ql2*ZV32*conjg(ZV12)*Cos(TW &
      )*Sin(TWp)**2 - (0,1)*g2*gp*Ql3*ZV33*conjg(ZV13)*Cos(TW)*Sin(TWp)**2 - (0,1)*g1*gp &
      *Ql1*ZV31*conjg(ZV11)*Sin(TW)*Sin(TWp)**2 - (0,1)*g1*gp*Ql2*ZV32*conjg(ZV12)*Sin( &
      TW)*Sin(TWp)**2 - (0,1)*g1*gp*Ql3*ZV33*conjg(ZV13)*Sin(TW)*Sin(TWp)**2)
   G_sv2_sv1c_z_1_zp_1 = (0,-1)*((0,1)*g2*gp*Ql1*ZV11*conjg(ZV21)*Cos(TW)*Cos(TWp &
      )**2 + (0,1)*g2*gp*Ql2*ZV12*conjg(ZV22)*Cos(TW)*Cos(TWp)**2 + (0,1)*g2*gp*Ql3*ZV13* &
      conjg(ZV23)*Cos(TW)*Cos(TWp)**2 + (0,1)*g1*gp*Ql1*ZV11*conjg(ZV21)*Cos(TWp)**2*Sin(TW &
      ) + (0,1)*g1*gp*Ql2*ZV12*conjg(ZV22)*Cos(TWp)**2*Sin(TW) + (0,1)*g1*gp*Ql3*ZV13*conjg &
      (ZV23)*Cos(TWp)**2*Sin(TW) + (0,2)*gp**2*Ql1**2*ZV11*conjg(ZV21)*Cos(TWp)*Sin(TWp &
      ) + (0,2)*gp**2*Ql2**2*ZV12*conjg(ZV22)*Cos(TWp)*Sin(TWp) + (0,2)*gp**2*Ql3**2*ZV13* &
      conjg(ZV23)*Cos(TWp)*Sin(TWp) - (0,0.5_default)*g2**2*ZV11*conjg(ZV21)*Cos(TW)**2*Cos &
      (TWp)*Sin(TWp) - (0,0.5_default)*g2**2*ZV12*conjg(ZV22)*Cos(TW)**2*Cos(TWp)*Sin( &
      TWp) - (0,0.5_default)*g2**2*ZV13*conjg(ZV23)*Cos(TW)**2*Cos(TWp)*Sin(TWp) - (0,1)* &
      g1*g2*ZV11*conjg(ZV21)*Cos(TW)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,1)*g1*g2*ZV12*conjg( &
      ZV22)*Cos(TW)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,1)*g1*g2*ZV13*conjg(ZV23)*Cos(TW)*Cos( &
      TWp)*Sin(TW)*Sin(TWp) - (0,0.5_default)*g1**2*ZV11*conjg(ZV21)*Cos(TWp)*Sin(TW)**2* &
      Sin(TWp) - (0,0.5_default)*g1**2*ZV12*conjg(ZV22)*Cos(TWp)*Sin(TW)**2*Sin(TWp) - (0 &
      ,0.5_default)*g1**2*ZV13*conjg(ZV23)*Cos(TWp)*Sin(TW)**2*Sin(TWp) - (0,1)*g2*gp* &
      Ql1*ZV11*conjg(ZV21)*Cos(TW)*Sin(TWp)**2 - (0,1)*g2*gp*Ql2*ZV12*conjg(ZV22)*Cos(TW &
      )*Sin(TWp)**2 - (0,1)*g2*gp*Ql3*ZV13*conjg(ZV23)*Cos(TW)*Sin(TWp)**2 - (0,1)*g1*gp &
      *Ql1*ZV11*conjg(ZV21)*Sin(TW)*Sin(TWp)**2 - (0,1)*g1*gp*Ql2*ZV12*conjg(ZV22)*Sin( &
      TW)*Sin(TWp)**2 - (0,1)*g1*gp*Ql3*ZV13*conjg(ZV23)*Sin(TW)*Sin(TWp)**2)
   G_sv2_sv2c_z_1_zp_1 = (0,-1)*((0,1)*g2*gp*Ql1*ZV21*conjg(ZV21)*Cos(TW)*Cos(TWp &
      )**2 + (0,1)*g2*gp*Ql2*ZV22*conjg(ZV22)*Cos(TW)*Cos(TWp)**2 + (0,1)*g2*gp*Ql3*ZV23* &
      conjg(ZV23)*Cos(TW)*Cos(TWp)**2 + (0,1)*g1*gp*Ql1*ZV21*conjg(ZV21)*Cos(TWp)**2*Sin(TW &
      ) + (0,1)*g1*gp*Ql2*ZV22*conjg(ZV22)*Cos(TWp)**2*Sin(TW) + (0,1)*g1*gp*Ql3*ZV23*conjg &
      (ZV23)*Cos(TWp)**2*Sin(TW) + (0,2)*gp**2*Ql1**2*ZV21*conjg(ZV21)*Cos(TWp)*Sin(TWp &
      ) + (0,2)*gp**2*Ql2**2*ZV22*conjg(ZV22)*Cos(TWp)*Sin(TWp) + (0,2)*gp**2*Ql3**2*ZV23* &
      conjg(ZV23)*Cos(TWp)*Sin(TWp) - (0,0.5_default)*g2**2*ZV21*conjg(ZV21)*Cos(TW)**2*Cos &
      (TWp)*Sin(TWp) - (0,0.5_default)*g2**2*ZV22*conjg(ZV22)*Cos(TW)**2*Cos(TWp)*Sin( &
      TWp) - (0,0.5_default)*g2**2*ZV23*conjg(ZV23)*Cos(TW)**2*Cos(TWp)*Sin(TWp) - (0,1)* &
      g1*g2*ZV21*conjg(ZV21)*Cos(TW)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,1)*g1*g2*ZV22*conjg( &
      ZV22)*Cos(TW)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,1)*g1*g2*ZV23*conjg(ZV23)*Cos(TW)*Cos( &
      TWp)*Sin(TW)*Sin(TWp) - (0,0.5_default)*g1**2*ZV21*conjg(ZV21)*Cos(TWp)*Sin(TW)**2* &
      Sin(TWp) - (0,0.5_default)*g1**2*ZV22*conjg(ZV22)*Cos(TWp)*Sin(TW)**2*Sin(TWp) - (0 &
      ,0.5_default)*g1**2*ZV23*conjg(ZV23)*Cos(TWp)*Sin(TW)**2*Sin(TWp) - (0,1)*g2*gp* &
      Ql1*ZV21*conjg(ZV21)*Cos(TW)*Sin(TWp)**2 - (0,1)*g2*gp*Ql2*ZV22*conjg(ZV22)*Cos(TW &
      )*Sin(TWp)**2 - (0,1)*g2*gp*Ql3*ZV23*conjg(ZV23)*Cos(TW)*Sin(TWp)**2 - (0,1)*g1*gp &
      *Ql1*ZV21*conjg(ZV21)*Sin(TW)*Sin(TWp)**2 - (0,1)*g1*gp*Ql2*ZV22*conjg(ZV22)*Sin( &
      TW)*Sin(TWp)**2 - (0,1)*g1*gp*Ql3*ZV23*conjg(ZV23)*Sin(TW)*Sin(TWp)**2)
   G_sv2_sv3c_z_1_zp_1 = (0,-1)*((0,1)*g2*gp*Ql1*ZV31*conjg(ZV21)*Cos(TW)*Cos(TWp &
      )**2 + (0,1)*g2*gp*Ql2*ZV32*conjg(ZV22)*Cos(TW)*Cos(TWp)**2 + (0,1)*g2*gp*Ql3*ZV33* &
      conjg(ZV23)*Cos(TW)*Cos(TWp)**2 + (0,1)*g1*gp*Ql1*ZV31*conjg(ZV21)*Cos(TWp)**2*Sin(TW &
      ) + (0,1)*g1*gp*Ql2*ZV32*conjg(ZV22)*Cos(TWp)**2*Sin(TW) + (0,1)*g1*gp*Ql3*ZV33*conjg &
      (ZV23)*Cos(TWp)**2*Sin(TW) + (0,2)*gp**2*Ql1**2*ZV31*conjg(ZV21)*Cos(TWp)*Sin(TWp &
      ) + (0,2)*gp**2*Ql2**2*ZV32*conjg(ZV22)*Cos(TWp)*Sin(TWp) + (0,2)*gp**2*Ql3**2*ZV33* &
      conjg(ZV23)*Cos(TWp)*Sin(TWp) - (0,0.5_default)*g2**2*ZV31*conjg(ZV21)*Cos(TW)**2*Cos &
      (TWp)*Sin(TWp) - (0,0.5_default)*g2**2*ZV32*conjg(ZV22)*Cos(TW)**2*Cos(TWp)*Sin( &
      TWp) - (0,0.5_default)*g2**2*ZV33*conjg(ZV23)*Cos(TW)**2*Cos(TWp)*Sin(TWp) - (0,1)* &
      g1*g2*ZV31*conjg(ZV21)*Cos(TW)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,1)*g1*g2*ZV32*conjg( &
      ZV22)*Cos(TW)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,1)*g1*g2*ZV33*conjg(ZV23)*Cos(TW)*Cos( &
      TWp)*Sin(TW)*Sin(TWp) - (0,0.5_default)*g1**2*ZV31*conjg(ZV21)*Cos(TWp)*Sin(TW)**2* &
      Sin(TWp) - (0,0.5_default)*g1**2*ZV32*conjg(ZV22)*Cos(TWp)*Sin(TW)**2*Sin(TWp) - (0 &
      ,0.5_default)*g1**2*ZV33*conjg(ZV23)*Cos(TWp)*Sin(TW)**2*Sin(TWp) - (0,1)*g2*gp* &
      Ql1*ZV31*conjg(ZV21)*Cos(TW)*Sin(TWp)**2 - (0,1)*g2*gp*Ql2*ZV32*conjg(ZV22)*Cos(TW &
      )*Sin(TWp)**2 - (0,1)*g2*gp*Ql3*ZV33*conjg(ZV23)*Cos(TW)*Sin(TWp)**2 - (0,1)*g1*gp &
      *Ql1*ZV31*conjg(ZV21)*Sin(TW)*Sin(TWp)**2 - (0,1)*g1*gp*Ql2*ZV32*conjg(ZV22)*Sin( &
      TW)*Sin(TWp)**2 - (0,1)*g1*gp*Ql3*ZV33*conjg(ZV23)*Sin(TW)*Sin(TWp)**2)
   G_sv3_sv1c_z_1_zp_1 = (0,-1)*((0,1)*g2*gp*Ql1*ZV11*conjg(ZV31)*Cos(TW)*Cos(TWp &
      )**2 + (0,1)*g2*gp*Ql2*ZV12*conjg(ZV32)*Cos(TW)*Cos(TWp)**2 + (0,1)*g2*gp*Ql3*ZV13* &
      conjg(ZV33)*Cos(TW)*Cos(TWp)**2 + (0,1)*g1*gp*Ql1*ZV11*conjg(ZV31)*Cos(TWp)**2*Sin(TW &
      ) + (0,1)*g1*gp*Ql2*ZV12*conjg(ZV32)*Cos(TWp)**2*Sin(TW) + (0,1)*g1*gp*Ql3*ZV13*conjg &
      (ZV33)*Cos(TWp)**2*Sin(TW) + (0,2)*gp**2*Ql1**2*ZV11*conjg(ZV31)*Cos(TWp)*Sin(TWp &
      ) + (0,2)*gp**2*Ql2**2*ZV12*conjg(ZV32)*Cos(TWp)*Sin(TWp) + (0,2)*gp**2*Ql3**2*ZV13* &
      conjg(ZV33)*Cos(TWp)*Sin(TWp) - (0,0.5_default)*g2**2*ZV11*conjg(ZV31)*Cos(TW)**2*Cos &
      (TWp)*Sin(TWp) - (0,0.5_default)*g2**2*ZV12*conjg(ZV32)*Cos(TW)**2*Cos(TWp)*Sin( &
      TWp) - (0,0.5_default)*g2**2*ZV13*conjg(ZV33)*Cos(TW)**2*Cos(TWp)*Sin(TWp) - (0,1)* &
      g1*g2*ZV11*conjg(ZV31)*Cos(TW)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,1)*g1*g2*ZV12*conjg( &
      ZV32)*Cos(TW)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,1)*g1*g2*ZV13*conjg(ZV33)*Cos(TW)*Cos( &
      TWp)*Sin(TW)*Sin(TWp) - (0,0.5_default)*g1**2*ZV11*conjg(ZV31)*Cos(TWp)*Sin(TW)**2* &
      Sin(TWp) - (0,0.5_default)*g1**2*ZV12*conjg(ZV32)*Cos(TWp)*Sin(TW)**2*Sin(TWp) - (0 &
      ,0.5_default)*g1**2*ZV13*conjg(ZV33)*Cos(TWp)*Sin(TW)**2*Sin(TWp) - (0,1)*g2*gp* &
      Ql1*ZV11*conjg(ZV31)*Cos(TW)*Sin(TWp)**2 - (0,1)*g2*gp*Ql2*ZV12*conjg(ZV32)*Cos(TW &
      )*Sin(TWp)**2 - (0,1)*g2*gp*Ql3*ZV13*conjg(ZV33)*Cos(TW)*Sin(TWp)**2 - (0,1)*g1*gp &
      *Ql1*ZV11*conjg(ZV31)*Sin(TW)*Sin(TWp)**2 - (0,1)*g1*gp*Ql2*ZV12*conjg(ZV32)*Sin( &
      TW)*Sin(TWp)**2 - (0,1)*g1*gp*Ql3*ZV13*conjg(ZV33)*Sin(TW)*Sin(TWp)**2)
   G_sv3_sv2c_z_1_zp_1 = (0,-1)*((0,1)*g2*gp*Ql1*ZV21*conjg(ZV31)*Cos(TW)*Cos(TWp &
      )**2 + (0,1)*g2*gp*Ql2*ZV22*conjg(ZV32)*Cos(TW)*Cos(TWp)**2 + (0,1)*g2*gp*Ql3*ZV23* &
      conjg(ZV33)*Cos(TW)*Cos(TWp)**2 + (0,1)*g1*gp*Ql1*ZV21*conjg(ZV31)*Cos(TWp)**2*Sin(TW &
      ) + (0,1)*g1*gp*Ql2*ZV22*conjg(ZV32)*Cos(TWp)**2*Sin(TW) + (0,1)*g1*gp*Ql3*ZV23*conjg &
      (ZV33)*Cos(TWp)**2*Sin(TW) + (0,2)*gp**2*Ql1**2*ZV21*conjg(ZV31)*Cos(TWp)*Sin(TWp &
      ) + (0,2)*gp**2*Ql2**2*ZV22*conjg(ZV32)*Cos(TWp)*Sin(TWp) + (0,2)*gp**2*Ql3**2*ZV23* &
      conjg(ZV33)*Cos(TWp)*Sin(TWp) - (0,0.5_default)*g2**2*ZV21*conjg(ZV31)*Cos(TW)**2*Cos &
      (TWp)*Sin(TWp) - (0,0.5_default)*g2**2*ZV22*conjg(ZV32)*Cos(TW)**2*Cos(TWp)*Sin( &
      TWp) - (0,0.5_default)*g2**2*ZV23*conjg(ZV33)*Cos(TW)**2*Cos(TWp)*Sin(TWp) - (0,1)* &
      g1*g2*ZV21*conjg(ZV31)*Cos(TW)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,1)*g1*g2*ZV22*conjg( &
      ZV32)*Cos(TW)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,1)*g1*g2*ZV23*conjg(ZV33)*Cos(TW)*Cos( &
      TWp)*Sin(TW)*Sin(TWp) - (0,0.5_default)*g1**2*ZV21*conjg(ZV31)*Cos(TWp)*Sin(TW)**2* &
      Sin(TWp) - (0,0.5_default)*g1**2*ZV22*conjg(ZV32)*Cos(TWp)*Sin(TW)**2*Sin(TWp) - (0 &
      ,0.5_default)*g1**2*ZV23*conjg(ZV33)*Cos(TWp)*Sin(TW)**2*Sin(TWp) - (0,1)*g2*gp* &
      Ql1*ZV21*conjg(ZV31)*Cos(TW)*Sin(TWp)**2 - (0,1)*g2*gp*Ql2*ZV22*conjg(ZV32)*Cos(TW &
      )*Sin(TWp)**2 - (0,1)*g2*gp*Ql3*ZV23*conjg(ZV33)*Cos(TW)*Sin(TWp)**2 - (0,1)*g1*gp &
      *Ql1*ZV21*conjg(ZV31)*Sin(TW)*Sin(TWp)**2 - (0,1)*g1*gp*Ql2*ZV22*conjg(ZV32)*Sin( &
      TW)*Sin(TWp)**2 - (0,1)*g1*gp*Ql3*ZV23*conjg(ZV33)*Sin(TW)*Sin(TWp)**2)
   G_sv3_sv3c_z_1_zp_1 = (0,-1)*((0,1)*g2*gp*Ql1*ZV31*conjg(ZV31)*Cos(TW)*Cos(TWp &
      )**2 + (0,1)*g2*gp*Ql2*ZV32*conjg(ZV32)*Cos(TW)*Cos(TWp)**2 + (0,1)*g2*gp*Ql3*ZV33* &
      conjg(ZV33)*Cos(TW)*Cos(TWp)**2 + (0,1)*g1*gp*Ql1*ZV31*conjg(ZV31)*Cos(TWp)**2*Sin(TW &
      ) + (0,1)*g1*gp*Ql2*ZV32*conjg(ZV32)*Cos(TWp)**2*Sin(TW) + (0,1)*g1*gp*Ql3*ZV33*conjg &
      (ZV33)*Cos(TWp)**2*Sin(TW) + (0,2)*gp**2*Ql1**2*ZV31*conjg(ZV31)*Cos(TWp)*Sin(TWp &
      ) + (0,2)*gp**2*Ql2**2*ZV32*conjg(ZV32)*Cos(TWp)*Sin(TWp) + (0,2)*gp**2*Ql3**2*ZV33* &
      conjg(ZV33)*Cos(TWp)*Sin(TWp) - (0,0.5_default)*g2**2*ZV31*conjg(ZV31)*Cos(TW)**2*Cos &
      (TWp)*Sin(TWp) - (0,0.5_default)*g2**2*ZV32*conjg(ZV32)*Cos(TW)**2*Cos(TWp)*Sin( &
      TWp) - (0,0.5_default)*g2**2*ZV33*conjg(ZV33)*Cos(TW)**2*Cos(TWp)*Sin(TWp) - (0,1)* &
      g1*g2*ZV31*conjg(ZV31)*Cos(TW)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,1)*g1*g2*ZV32*conjg( &
      ZV32)*Cos(TW)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,1)*g1*g2*ZV33*conjg(ZV33)*Cos(TW)*Cos( &
      TWp)*Sin(TW)*Sin(TWp) - (0,0.5_default)*g1**2*ZV31*conjg(ZV31)*Cos(TWp)*Sin(TW)**2* &
      Sin(TWp) - (0,0.5_default)*g1**2*ZV32*conjg(ZV32)*Cos(TWp)*Sin(TW)**2*Sin(TWp) - (0 &
      ,0.5_default)*g1**2*ZV33*conjg(ZV33)*Cos(TWp)*Sin(TW)**2*Sin(TWp) - (0,1)*g2*gp* &
      Ql1*ZV31*conjg(ZV31)*Cos(TW)*Sin(TWp)**2 - (0,1)*g2*gp*Ql2*ZV32*conjg(ZV32)*Cos(TW &
      )*Sin(TWp)**2 - (0,1)*g2*gp*Ql3*ZV33*conjg(ZV33)*Cos(TW)*Sin(TWp)**2 - (0,1)*g1*gp &
      *Ql1*ZV31*conjg(ZV31)*Sin(TW)*Sin(TWp)**2 - (0,1)*g1*gp*Ql2*ZV32*conjg(ZV32)*Sin( &
      TW)*Sin(TWp)**2 - (0,1)*g1*gp*Ql3*ZV33*conjg(ZV33)*Sin(TW)*Sin(TWp)**2)
   G_sv1_sv1c_zp_1_zp_1 = (0,-1)*((0,2)*gp**2*Ql1**2*ZV11*conjg(ZV11)*Cos(TWp)**2 &
       + (0,2)*gp**2*Ql2**2*ZV12*conjg(ZV12)*Cos(TWp)**2 + (0,2)*gp**2*Ql3**2*ZV13*conjg( &
      ZV13)*Cos(TWp)**2 - (0,2)*g2*gp*Ql1*ZV11*conjg(ZV11)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0, &
      2)*g2*gp*Ql2*ZV12*conjg(ZV12)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0,2)*g2*gp*Ql3*ZV13* &
      conjg(ZV13)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0,2)*g1*gp*Ql1*ZV11*conjg(ZV11)*Cos(TWp)*Sin &
      (TW)*Sin(TWp) - (0,2)*g1*gp*Ql2*ZV12*conjg(ZV12)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,2 &
      )*g1*gp*Ql3*ZV13*conjg(ZV13)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,0.5_default)*g2**2* &
      ZV11*conjg(ZV11)*Cos(TW)**2*Sin(TWp)**2 + (0,0.5_default)*g2**2*ZV12*conjg(ZV12)*Cos &
      (TW)**2*Sin(TWp)**2 + (0,0.5_default)*g2**2*ZV13*conjg(ZV13)*Cos(TW)**2*Sin(TWp &
      )**2 + (0,1)*g1*g2*ZV11*conjg(ZV11)*Cos(TW)*Sin(TW)*Sin(TWp)**2 + (0,1)*g1*g2*ZV12* &
      conjg(ZV12)*Cos(TW)*Sin(TW)*Sin(TWp)**2 + (0,1)*g1*g2*ZV13*conjg(ZV13)*Cos(TW)*Sin(TW &
      )*Sin(TWp)**2 + (0,0.5_default)*g1**2*ZV11*conjg(ZV11)*Sin(TW)**2*Sin(TWp)**2 + (0 &
      ,0.5_default)*g1**2*ZV12*conjg(ZV12)*Sin(TW)**2*Sin(TWp)**2 + (0,0.5_default)*g1 &
      **2*ZV13*conjg(ZV13)*Sin(TW)**2*Sin(TWp)**2)
   G_sv1_sv2c_zp_1_zp_1 = (0,-1)*((0,2)*gp**2*Ql1**2*ZV21*conjg(ZV11)*Cos(TWp)**2 &
       + (0,2)*gp**2*Ql2**2*ZV22*conjg(ZV12)*Cos(TWp)**2 + (0,2)*gp**2*Ql3**2*ZV23*conjg( &
      ZV13)*Cos(TWp)**2 - (0,2)*g2*gp*Ql1*ZV21*conjg(ZV11)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0, &
      2)*g2*gp*Ql2*ZV22*conjg(ZV12)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0,2)*g2*gp*Ql3*ZV23* &
      conjg(ZV13)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0,2)*g1*gp*Ql1*ZV21*conjg(ZV11)*Cos(TWp)*Sin &
      (TW)*Sin(TWp) - (0,2)*g1*gp*Ql2*ZV22*conjg(ZV12)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,2 &
      )*g1*gp*Ql3*ZV23*conjg(ZV13)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,0.5_default)*g2**2* &
      ZV21*conjg(ZV11)*Cos(TW)**2*Sin(TWp)**2 + (0,0.5_default)*g2**2*ZV22*conjg(ZV12)*Cos &
      (TW)**2*Sin(TWp)**2 + (0,0.5_default)*g2**2*ZV23*conjg(ZV13)*Cos(TW)**2*Sin(TWp &
      )**2 + (0,1)*g1*g2*ZV21*conjg(ZV11)*Cos(TW)*Sin(TW)*Sin(TWp)**2 + (0,1)*g1*g2*ZV22* &
      conjg(ZV12)*Cos(TW)*Sin(TW)*Sin(TWp)**2 + (0,1)*g1*g2*ZV23*conjg(ZV13)*Cos(TW)*Sin(TW &
      )*Sin(TWp)**2 + (0,0.5_default)*g1**2*ZV21*conjg(ZV11)*Sin(TW)**2*Sin(TWp)**2 + (0 &
      ,0.5_default)*g1**2*ZV22*conjg(ZV12)*Sin(TW)**2*Sin(TWp)**2 + (0,0.5_default)*g1 &
      **2*ZV23*conjg(ZV13)*Sin(TW)**2*Sin(TWp)**2)
   G_sv1_sv3c_zp_1_zp_1 = (0,-1)*((0,2)*gp**2*Ql1**2*ZV31*conjg(ZV11)*Cos(TWp)**2 &
       + (0,2)*gp**2*Ql2**2*ZV32*conjg(ZV12)*Cos(TWp)**2 + (0,2)*gp**2*Ql3**2*ZV33*conjg( &
      ZV13)*Cos(TWp)**2 - (0,2)*g2*gp*Ql1*ZV31*conjg(ZV11)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0, &
      2)*g2*gp*Ql2*ZV32*conjg(ZV12)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0,2)*g2*gp*Ql3*ZV33* &
      conjg(ZV13)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0,2)*g1*gp*Ql1*ZV31*conjg(ZV11)*Cos(TWp)*Sin &
      (TW)*Sin(TWp) - (0,2)*g1*gp*Ql2*ZV32*conjg(ZV12)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,2 &
      )*g1*gp*Ql3*ZV33*conjg(ZV13)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,0.5_default)*g2**2* &
      ZV31*conjg(ZV11)*Cos(TW)**2*Sin(TWp)**2 + (0,0.5_default)*g2**2*ZV32*conjg(ZV12)*Cos &
      (TW)**2*Sin(TWp)**2 + (0,0.5_default)*g2**2*ZV33*conjg(ZV13)*Cos(TW)**2*Sin(TWp &
      )**2 + (0,1)*g1*g2*ZV31*conjg(ZV11)*Cos(TW)*Sin(TW)*Sin(TWp)**2 + (0,1)*g1*g2*ZV32* &
      conjg(ZV12)*Cos(TW)*Sin(TW)*Sin(TWp)**2 + (0,1)*g1*g2*ZV33*conjg(ZV13)*Cos(TW)*Sin(TW &
      )*Sin(TWp)**2 + (0,0.5_default)*g1**2*ZV31*conjg(ZV11)*Sin(TW)**2*Sin(TWp)**2 + (0 &
      ,0.5_default)*g1**2*ZV32*conjg(ZV12)*Sin(TW)**2*Sin(TWp)**2 + (0,0.5_default)*g1 &
      **2*ZV33*conjg(ZV13)*Sin(TW)**2*Sin(TWp)**2)
   G_sv2_sv1c_zp_1_zp_1 = (0,-1)*((0,2)*gp**2*Ql1**2*ZV11*conjg(ZV21)*Cos(TWp)**2 &
       + (0,2)*gp**2*Ql2**2*ZV12*conjg(ZV22)*Cos(TWp)**2 + (0,2)*gp**2*Ql3**2*ZV13*conjg( &
      ZV23)*Cos(TWp)**2 - (0,2)*g2*gp*Ql1*ZV11*conjg(ZV21)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0, &
      2)*g2*gp*Ql2*ZV12*conjg(ZV22)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0,2)*g2*gp*Ql3*ZV13* &
      conjg(ZV23)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0,2)*g1*gp*Ql1*ZV11*conjg(ZV21)*Cos(TWp)*Sin &
      (TW)*Sin(TWp) - (0,2)*g1*gp*Ql2*ZV12*conjg(ZV22)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,2 &
      )*g1*gp*Ql3*ZV13*conjg(ZV23)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,0.5_default)*g2**2* &
      ZV11*conjg(ZV21)*Cos(TW)**2*Sin(TWp)**2 + (0,0.5_default)*g2**2*ZV12*conjg(ZV22)*Cos &
      (TW)**2*Sin(TWp)**2 + (0,0.5_default)*g2**2*ZV13*conjg(ZV23)*Cos(TW)**2*Sin(TWp &
      )**2 + (0,1)*g1*g2*ZV11*conjg(ZV21)*Cos(TW)*Sin(TW)*Sin(TWp)**2 + (0,1)*g1*g2*ZV12* &
      conjg(ZV22)*Cos(TW)*Sin(TW)*Sin(TWp)**2 + (0,1)*g1*g2*ZV13*conjg(ZV23)*Cos(TW)*Sin(TW &
      )*Sin(TWp)**2 + (0,0.5_default)*g1**2*ZV11*conjg(ZV21)*Sin(TW)**2*Sin(TWp)**2 + (0 &
      ,0.5_default)*g1**2*ZV12*conjg(ZV22)*Sin(TW)**2*Sin(TWp)**2 + (0,0.5_default)*g1 &
      **2*ZV13*conjg(ZV23)*Sin(TW)**2*Sin(TWp)**2)
   G_sv2_sv2c_zp_1_zp_1 = (0,-1)*((0,2)*gp**2*Ql1**2*ZV21*conjg(ZV21)*Cos(TWp)**2 &
       + (0,2)*gp**2*Ql2**2*ZV22*conjg(ZV22)*Cos(TWp)**2 + (0,2)*gp**2*Ql3**2*ZV23*conjg( &
      ZV23)*Cos(TWp)**2 - (0,2)*g2*gp*Ql1*ZV21*conjg(ZV21)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0, &
      2)*g2*gp*Ql2*ZV22*conjg(ZV22)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0,2)*g2*gp*Ql3*ZV23* &
      conjg(ZV23)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0,2)*g1*gp*Ql1*ZV21*conjg(ZV21)*Cos(TWp)*Sin &
      (TW)*Sin(TWp) - (0,2)*g1*gp*Ql2*ZV22*conjg(ZV22)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,2 &
      )*g1*gp*Ql3*ZV23*conjg(ZV23)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,0.5_default)*g2**2* &
      ZV21*conjg(ZV21)*Cos(TW)**2*Sin(TWp)**2 + (0,0.5_default)*g2**2*ZV22*conjg(ZV22)*Cos &
      (TW)**2*Sin(TWp)**2 + (0,0.5_default)*g2**2*ZV23*conjg(ZV23)*Cos(TW)**2*Sin(TWp &
      )**2 + (0,1)*g1*g2*ZV21*conjg(ZV21)*Cos(TW)*Sin(TW)*Sin(TWp)**2 + (0,1)*g1*g2*ZV22* &
      conjg(ZV22)*Cos(TW)*Sin(TW)*Sin(TWp)**2 + (0,1)*g1*g2*ZV23*conjg(ZV23)*Cos(TW)*Sin(TW &
      )*Sin(TWp)**2 + (0,0.5_default)*g1**2*ZV21*conjg(ZV21)*Sin(TW)**2*Sin(TWp)**2 + (0 &
      ,0.5_default)*g1**2*ZV22*conjg(ZV22)*Sin(TW)**2*Sin(TWp)**2 + (0,0.5_default)*g1 &
      **2*ZV23*conjg(ZV23)*Sin(TW)**2*Sin(TWp)**2)
   G_sv2_sv3c_zp_1_zp_1 = (0,-1)*((0,2)*gp**2*Ql1**2*ZV31*conjg(ZV21)*Cos(TWp)**2 &
       + (0,2)*gp**2*Ql2**2*ZV32*conjg(ZV22)*Cos(TWp)**2 + (0,2)*gp**2*Ql3**2*ZV33*conjg( &
      ZV23)*Cos(TWp)**2 - (0,2)*g2*gp*Ql1*ZV31*conjg(ZV21)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0, &
      2)*g2*gp*Ql2*ZV32*conjg(ZV22)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0,2)*g2*gp*Ql3*ZV33* &
      conjg(ZV23)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0,2)*g1*gp*Ql1*ZV31*conjg(ZV21)*Cos(TWp)*Sin &
      (TW)*Sin(TWp) - (0,2)*g1*gp*Ql2*ZV32*conjg(ZV22)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,2 &
      )*g1*gp*Ql3*ZV33*conjg(ZV23)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,0.5_default)*g2**2* &
      ZV31*conjg(ZV21)*Cos(TW)**2*Sin(TWp)**2 + (0,0.5_default)*g2**2*ZV32*conjg(ZV22)*Cos &
      (TW)**2*Sin(TWp)**2 + (0,0.5_default)*g2**2*ZV33*conjg(ZV23)*Cos(TW)**2*Sin(TWp &
      )**2 + (0,1)*g1*g2*ZV31*conjg(ZV21)*Cos(TW)*Sin(TW)*Sin(TWp)**2 + (0,1)*g1*g2*ZV32* &
      conjg(ZV22)*Cos(TW)*Sin(TW)*Sin(TWp)**2 + (0,1)*g1*g2*ZV33*conjg(ZV23)*Cos(TW)*Sin(TW &
      )*Sin(TWp)**2 + (0,0.5_default)*g1**2*ZV31*conjg(ZV21)*Sin(TW)**2*Sin(TWp)**2 + (0 &
      ,0.5_default)*g1**2*ZV32*conjg(ZV22)*Sin(TW)**2*Sin(TWp)**2 + (0,0.5_default)*g1 &
      **2*ZV33*conjg(ZV23)*Sin(TW)**2*Sin(TWp)**2)
   G_sv3_sv1c_zp_1_zp_1 = (0,-1)*((0,2)*gp**2*Ql1**2*ZV11*conjg(ZV31)*Cos(TWp)**2 &
       + (0,2)*gp**2*Ql2**2*ZV12*conjg(ZV32)*Cos(TWp)**2 + (0,2)*gp**2*Ql3**2*ZV13*conjg( &
      ZV33)*Cos(TWp)**2 - (0,2)*g2*gp*Ql1*ZV11*conjg(ZV31)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0, &
      2)*g2*gp*Ql2*ZV12*conjg(ZV32)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0,2)*g2*gp*Ql3*ZV13* &
      conjg(ZV33)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0,2)*g1*gp*Ql1*ZV11*conjg(ZV31)*Cos(TWp)*Sin &
      (TW)*Sin(TWp) - (0,2)*g1*gp*Ql2*ZV12*conjg(ZV32)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,2 &
      )*g1*gp*Ql3*ZV13*conjg(ZV33)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,0.5_default)*g2**2* &
      ZV11*conjg(ZV31)*Cos(TW)**2*Sin(TWp)**2 + (0,0.5_default)*g2**2*ZV12*conjg(ZV32)*Cos &
      (TW)**2*Sin(TWp)**2 + (0,0.5_default)*g2**2*ZV13*conjg(ZV33)*Cos(TW)**2*Sin(TWp &
      )**2 + (0,1)*g1*g2*ZV11*conjg(ZV31)*Cos(TW)*Sin(TW)*Sin(TWp)**2 + (0,1)*g1*g2*ZV12* &
      conjg(ZV32)*Cos(TW)*Sin(TW)*Sin(TWp)**2 + (0,1)*g1*g2*ZV13*conjg(ZV33)*Cos(TW)*Sin(TW &
      )*Sin(TWp)**2 + (0,0.5_default)*g1**2*ZV11*conjg(ZV31)*Sin(TW)**2*Sin(TWp)**2 + (0 &
      ,0.5_default)*g1**2*ZV12*conjg(ZV32)*Sin(TW)**2*Sin(TWp)**2 + (0,0.5_default)*g1 &
      **2*ZV13*conjg(ZV33)*Sin(TW)**2*Sin(TWp)**2)
   G_sv3_sv2c_zp_1_zp_1 = (0,-1)*((0,2)*gp**2*Ql1**2*ZV21*conjg(ZV31)*Cos(TWp)**2 &
       + (0,2)*gp**2*Ql2**2*ZV22*conjg(ZV32)*Cos(TWp)**2 + (0,2)*gp**2*Ql3**2*ZV23*conjg( &
      ZV33)*Cos(TWp)**2 - (0,2)*g2*gp*Ql1*ZV21*conjg(ZV31)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0, &
      2)*g2*gp*Ql2*ZV22*conjg(ZV32)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0,2)*g2*gp*Ql3*ZV23* &
      conjg(ZV33)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0,2)*g1*gp*Ql1*ZV21*conjg(ZV31)*Cos(TWp)*Sin &
      (TW)*Sin(TWp) - (0,2)*g1*gp*Ql2*ZV22*conjg(ZV32)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,2 &
      )*g1*gp*Ql3*ZV23*conjg(ZV33)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,0.5_default)*g2**2* &
      ZV21*conjg(ZV31)*Cos(TW)**2*Sin(TWp)**2 + (0,0.5_default)*g2**2*ZV22*conjg(ZV32)*Cos &
      (TW)**2*Sin(TWp)**2 + (0,0.5_default)*g2**2*ZV23*conjg(ZV33)*Cos(TW)**2*Sin(TWp &
      )**2 + (0,1)*g1*g2*ZV21*conjg(ZV31)*Cos(TW)*Sin(TW)*Sin(TWp)**2 + (0,1)*g1*g2*ZV22* &
      conjg(ZV32)*Cos(TW)*Sin(TW)*Sin(TWp)**2 + (0,1)*g1*g2*ZV23*conjg(ZV33)*Cos(TW)*Sin(TW &
      )*Sin(TWp)**2 + (0,0.5_default)*g1**2*ZV21*conjg(ZV31)*Sin(TW)**2*Sin(TWp)**2 + (0 &
      ,0.5_default)*g1**2*ZV22*conjg(ZV32)*Sin(TW)**2*Sin(TWp)**2 + (0,0.5_default)*g1 &
      **2*ZV23*conjg(ZV33)*Sin(TW)**2*Sin(TWp)**2)
   G_sv3_sv3c_zp_1_zp_1 = (0,-1)*((0,2)*gp**2*Ql1**2*ZV31*conjg(ZV31)*Cos(TWp)**2 &
       + (0,2)*gp**2*Ql2**2*ZV32*conjg(ZV32)*Cos(TWp)**2 + (0,2)*gp**2*Ql3**2*ZV33*conjg( &
      ZV33)*Cos(TWp)**2 - (0,2)*g2*gp*Ql1*ZV31*conjg(ZV31)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0, &
      2)*g2*gp*Ql2*ZV32*conjg(ZV32)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0,2)*g2*gp*Ql3*ZV33* &
      conjg(ZV33)*Cos(TW)*Cos(TWp)*Sin(TWp) - (0,2)*g1*gp*Ql1*ZV31*conjg(ZV31)*Cos(TWp)*Sin &
      (TW)*Sin(TWp) - (0,2)*g1*gp*Ql2*ZV32*conjg(ZV32)*Cos(TWp)*Sin(TW)*Sin(TWp) - (0,2 &
      )*g1*gp*Ql3*ZV33*conjg(ZV33)*Cos(TWp)*Sin(TW)*Sin(TWp) + (0,0.5_default)*g2**2* &
      ZV31*conjg(ZV31)*Cos(TW)**2*Sin(TWp)**2 + (0,0.5_default)*g2**2*ZV32*conjg(ZV32)*Cos &
      (TW)**2*Sin(TWp)**2 + (0,0.5_default)*g2**2*ZV33*conjg(ZV33)*Cos(TW)**2*Sin(TWp &
      )**2 + (0,1)*g1*g2*ZV31*conjg(ZV31)*Cos(TW)*Sin(TW)*Sin(TWp)**2 + (0,1)*g1*g2*ZV32* &
      conjg(ZV32)*Cos(TW)*Sin(TW)*Sin(TWp)**2 + (0,1)*g1*g2*ZV33*conjg(ZV33)*Cos(TW)*Sin(TW &
      )*Sin(TWp)**2 + (0,0.5_default)*g1**2*ZV31*conjg(ZV31)*Sin(TW)**2*Sin(TWp)**2 + (0 &
      ,0.5_default)*g1**2*ZV32*conjg(ZV32)*Sin(TW)**2*Sin(TWp)**2 + (0,0.5_default)*g1 &
      **2*ZV33*conjg(ZV33)*Sin(TW)**2*Sin(TWp)**2)
   G_z_1_ah3_h1 = (0,-1)*((g2*conjg(ZA31)*conjg(ZH11)*Cos(TW)*Cos(TWp))/2._default &
       - (g2*conjg(ZA32)*conjg(ZH12)*Cos(TW)*Cos(TWp))/2._default + (g1*conjg(ZA31)*conjg( &
      ZH11)*Cos(TWp)*Sin(TW))/2._default - (g1*conjg(ZA32)*conjg(ZH12)*Cos(TWp)*Sin(TW))/ &
      2._default + gp*QHd*conjg(ZA31)*conjg(ZH11)*Sin(TWp) + gp*QHu*conjg(ZA32)*conjg(ZH12)*Sin( &
      TWp) + gp*Qs*conjg(ZA33)*conjg(ZH13)*Sin(TWp))
   G_z_1_ah3_h2 = (0,-1)*((g2*conjg(ZA31)*conjg(ZH21)*Cos(TW)*Cos(TWp))/2._default &
       - (g2*conjg(ZA32)*conjg(ZH22)*Cos(TW)*Cos(TWp))/2._default + (g1*conjg(ZA31)*conjg( &
      ZH21)*Cos(TWp)*Sin(TW))/2._default - (g1*conjg(ZA32)*conjg(ZH22)*Cos(TWp)*Sin(TW))/ &
      2._default + gp*QHd*conjg(ZA31)*conjg(ZH21)*Sin(TWp) + gp*QHu*conjg(ZA32)*conjg(ZH22)*Sin( &
      TWp) + gp*Qs*conjg(ZA33)*conjg(ZH23)*Sin(TWp))
   G_z_1_ah3_h3 = (0,-1)*((g2*conjg(ZA31)*conjg(ZH31)*Cos(TW)*Cos(TWp))/2._default &
       - (g2*conjg(ZA32)*conjg(ZH32)*Cos(TW)*Cos(TWp))/2._default + (g1*conjg(ZA31)*conjg( &
      ZH31)*Cos(TWp)*Sin(TW))/2._default - (g1*conjg(ZA32)*conjg(ZH32)*Cos(TWp)*Sin(TW))/ &
      2._default + gp*QHd*conjg(ZA31)*conjg(ZH31)*Sin(TWp) + gp*QHu*conjg(ZA32)*conjg(ZH32)*Sin( &
      TWp) + gp*Qs*conjg(ZA33)*conjg(ZH33)*Sin(TWp))
   G_zp_1_ah3_h1 = (0,-1)*(gp*QHd*conjg(ZA31)*conjg(ZH11)*Cos(TWp) + gp*QHu*conjg( &
      ZA32)*conjg(ZH12)*Cos(TWp) + gp*Qs*conjg(ZA33)*conjg(ZH13)*Cos(TWp) - (g2*conjg(ZA31 &
      )*conjg(ZH11)*Cos(TW)*Sin(TWp))/2._default + (g2*conjg(ZA32)*conjg(ZH12)*Cos(TW)* &
      Sin(TWp))/2._default - (g1*conjg(ZA31)*conjg(ZH11)*Sin(TW)*Sin(TWp))/2._default + ( &
      g1*conjg(ZA32)*conjg(ZH12)*Sin(TW)*Sin(TWp))/2._default)
   G_zp_1_ah3_h2 = (0,-1)*(gp*QHd*conjg(ZA31)*conjg(ZH21)*Cos(TWp) + gp*QHu*conjg( &
      ZA32)*conjg(ZH22)*Cos(TWp) + gp*Qs*conjg(ZA33)*conjg(ZH23)*Cos(TWp) - (g2*conjg(ZA31 &
      )*conjg(ZH21)*Cos(TW)*Sin(TWp))/2._default + (g2*conjg(ZA32)*conjg(ZH22)*Cos(TW)* &
      Sin(TWp))/2._default - (g1*conjg(ZA31)*conjg(ZH21)*Sin(TW)*Sin(TWp))/2._default + ( &
      g1*conjg(ZA32)*conjg(ZH22)*Sin(TW)*Sin(TWp))/2._default)
   G_zp_1_ah3_h3 = (0,-1)*(gp*QHd*conjg(ZA31)*conjg(ZH31)*Cos(TWp) + gp*QHu*conjg( &
      ZA32)*conjg(ZH32)*Cos(TWp) + gp*Qs*conjg(ZA33)*conjg(ZH33)*Cos(TWp) - (g2*conjg(ZA31 &
      )*conjg(ZH31)*Cos(TW)*Sin(TWp))/2._default + (g2*conjg(ZA32)*conjg(ZH32)*Cos(TW)* &
      Sin(TWp))/2._default - (g1*conjg(ZA31)*conjg(ZH31)*Sin(TW)*Sin(TWp))/2._default + ( &
      g1*conjg(ZA32)*conjg(ZH32)*Sin(TW)*Sin(TWp))/2._default)
   G_wmc_ah3_hm2 = (0,-1)*((g2*ZP21*conjg(ZA31))/2._default + (g2*ZP22*conjg(ZA32 &
      ))/2._default)
   G_wmc_h1_hm2 = (0,-1)*((0,0.5_default)*g2*ZP21*conjg(ZH11) - (0,0.5_default)*g2* &
      ZP22*conjg(ZH12))
   G_wmc_h2_hm2 = (0,-1)*((0,0.5_default)*g2*ZP21*conjg(ZH21) - (0,0.5_default)*g2* &
      ZP22*conjg(ZH22))
   G_wmc_h3_hm2 = (0,-1)*((0,0.5_default)*g2*ZP21*conjg(ZH31) - (0,0.5_default)*g2* &
      ZP22*conjg(ZH32))
   G_wm_1_h1_hm2c = (0,-1)*((0,-0.5_default)*g2*ZP21*conjg(ZH11) + (0,0.5_default)* &
      g2*ZP22*conjg(ZH12))
   G_wm_1_h2_hm2c = (0,-1)*((0,-0.5_default)*g2*ZP21*conjg(ZH21) + (0,0.5_default)* &
      g2*ZP22*conjg(ZH22))
   G_wm_1_h3_hm2c = (0,-1)*((0,-0.5_default)*g2*ZP21*conjg(ZH31) + (0,0.5_default)* &
      g2*ZP22*conjg(ZH32))
   G_a_1_hm2_hm2c = (0,-1)*((0,0.5_default)*g1*ZP21**2*Cos(TW) + (0,0.5_default)*g1 &
      *ZP22**2*Cos(TW) + (0,0.5_default)*g2*ZP21**2*Sin(TW) + (0,0.5_default)*g2*ZP22** &
      2*Sin(TW))
   G_z_1_hm2_hm2c = (0,-1)*((0,0.5_default)*g2*ZP21**2*Cos(TW)*Cos(TWp) + (0, &
      0.5_default)*g2*ZP22**2*Cos(TW)*Cos(TWp) - (0,0.5_default)*g1*ZP21**2*Cos(TWp)*Sin(TW) - (0 &
      ,0.5_default)*g1*ZP22**2*Cos(TWp)*Sin(TW) - (0,1)*gp*QHd*ZP21**2*Sin(TWp) + (0,1 &
      )*gp*QHu*ZP22**2*Sin(TWp))
   G_zp_1_hm2_hm2c = (0,-1)*((0,-1)*gp*QHd*ZP21**2*Cos(TWp) + (0,1)*gp*QHu*ZP22**2* &
      Cos(TWp) - (0,0.5_default)*g2*ZP21**2*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZP22**2 &
      *Cos(TW)*Sin(TWp) + (0,0.5_default)*g1*ZP21**2*Sin(TW)*Sin(TWp) + (0,0.5_default &
      )*g1*ZP22**2*Sin(TW)*Sin(TWp))
   G_g_1_sd1_sd1c = -(g3/Sqrt (2._default))
   G_a_1_sd1_sd1c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD11*conjg(ZD11)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD12*conjg(ZD12)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD13*conjg(ZD13)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD14*conjg( &
      ZD14)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD15*conjg(ZD15)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD16*conjg(ZD16)*Cos(TW) + (0,0.5_default)*g2*ZD11*conjg(ZD11)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD12*conjg(ZD12)*Sin(TW) + (0,0.5_default)*g2*ZD13*conjg(ZD13)* &
      Sin(TW))
   G_a_1_sd1_sd2c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD21*conjg(ZD11)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD22*conjg(ZD12)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD23*conjg(ZD13)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD24*conjg( &
      ZD14)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD25*conjg(ZD15)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD26*conjg(ZD16)*Cos(TW) + (0,0.5_default)*g2*ZD21*conjg(ZD11)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD22*conjg(ZD12)*Sin(TW) + (0,0.5_default)*g2*ZD23*conjg(ZD13)* &
      Sin(TW))
   G_a_1_sd1_sd3c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD31*conjg(ZD11)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD32*conjg(ZD12)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD33*conjg(ZD13)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD34*conjg( &
      ZD14)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD35*conjg(ZD15)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD36*conjg(ZD16)*Cos(TW) + (0,0.5_default)*g2*ZD31*conjg(ZD11)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD32*conjg(ZD12)*Sin(TW) + (0,0.5_default)*g2*ZD33*conjg(ZD13)* &
      Sin(TW))
   G_a_1_sd1_sd4c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD41*conjg(ZD11)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD42*conjg(ZD12)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD43*conjg(ZD13)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD44*conjg( &
      ZD14)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD45*conjg(ZD15)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD46*conjg(ZD16)*Cos(TW) + (0,0.5_default)*g2*ZD41*conjg(ZD11)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD42*conjg(ZD12)*Sin(TW) + (0,0.5_default)*g2*ZD43*conjg(ZD13)* &
      Sin(TW))
   G_a_1_sd1_sd5c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD51*conjg(ZD11)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD52*conjg(ZD12)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD53*conjg(ZD13)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD54*conjg( &
      ZD14)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD55*conjg(ZD15)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD56*conjg(ZD16)*Cos(TW) + (0,0.5_default)*g2*ZD51*conjg(ZD11)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD52*conjg(ZD12)*Sin(TW) + (0,0.5_default)*g2*ZD53*conjg(ZD13)* &
      Sin(TW))
   G_a_1_sd1_sd6c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD61*conjg(ZD11)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD62*conjg(ZD12)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD63*conjg(ZD13)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD64*conjg( &
      ZD14)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD65*conjg(ZD15)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD66*conjg(ZD16)*Cos(TW) + (0,0.5_default)*g2*ZD61*conjg(ZD11)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD62*conjg(ZD12)*Sin(TW) + (0,0.5_default)*g2*ZD63*conjg(ZD13)* &
      Sin(TW))
   G_a_1_sd2_sd1c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD11*conjg(ZD21)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD12*conjg(ZD22)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD13*conjg(ZD23)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD14*conjg( &
      ZD24)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD15*conjg(ZD25)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD16*conjg(ZD26)*Cos(TW) + (0,0.5_default)*g2*ZD11*conjg(ZD21)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD12*conjg(ZD22)*Sin(TW) + (0,0.5_default)*g2*ZD13*conjg(ZD23)* &
      Sin(TW))
   G_a_1_sd2_sd2c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD21*conjg(ZD21)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD22*conjg(ZD22)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD23*conjg(ZD23)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD24*conjg( &
      ZD24)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD25*conjg(ZD25)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD26*conjg(ZD26)*Cos(TW) + (0,0.5_default)*g2*ZD21*conjg(ZD21)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD22*conjg(ZD22)*Sin(TW) + (0,0.5_default)*g2*ZD23*conjg(ZD23)* &
      Sin(TW))
   G_a_1_sd2_sd3c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD31*conjg(ZD21)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD32*conjg(ZD22)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD33*conjg(ZD23)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD34*conjg( &
      ZD24)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD35*conjg(ZD25)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD36*conjg(ZD26)*Cos(TW) + (0,0.5_default)*g2*ZD31*conjg(ZD21)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD32*conjg(ZD22)*Sin(TW) + (0,0.5_default)*g2*ZD33*conjg(ZD23)* &
      Sin(TW))
   G_a_1_sd2_sd4c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD41*conjg(ZD21)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD42*conjg(ZD22)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD43*conjg(ZD23)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD44*conjg( &
      ZD24)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD45*conjg(ZD25)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD46*conjg(ZD26)*Cos(TW) + (0,0.5_default)*g2*ZD41*conjg(ZD21)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD42*conjg(ZD22)*Sin(TW) + (0,0.5_default)*g2*ZD43*conjg(ZD23)* &
      Sin(TW))
   G_a_1_sd2_sd5c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD51*conjg(ZD21)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD52*conjg(ZD22)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD53*conjg(ZD23)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD54*conjg( &
      ZD24)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD55*conjg(ZD25)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD56*conjg(ZD26)*Cos(TW) + (0,0.5_default)*g2*ZD51*conjg(ZD21)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD52*conjg(ZD22)*Sin(TW) + (0,0.5_default)*g2*ZD53*conjg(ZD23)* &
      Sin(TW))
   G_a_1_sd2_sd6c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD61*conjg(ZD21)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD62*conjg(ZD22)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD63*conjg(ZD23)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD64*conjg( &
      ZD24)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD65*conjg(ZD25)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD66*conjg(ZD26)*Cos(TW) + (0,0.5_default)*g2*ZD61*conjg(ZD21)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD62*conjg(ZD22)*Sin(TW) + (0,0.5_default)*g2*ZD63*conjg(ZD23)* &
      Sin(TW))
   G_a_1_sd3_sd1c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD11*conjg(ZD31)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD12*conjg(ZD32)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD13*conjg(ZD33)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD14*conjg( &
      ZD34)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD15*conjg(ZD35)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD16*conjg(ZD36)*Cos(TW) + (0,0.5_default)*g2*ZD11*conjg(ZD31)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD12*conjg(ZD32)*Sin(TW) + (0,0.5_default)*g2*ZD13*conjg(ZD33)* &
      Sin(TW))
   G_a_1_sd3_sd2c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD21*conjg(ZD31)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD22*conjg(ZD32)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD23*conjg(ZD33)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD24*conjg( &
      ZD34)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD25*conjg(ZD35)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD26*conjg(ZD36)*Cos(TW) + (0,0.5_default)*g2*ZD21*conjg(ZD31)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD22*conjg(ZD32)*Sin(TW) + (0,0.5_default)*g2*ZD23*conjg(ZD33)* &
      Sin(TW))
   G_a_1_sd3_sd3c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD31*conjg(ZD31)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD32*conjg(ZD32)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD33*conjg(ZD33)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD34*conjg( &
      ZD34)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD35*conjg(ZD35)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD36*conjg(ZD36)*Cos(TW) + (0,0.5_default)*g2*ZD31*conjg(ZD31)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD32*conjg(ZD32)*Sin(TW) + (0,0.5_default)*g2*ZD33*conjg(ZD33)* &
      Sin(TW))
   G_a_1_sd3_sd4c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD41*conjg(ZD31)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD42*conjg(ZD32)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD43*conjg(ZD33)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD44*conjg( &
      ZD34)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD45*conjg(ZD35)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD46*conjg(ZD36)*Cos(TW) + (0,0.5_default)*g2*ZD41*conjg(ZD31)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD42*conjg(ZD32)*Sin(TW) + (0,0.5_default)*g2*ZD43*conjg(ZD33)* &
      Sin(TW))
   G_a_1_sd3_sd5c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD51*conjg(ZD31)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD52*conjg(ZD32)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD53*conjg(ZD33)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD54*conjg( &
      ZD34)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD55*conjg(ZD35)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD56*conjg(ZD36)*Cos(TW) + (0,0.5_default)*g2*ZD51*conjg(ZD31)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD52*conjg(ZD32)*Sin(TW) + (0,0.5_default)*g2*ZD53*conjg(ZD33)* &
      Sin(TW))
   G_a_1_sd3_sd6c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD61*conjg(ZD31)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD62*conjg(ZD32)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD63*conjg(ZD33)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD64*conjg( &
      ZD34)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD65*conjg(ZD35)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD66*conjg(ZD36)*Cos(TW) + (0,0.5_default)*g2*ZD61*conjg(ZD31)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD62*conjg(ZD32)*Sin(TW) + (0,0.5_default)*g2*ZD63*conjg(ZD33)* &
      Sin(TW))
   G_a_1_sd4_sd1c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD11*conjg(ZD41)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD12*conjg(ZD42)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD13*conjg(ZD43)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD14*conjg( &
      ZD44)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD15*conjg(ZD45)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD16*conjg(ZD46)*Cos(TW) + (0,0.5_default)*g2*ZD11*conjg(ZD41)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD12*conjg(ZD42)*Sin(TW) + (0,0.5_default)*g2*ZD13*conjg(ZD43)* &
      Sin(TW))
   G_a_1_sd4_sd2c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD21*conjg(ZD41)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD22*conjg(ZD42)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD23*conjg(ZD43)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD24*conjg( &
      ZD44)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD25*conjg(ZD45)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD26*conjg(ZD46)*Cos(TW) + (0,0.5_default)*g2*ZD21*conjg(ZD41)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD22*conjg(ZD42)*Sin(TW) + (0,0.5_default)*g2*ZD23*conjg(ZD43)* &
      Sin(TW))
   G_a_1_sd4_sd3c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD31*conjg(ZD41)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD32*conjg(ZD42)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD33*conjg(ZD43)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD34*conjg( &
      ZD44)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD35*conjg(ZD45)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD36*conjg(ZD46)*Cos(TW) + (0,0.5_default)*g2*ZD31*conjg(ZD41)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD32*conjg(ZD42)*Sin(TW) + (0,0.5_default)*g2*ZD33*conjg(ZD43)* &
      Sin(TW))
   G_a_1_sd4_sd4c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD41*conjg(ZD41)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD42*conjg(ZD42)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD43*conjg(ZD43)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD44*conjg( &
      ZD44)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD45*conjg(ZD45)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD46*conjg(ZD46)*Cos(TW) + (0,0.5_default)*g2*ZD41*conjg(ZD41)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD42*conjg(ZD42)*Sin(TW) + (0,0.5_default)*g2*ZD43*conjg(ZD43)* &
      Sin(TW))
   G_a_1_sd4_sd5c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD51*conjg(ZD41)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD52*conjg(ZD42)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD53*conjg(ZD43)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD54*conjg( &
      ZD44)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD55*conjg(ZD45)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD56*conjg(ZD46)*Cos(TW) + (0,0.5_default)*g2*ZD51*conjg(ZD41)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD52*conjg(ZD42)*Sin(TW) + (0,0.5_default)*g2*ZD53*conjg(ZD43)* &
      Sin(TW))
   G_a_1_sd4_sd6c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD61*conjg(ZD41)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD62*conjg(ZD42)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD63*conjg(ZD43)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD64*conjg( &
      ZD44)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD65*conjg(ZD45)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD66*conjg(ZD46)*Cos(TW) + (0,0.5_default)*g2*ZD61*conjg(ZD41)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD62*conjg(ZD42)*Sin(TW) + (0,0.5_default)*g2*ZD63*conjg(ZD43)* &
      Sin(TW))
   G_a_1_sd5_sd1c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD11*conjg(ZD51)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD12*conjg(ZD52)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD13*conjg(ZD53)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD14*conjg( &
      ZD54)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD15*conjg(ZD55)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD16*conjg(ZD56)*Cos(TW) + (0,0.5_default)*g2*ZD11*conjg(ZD51)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD12*conjg(ZD52)*Sin(TW) + (0,0.5_default)*g2*ZD13*conjg(ZD53)* &
      Sin(TW))
   G_a_1_sd5_sd2c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD21*conjg(ZD51)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD22*conjg(ZD52)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD23*conjg(ZD53)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD24*conjg( &
      ZD54)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD25*conjg(ZD55)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD26*conjg(ZD56)*Cos(TW) + (0,0.5_default)*g2*ZD21*conjg(ZD51)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD22*conjg(ZD52)*Sin(TW) + (0,0.5_default)*g2*ZD23*conjg(ZD53)* &
      Sin(TW))
   G_a_1_sd5_sd3c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD31*conjg(ZD51)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD32*conjg(ZD52)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD33*conjg(ZD53)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD34*conjg( &
      ZD54)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD35*conjg(ZD55)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD36*conjg(ZD56)*Cos(TW) + (0,0.5_default)*g2*ZD31*conjg(ZD51)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD32*conjg(ZD52)*Sin(TW) + (0,0.5_default)*g2*ZD33*conjg(ZD53)* &
      Sin(TW))
   G_a_1_sd5_sd4c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD41*conjg(ZD51)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD42*conjg(ZD52)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD43*conjg(ZD53)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD44*conjg( &
      ZD54)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD45*conjg(ZD55)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD46*conjg(ZD56)*Cos(TW) + (0,0.5_default)*g2*ZD41*conjg(ZD51)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD42*conjg(ZD52)*Sin(TW) + (0,0.5_default)*g2*ZD43*conjg(ZD53)* &
      Sin(TW))
   G_a_1_sd5_sd5c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD51*conjg(ZD51)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD52*conjg(ZD52)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD53*conjg(ZD53)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD54*conjg( &
      ZD54)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD55*conjg(ZD55)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD56*conjg(ZD56)*Cos(TW) + (0,0.5_default)*g2*ZD51*conjg(ZD51)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD52*conjg(ZD52)*Sin(TW) + (0,0.5_default)*g2*ZD53*conjg(ZD53)* &
      Sin(TW))
   G_a_1_sd5_sd6c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD61*conjg(ZD51)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD62*conjg(ZD52)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD63*conjg(ZD53)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD64*conjg( &
      ZD54)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD65*conjg(ZD55)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD66*conjg(ZD56)*Cos(TW) + (0,0.5_default)*g2*ZD61*conjg(ZD51)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD62*conjg(ZD52)*Sin(TW) + (0,0.5_default)*g2*ZD63*conjg(ZD53)* &
      Sin(TW))
   G_a_1_sd6_sd1c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD11*conjg(ZD61)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD12*conjg(ZD62)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD13*conjg(ZD63)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD14*conjg( &
      ZD64)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD15*conjg(ZD65)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD16*conjg(ZD66)*Cos(TW) + (0,0.5_default)*g2*ZD11*conjg(ZD61)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD12*conjg(ZD62)*Sin(TW) + (0,0.5_default)*g2*ZD13*conjg(ZD63)* &
      Sin(TW))
   G_a_1_sd6_sd2c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD21*conjg(ZD61)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD22*conjg(ZD62)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD23*conjg(ZD63)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD24*conjg( &
      ZD64)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD25*conjg(ZD65)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD26*conjg(ZD66)*Cos(TW) + (0,0.5_default)*g2*ZD21*conjg(ZD61)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD22*conjg(ZD62)*Sin(TW) + (0,0.5_default)*g2*ZD23*conjg(ZD63)* &
      Sin(TW))
   G_a_1_sd6_sd3c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD31*conjg(ZD61)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD32*conjg(ZD62)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD33*conjg(ZD63)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD34*conjg( &
      ZD64)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD35*conjg(ZD65)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD36*conjg(ZD66)*Cos(TW) + (0,0.5_default)*g2*ZD31*conjg(ZD61)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD32*conjg(ZD62)*Sin(TW) + (0,0.5_default)*g2*ZD33*conjg(ZD63)* &
      Sin(TW))
   G_a_1_sd6_sd4c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD41*conjg(ZD61)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD42*conjg(ZD62)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD43*conjg(ZD63)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD44*conjg( &
      ZD64)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD45*conjg(ZD65)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD46*conjg(ZD66)*Cos(TW) + (0,0.5_default)*g2*ZD41*conjg(ZD61)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD42*conjg(ZD62)*Sin(TW) + (0,0.5_default)*g2*ZD43*conjg(ZD63)* &
      Sin(TW))
   G_a_1_sd6_sd5c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD51*conjg(ZD61)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD52*conjg(ZD62)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD53*conjg(ZD63)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD54*conjg( &
      ZD64)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD55*conjg(ZD65)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD56*conjg(ZD66)*Cos(TW) + (0,0.5_default)*g2*ZD51*conjg(ZD61)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD52*conjg(ZD62)*Sin(TW) + (0,0.5_default)*g2*ZD53*conjg(ZD63)* &
      Sin(TW))
   G_a_1_sd6_sd6c = (0,-1)*((0,-0.16666666666666666_default)*g1*ZD61*conjg(ZD61)* &
      Cos(TW) - (0,0.16666666666666666_default)*g1*ZD62*conjg(ZD62)*Cos(TW) - (0, &
      0.16666666666666666_default)*g1*ZD63*conjg(ZD63)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD64*conjg( &
      ZD64)*Cos(TW) + (0,0.3333333333333333_default)*g1*ZD65*conjg(ZD65)*Cos(TW) + (0, &
      0.3333333333333333_default)*g1*ZD66*conjg(ZD66)*Cos(TW) + (0,0.5_default)*g2*ZD61*conjg(ZD61)*Sin(TW) + (0 &
      ,0.5_default)*g2*ZD62*conjg(ZD62)*Sin(TW) + (0,0.5_default)*g2*ZD63*conjg(ZD63)* &
      Sin(TW))
   G_z_1_sd1_sd1c = (0,-1)*((0,0.5_default)*g2*ZD11*conjg(ZD11)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD12*conjg(ZD12)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD13* &
      conjg(ZD13)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD11*conjg(ZD11)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD12*conjg(ZD12)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD13*conjg(ZD13)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD14*conjg(ZD14)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD15* &
      conjg(ZD15)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD16*conjg(ZD16)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD11*conjg(ZD11)*Sin(TWp) - (0,1)*gp*Qq*ZD12*conjg( &
      ZD12)*Sin(TWp) - (0,1)*gp*Qq*ZD13*conjg(ZD13)*Sin(TWp) + (0,1)*gp*Qd*ZD14*conjg(ZD14 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD15*conjg(ZD15)*Sin(TWp) + (0,1)*gp*Qd*ZD16*conjg(ZD16)* &
      Sin(TWp))
   G_z_1_sd1_sd2c = (0,-1)*((0,0.5_default)*g2*ZD21*conjg(ZD11)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD22*conjg(ZD12)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD23* &
      conjg(ZD13)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD21*conjg(ZD11)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD22*conjg(ZD12)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD23*conjg(ZD13)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD24*conjg(ZD14)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD25* &
      conjg(ZD15)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD26*conjg(ZD16)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD21*conjg(ZD11)*Sin(TWp) - (0,1)*gp*Qq*ZD22*conjg( &
      ZD12)*Sin(TWp) - (0,1)*gp*Qq*ZD23*conjg(ZD13)*Sin(TWp) + (0,1)*gp*Qd*ZD24*conjg(ZD14 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD25*conjg(ZD15)*Sin(TWp) + (0,1)*gp*Qd*ZD26*conjg(ZD16)* &
      Sin(TWp))
   G_z_1_sd1_sd3c = (0,-1)*((0,0.5_default)*g2*ZD31*conjg(ZD11)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD32*conjg(ZD12)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD33* &
      conjg(ZD13)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD31*conjg(ZD11)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD32*conjg(ZD12)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD33*conjg(ZD13)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD34*conjg(ZD14)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD35* &
      conjg(ZD15)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD36*conjg(ZD16)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD31*conjg(ZD11)*Sin(TWp) - (0,1)*gp*Qq*ZD32*conjg( &
      ZD12)*Sin(TWp) - (0,1)*gp*Qq*ZD33*conjg(ZD13)*Sin(TWp) + (0,1)*gp*Qd*ZD34*conjg(ZD14 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD35*conjg(ZD15)*Sin(TWp) + (0,1)*gp*Qd*ZD36*conjg(ZD16)* &
      Sin(TWp))
   G_z_1_sd1_sd4c = (0,-1)*((0,0.5_default)*g2*ZD41*conjg(ZD11)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD42*conjg(ZD12)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD43* &
      conjg(ZD13)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD41*conjg(ZD11)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD42*conjg(ZD12)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD43*conjg(ZD13)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD44*conjg(ZD14)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD45* &
      conjg(ZD15)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD46*conjg(ZD16)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD41*conjg(ZD11)*Sin(TWp) - (0,1)*gp*Qq*ZD42*conjg( &
      ZD12)*Sin(TWp) - (0,1)*gp*Qq*ZD43*conjg(ZD13)*Sin(TWp) + (0,1)*gp*Qd*ZD44*conjg(ZD14 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD45*conjg(ZD15)*Sin(TWp) + (0,1)*gp*Qd*ZD46*conjg(ZD16)* &
      Sin(TWp))
   G_z_1_sd1_sd5c = (0,-1)*((0,0.5_default)*g2*ZD51*conjg(ZD11)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD52*conjg(ZD12)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD53* &
      conjg(ZD13)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD51*conjg(ZD11)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD52*conjg(ZD12)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD53*conjg(ZD13)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD54*conjg(ZD14)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD55* &
      conjg(ZD15)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD56*conjg(ZD16)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD51*conjg(ZD11)*Sin(TWp) - (0,1)*gp*Qq*ZD52*conjg( &
      ZD12)*Sin(TWp) - (0,1)*gp*Qq*ZD53*conjg(ZD13)*Sin(TWp) + (0,1)*gp*Qd*ZD54*conjg(ZD14 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD55*conjg(ZD15)*Sin(TWp) + (0,1)*gp*Qd*ZD56*conjg(ZD16)* &
      Sin(TWp))
   G_z_1_sd1_sd6c = (0,-1)*((0,0.5_default)*g2*ZD61*conjg(ZD11)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD62*conjg(ZD12)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD63* &
      conjg(ZD13)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD61*conjg(ZD11)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD62*conjg(ZD12)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD63*conjg(ZD13)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD64*conjg(ZD14)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD65* &
      conjg(ZD15)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD66*conjg(ZD16)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD61*conjg(ZD11)*Sin(TWp) - (0,1)*gp*Qq*ZD62*conjg( &
      ZD12)*Sin(TWp) - (0,1)*gp*Qq*ZD63*conjg(ZD13)*Sin(TWp) + (0,1)*gp*Qd*ZD64*conjg(ZD14 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD65*conjg(ZD15)*Sin(TWp) + (0,1)*gp*Qd*ZD66*conjg(ZD16)* &
      Sin(TWp))
   G_z_1_sd2_sd1c = (0,-1)*((0,0.5_default)*g2*ZD11*conjg(ZD21)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD12*conjg(ZD22)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD13* &
      conjg(ZD23)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD11*conjg(ZD21)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD12*conjg(ZD22)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD13*conjg(ZD23)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD14*conjg(ZD24)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD15* &
      conjg(ZD25)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD16*conjg(ZD26)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD11*conjg(ZD21)*Sin(TWp) - (0,1)*gp*Qq*ZD12*conjg( &
      ZD22)*Sin(TWp) - (0,1)*gp*Qq*ZD13*conjg(ZD23)*Sin(TWp) + (0,1)*gp*Qd*ZD14*conjg(ZD24 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD15*conjg(ZD25)*Sin(TWp) + (0,1)*gp*Qd*ZD16*conjg(ZD26)* &
      Sin(TWp))
   G_z_1_sd2_sd2c = (0,-1)*((0,0.5_default)*g2*ZD21*conjg(ZD21)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD22*conjg(ZD22)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD23* &
      conjg(ZD23)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD21*conjg(ZD21)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD22*conjg(ZD22)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD23*conjg(ZD23)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD24*conjg(ZD24)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD25* &
      conjg(ZD25)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD26*conjg(ZD26)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD21*conjg(ZD21)*Sin(TWp) - (0,1)*gp*Qq*ZD22*conjg( &
      ZD22)*Sin(TWp) - (0,1)*gp*Qq*ZD23*conjg(ZD23)*Sin(TWp) + (0,1)*gp*Qd*ZD24*conjg(ZD24 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD25*conjg(ZD25)*Sin(TWp) + (0,1)*gp*Qd*ZD26*conjg(ZD26)* &
      Sin(TWp))
   G_z_1_sd2_sd3c = (0,-1)*((0,0.5_default)*g2*ZD31*conjg(ZD21)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD32*conjg(ZD22)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD33* &
      conjg(ZD23)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD31*conjg(ZD21)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD32*conjg(ZD22)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD33*conjg(ZD23)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD34*conjg(ZD24)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD35* &
      conjg(ZD25)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD36*conjg(ZD26)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD31*conjg(ZD21)*Sin(TWp) - (0,1)*gp*Qq*ZD32*conjg( &
      ZD22)*Sin(TWp) - (0,1)*gp*Qq*ZD33*conjg(ZD23)*Sin(TWp) + (0,1)*gp*Qd*ZD34*conjg(ZD24 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD35*conjg(ZD25)*Sin(TWp) + (0,1)*gp*Qd*ZD36*conjg(ZD26)* &
      Sin(TWp))
end subroutine calc_cpl14

end module parameters_nonumssm_sarah_cpl14