! --------------------------------------------------------------------------------
! Autogenerated by the happy scrappy WHIZARD model file generator on 2/10/2021 , 0:41:44
! WHIZARD interface svn revision info: $Id: WOMathematicaInterface.m 3666 2012-01-14 17:03:09Z cnspeckn $
! Code generated for WHIZARD / O'Mega version 2.4.0
! Model name: nonumssm_sarah
! Gauge: Unitarity
! Maximum number of couplings per FORTRAN module: 150
! --------------------------------------------------------------------------------
! 
! --------------------------------------------------------------------------------

module parameters_nonumssm_sarah_cpl26
use parameters_nonumssm_sarah_global
use parameters_nonumssm_sarah_local
implicit none

contains

subroutine calc_cpl26
   G_d3bar_hm2_u3(1) = (0,-0.5_default)*((0,1)*Yd11*ZP21*conjg(ZDR31)*conjg(ZUL31 &
      ) + (0,1)*Yd21*ZP21*conjg(ZDR32)*conjg(ZUL31) + (0,1)*Yd31*ZP21*conjg(ZDR33)*conjg( &
      ZUL31) + (0,1)*Yd12*ZP21*conjg(ZDR31)*conjg(ZUL32) + (0,1)*Yd22*ZP21*conjg(ZDR32)* &
      conjg(ZUL32) + (0,1)*Yd32*ZP21*conjg(ZDR33)*conjg(ZUL32) + (0,1)*Yd13*ZP21*conjg( &
      ZDR31)*conjg(ZUL33) + (0,1)*Yd23*ZP21*conjg(ZDR32)*conjg(ZUL33) + (0,1)*Yd33*ZP21* &
      conjg(ZDR33)*conjg(ZUL33))
   G_d3bar_hm2_u3(2) = (0,-0.5_default)*((0,1)*ZDL31*ZP22*ZUR31*conjg(Yu11) + (0,1 &
      )*ZDL32*ZP22*ZUR31*conjg(Yu12) + (0,1)*ZDL33*ZP22*ZUR31*conjg(Yu13) + (0,1)*ZDL31* &
      ZP22*ZUR32*conjg(Yu21) + (0,1)*ZDL32*ZP22*ZUR32*conjg(Yu22) + (0,1)*ZDL33*ZP22*ZUR32 &
      *conjg(Yu23) + (0,1)*ZDL31*ZP22*ZUR33*conjg(Yu31) + (0,1)*ZDL32*ZP22*ZUR33*conjg( &
      Yu32) + (0,1)*ZDL33*ZP22*ZUR33*conjg(Yu33))
   G_e1bar_hm2_nu1 = (0,-0.5_default)*((0,1)*Ye11*ZP21*conjg(ZER11)*conjg(ZVL11 &
      ) + (0,1)*Ye22*ZP21*conjg(ZER12)*conjg(ZVL12) + (0,1)*Ye33*ZP21*conjg(ZER13)*conjg( &
      ZVL13))
   G_e1bar_hm2_nu2 = (0,-0.5_default)*((0,1)*Ye11*ZP21*conjg(ZER11)*conjg(ZVL21 &
      ) + (0,1)*Ye22*ZP21*conjg(ZER12)*conjg(ZVL22) + (0,1)*Ye33*ZP21*conjg(ZER13)*conjg( &
      ZVL23))
   G_e1bar_hm2_nu3 = (0,-0.5_default)*((0,1)*Ye11*ZP21*conjg(ZER11)*conjg(ZVL31 &
      ) + (0,1)*Ye22*ZP21*conjg(ZER12)*conjg(ZVL32) + (0,1)*Ye33*ZP21*conjg(ZER13)*conjg( &
      ZVL33))
   G_e2bar_hm2_nu1 = (0,-0.5_default)*((0,1)*Ye11*ZP21*conjg(ZER21)*conjg(ZVL11 &
      ) + (0,1)*Ye22*ZP21*conjg(ZER22)*conjg(ZVL12) + (0,1)*Ye33*ZP21*conjg(ZER23)*conjg( &
      ZVL13))
   G_e2bar_hm2_nu2 = (0,-0.5_default)*((0,1)*Ye11*ZP21*conjg(ZER21)*conjg(ZVL21 &
      ) + (0,1)*Ye22*ZP21*conjg(ZER22)*conjg(ZVL22) + (0,1)*Ye33*ZP21*conjg(ZER23)*conjg( &
      ZVL23))
   G_e2bar_hm2_nu3 = (0,-0.5_default)*((0,1)*Ye11*ZP21*conjg(ZER21)*conjg(ZVL31 &
      ) + (0,1)*Ye22*ZP21*conjg(ZER22)*conjg(ZVL32) + (0,1)*Ye33*ZP21*conjg(ZER23)*conjg( &
      ZVL33))
   G_e3bar_hm2_nu1 = (0,-0.5_default)*((0,1)*Ye11*ZP21*conjg(ZER31)*conjg(ZVL11 &
      ) + (0,1)*Ye22*ZP21*conjg(ZER32)*conjg(ZVL12) + (0,1)*Ye33*ZP21*conjg(ZER33)*conjg( &
      ZVL13))
   G_e3bar_hm2_nu2 = (0,-0.5_default)*((0,1)*Ye11*ZP21*conjg(ZER31)*conjg(ZVL21 &
      ) + (0,1)*Ye22*ZP21*conjg(ZER32)*conjg(ZVL22) + (0,1)*Ye33*ZP21*conjg(ZER33)*conjg( &
      ZVL23))
   G_e3bar_hm2_nu3 = (0,-0.5_default)*((0,1)*Ye11*ZP21*conjg(ZER31)*conjg(ZVL31 &
      ) + (0,1)*Ye22*ZP21*conjg(ZER32)*conjg(ZVL32) + (0,1)*Ye33*ZP21*conjg(ZER33)*conjg( &
      ZVL33))
   G_d1bar_sd1_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZD14)*conjg(ZDR11) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZD15)*conjg(ZDR12) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZD16)*conjg(ZDR13)))/Sqrt (2._default)
   G_d1bar_sd1_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZDL11*conjg &
      (pG)*conjg(ZD11) - (0,1)*Sqrt (2._default)*g3*ZDL12*conjg(pG)*conjg(ZD12) - (0,1 &
      )*Sqrt (2._default)*g3*ZDL13*conjg(pG)*conjg(ZD13)))/Sqrt (2._default)
   G_d1bar_sd2_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZD24)*conjg(ZDR11) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZD25)*conjg(ZDR12) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZD26)*conjg(ZDR13)))/Sqrt (2._default)
   G_d1bar_sd2_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZDL11*conjg &
      (pG)*conjg(ZD21) - (0,1)*Sqrt (2._default)*g3*ZDL12*conjg(pG)*conjg(ZD22) - (0,1 &
      )*Sqrt (2._default)*g3*ZDL13*conjg(pG)*conjg(ZD23)))/Sqrt (2._default)
   G_d1bar_sd3_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZD34)*conjg(ZDR11) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZD35)*conjg(ZDR12) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZD36)*conjg(ZDR13)))/Sqrt (2._default)
   G_d1bar_sd3_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZDL11*conjg &
      (pG)*conjg(ZD31) - (0,1)*Sqrt (2._default)*g3*ZDL12*conjg(pG)*conjg(ZD32) - (0,1 &
      )*Sqrt (2._default)*g3*ZDL13*conjg(pG)*conjg(ZD33)))/Sqrt (2._default)
   G_d1bar_sd4_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZD44)*conjg(ZDR11) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZD45)*conjg(ZDR12) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZD46)*conjg(ZDR13)))/Sqrt (2._default)
   G_d1bar_sd4_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZDL11*conjg &
      (pG)*conjg(ZD41) - (0,1)*Sqrt (2._default)*g3*ZDL12*conjg(pG)*conjg(ZD42) - (0,1 &
      )*Sqrt (2._default)*g3*ZDL13*conjg(pG)*conjg(ZD43)))/Sqrt (2._default)
   G_d1bar_sd5_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZD54)*conjg(ZDR11) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZD55)*conjg(ZDR12) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZD56)*conjg(ZDR13)))/Sqrt (2._default)
   G_d1bar_sd5_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZDL11*conjg &
      (pG)*conjg(ZD51) - (0,1)*Sqrt (2._default)*g3*ZDL12*conjg(pG)*conjg(ZD52) - (0,1 &
      )*Sqrt (2._default)*g3*ZDL13*conjg(pG)*conjg(ZD53)))/Sqrt (2._default)
   G_d1bar_sd6_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZD64)*conjg(ZDR11) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZD65)*conjg(ZDR12) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZD66)*conjg(ZDR13)))/Sqrt (2._default)
   G_d1bar_sd6_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZDL11*conjg &
      (pG)*conjg(ZD61) - (0,1)*Sqrt (2._default)*g3*ZDL12*conjg(pG)*conjg(ZD62) - (0,1 &
      )*Sqrt (2._default)*g3*ZDL13*conjg(pG)*conjg(ZD63)))/Sqrt (2._default)
   G_d2bar_sd1_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZD14)*conjg(ZDR21) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZD15)*conjg(ZDR22) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZD16)*conjg(ZDR23)))/Sqrt (2._default)
   G_d2bar_sd1_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZDL21*conjg &
      (pG)*conjg(ZD11) - (0,1)*Sqrt (2._default)*g3*ZDL22*conjg(pG)*conjg(ZD12) - (0,1 &
      )*Sqrt (2._default)*g3*ZDL23*conjg(pG)*conjg(ZD13)))/Sqrt (2._default)
   G_d2bar_sd2_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZD24)*conjg(ZDR21) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZD25)*conjg(ZDR22) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZD26)*conjg(ZDR23)))/Sqrt (2._default)
   G_d2bar_sd2_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZDL21*conjg &
      (pG)*conjg(ZD21) - (0,1)*Sqrt (2._default)*g3*ZDL22*conjg(pG)*conjg(ZD22) - (0,1 &
      )*Sqrt (2._default)*g3*ZDL23*conjg(pG)*conjg(ZD23)))/Sqrt (2._default)
   G_d2bar_sd3_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZD34)*conjg(ZDR21) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZD35)*conjg(ZDR22) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZD36)*conjg(ZDR23)))/Sqrt (2._default)
   G_d2bar_sd3_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZDL21*conjg &
      (pG)*conjg(ZD31) - (0,1)*Sqrt (2._default)*g3*ZDL22*conjg(pG)*conjg(ZD32) - (0,1 &
      )*Sqrt (2._default)*g3*ZDL23*conjg(pG)*conjg(ZD33)))/Sqrt (2._default)
   G_d2bar_sd4_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZD44)*conjg(ZDR21) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZD45)*conjg(ZDR22) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZD46)*conjg(ZDR23)))/Sqrt (2._default)
   G_d2bar_sd4_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZDL21*conjg &
      (pG)*conjg(ZD41) - (0,1)*Sqrt (2._default)*g3*ZDL22*conjg(pG)*conjg(ZD42) - (0,1 &
      )*Sqrt (2._default)*g3*ZDL23*conjg(pG)*conjg(ZD43)))/Sqrt (2._default)
   G_d2bar_sd5_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZD54)*conjg(ZDR21) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZD55)*conjg(ZDR22) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZD56)*conjg(ZDR23)))/Sqrt (2._default)
   G_d2bar_sd5_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZDL21*conjg &
      (pG)*conjg(ZD51) - (0,1)*Sqrt (2._default)*g3*ZDL22*conjg(pG)*conjg(ZD52) - (0,1 &
      )*Sqrt (2._default)*g3*ZDL23*conjg(pG)*conjg(ZD53)))/Sqrt (2._default)
   G_d2bar_sd6_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZD64)*conjg(ZDR21) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZD65)*conjg(ZDR22) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZD66)*conjg(ZDR23)))/Sqrt (2._default)
   G_d2bar_sd6_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZDL21*conjg &
      (pG)*conjg(ZD61) - (0,1)*Sqrt (2._default)*g3*ZDL22*conjg(pG)*conjg(ZD62) - (0,1 &
      )*Sqrt (2._default)*g3*ZDL23*conjg(pG)*conjg(ZD63)))/Sqrt (2._default)
   G_d3bar_sd1_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZD14)*conjg(ZDR31) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZD15)*conjg(ZDR32) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZD16)*conjg(ZDR33)))/Sqrt (2._default)
   G_d3bar_sd1_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZDL31*conjg &
      (pG)*conjg(ZD11) - (0,1)*Sqrt (2._default)*g3*ZDL32*conjg(pG)*conjg(ZD12) - (0,1 &
      )*Sqrt (2._default)*g3*ZDL33*conjg(pG)*conjg(ZD13)))/Sqrt (2._default)
   G_d3bar_sd2_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZD24)*conjg(ZDR31) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZD25)*conjg(ZDR32) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZD26)*conjg(ZDR33)))/Sqrt (2._default)
   G_d3bar_sd2_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZDL31*conjg &
      (pG)*conjg(ZD21) - (0,1)*Sqrt (2._default)*g3*ZDL32*conjg(pG)*conjg(ZD22) - (0,1 &
      )*Sqrt (2._default)*g3*ZDL33*conjg(pG)*conjg(ZD23)))/Sqrt (2._default)
   G_d3bar_sd3_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZD34)*conjg(ZDR31) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZD35)*conjg(ZDR32) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZD36)*conjg(ZDR33)))/Sqrt (2._default)
   G_d3bar_sd3_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZDL31*conjg &
      (pG)*conjg(ZD31) - (0,1)*Sqrt (2._default)*g3*ZDL32*conjg(pG)*conjg(ZD32) - (0,1 &
      )*Sqrt (2._default)*g3*ZDL33*conjg(pG)*conjg(ZD33)))/Sqrt (2._default)
   G_d3bar_sd4_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZD44)*conjg(ZDR31) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZD45)*conjg(ZDR32) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZD46)*conjg(ZDR33)))/Sqrt (2._default)
   G_d3bar_sd4_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZDL31*conjg &
      (pG)*conjg(ZD41) - (0,1)*Sqrt (2._default)*g3*ZDL32*conjg(pG)*conjg(ZD42) - (0,1 &
      )*Sqrt (2._default)*g3*ZDL33*conjg(pG)*conjg(ZD43)))/Sqrt (2._default)
   G_d3bar_sd5_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZD54)*conjg(ZDR31) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZD55)*conjg(ZDR32) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZD56)*conjg(ZDR33)))/Sqrt (2._default)
   G_d3bar_sd5_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZDL31*conjg &
      (pG)*conjg(ZD51) - (0,1)*Sqrt (2._default)*g3*ZDL32*conjg(pG)*conjg(ZD52) - (0,1 &
      )*Sqrt (2._default)*g3*ZDL33*conjg(pG)*conjg(ZD53)))/Sqrt (2._default)
   G_d3bar_sd6_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZD64)*conjg(ZDR31) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZD65)*conjg(ZDR32) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZD66)*conjg(ZDR33)))/Sqrt (2._default)
   G_d3bar_sd6_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZDL31*conjg &
      (pG)*conjg(ZD61) - (0,1)*Sqrt (2._default)*g3*ZDL32*conjg(pG)*conjg(ZD62) - (0,1 &
      )*Sqrt (2._default)*g3*ZDL33*conjg(pG)*conjg(ZD63)))/Sqrt (2._default)
   G_u1bar_su1_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZU14)*conjg(ZUR11) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZU15)*conjg(ZUR12) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZU16)*conjg(ZUR13)))/Sqrt (2._default)
   G_u1bar_su1_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZUL11*conjg &
      (pG)*conjg(ZU11) - (0,1)*Sqrt (2._default)*g3*ZUL12*conjg(pG)*conjg(ZU12) - (0,1 &
      )*Sqrt (2._default)*g3*ZUL13*conjg(pG)*conjg(ZU13)))/Sqrt (2._default)
   G_u1bar_su2_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZU24)*conjg(ZUR11) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZU25)*conjg(ZUR12) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZU26)*conjg(ZUR13)))/Sqrt (2._default)
   G_u1bar_su2_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZUL11*conjg &
      (pG)*conjg(ZU21) - (0,1)*Sqrt (2._default)*g3*ZUL12*conjg(pG)*conjg(ZU22) - (0,1 &
      )*Sqrt (2._default)*g3*ZUL13*conjg(pG)*conjg(ZU23)))/Sqrt (2._default)
   G_u1bar_su3_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZU34)*conjg(ZUR11) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZU35)*conjg(ZUR12) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZU36)*conjg(ZUR13)))/Sqrt (2._default)
   G_u1bar_su3_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZUL11*conjg &
      (pG)*conjg(ZU31) - (0,1)*Sqrt (2._default)*g3*ZUL12*conjg(pG)*conjg(ZU32) - (0,1 &
      )*Sqrt (2._default)*g3*ZUL13*conjg(pG)*conjg(ZU33)))/Sqrt (2._default)
   G_u1bar_su4_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZU44)*conjg(ZUR11) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZU45)*conjg(ZUR12) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZU46)*conjg(ZUR13)))/Sqrt (2._default)
   G_u1bar_su4_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZUL11*conjg &
      (pG)*conjg(ZU41) - (0,1)*Sqrt (2._default)*g3*ZUL12*conjg(pG)*conjg(ZU42) - (0,1 &
      )*Sqrt (2._default)*g3*ZUL13*conjg(pG)*conjg(ZU43)))/Sqrt (2._default)
   G_u1bar_su5_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZU54)*conjg(ZUR11) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZU55)*conjg(ZUR12) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZU56)*conjg(ZUR13)))/Sqrt (2._default)
   G_u1bar_su5_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZUL11*conjg &
      (pG)*conjg(ZU51) - (0,1)*Sqrt (2._default)*g3*ZUL12*conjg(pG)*conjg(ZU52) - (0,1 &
      )*Sqrt (2._default)*g3*ZUL13*conjg(pG)*conjg(ZU53)))/Sqrt (2._default)
   G_u1bar_su6_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZU64)*conjg(ZUR11) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZU65)*conjg(ZUR12) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZU66)*conjg(ZUR13)))/Sqrt (2._default)
   G_u1bar_su6_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZUL11*conjg &
      (pG)*conjg(ZU61) - (0,1)*Sqrt (2._default)*g3*ZUL12*conjg(pG)*conjg(ZU62) - (0,1 &
      )*Sqrt (2._default)*g3*ZUL13*conjg(pG)*conjg(ZU63)))/Sqrt (2._default)
   G_u2bar_su1_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZU14)*conjg(ZUR21) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZU15)*conjg(ZUR22) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZU16)*conjg(ZUR23)))/Sqrt (2._default)
   G_u2bar_su1_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZUL21*conjg &
      (pG)*conjg(ZU11) - (0,1)*Sqrt (2._default)*g3*ZUL22*conjg(pG)*conjg(ZU12) - (0,1 &
      )*Sqrt (2._default)*g3*ZUL23*conjg(pG)*conjg(ZU13)))/Sqrt (2._default)
   G_u2bar_su2_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZU24)*conjg(ZUR21) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZU25)*conjg(ZUR22) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZU26)*conjg(ZUR23)))/Sqrt (2._default)
   G_u2bar_su2_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZUL21*conjg &
      (pG)*conjg(ZU21) - (0,1)*Sqrt (2._default)*g3*ZUL22*conjg(pG)*conjg(ZU22) - (0,1 &
      )*Sqrt (2._default)*g3*ZUL23*conjg(pG)*conjg(ZU23)))/Sqrt (2._default)
   G_u2bar_su3_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZU34)*conjg(ZUR21) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZU35)*conjg(ZUR22) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZU36)*conjg(ZUR23)))/Sqrt (2._default)
   G_u2bar_su3_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZUL21*conjg &
      (pG)*conjg(ZU31) - (0,1)*Sqrt (2._default)*g3*ZUL22*conjg(pG)*conjg(ZU32) - (0,1 &
      )*Sqrt (2._default)*g3*ZUL23*conjg(pG)*conjg(ZU33)))/Sqrt (2._default)
   G_u2bar_su4_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZU44)*conjg(ZUR21) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZU45)*conjg(ZUR22) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZU46)*conjg(ZUR23)))/Sqrt (2._default)
   G_u2bar_su4_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZUL21*conjg &
      (pG)*conjg(ZU41) - (0,1)*Sqrt (2._default)*g3*ZUL22*conjg(pG)*conjg(ZU42) - (0,1 &
      )*Sqrt (2._default)*g3*ZUL23*conjg(pG)*conjg(ZU43)))/Sqrt (2._default)
   G_u2bar_su5_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZU54)*conjg(ZUR21) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZU55)*conjg(ZUR22) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZU56)*conjg(ZUR23)))/Sqrt (2._default)
   G_u2bar_su5_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZUL21*conjg &
      (pG)*conjg(ZU51) - (0,1)*Sqrt (2._default)*g3*ZUL22*conjg(pG)*conjg(ZU52) - (0,1 &
      )*Sqrt (2._default)*g3*ZUL23*conjg(pG)*conjg(ZU53)))/Sqrt (2._default)
   G_u2bar_su6_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZU64)*conjg(ZUR21) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZU65)*conjg(ZUR22) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZU66)*conjg(ZUR23)))/Sqrt (2._default)
   G_u2bar_su6_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZUL21*conjg &
      (pG)*conjg(ZU61) - (0,1)*Sqrt (2._default)*g3*ZUL22*conjg(pG)*conjg(ZU62) - (0,1 &
      )*Sqrt (2._default)*g3*ZUL23*conjg(pG)*conjg(ZU63)))/Sqrt (2._default)
   G_u3bar_su1_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZU14)*conjg(ZUR31) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZU15)*conjg(ZUR32) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZU16)*conjg(ZUR33)))/Sqrt (2._default)
   G_u3bar_su1_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZUL31*conjg &
      (pG)*conjg(ZU11) - (0,1)*Sqrt (2._default)*g3*ZUL32*conjg(pG)*conjg(ZU12) - (0,1 &
      )*Sqrt (2._default)*g3*ZUL33*conjg(pG)*conjg(ZU13)))/Sqrt (2._default)
   G_u3bar_su2_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZU24)*conjg(ZUR31) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZU25)*conjg(ZUR32) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZU26)*conjg(ZUR33)))/Sqrt (2._default)
   G_u3bar_su2_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZUL31*conjg &
      (pG)*conjg(ZU21) - (0,1)*Sqrt (2._default)*g3*ZUL32*conjg(pG)*conjg(ZU22) - (0,1 &
      )*Sqrt (2._default)*g3*ZUL33*conjg(pG)*conjg(ZU23)))/Sqrt (2._default)
   G_u3bar_su3_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZU34)*conjg(ZUR31) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZU35)*conjg(ZUR32) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZU36)*conjg(ZUR33)))/Sqrt (2._default)
   G_u3bar_su3_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZUL31*conjg &
      (pG)*conjg(ZU31) - (0,1)*Sqrt (2._default)*g3*ZUL32*conjg(pG)*conjg(ZU32) - (0,1 &
      )*Sqrt (2._default)*g3*ZUL33*conjg(pG)*conjg(ZU33)))/Sqrt (2._default)
   G_u3bar_su4_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZU44)*conjg(ZUR31) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZU45)*conjg(ZUR32) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZU46)*conjg(ZUR33)))/Sqrt (2._default)
   G_u3bar_su4_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZUL31*conjg &
      (pG)*conjg(ZU41) - (0,1)*Sqrt (2._default)*g3*ZUL32*conjg(pG)*conjg(ZU42) - (0,1 &
      )*Sqrt (2._default)*g3*ZUL33*conjg(pG)*conjg(ZU43)))/Sqrt (2._default)
   G_u3bar_su5_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZU54)*conjg(ZUR31) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZU55)*conjg(ZUR32) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZU56)*conjg(ZUR33)))/Sqrt (2._default)
   G_u3bar_su5_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZUL31*conjg &
      (pG)*conjg(ZU51) - (0,1)*Sqrt (2._default)*g3*ZUL32*conjg(pG)*conjg(ZU52) - (0,1 &
      )*Sqrt (2._default)*g3*ZUL33*conjg(pG)*conjg(ZU53)))/Sqrt (2._default)
   G_u3bar_su6_go_1(1) = ((0,-0.5_default)*((0,1)*Sqrt (2._default)*g3*pG*conjg( &
      ZU64)*conjg(ZUR31) + (0,1)*Sqrt (2._default)*g3*pG*conjg(ZU65)*conjg(ZUR32) + (0,1)* &
      Sqrt (2._default)*g3*pG*conjg(ZU66)*conjg(ZUR33)))/Sqrt (2._default)
   G_u3bar_su6_go_1(2) = ((0,-0.5_default)*((0,-1)*Sqrt (2._default)*g3*ZUL31*conjg &
      (pG)*conjg(ZU61) - (0,1)*Sqrt (2._default)*g3*ZUL32*conjg(pG)*conjg(ZU62) - (0,1 &
      )*Sqrt (2._default)*g3*ZUL33*conjg(pG)*conjg(ZU63)))/Sqrt (2._default)
   G_c1bar_sd1_u1bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP12)*conjg(ZD11)* &
      conjg(ZUR11) + (0,1)*Yu12*conjg(UP12)*conjg(ZD12)*conjg(ZUR11) + (0,1)*Yu13*conjg( &
      UP12)*conjg(ZD13)*conjg(ZUR11) + (0,1)*Yu21*conjg(UP12)*conjg(ZD11)*conjg(ZUR12) + ( &
      0,1)*Yu22*conjg(UP12)*conjg(ZD12)*conjg(ZUR12) + (0,1)*Yu23*conjg(UP12)*conjg( &
      ZD13)*conjg(ZUR12) + (0,1)*Yu31*conjg(UP12)*conjg(ZD11)*conjg(ZUR13) + (0,1)*Yu32* &
      conjg(UP12)*conjg(ZD12)*conjg(ZUR13) + (0,1)*Yu33*conjg(UP12)*conjg(ZD13)*conjg(ZUR13 &
      ))
   G_c1bar_sd1_u1bar(2) = (0,-0.5_default)*((0,-1)*g2*UM11*ZUL11*conjg(ZD11) - (0,1 &
      )*g2*UM11*ZUL12*conjg(ZD12) - (0,1)*g2*UM11*ZUL13*conjg(ZD13) + (0,1)*UM12*ZUL11* &
      conjg(Yd11)*conjg(ZD14) + (0,1)*UM12*ZUL12*conjg(Yd12)*conjg(ZD14) + (0,1)*UM12*ZUL13 &
      *conjg(Yd13)*conjg(ZD14) + (0,1)*UM12*ZUL11*conjg(Yd21)*conjg(ZD15) + (0,1)*UM12* &
      ZUL12*conjg(Yd22)*conjg(ZD15) + (0,1)*UM12*ZUL13*conjg(Yd23)*conjg(ZD15) + (0,1)*UM12 &
      *ZUL11*conjg(Yd31)*conjg(ZD16) + (0,1)*UM12*ZUL12*conjg(Yd32)*conjg(ZD16) + (0,1 &
      )*UM12*ZUL13*conjg(Yd33)*conjg(ZD16))
   G_c1bar_sd2_u1bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP12)*conjg(ZD21)* &
      conjg(ZUR11) + (0,1)*Yu12*conjg(UP12)*conjg(ZD22)*conjg(ZUR11) + (0,1)*Yu13*conjg( &
      UP12)*conjg(ZD23)*conjg(ZUR11) + (0,1)*Yu21*conjg(UP12)*conjg(ZD21)*conjg(ZUR12) + ( &
      0,1)*Yu22*conjg(UP12)*conjg(ZD22)*conjg(ZUR12) + (0,1)*Yu23*conjg(UP12)*conjg( &
      ZD23)*conjg(ZUR12) + (0,1)*Yu31*conjg(UP12)*conjg(ZD21)*conjg(ZUR13) + (0,1)*Yu32* &
      conjg(UP12)*conjg(ZD22)*conjg(ZUR13) + (0,1)*Yu33*conjg(UP12)*conjg(ZD23)*conjg(ZUR13 &
      ))
   G_c1bar_sd2_u1bar(2) = (0,-0.5_default)*((0,-1)*g2*UM11*ZUL11*conjg(ZD21) - (0,1 &
      )*g2*UM11*ZUL12*conjg(ZD22) - (0,1)*g2*UM11*ZUL13*conjg(ZD23) + (0,1)*UM12*ZUL11* &
      conjg(Yd11)*conjg(ZD24) + (0,1)*UM12*ZUL12*conjg(Yd12)*conjg(ZD24) + (0,1)*UM12*ZUL13 &
      *conjg(Yd13)*conjg(ZD24) + (0,1)*UM12*ZUL11*conjg(Yd21)*conjg(ZD25) + (0,1)*UM12* &
      ZUL12*conjg(Yd22)*conjg(ZD25) + (0,1)*UM12*ZUL13*conjg(Yd23)*conjg(ZD25) + (0,1)*UM12 &
      *ZUL11*conjg(Yd31)*conjg(ZD26) + (0,1)*UM12*ZUL12*conjg(Yd32)*conjg(ZD26) + (0,1 &
      )*UM12*ZUL13*conjg(Yd33)*conjg(ZD26))
   G_c1bar_sd3_u1bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP12)*conjg(ZD31)* &
      conjg(ZUR11) + (0,1)*Yu12*conjg(UP12)*conjg(ZD32)*conjg(ZUR11) + (0,1)*Yu13*conjg( &
      UP12)*conjg(ZD33)*conjg(ZUR11) + (0,1)*Yu21*conjg(UP12)*conjg(ZD31)*conjg(ZUR12) + ( &
      0,1)*Yu22*conjg(UP12)*conjg(ZD32)*conjg(ZUR12) + (0,1)*Yu23*conjg(UP12)*conjg( &
      ZD33)*conjg(ZUR12) + (0,1)*Yu31*conjg(UP12)*conjg(ZD31)*conjg(ZUR13) + (0,1)*Yu32* &
      conjg(UP12)*conjg(ZD32)*conjg(ZUR13) + (0,1)*Yu33*conjg(UP12)*conjg(ZD33)*conjg(ZUR13 &
      ))
   G_c1bar_sd3_u1bar(2) = (0,-0.5_default)*((0,-1)*g2*UM11*ZUL11*conjg(ZD31) - (0,1 &
      )*g2*UM11*ZUL12*conjg(ZD32) - (0,1)*g2*UM11*ZUL13*conjg(ZD33) + (0,1)*UM12*ZUL11* &
      conjg(Yd11)*conjg(ZD34) + (0,1)*UM12*ZUL12*conjg(Yd12)*conjg(ZD34) + (0,1)*UM12*ZUL13 &
      *conjg(Yd13)*conjg(ZD34) + (0,1)*UM12*ZUL11*conjg(Yd21)*conjg(ZD35) + (0,1)*UM12* &
      ZUL12*conjg(Yd22)*conjg(ZD35) + (0,1)*UM12*ZUL13*conjg(Yd23)*conjg(ZD35) + (0,1)*UM12 &
      *ZUL11*conjg(Yd31)*conjg(ZD36) + (0,1)*UM12*ZUL12*conjg(Yd32)*conjg(ZD36) + (0,1 &
      )*UM12*ZUL13*conjg(Yd33)*conjg(ZD36))
   G_c1bar_sd4_u1bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP12)*conjg(ZD41)* &
      conjg(ZUR11) + (0,1)*Yu12*conjg(UP12)*conjg(ZD42)*conjg(ZUR11) + (0,1)*Yu13*conjg( &
      UP12)*conjg(ZD43)*conjg(ZUR11) + (0,1)*Yu21*conjg(UP12)*conjg(ZD41)*conjg(ZUR12) + ( &
      0,1)*Yu22*conjg(UP12)*conjg(ZD42)*conjg(ZUR12) + (0,1)*Yu23*conjg(UP12)*conjg( &
      ZD43)*conjg(ZUR12) + (0,1)*Yu31*conjg(UP12)*conjg(ZD41)*conjg(ZUR13) + (0,1)*Yu32* &
      conjg(UP12)*conjg(ZD42)*conjg(ZUR13) + (0,1)*Yu33*conjg(UP12)*conjg(ZD43)*conjg(ZUR13 &
      ))
   G_c1bar_sd4_u1bar(2) = (0,-0.5_default)*((0,-1)*g2*UM11*ZUL11*conjg(ZD41) - (0,1 &
      )*g2*UM11*ZUL12*conjg(ZD42) - (0,1)*g2*UM11*ZUL13*conjg(ZD43) + (0,1)*UM12*ZUL11* &
      conjg(Yd11)*conjg(ZD44) + (0,1)*UM12*ZUL12*conjg(Yd12)*conjg(ZD44) + (0,1)*UM12*ZUL13 &
      *conjg(Yd13)*conjg(ZD44) + (0,1)*UM12*ZUL11*conjg(Yd21)*conjg(ZD45) + (0,1)*UM12* &
      ZUL12*conjg(Yd22)*conjg(ZD45) + (0,1)*UM12*ZUL13*conjg(Yd23)*conjg(ZD45) + (0,1)*UM12 &
      *ZUL11*conjg(Yd31)*conjg(ZD46) + (0,1)*UM12*ZUL12*conjg(Yd32)*conjg(ZD46) + (0,1 &
      )*UM12*ZUL13*conjg(Yd33)*conjg(ZD46))
   G_c1bar_sd5_u1bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP12)*conjg(ZD51)* &
      conjg(ZUR11) + (0,1)*Yu12*conjg(UP12)*conjg(ZD52)*conjg(ZUR11) + (0,1)*Yu13*conjg( &
      UP12)*conjg(ZD53)*conjg(ZUR11) + (0,1)*Yu21*conjg(UP12)*conjg(ZD51)*conjg(ZUR12) + ( &
      0,1)*Yu22*conjg(UP12)*conjg(ZD52)*conjg(ZUR12) + (0,1)*Yu23*conjg(UP12)*conjg( &
      ZD53)*conjg(ZUR12) + (0,1)*Yu31*conjg(UP12)*conjg(ZD51)*conjg(ZUR13) + (0,1)*Yu32* &
      conjg(UP12)*conjg(ZD52)*conjg(ZUR13) + (0,1)*Yu33*conjg(UP12)*conjg(ZD53)*conjg(ZUR13 &
      ))
   G_c1bar_sd5_u1bar(2) = (0,-0.5_default)*((0,-1)*g2*UM11*ZUL11*conjg(ZD51) - (0,1 &
      )*g2*UM11*ZUL12*conjg(ZD52) - (0,1)*g2*UM11*ZUL13*conjg(ZD53) + (0,1)*UM12*ZUL11* &
      conjg(Yd11)*conjg(ZD54) + (0,1)*UM12*ZUL12*conjg(Yd12)*conjg(ZD54) + (0,1)*UM12*ZUL13 &
      *conjg(Yd13)*conjg(ZD54) + (0,1)*UM12*ZUL11*conjg(Yd21)*conjg(ZD55) + (0,1)*UM12* &
      ZUL12*conjg(Yd22)*conjg(ZD55) + (0,1)*UM12*ZUL13*conjg(Yd23)*conjg(ZD55) + (0,1)*UM12 &
      *ZUL11*conjg(Yd31)*conjg(ZD56) + (0,1)*UM12*ZUL12*conjg(Yd32)*conjg(ZD56) + (0,1 &
      )*UM12*ZUL13*conjg(Yd33)*conjg(ZD56))
   G_c1bar_sd6_u1bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP12)*conjg(ZD61)* &
      conjg(ZUR11) + (0,1)*Yu12*conjg(UP12)*conjg(ZD62)*conjg(ZUR11) + (0,1)*Yu13*conjg( &
      UP12)*conjg(ZD63)*conjg(ZUR11) + (0,1)*Yu21*conjg(UP12)*conjg(ZD61)*conjg(ZUR12) + ( &
      0,1)*Yu22*conjg(UP12)*conjg(ZD62)*conjg(ZUR12) + (0,1)*Yu23*conjg(UP12)*conjg( &
      ZD63)*conjg(ZUR12) + (0,1)*Yu31*conjg(UP12)*conjg(ZD61)*conjg(ZUR13) + (0,1)*Yu32* &
      conjg(UP12)*conjg(ZD62)*conjg(ZUR13) + (0,1)*Yu33*conjg(UP12)*conjg(ZD63)*conjg(ZUR13 &
      ))
   G_c1bar_sd6_u1bar(2) = (0,-0.5_default)*((0,-1)*g2*UM11*ZUL11*conjg(ZD61) - (0,1 &
      )*g2*UM11*ZUL12*conjg(ZD62) - (0,1)*g2*UM11*ZUL13*conjg(ZD63) + (0,1)*UM12*ZUL11* &
      conjg(Yd11)*conjg(ZD64) + (0,1)*UM12*ZUL12*conjg(Yd12)*conjg(ZD64) + (0,1)*UM12*ZUL13 &
      *conjg(Yd13)*conjg(ZD64) + (0,1)*UM12*ZUL11*conjg(Yd21)*conjg(ZD65) + (0,1)*UM12* &
      ZUL12*conjg(Yd22)*conjg(ZD65) + (0,1)*UM12*ZUL13*conjg(Yd23)*conjg(ZD65) + (0,1)*UM12 &
      *ZUL11*conjg(Yd31)*conjg(ZD66) + (0,1)*UM12*ZUL12*conjg(Yd32)*conjg(ZD66) + (0,1 &
      )*UM12*ZUL13*conjg(Yd33)*conjg(ZD66))
   G_c1bar_sd1_u2bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP12)*conjg(ZD11)* &
      conjg(ZUR21) + (0,1)*Yu12*conjg(UP12)*conjg(ZD12)*conjg(ZUR21) + (0,1)*Yu13*conjg( &
      UP12)*conjg(ZD13)*conjg(ZUR21) + (0,1)*Yu21*conjg(UP12)*conjg(ZD11)*conjg(ZUR22) + ( &
      0,1)*Yu22*conjg(UP12)*conjg(ZD12)*conjg(ZUR22) + (0,1)*Yu23*conjg(UP12)*conjg( &
      ZD13)*conjg(ZUR22) + (0,1)*Yu31*conjg(UP12)*conjg(ZD11)*conjg(ZUR23) + (0,1)*Yu32* &
      conjg(UP12)*conjg(ZD12)*conjg(ZUR23) + (0,1)*Yu33*conjg(UP12)*conjg(ZD13)*conjg(ZUR23 &
      ))
   G_c1bar_sd1_u2bar(2) = (0,-0.5_default)*((0,-1)*g2*UM11*ZUL21*conjg(ZD11) - (0,1 &
      )*g2*UM11*ZUL22*conjg(ZD12) - (0,1)*g2*UM11*ZUL23*conjg(ZD13) + (0,1)*UM12*ZUL21* &
      conjg(Yd11)*conjg(ZD14) + (0,1)*UM12*ZUL22*conjg(Yd12)*conjg(ZD14) + (0,1)*UM12*ZUL23 &
      *conjg(Yd13)*conjg(ZD14) + (0,1)*UM12*ZUL21*conjg(Yd21)*conjg(ZD15) + (0,1)*UM12* &
      ZUL22*conjg(Yd22)*conjg(ZD15) + (0,1)*UM12*ZUL23*conjg(Yd23)*conjg(ZD15) + (0,1)*UM12 &
      *ZUL21*conjg(Yd31)*conjg(ZD16) + (0,1)*UM12*ZUL22*conjg(Yd32)*conjg(ZD16) + (0,1 &
      )*UM12*ZUL23*conjg(Yd33)*conjg(ZD16))
   G_c1bar_sd2_u2bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP12)*conjg(ZD21)* &
      conjg(ZUR21) + (0,1)*Yu12*conjg(UP12)*conjg(ZD22)*conjg(ZUR21) + (0,1)*Yu13*conjg( &
      UP12)*conjg(ZD23)*conjg(ZUR21) + (0,1)*Yu21*conjg(UP12)*conjg(ZD21)*conjg(ZUR22) + ( &
      0,1)*Yu22*conjg(UP12)*conjg(ZD22)*conjg(ZUR22) + (0,1)*Yu23*conjg(UP12)*conjg( &
      ZD23)*conjg(ZUR22) + (0,1)*Yu31*conjg(UP12)*conjg(ZD21)*conjg(ZUR23) + (0,1)*Yu32* &
      conjg(UP12)*conjg(ZD22)*conjg(ZUR23) + (0,1)*Yu33*conjg(UP12)*conjg(ZD23)*conjg(ZUR23 &
      ))
   G_c1bar_sd2_u2bar(2) = (0,-0.5_default)*((0,-1)*g2*UM11*ZUL21*conjg(ZD21) - (0,1 &
      )*g2*UM11*ZUL22*conjg(ZD22) - (0,1)*g2*UM11*ZUL23*conjg(ZD23) + (0,1)*UM12*ZUL21* &
      conjg(Yd11)*conjg(ZD24) + (0,1)*UM12*ZUL22*conjg(Yd12)*conjg(ZD24) + (0,1)*UM12*ZUL23 &
      *conjg(Yd13)*conjg(ZD24) + (0,1)*UM12*ZUL21*conjg(Yd21)*conjg(ZD25) + (0,1)*UM12* &
      ZUL22*conjg(Yd22)*conjg(ZD25) + (0,1)*UM12*ZUL23*conjg(Yd23)*conjg(ZD25) + (0,1)*UM12 &
      *ZUL21*conjg(Yd31)*conjg(ZD26) + (0,1)*UM12*ZUL22*conjg(Yd32)*conjg(ZD26) + (0,1 &
      )*UM12*ZUL23*conjg(Yd33)*conjg(ZD26))
   G_c1bar_sd3_u2bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP12)*conjg(ZD31)* &
      conjg(ZUR21) + (0,1)*Yu12*conjg(UP12)*conjg(ZD32)*conjg(ZUR21) + (0,1)*Yu13*conjg( &
      UP12)*conjg(ZD33)*conjg(ZUR21) + (0,1)*Yu21*conjg(UP12)*conjg(ZD31)*conjg(ZUR22) + ( &
      0,1)*Yu22*conjg(UP12)*conjg(ZD32)*conjg(ZUR22) + (0,1)*Yu23*conjg(UP12)*conjg( &
      ZD33)*conjg(ZUR22) + (0,1)*Yu31*conjg(UP12)*conjg(ZD31)*conjg(ZUR23) + (0,1)*Yu32* &
      conjg(UP12)*conjg(ZD32)*conjg(ZUR23) + (0,1)*Yu33*conjg(UP12)*conjg(ZD33)*conjg(ZUR23 &
      ))
   G_c1bar_sd3_u2bar(2) = (0,-0.5_default)*((0,-1)*g2*UM11*ZUL21*conjg(ZD31) - (0,1 &
      )*g2*UM11*ZUL22*conjg(ZD32) - (0,1)*g2*UM11*ZUL23*conjg(ZD33) + (0,1)*UM12*ZUL21* &
      conjg(Yd11)*conjg(ZD34) + (0,1)*UM12*ZUL22*conjg(Yd12)*conjg(ZD34) + (0,1)*UM12*ZUL23 &
      *conjg(Yd13)*conjg(ZD34) + (0,1)*UM12*ZUL21*conjg(Yd21)*conjg(ZD35) + (0,1)*UM12* &
      ZUL22*conjg(Yd22)*conjg(ZD35) + (0,1)*UM12*ZUL23*conjg(Yd23)*conjg(ZD35) + (0,1)*UM12 &
      *ZUL21*conjg(Yd31)*conjg(ZD36) + (0,1)*UM12*ZUL22*conjg(Yd32)*conjg(ZD36) + (0,1 &
      )*UM12*ZUL23*conjg(Yd33)*conjg(ZD36))
   G_c1bar_sd4_u2bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP12)*conjg(ZD41)* &
      conjg(ZUR21) + (0,1)*Yu12*conjg(UP12)*conjg(ZD42)*conjg(ZUR21) + (0,1)*Yu13*conjg( &
      UP12)*conjg(ZD43)*conjg(ZUR21) + (0,1)*Yu21*conjg(UP12)*conjg(ZD41)*conjg(ZUR22) + ( &
      0,1)*Yu22*conjg(UP12)*conjg(ZD42)*conjg(ZUR22) + (0,1)*Yu23*conjg(UP12)*conjg( &
      ZD43)*conjg(ZUR22) + (0,1)*Yu31*conjg(UP12)*conjg(ZD41)*conjg(ZUR23) + (0,1)*Yu32* &
      conjg(UP12)*conjg(ZD42)*conjg(ZUR23) + (0,1)*Yu33*conjg(UP12)*conjg(ZD43)*conjg(ZUR23 &
      ))
   G_c1bar_sd4_u2bar(2) = (0,-0.5_default)*((0,-1)*g2*UM11*ZUL21*conjg(ZD41) - (0,1 &
      )*g2*UM11*ZUL22*conjg(ZD42) - (0,1)*g2*UM11*ZUL23*conjg(ZD43) + (0,1)*UM12*ZUL21* &
      conjg(Yd11)*conjg(ZD44) + (0,1)*UM12*ZUL22*conjg(Yd12)*conjg(ZD44) + (0,1)*UM12*ZUL23 &
      *conjg(Yd13)*conjg(ZD44) + (0,1)*UM12*ZUL21*conjg(Yd21)*conjg(ZD45) + (0,1)*UM12* &
      ZUL22*conjg(Yd22)*conjg(ZD45) + (0,1)*UM12*ZUL23*conjg(Yd23)*conjg(ZD45) + (0,1)*UM12 &
      *ZUL21*conjg(Yd31)*conjg(ZD46) + (0,1)*UM12*ZUL22*conjg(Yd32)*conjg(ZD46) + (0,1 &
      )*UM12*ZUL23*conjg(Yd33)*conjg(ZD46))
   G_c1bar_sd5_u2bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP12)*conjg(ZD51)* &
      conjg(ZUR21) + (0,1)*Yu12*conjg(UP12)*conjg(ZD52)*conjg(ZUR21) + (0,1)*Yu13*conjg( &
      UP12)*conjg(ZD53)*conjg(ZUR21) + (0,1)*Yu21*conjg(UP12)*conjg(ZD51)*conjg(ZUR22) + ( &
      0,1)*Yu22*conjg(UP12)*conjg(ZD52)*conjg(ZUR22) + (0,1)*Yu23*conjg(UP12)*conjg( &
      ZD53)*conjg(ZUR22) + (0,1)*Yu31*conjg(UP12)*conjg(ZD51)*conjg(ZUR23) + (0,1)*Yu32* &
      conjg(UP12)*conjg(ZD52)*conjg(ZUR23) + (0,1)*Yu33*conjg(UP12)*conjg(ZD53)*conjg(ZUR23 &
      ))
   G_c1bar_sd5_u2bar(2) = (0,-0.5_default)*((0,-1)*g2*UM11*ZUL21*conjg(ZD51) - (0,1 &
      )*g2*UM11*ZUL22*conjg(ZD52) - (0,1)*g2*UM11*ZUL23*conjg(ZD53) + (0,1)*UM12*ZUL21* &
      conjg(Yd11)*conjg(ZD54) + (0,1)*UM12*ZUL22*conjg(Yd12)*conjg(ZD54) + (0,1)*UM12*ZUL23 &
      *conjg(Yd13)*conjg(ZD54) + (0,1)*UM12*ZUL21*conjg(Yd21)*conjg(ZD55) + (0,1)*UM12* &
      ZUL22*conjg(Yd22)*conjg(ZD55) + (0,1)*UM12*ZUL23*conjg(Yd23)*conjg(ZD55) + (0,1)*UM12 &
      *ZUL21*conjg(Yd31)*conjg(ZD56) + (0,1)*UM12*ZUL22*conjg(Yd32)*conjg(ZD56) + (0,1 &
      )*UM12*ZUL23*conjg(Yd33)*conjg(ZD56))
   G_c1bar_sd6_u2bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP12)*conjg(ZD61)* &
      conjg(ZUR21) + (0,1)*Yu12*conjg(UP12)*conjg(ZD62)*conjg(ZUR21) + (0,1)*Yu13*conjg( &
      UP12)*conjg(ZD63)*conjg(ZUR21) + (0,1)*Yu21*conjg(UP12)*conjg(ZD61)*conjg(ZUR22) + ( &
      0,1)*Yu22*conjg(UP12)*conjg(ZD62)*conjg(ZUR22) + (0,1)*Yu23*conjg(UP12)*conjg( &
      ZD63)*conjg(ZUR22) + (0,1)*Yu31*conjg(UP12)*conjg(ZD61)*conjg(ZUR23) + (0,1)*Yu32* &
      conjg(UP12)*conjg(ZD62)*conjg(ZUR23) + (0,1)*Yu33*conjg(UP12)*conjg(ZD63)*conjg(ZUR23 &
      ))
   G_c1bar_sd6_u2bar(2) = (0,-0.5_default)*((0,-1)*g2*UM11*ZUL21*conjg(ZD61) - (0,1 &
      )*g2*UM11*ZUL22*conjg(ZD62) - (0,1)*g2*UM11*ZUL23*conjg(ZD63) + (0,1)*UM12*ZUL21* &
      conjg(Yd11)*conjg(ZD64) + (0,1)*UM12*ZUL22*conjg(Yd12)*conjg(ZD64) + (0,1)*UM12*ZUL23 &
      *conjg(Yd13)*conjg(ZD64) + (0,1)*UM12*ZUL21*conjg(Yd21)*conjg(ZD65) + (0,1)*UM12* &
      ZUL22*conjg(Yd22)*conjg(ZD65) + (0,1)*UM12*ZUL23*conjg(Yd23)*conjg(ZD65) + (0,1)*UM12 &
      *ZUL21*conjg(Yd31)*conjg(ZD66) + (0,1)*UM12*ZUL22*conjg(Yd32)*conjg(ZD66) + (0,1 &
      )*UM12*ZUL23*conjg(Yd33)*conjg(ZD66))
   G_c1bar_sd1_u3bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP12)*conjg(ZD11)* &
      conjg(ZUR31) + (0,1)*Yu12*conjg(UP12)*conjg(ZD12)*conjg(ZUR31) + (0,1)*Yu13*conjg( &
      UP12)*conjg(ZD13)*conjg(ZUR31) + (0,1)*Yu21*conjg(UP12)*conjg(ZD11)*conjg(ZUR32) + ( &
      0,1)*Yu22*conjg(UP12)*conjg(ZD12)*conjg(ZUR32) + (0,1)*Yu23*conjg(UP12)*conjg( &
      ZD13)*conjg(ZUR32) + (0,1)*Yu31*conjg(UP12)*conjg(ZD11)*conjg(ZUR33) + (0,1)*Yu32* &
      conjg(UP12)*conjg(ZD12)*conjg(ZUR33) + (0,1)*Yu33*conjg(UP12)*conjg(ZD13)*conjg(ZUR33 &
      ))
   G_c1bar_sd1_u3bar(2) = (0,-0.5_default)*((0,-1)*g2*UM11*ZUL31*conjg(ZD11) - (0,1 &
      )*g2*UM11*ZUL32*conjg(ZD12) - (0,1)*g2*UM11*ZUL33*conjg(ZD13) + (0,1)*UM12*ZUL31* &
      conjg(Yd11)*conjg(ZD14) + (0,1)*UM12*ZUL32*conjg(Yd12)*conjg(ZD14) + (0,1)*UM12*ZUL33 &
      *conjg(Yd13)*conjg(ZD14) + (0,1)*UM12*ZUL31*conjg(Yd21)*conjg(ZD15) + (0,1)*UM12* &
      ZUL32*conjg(Yd22)*conjg(ZD15) + (0,1)*UM12*ZUL33*conjg(Yd23)*conjg(ZD15) + (0,1)*UM12 &
      *ZUL31*conjg(Yd31)*conjg(ZD16) + (0,1)*UM12*ZUL32*conjg(Yd32)*conjg(ZD16) + (0,1 &
      )*UM12*ZUL33*conjg(Yd33)*conjg(ZD16))
   G_c1bar_sd2_u3bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP12)*conjg(ZD21)* &
      conjg(ZUR31) + (0,1)*Yu12*conjg(UP12)*conjg(ZD22)*conjg(ZUR31) + (0,1)*Yu13*conjg( &
      UP12)*conjg(ZD23)*conjg(ZUR31) + (0,1)*Yu21*conjg(UP12)*conjg(ZD21)*conjg(ZUR32) + ( &
      0,1)*Yu22*conjg(UP12)*conjg(ZD22)*conjg(ZUR32) + (0,1)*Yu23*conjg(UP12)*conjg( &
      ZD23)*conjg(ZUR32) + (0,1)*Yu31*conjg(UP12)*conjg(ZD21)*conjg(ZUR33) + (0,1)*Yu32* &
      conjg(UP12)*conjg(ZD22)*conjg(ZUR33) + (0,1)*Yu33*conjg(UP12)*conjg(ZD23)*conjg(ZUR33 &
      ))
   G_c1bar_sd2_u3bar(2) = (0,-0.5_default)*((0,-1)*g2*UM11*ZUL31*conjg(ZD21) - (0,1 &
      )*g2*UM11*ZUL32*conjg(ZD22) - (0,1)*g2*UM11*ZUL33*conjg(ZD23) + (0,1)*UM12*ZUL31* &
      conjg(Yd11)*conjg(ZD24) + (0,1)*UM12*ZUL32*conjg(Yd12)*conjg(ZD24) + (0,1)*UM12*ZUL33 &
      *conjg(Yd13)*conjg(ZD24) + (0,1)*UM12*ZUL31*conjg(Yd21)*conjg(ZD25) + (0,1)*UM12* &
      ZUL32*conjg(Yd22)*conjg(ZD25) + (0,1)*UM12*ZUL33*conjg(Yd23)*conjg(ZD25) + (0,1)*UM12 &
      *ZUL31*conjg(Yd31)*conjg(ZD26) + (0,1)*UM12*ZUL32*conjg(Yd32)*conjg(ZD26) + (0,1 &
      )*UM12*ZUL33*conjg(Yd33)*conjg(ZD26))
   G_c1bar_sd3_u3bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP12)*conjg(ZD31)* &
      conjg(ZUR31) + (0,1)*Yu12*conjg(UP12)*conjg(ZD32)*conjg(ZUR31) + (0,1)*Yu13*conjg( &
      UP12)*conjg(ZD33)*conjg(ZUR31) + (0,1)*Yu21*conjg(UP12)*conjg(ZD31)*conjg(ZUR32) + ( &
      0,1)*Yu22*conjg(UP12)*conjg(ZD32)*conjg(ZUR32) + (0,1)*Yu23*conjg(UP12)*conjg( &
      ZD33)*conjg(ZUR32) + (0,1)*Yu31*conjg(UP12)*conjg(ZD31)*conjg(ZUR33) + (0,1)*Yu32* &
      conjg(UP12)*conjg(ZD32)*conjg(ZUR33) + (0,1)*Yu33*conjg(UP12)*conjg(ZD33)*conjg(ZUR33 &
      ))
   G_c1bar_sd3_u3bar(2) = (0,-0.5_default)*((0,-1)*g2*UM11*ZUL31*conjg(ZD31) - (0,1 &
      )*g2*UM11*ZUL32*conjg(ZD32) - (0,1)*g2*UM11*ZUL33*conjg(ZD33) + (0,1)*UM12*ZUL31* &
      conjg(Yd11)*conjg(ZD34) + (0,1)*UM12*ZUL32*conjg(Yd12)*conjg(ZD34) + (0,1)*UM12*ZUL33 &
      *conjg(Yd13)*conjg(ZD34) + (0,1)*UM12*ZUL31*conjg(Yd21)*conjg(ZD35) + (0,1)*UM12* &
      ZUL32*conjg(Yd22)*conjg(ZD35) + (0,1)*UM12*ZUL33*conjg(Yd23)*conjg(ZD35) + (0,1)*UM12 &
      *ZUL31*conjg(Yd31)*conjg(ZD36) + (0,1)*UM12*ZUL32*conjg(Yd32)*conjg(ZD36) + (0,1 &
      )*UM12*ZUL33*conjg(Yd33)*conjg(ZD36))
   G_c1bar_sd4_u3bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP12)*conjg(ZD41)* &
      conjg(ZUR31) + (0,1)*Yu12*conjg(UP12)*conjg(ZD42)*conjg(ZUR31) + (0,1)*Yu13*conjg( &
      UP12)*conjg(ZD43)*conjg(ZUR31) + (0,1)*Yu21*conjg(UP12)*conjg(ZD41)*conjg(ZUR32) + ( &
      0,1)*Yu22*conjg(UP12)*conjg(ZD42)*conjg(ZUR32) + (0,1)*Yu23*conjg(UP12)*conjg( &
      ZD43)*conjg(ZUR32) + (0,1)*Yu31*conjg(UP12)*conjg(ZD41)*conjg(ZUR33) + (0,1)*Yu32* &
      conjg(UP12)*conjg(ZD42)*conjg(ZUR33) + (0,1)*Yu33*conjg(UP12)*conjg(ZD43)*conjg(ZUR33 &
      ))
   G_c1bar_sd4_u3bar(2) = (0,-0.5_default)*((0,-1)*g2*UM11*ZUL31*conjg(ZD41) - (0,1 &
      )*g2*UM11*ZUL32*conjg(ZD42) - (0,1)*g2*UM11*ZUL33*conjg(ZD43) + (0,1)*UM12*ZUL31* &
      conjg(Yd11)*conjg(ZD44) + (0,1)*UM12*ZUL32*conjg(Yd12)*conjg(ZD44) + (0,1)*UM12*ZUL33 &
      *conjg(Yd13)*conjg(ZD44) + (0,1)*UM12*ZUL31*conjg(Yd21)*conjg(ZD45) + (0,1)*UM12* &
      ZUL32*conjg(Yd22)*conjg(ZD45) + (0,1)*UM12*ZUL33*conjg(Yd23)*conjg(ZD45) + (0,1)*UM12 &
      *ZUL31*conjg(Yd31)*conjg(ZD46) + (0,1)*UM12*ZUL32*conjg(Yd32)*conjg(ZD46) + (0,1 &
      )*UM12*ZUL33*conjg(Yd33)*conjg(ZD46))
   G_c1bar_sd5_u3bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP12)*conjg(ZD51)* &
      conjg(ZUR31) + (0,1)*Yu12*conjg(UP12)*conjg(ZD52)*conjg(ZUR31) + (0,1)*Yu13*conjg( &
      UP12)*conjg(ZD53)*conjg(ZUR31) + (0,1)*Yu21*conjg(UP12)*conjg(ZD51)*conjg(ZUR32) + ( &
      0,1)*Yu22*conjg(UP12)*conjg(ZD52)*conjg(ZUR32) + (0,1)*Yu23*conjg(UP12)*conjg( &
      ZD53)*conjg(ZUR32) + (0,1)*Yu31*conjg(UP12)*conjg(ZD51)*conjg(ZUR33) + (0,1)*Yu32* &
      conjg(UP12)*conjg(ZD52)*conjg(ZUR33) + (0,1)*Yu33*conjg(UP12)*conjg(ZD53)*conjg(ZUR33 &
      ))
   G_c1bar_sd5_u3bar(2) = (0,-0.5_default)*((0,-1)*g2*UM11*ZUL31*conjg(ZD51) - (0,1 &
      )*g2*UM11*ZUL32*conjg(ZD52) - (0,1)*g2*UM11*ZUL33*conjg(ZD53) + (0,1)*UM12*ZUL31* &
      conjg(Yd11)*conjg(ZD54) + (0,1)*UM12*ZUL32*conjg(Yd12)*conjg(ZD54) + (0,1)*UM12*ZUL33 &
      *conjg(Yd13)*conjg(ZD54) + (0,1)*UM12*ZUL31*conjg(Yd21)*conjg(ZD55) + (0,1)*UM12* &
      ZUL32*conjg(Yd22)*conjg(ZD55) + (0,1)*UM12*ZUL33*conjg(Yd23)*conjg(ZD55) + (0,1)*UM12 &
      *ZUL31*conjg(Yd31)*conjg(ZD56) + (0,1)*UM12*ZUL32*conjg(Yd32)*conjg(ZD56) + (0,1 &
      )*UM12*ZUL33*conjg(Yd33)*conjg(ZD56))
   G_c1bar_sd6_u3bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP12)*conjg(ZD61)* &
      conjg(ZUR31) + (0,1)*Yu12*conjg(UP12)*conjg(ZD62)*conjg(ZUR31) + (0,1)*Yu13*conjg( &
      UP12)*conjg(ZD63)*conjg(ZUR31) + (0,1)*Yu21*conjg(UP12)*conjg(ZD61)*conjg(ZUR32) + ( &
      0,1)*Yu22*conjg(UP12)*conjg(ZD62)*conjg(ZUR32) + (0,1)*Yu23*conjg(UP12)*conjg( &
      ZD63)*conjg(ZUR32) + (0,1)*Yu31*conjg(UP12)*conjg(ZD61)*conjg(ZUR33) + (0,1)*Yu32* &
      conjg(UP12)*conjg(ZD62)*conjg(ZUR33) + (0,1)*Yu33*conjg(UP12)*conjg(ZD63)*conjg(ZUR33 &
      ))
   G_c1bar_sd6_u3bar(2) = (0,-0.5_default)*((0,-1)*g2*UM11*ZUL31*conjg(ZD61) - (0,1 &
      )*g2*UM11*ZUL32*conjg(ZD62) - (0,1)*g2*UM11*ZUL33*conjg(ZD63) + (0,1)*UM12*ZUL31* &
      conjg(Yd11)*conjg(ZD64) + (0,1)*UM12*ZUL32*conjg(Yd12)*conjg(ZD64) + (0,1)*UM12*ZUL33 &
      *conjg(Yd13)*conjg(ZD64) + (0,1)*UM12*ZUL31*conjg(Yd21)*conjg(ZD65) + (0,1)*UM12* &
      ZUL32*conjg(Yd22)*conjg(ZD65) + (0,1)*UM12*ZUL33*conjg(Yd23)*conjg(ZD65) + (0,1)*UM12 &
      *ZUL31*conjg(Yd31)*conjg(ZD66) + (0,1)*UM12*ZUL32*conjg(Yd32)*conjg(ZD66) + (0,1 &
      )*UM12*ZUL33*conjg(Yd33)*conjg(ZD66))
   G_c2bar_sd1_u1bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP22)*conjg(ZD11)* &
      conjg(ZUR11) + (0,1)*Yu12*conjg(UP22)*conjg(ZD12)*conjg(ZUR11) + (0,1)*Yu13*conjg( &
      UP22)*conjg(ZD13)*conjg(ZUR11) + (0,1)*Yu21*conjg(UP22)*conjg(ZD11)*conjg(ZUR12) + ( &
      0,1)*Yu22*conjg(UP22)*conjg(ZD12)*conjg(ZUR12) + (0,1)*Yu23*conjg(UP22)*conjg( &
      ZD13)*conjg(ZUR12) + (0,1)*Yu31*conjg(UP22)*conjg(ZD11)*conjg(ZUR13) + (0,1)*Yu32* &
      conjg(UP22)*conjg(ZD12)*conjg(ZUR13) + (0,1)*Yu33*conjg(UP22)*conjg(ZD13)*conjg(ZUR13 &
      ))
   G_c2bar_sd1_u1bar(2) = (0,-0.5_default)*((0,-1)*g2*UM21*ZUL11*conjg(ZD11) - (0,1 &
      )*g2*UM21*ZUL12*conjg(ZD12) - (0,1)*g2*UM21*ZUL13*conjg(ZD13) + (0,1)*UM22*ZUL11* &
      conjg(Yd11)*conjg(ZD14) + (0,1)*UM22*ZUL12*conjg(Yd12)*conjg(ZD14) + (0,1)*UM22*ZUL13 &
      *conjg(Yd13)*conjg(ZD14) + (0,1)*UM22*ZUL11*conjg(Yd21)*conjg(ZD15) + (0,1)*UM22* &
      ZUL12*conjg(Yd22)*conjg(ZD15) + (0,1)*UM22*ZUL13*conjg(Yd23)*conjg(ZD15) + (0,1)*UM22 &
      *ZUL11*conjg(Yd31)*conjg(ZD16) + (0,1)*UM22*ZUL12*conjg(Yd32)*conjg(ZD16) + (0,1 &
      )*UM22*ZUL13*conjg(Yd33)*conjg(ZD16))
   G_c2bar_sd2_u1bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP22)*conjg(ZD21)* &
      conjg(ZUR11) + (0,1)*Yu12*conjg(UP22)*conjg(ZD22)*conjg(ZUR11) + (0,1)*Yu13*conjg( &
      UP22)*conjg(ZD23)*conjg(ZUR11) + (0,1)*Yu21*conjg(UP22)*conjg(ZD21)*conjg(ZUR12) + ( &
      0,1)*Yu22*conjg(UP22)*conjg(ZD22)*conjg(ZUR12) + (0,1)*Yu23*conjg(UP22)*conjg( &
      ZD23)*conjg(ZUR12) + (0,1)*Yu31*conjg(UP22)*conjg(ZD21)*conjg(ZUR13) + (0,1)*Yu32* &
      conjg(UP22)*conjg(ZD22)*conjg(ZUR13) + (0,1)*Yu33*conjg(UP22)*conjg(ZD23)*conjg(ZUR13 &
      ))
   G_c2bar_sd2_u1bar(2) = (0,-0.5_default)*((0,-1)*g2*UM21*ZUL11*conjg(ZD21) - (0,1 &
      )*g2*UM21*ZUL12*conjg(ZD22) - (0,1)*g2*UM21*ZUL13*conjg(ZD23) + (0,1)*UM22*ZUL11* &
      conjg(Yd11)*conjg(ZD24) + (0,1)*UM22*ZUL12*conjg(Yd12)*conjg(ZD24) + (0,1)*UM22*ZUL13 &
      *conjg(Yd13)*conjg(ZD24) + (0,1)*UM22*ZUL11*conjg(Yd21)*conjg(ZD25) + (0,1)*UM22* &
      ZUL12*conjg(Yd22)*conjg(ZD25) + (0,1)*UM22*ZUL13*conjg(Yd23)*conjg(ZD25) + (0,1)*UM22 &
      *ZUL11*conjg(Yd31)*conjg(ZD26) + (0,1)*UM22*ZUL12*conjg(Yd32)*conjg(ZD26) + (0,1 &
      )*UM22*ZUL13*conjg(Yd33)*conjg(ZD26))
   G_c2bar_sd3_u1bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP22)*conjg(ZD31)* &
      conjg(ZUR11) + (0,1)*Yu12*conjg(UP22)*conjg(ZD32)*conjg(ZUR11) + (0,1)*Yu13*conjg( &
      UP22)*conjg(ZD33)*conjg(ZUR11) + (0,1)*Yu21*conjg(UP22)*conjg(ZD31)*conjg(ZUR12) + ( &
      0,1)*Yu22*conjg(UP22)*conjg(ZD32)*conjg(ZUR12) + (0,1)*Yu23*conjg(UP22)*conjg( &
      ZD33)*conjg(ZUR12) + (0,1)*Yu31*conjg(UP22)*conjg(ZD31)*conjg(ZUR13) + (0,1)*Yu32* &
      conjg(UP22)*conjg(ZD32)*conjg(ZUR13) + (0,1)*Yu33*conjg(UP22)*conjg(ZD33)*conjg(ZUR13 &
      ))
   G_c2bar_sd3_u1bar(2) = (0,-0.5_default)*((0,-1)*g2*UM21*ZUL11*conjg(ZD31) - (0,1 &
      )*g2*UM21*ZUL12*conjg(ZD32) - (0,1)*g2*UM21*ZUL13*conjg(ZD33) + (0,1)*UM22*ZUL11* &
      conjg(Yd11)*conjg(ZD34) + (0,1)*UM22*ZUL12*conjg(Yd12)*conjg(ZD34) + (0,1)*UM22*ZUL13 &
      *conjg(Yd13)*conjg(ZD34) + (0,1)*UM22*ZUL11*conjg(Yd21)*conjg(ZD35) + (0,1)*UM22* &
      ZUL12*conjg(Yd22)*conjg(ZD35) + (0,1)*UM22*ZUL13*conjg(Yd23)*conjg(ZD35) + (0,1)*UM22 &
      *ZUL11*conjg(Yd31)*conjg(ZD36) + (0,1)*UM22*ZUL12*conjg(Yd32)*conjg(ZD36) + (0,1 &
      )*UM22*ZUL13*conjg(Yd33)*conjg(ZD36))
   G_c2bar_sd4_u1bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP22)*conjg(ZD41)* &
      conjg(ZUR11) + (0,1)*Yu12*conjg(UP22)*conjg(ZD42)*conjg(ZUR11) + (0,1)*Yu13*conjg( &
      UP22)*conjg(ZD43)*conjg(ZUR11) + (0,1)*Yu21*conjg(UP22)*conjg(ZD41)*conjg(ZUR12) + ( &
      0,1)*Yu22*conjg(UP22)*conjg(ZD42)*conjg(ZUR12) + (0,1)*Yu23*conjg(UP22)*conjg( &
      ZD43)*conjg(ZUR12) + (0,1)*Yu31*conjg(UP22)*conjg(ZD41)*conjg(ZUR13) + (0,1)*Yu32* &
      conjg(UP22)*conjg(ZD42)*conjg(ZUR13) + (0,1)*Yu33*conjg(UP22)*conjg(ZD43)*conjg(ZUR13 &
      ))
   G_c2bar_sd4_u1bar(2) = (0,-0.5_default)*((0,-1)*g2*UM21*ZUL11*conjg(ZD41) - (0,1 &
      )*g2*UM21*ZUL12*conjg(ZD42) - (0,1)*g2*UM21*ZUL13*conjg(ZD43) + (0,1)*UM22*ZUL11* &
      conjg(Yd11)*conjg(ZD44) + (0,1)*UM22*ZUL12*conjg(Yd12)*conjg(ZD44) + (0,1)*UM22*ZUL13 &
      *conjg(Yd13)*conjg(ZD44) + (0,1)*UM22*ZUL11*conjg(Yd21)*conjg(ZD45) + (0,1)*UM22* &
      ZUL12*conjg(Yd22)*conjg(ZD45) + (0,1)*UM22*ZUL13*conjg(Yd23)*conjg(ZD45) + (0,1)*UM22 &
      *ZUL11*conjg(Yd31)*conjg(ZD46) + (0,1)*UM22*ZUL12*conjg(Yd32)*conjg(ZD46) + (0,1 &
      )*UM22*ZUL13*conjg(Yd33)*conjg(ZD46))
   G_c2bar_sd5_u1bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP22)*conjg(ZD51)* &
      conjg(ZUR11) + (0,1)*Yu12*conjg(UP22)*conjg(ZD52)*conjg(ZUR11) + (0,1)*Yu13*conjg( &
      UP22)*conjg(ZD53)*conjg(ZUR11) + (0,1)*Yu21*conjg(UP22)*conjg(ZD51)*conjg(ZUR12) + ( &
      0,1)*Yu22*conjg(UP22)*conjg(ZD52)*conjg(ZUR12) + (0,1)*Yu23*conjg(UP22)*conjg( &
      ZD53)*conjg(ZUR12) + (0,1)*Yu31*conjg(UP22)*conjg(ZD51)*conjg(ZUR13) + (0,1)*Yu32* &
      conjg(UP22)*conjg(ZD52)*conjg(ZUR13) + (0,1)*Yu33*conjg(UP22)*conjg(ZD53)*conjg(ZUR13 &
      ))
   G_c2bar_sd5_u1bar(2) = (0,-0.5_default)*((0,-1)*g2*UM21*ZUL11*conjg(ZD51) - (0,1 &
      )*g2*UM21*ZUL12*conjg(ZD52) - (0,1)*g2*UM21*ZUL13*conjg(ZD53) + (0,1)*UM22*ZUL11* &
      conjg(Yd11)*conjg(ZD54) + (0,1)*UM22*ZUL12*conjg(Yd12)*conjg(ZD54) + (0,1)*UM22*ZUL13 &
      *conjg(Yd13)*conjg(ZD54) + (0,1)*UM22*ZUL11*conjg(Yd21)*conjg(ZD55) + (0,1)*UM22* &
      ZUL12*conjg(Yd22)*conjg(ZD55) + (0,1)*UM22*ZUL13*conjg(Yd23)*conjg(ZD55) + (0,1)*UM22 &
      *ZUL11*conjg(Yd31)*conjg(ZD56) + (0,1)*UM22*ZUL12*conjg(Yd32)*conjg(ZD56) + (0,1 &
      )*UM22*ZUL13*conjg(Yd33)*conjg(ZD56))
   G_c2bar_sd6_u1bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP22)*conjg(ZD61)* &
      conjg(ZUR11) + (0,1)*Yu12*conjg(UP22)*conjg(ZD62)*conjg(ZUR11) + (0,1)*Yu13*conjg( &
      UP22)*conjg(ZD63)*conjg(ZUR11) + (0,1)*Yu21*conjg(UP22)*conjg(ZD61)*conjg(ZUR12) + ( &
      0,1)*Yu22*conjg(UP22)*conjg(ZD62)*conjg(ZUR12) + (0,1)*Yu23*conjg(UP22)*conjg( &
      ZD63)*conjg(ZUR12) + (0,1)*Yu31*conjg(UP22)*conjg(ZD61)*conjg(ZUR13) + (0,1)*Yu32* &
      conjg(UP22)*conjg(ZD62)*conjg(ZUR13) + (0,1)*Yu33*conjg(UP22)*conjg(ZD63)*conjg(ZUR13 &
      ))
   G_c2bar_sd6_u1bar(2) = (0,-0.5_default)*((0,-1)*g2*UM21*ZUL11*conjg(ZD61) - (0,1 &
      )*g2*UM21*ZUL12*conjg(ZD62) - (0,1)*g2*UM21*ZUL13*conjg(ZD63) + (0,1)*UM22*ZUL11* &
      conjg(Yd11)*conjg(ZD64) + (0,1)*UM22*ZUL12*conjg(Yd12)*conjg(ZD64) + (0,1)*UM22*ZUL13 &
      *conjg(Yd13)*conjg(ZD64) + (0,1)*UM22*ZUL11*conjg(Yd21)*conjg(ZD65) + (0,1)*UM22* &
      ZUL12*conjg(Yd22)*conjg(ZD65) + (0,1)*UM22*ZUL13*conjg(Yd23)*conjg(ZD65) + (0,1)*UM22 &
      *ZUL11*conjg(Yd31)*conjg(ZD66) + (0,1)*UM22*ZUL12*conjg(Yd32)*conjg(ZD66) + (0,1 &
      )*UM22*ZUL13*conjg(Yd33)*conjg(ZD66))
   G_c2bar_sd1_u2bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP22)*conjg(ZD11)* &
      conjg(ZUR21) + (0,1)*Yu12*conjg(UP22)*conjg(ZD12)*conjg(ZUR21) + (0,1)*Yu13*conjg( &
      UP22)*conjg(ZD13)*conjg(ZUR21) + (0,1)*Yu21*conjg(UP22)*conjg(ZD11)*conjg(ZUR22) + ( &
      0,1)*Yu22*conjg(UP22)*conjg(ZD12)*conjg(ZUR22) + (0,1)*Yu23*conjg(UP22)*conjg( &
      ZD13)*conjg(ZUR22) + (0,1)*Yu31*conjg(UP22)*conjg(ZD11)*conjg(ZUR23) + (0,1)*Yu32* &
      conjg(UP22)*conjg(ZD12)*conjg(ZUR23) + (0,1)*Yu33*conjg(UP22)*conjg(ZD13)*conjg(ZUR23 &
      ))
   G_c2bar_sd1_u2bar(2) = (0,-0.5_default)*((0,-1)*g2*UM21*ZUL21*conjg(ZD11) - (0,1 &
      )*g2*UM21*ZUL22*conjg(ZD12) - (0,1)*g2*UM21*ZUL23*conjg(ZD13) + (0,1)*UM22*ZUL21* &
      conjg(Yd11)*conjg(ZD14) + (0,1)*UM22*ZUL22*conjg(Yd12)*conjg(ZD14) + (0,1)*UM22*ZUL23 &
      *conjg(Yd13)*conjg(ZD14) + (0,1)*UM22*ZUL21*conjg(Yd21)*conjg(ZD15) + (0,1)*UM22* &
      ZUL22*conjg(Yd22)*conjg(ZD15) + (0,1)*UM22*ZUL23*conjg(Yd23)*conjg(ZD15) + (0,1)*UM22 &
      *ZUL21*conjg(Yd31)*conjg(ZD16) + (0,1)*UM22*ZUL22*conjg(Yd32)*conjg(ZD16) + (0,1 &
      )*UM22*ZUL23*conjg(Yd33)*conjg(ZD16))
   G_c2bar_sd2_u2bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP22)*conjg(ZD21)* &
      conjg(ZUR21) + (0,1)*Yu12*conjg(UP22)*conjg(ZD22)*conjg(ZUR21) + (0,1)*Yu13*conjg( &
      UP22)*conjg(ZD23)*conjg(ZUR21) + (0,1)*Yu21*conjg(UP22)*conjg(ZD21)*conjg(ZUR22) + ( &
      0,1)*Yu22*conjg(UP22)*conjg(ZD22)*conjg(ZUR22) + (0,1)*Yu23*conjg(UP22)*conjg( &
      ZD23)*conjg(ZUR22) + (0,1)*Yu31*conjg(UP22)*conjg(ZD21)*conjg(ZUR23) + (0,1)*Yu32* &
      conjg(UP22)*conjg(ZD22)*conjg(ZUR23) + (0,1)*Yu33*conjg(UP22)*conjg(ZD23)*conjg(ZUR23 &
      ))
   G_c2bar_sd2_u2bar(2) = (0,-0.5_default)*((0,-1)*g2*UM21*ZUL21*conjg(ZD21) - (0,1 &
      )*g2*UM21*ZUL22*conjg(ZD22) - (0,1)*g2*UM21*ZUL23*conjg(ZD23) + (0,1)*UM22*ZUL21* &
      conjg(Yd11)*conjg(ZD24) + (0,1)*UM22*ZUL22*conjg(Yd12)*conjg(ZD24) + (0,1)*UM22*ZUL23 &
      *conjg(Yd13)*conjg(ZD24) + (0,1)*UM22*ZUL21*conjg(Yd21)*conjg(ZD25) + (0,1)*UM22* &
      ZUL22*conjg(Yd22)*conjg(ZD25) + (0,1)*UM22*ZUL23*conjg(Yd23)*conjg(ZD25) + (0,1)*UM22 &
      *ZUL21*conjg(Yd31)*conjg(ZD26) + (0,1)*UM22*ZUL22*conjg(Yd32)*conjg(ZD26) + (0,1 &
      )*UM22*ZUL23*conjg(Yd33)*conjg(ZD26))
   G_c2bar_sd3_u2bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP22)*conjg(ZD31)* &
      conjg(ZUR21) + (0,1)*Yu12*conjg(UP22)*conjg(ZD32)*conjg(ZUR21) + (0,1)*Yu13*conjg( &
      UP22)*conjg(ZD33)*conjg(ZUR21) + (0,1)*Yu21*conjg(UP22)*conjg(ZD31)*conjg(ZUR22) + ( &
      0,1)*Yu22*conjg(UP22)*conjg(ZD32)*conjg(ZUR22) + (0,1)*Yu23*conjg(UP22)*conjg( &
      ZD33)*conjg(ZUR22) + (0,1)*Yu31*conjg(UP22)*conjg(ZD31)*conjg(ZUR23) + (0,1)*Yu32* &
      conjg(UP22)*conjg(ZD32)*conjg(ZUR23) + (0,1)*Yu33*conjg(UP22)*conjg(ZD33)*conjg(ZUR23 &
      ))
   G_c2bar_sd3_u2bar(2) = (0,-0.5_default)*((0,-1)*g2*UM21*ZUL21*conjg(ZD31) - (0,1 &
      )*g2*UM21*ZUL22*conjg(ZD32) - (0,1)*g2*UM21*ZUL23*conjg(ZD33) + (0,1)*UM22*ZUL21* &
      conjg(Yd11)*conjg(ZD34) + (0,1)*UM22*ZUL22*conjg(Yd12)*conjg(ZD34) + (0,1)*UM22*ZUL23 &
      *conjg(Yd13)*conjg(ZD34) + (0,1)*UM22*ZUL21*conjg(Yd21)*conjg(ZD35) + (0,1)*UM22* &
      ZUL22*conjg(Yd22)*conjg(ZD35) + (0,1)*UM22*ZUL23*conjg(Yd23)*conjg(ZD35) + (0,1)*UM22 &
      *ZUL21*conjg(Yd31)*conjg(ZD36) + (0,1)*UM22*ZUL22*conjg(Yd32)*conjg(ZD36) + (0,1 &
      )*UM22*ZUL23*conjg(Yd33)*conjg(ZD36))
   G_c2bar_sd4_u2bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP22)*conjg(ZD41)* &
      conjg(ZUR21) + (0,1)*Yu12*conjg(UP22)*conjg(ZD42)*conjg(ZUR21) + (0,1)*Yu13*conjg( &
      UP22)*conjg(ZD43)*conjg(ZUR21) + (0,1)*Yu21*conjg(UP22)*conjg(ZD41)*conjg(ZUR22) + ( &
      0,1)*Yu22*conjg(UP22)*conjg(ZD42)*conjg(ZUR22) + (0,1)*Yu23*conjg(UP22)*conjg( &
      ZD43)*conjg(ZUR22) + (0,1)*Yu31*conjg(UP22)*conjg(ZD41)*conjg(ZUR23) + (0,1)*Yu32* &
      conjg(UP22)*conjg(ZD42)*conjg(ZUR23) + (0,1)*Yu33*conjg(UP22)*conjg(ZD43)*conjg(ZUR23 &
      ))
   G_c2bar_sd4_u2bar(2) = (0,-0.5_default)*((0,-1)*g2*UM21*ZUL21*conjg(ZD41) - (0,1 &
      )*g2*UM21*ZUL22*conjg(ZD42) - (0,1)*g2*UM21*ZUL23*conjg(ZD43) + (0,1)*UM22*ZUL21* &
      conjg(Yd11)*conjg(ZD44) + (0,1)*UM22*ZUL22*conjg(Yd12)*conjg(ZD44) + (0,1)*UM22*ZUL23 &
      *conjg(Yd13)*conjg(ZD44) + (0,1)*UM22*ZUL21*conjg(Yd21)*conjg(ZD45) + (0,1)*UM22* &
      ZUL22*conjg(Yd22)*conjg(ZD45) + (0,1)*UM22*ZUL23*conjg(Yd23)*conjg(ZD45) + (0,1)*UM22 &
      *ZUL21*conjg(Yd31)*conjg(ZD46) + (0,1)*UM22*ZUL22*conjg(Yd32)*conjg(ZD46) + (0,1 &
      )*UM22*ZUL23*conjg(Yd33)*conjg(ZD46))
   G_c2bar_sd5_u2bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP22)*conjg(ZD51)* &
      conjg(ZUR21) + (0,1)*Yu12*conjg(UP22)*conjg(ZD52)*conjg(ZUR21) + (0,1)*Yu13*conjg( &
      UP22)*conjg(ZD53)*conjg(ZUR21) + (0,1)*Yu21*conjg(UP22)*conjg(ZD51)*conjg(ZUR22) + ( &
      0,1)*Yu22*conjg(UP22)*conjg(ZD52)*conjg(ZUR22) + (0,1)*Yu23*conjg(UP22)*conjg( &
      ZD53)*conjg(ZUR22) + (0,1)*Yu31*conjg(UP22)*conjg(ZD51)*conjg(ZUR23) + (0,1)*Yu32* &
      conjg(UP22)*conjg(ZD52)*conjg(ZUR23) + (0,1)*Yu33*conjg(UP22)*conjg(ZD53)*conjg(ZUR23 &
      ))
   G_c2bar_sd5_u2bar(2) = (0,-0.5_default)*((0,-1)*g2*UM21*ZUL21*conjg(ZD51) - (0,1 &
      )*g2*UM21*ZUL22*conjg(ZD52) - (0,1)*g2*UM21*ZUL23*conjg(ZD53) + (0,1)*UM22*ZUL21* &
      conjg(Yd11)*conjg(ZD54) + (0,1)*UM22*ZUL22*conjg(Yd12)*conjg(ZD54) + (0,1)*UM22*ZUL23 &
      *conjg(Yd13)*conjg(ZD54) + (0,1)*UM22*ZUL21*conjg(Yd21)*conjg(ZD55) + (0,1)*UM22* &
      ZUL22*conjg(Yd22)*conjg(ZD55) + (0,1)*UM22*ZUL23*conjg(Yd23)*conjg(ZD55) + (0,1)*UM22 &
      *ZUL21*conjg(Yd31)*conjg(ZD56) + (0,1)*UM22*ZUL22*conjg(Yd32)*conjg(ZD56) + (0,1 &
      )*UM22*ZUL23*conjg(Yd33)*conjg(ZD56))
   G_c2bar_sd6_u2bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP22)*conjg(ZD61)* &
      conjg(ZUR21) + (0,1)*Yu12*conjg(UP22)*conjg(ZD62)*conjg(ZUR21) + (0,1)*Yu13*conjg( &
      UP22)*conjg(ZD63)*conjg(ZUR21) + (0,1)*Yu21*conjg(UP22)*conjg(ZD61)*conjg(ZUR22) + ( &
      0,1)*Yu22*conjg(UP22)*conjg(ZD62)*conjg(ZUR22) + (0,1)*Yu23*conjg(UP22)*conjg( &
      ZD63)*conjg(ZUR22) + (0,1)*Yu31*conjg(UP22)*conjg(ZD61)*conjg(ZUR23) + (0,1)*Yu32* &
      conjg(UP22)*conjg(ZD62)*conjg(ZUR23) + (0,1)*Yu33*conjg(UP22)*conjg(ZD63)*conjg(ZUR23 &
      ))
   G_c2bar_sd6_u2bar(2) = (0,-0.5_default)*((0,-1)*g2*UM21*ZUL21*conjg(ZD61) - (0,1 &
      )*g2*UM21*ZUL22*conjg(ZD62) - (0,1)*g2*UM21*ZUL23*conjg(ZD63) + (0,1)*UM22*ZUL21* &
      conjg(Yd11)*conjg(ZD64) + (0,1)*UM22*ZUL22*conjg(Yd12)*conjg(ZD64) + (0,1)*UM22*ZUL23 &
      *conjg(Yd13)*conjg(ZD64) + (0,1)*UM22*ZUL21*conjg(Yd21)*conjg(ZD65) + (0,1)*UM22* &
      ZUL22*conjg(Yd22)*conjg(ZD65) + (0,1)*UM22*ZUL23*conjg(Yd23)*conjg(ZD65) + (0,1)*UM22 &
      *ZUL21*conjg(Yd31)*conjg(ZD66) + (0,1)*UM22*ZUL22*conjg(Yd32)*conjg(ZD66) + (0,1 &
      )*UM22*ZUL23*conjg(Yd33)*conjg(ZD66))
   G_c2bar_sd1_u3bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP22)*conjg(ZD11)* &
      conjg(ZUR31) + (0,1)*Yu12*conjg(UP22)*conjg(ZD12)*conjg(ZUR31) + (0,1)*Yu13*conjg( &
      UP22)*conjg(ZD13)*conjg(ZUR31) + (0,1)*Yu21*conjg(UP22)*conjg(ZD11)*conjg(ZUR32) + ( &
      0,1)*Yu22*conjg(UP22)*conjg(ZD12)*conjg(ZUR32) + (0,1)*Yu23*conjg(UP22)*conjg( &
      ZD13)*conjg(ZUR32) + (0,1)*Yu31*conjg(UP22)*conjg(ZD11)*conjg(ZUR33) + (0,1)*Yu32* &
      conjg(UP22)*conjg(ZD12)*conjg(ZUR33) + (0,1)*Yu33*conjg(UP22)*conjg(ZD13)*conjg(ZUR33 &
      ))
   G_c2bar_sd1_u3bar(2) = (0,-0.5_default)*((0,-1)*g2*UM21*ZUL31*conjg(ZD11) - (0,1 &
      )*g2*UM21*ZUL32*conjg(ZD12) - (0,1)*g2*UM21*ZUL33*conjg(ZD13) + (0,1)*UM22*ZUL31* &
      conjg(Yd11)*conjg(ZD14) + (0,1)*UM22*ZUL32*conjg(Yd12)*conjg(ZD14) + (0,1)*UM22*ZUL33 &
      *conjg(Yd13)*conjg(ZD14) + (0,1)*UM22*ZUL31*conjg(Yd21)*conjg(ZD15) + (0,1)*UM22* &
      ZUL32*conjg(Yd22)*conjg(ZD15) + (0,1)*UM22*ZUL33*conjg(Yd23)*conjg(ZD15) + (0,1)*UM22 &
      *ZUL31*conjg(Yd31)*conjg(ZD16) + (0,1)*UM22*ZUL32*conjg(Yd32)*conjg(ZD16) + (0,1 &
      )*UM22*ZUL33*conjg(Yd33)*conjg(ZD16))
   G_c2bar_sd2_u3bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP22)*conjg(ZD21)* &
      conjg(ZUR31) + (0,1)*Yu12*conjg(UP22)*conjg(ZD22)*conjg(ZUR31) + (0,1)*Yu13*conjg( &
      UP22)*conjg(ZD23)*conjg(ZUR31) + (0,1)*Yu21*conjg(UP22)*conjg(ZD21)*conjg(ZUR32) + ( &
      0,1)*Yu22*conjg(UP22)*conjg(ZD22)*conjg(ZUR32) + (0,1)*Yu23*conjg(UP22)*conjg( &
      ZD23)*conjg(ZUR32) + (0,1)*Yu31*conjg(UP22)*conjg(ZD21)*conjg(ZUR33) + (0,1)*Yu32* &
      conjg(UP22)*conjg(ZD22)*conjg(ZUR33) + (0,1)*Yu33*conjg(UP22)*conjg(ZD23)*conjg(ZUR33 &
      ))
   G_c2bar_sd2_u3bar(2) = (0,-0.5_default)*((0,-1)*g2*UM21*ZUL31*conjg(ZD21) - (0,1 &
      )*g2*UM21*ZUL32*conjg(ZD22) - (0,1)*g2*UM21*ZUL33*conjg(ZD23) + (0,1)*UM22*ZUL31* &
      conjg(Yd11)*conjg(ZD24) + (0,1)*UM22*ZUL32*conjg(Yd12)*conjg(ZD24) + (0,1)*UM22*ZUL33 &
      *conjg(Yd13)*conjg(ZD24) + (0,1)*UM22*ZUL31*conjg(Yd21)*conjg(ZD25) + (0,1)*UM22* &
      ZUL32*conjg(Yd22)*conjg(ZD25) + (0,1)*UM22*ZUL33*conjg(Yd23)*conjg(ZD25) + (0,1)*UM22 &
      *ZUL31*conjg(Yd31)*conjg(ZD26) + (0,1)*UM22*ZUL32*conjg(Yd32)*conjg(ZD26) + (0,1 &
      )*UM22*ZUL33*conjg(Yd33)*conjg(ZD26))
   G_c2bar_sd3_u3bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP22)*conjg(ZD31)* &
      conjg(ZUR31) + (0,1)*Yu12*conjg(UP22)*conjg(ZD32)*conjg(ZUR31) + (0,1)*Yu13*conjg( &
      UP22)*conjg(ZD33)*conjg(ZUR31) + (0,1)*Yu21*conjg(UP22)*conjg(ZD31)*conjg(ZUR32) + ( &
      0,1)*Yu22*conjg(UP22)*conjg(ZD32)*conjg(ZUR32) + (0,1)*Yu23*conjg(UP22)*conjg( &
      ZD33)*conjg(ZUR32) + (0,1)*Yu31*conjg(UP22)*conjg(ZD31)*conjg(ZUR33) + (0,1)*Yu32* &
      conjg(UP22)*conjg(ZD32)*conjg(ZUR33) + (0,1)*Yu33*conjg(UP22)*conjg(ZD33)*conjg(ZUR33 &
      ))
   G_c2bar_sd3_u3bar(2) = (0,-0.5_default)*((0,-1)*g2*UM21*ZUL31*conjg(ZD31) - (0,1 &
      )*g2*UM21*ZUL32*conjg(ZD32) - (0,1)*g2*UM21*ZUL33*conjg(ZD33) + (0,1)*UM22*ZUL31* &
      conjg(Yd11)*conjg(ZD34) + (0,1)*UM22*ZUL32*conjg(Yd12)*conjg(ZD34) + (0,1)*UM22*ZUL33 &
      *conjg(Yd13)*conjg(ZD34) + (0,1)*UM22*ZUL31*conjg(Yd21)*conjg(ZD35) + (0,1)*UM22* &
      ZUL32*conjg(Yd22)*conjg(ZD35) + (0,1)*UM22*ZUL33*conjg(Yd23)*conjg(ZD35) + (0,1)*UM22 &
      *ZUL31*conjg(Yd31)*conjg(ZD36) + (0,1)*UM22*ZUL32*conjg(Yd32)*conjg(ZD36) + (0,1 &
      )*UM22*ZUL33*conjg(Yd33)*conjg(ZD36))
   G_c2bar_sd4_u3bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP22)*conjg(ZD41)* &
      conjg(ZUR31) + (0,1)*Yu12*conjg(UP22)*conjg(ZD42)*conjg(ZUR31) + (0,1)*Yu13*conjg( &
      UP22)*conjg(ZD43)*conjg(ZUR31) + (0,1)*Yu21*conjg(UP22)*conjg(ZD41)*conjg(ZUR32) + ( &
      0,1)*Yu22*conjg(UP22)*conjg(ZD42)*conjg(ZUR32) + (0,1)*Yu23*conjg(UP22)*conjg( &
      ZD43)*conjg(ZUR32) + (0,1)*Yu31*conjg(UP22)*conjg(ZD41)*conjg(ZUR33) + (0,1)*Yu32* &
      conjg(UP22)*conjg(ZD42)*conjg(ZUR33) + (0,1)*Yu33*conjg(UP22)*conjg(ZD43)*conjg(ZUR33 &
      ))
   G_c2bar_sd4_u3bar(2) = (0,-0.5_default)*((0,-1)*g2*UM21*ZUL31*conjg(ZD41) - (0,1 &
      )*g2*UM21*ZUL32*conjg(ZD42) - (0,1)*g2*UM21*ZUL33*conjg(ZD43) + (0,1)*UM22*ZUL31* &
      conjg(Yd11)*conjg(ZD44) + (0,1)*UM22*ZUL32*conjg(Yd12)*conjg(ZD44) + (0,1)*UM22*ZUL33 &
      *conjg(Yd13)*conjg(ZD44) + (0,1)*UM22*ZUL31*conjg(Yd21)*conjg(ZD45) + (0,1)*UM22* &
      ZUL32*conjg(Yd22)*conjg(ZD45) + (0,1)*UM22*ZUL33*conjg(Yd23)*conjg(ZD45) + (0,1)*UM22 &
      *ZUL31*conjg(Yd31)*conjg(ZD46) + (0,1)*UM22*ZUL32*conjg(Yd32)*conjg(ZD46) + (0,1 &
      )*UM22*ZUL33*conjg(Yd33)*conjg(ZD46))
   G_c2bar_sd5_u3bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP22)*conjg(ZD51)* &
      conjg(ZUR31) + (0,1)*Yu12*conjg(UP22)*conjg(ZD52)*conjg(ZUR31) + (0,1)*Yu13*conjg( &
      UP22)*conjg(ZD53)*conjg(ZUR31) + (0,1)*Yu21*conjg(UP22)*conjg(ZD51)*conjg(ZUR32) + ( &
      0,1)*Yu22*conjg(UP22)*conjg(ZD52)*conjg(ZUR32) + (0,1)*Yu23*conjg(UP22)*conjg( &
      ZD53)*conjg(ZUR32) + (0,1)*Yu31*conjg(UP22)*conjg(ZD51)*conjg(ZUR33) + (0,1)*Yu32* &
      conjg(UP22)*conjg(ZD52)*conjg(ZUR33) + (0,1)*Yu33*conjg(UP22)*conjg(ZD53)*conjg(ZUR33 &
      ))
   G_c2bar_sd5_u3bar(2) = (0,-0.5_default)*((0,-1)*g2*UM21*ZUL31*conjg(ZD51) - (0,1 &
      )*g2*UM21*ZUL32*conjg(ZD52) - (0,1)*g2*UM21*ZUL33*conjg(ZD53) + (0,1)*UM22*ZUL31* &
      conjg(Yd11)*conjg(ZD54) + (0,1)*UM22*ZUL32*conjg(Yd12)*conjg(ZD54) + (0,1)*UM22*ZUL33 &
      *conjg(Yd13)*conjg(ZD54) + (0,1)*UM22*ZUL31*conjg(Yd21)*conjg(ZD55) + (0,1)*UM22* &
      ZUL32*conjg(Yd22)*conjg(ZD55) + (0,1)*UM22*ZUL33*conjg(Yd23)*conjg(ZD55) + (0,1)*UM22 &
      *ZUL31*conjg(Yd31)*conjg(ZD56) + (0,1)*UM22*ZUL32*conjg(Yd32)*conjg(ZD56) + (0,1 &
      )*UM22*ZUL33*conjg(Yd33)*conjg(ZD56))
   G_c2bar_sd6_u3bar(1) = (0,-0.5_default)*((0,1)*Yu11*conjg(UP22)*conjg(ZD61)* &
      conjg(ZUR31) + (0,1)*Yu12*conjg(UP22)*conjg(ZD62)*conjg(ZUR31) + (0,1)*Yu13*conjg( &
      UP22)*conjg(ZD63)*conjg(ZUR31) + (0,1)*Yu21*conjg(UP22)*conjg(ZD61)*conjg(ZUR32) + ( &
      0,1)*Yu22*conjg(UP22)*conjg(ZD62)*conjg(ZUR32) + (0,1)*Yu23*conjg(UP22)*conjg( &
      ZD63)*conjg(ZUR32) + (0,1)*Yu31*conjg(UP22)*conjg(ZD61)*conjg(ZUR33) + (0,1)*Yu32* &
      conjg(UP22)*conjg(ZD62)*conjg(ZUR33) + (0,1)*Yu33*conjg(UP22)*conjg(ZD63)*conjg(ZUR33 &
      ))
   G_c2bar_sd6_u3bar(2) = (0,-0.5_default)*((0,-1)*g2*UM21*ZUL31*conjg(ZD61) - (0,1 &
      )*g2*UM21*ZUL32*conjg(ZD62) - (0,1)*g2*UM21*ZUL33*conjg(ZD63) + (0,1)*UM22*ZUL31* &
      conjg(Yd11)*conjg(ZD64) + (0,1)*UM22*ZUL32*conjg(Yd12)*conjg(ZD64) + (0,1)*UM22*ZUL33 &
      *conjg(Yd13)*conjg(ZD64) + (0,1)*UM22*ZUL31*conjg(Yd21)*conjg(ZD65) + (0,1)*UM22* &
      ZUL32*conjg(Yd22)*conjg(ZD65) + (0,1)*UM22*ZUL33*conjg(Yd23)*conjg(ZD65) + (0,1)*UM22 &
      *ZUL31*conjg(Yd31)*conjg(ZD66) + (0,1)*UM22*ZUL32*conjg(Yd32)*conjg(ZD66) + (0,1 &
      )*UM22*ZUL33*conjg(Yd33)*conjg(ZD66))
   G_c1bar_se1_nu1bar = (0,-0.5_default)*((0,-1)*g2*UM11*ZVL11*conjg(ZE11) - (0,1)* &
      g2*UM11*ZVL12*conjg(ZE12) - (0,1)*g2*UM11*ZVL13*conjg(ZE13) + (0,1)*UM12*ZVL11* &
      conjg(Ye11)*conjg(ZE14) + (0,1)*UM12*ZVL12*conjg(Ye22)*conjg(ZE15) + (0,1)*UM12*ZVL13 &
      *conjg(Ye33)*conjg(ZE16))
   G_c1bar_se2_nu1bar = (0,-0.5_default)*((0,-1)*g2*UM11*ZVL11*conjg(ZE21) - (0,1)* &
      g2*UM11*ZVL12*conjg(ZE22) - (0,1)*g2*UM11*ZVL13*conjg(ZE23) + (0,1)*UM12*ZVL11* &
      conjg(Ye11)*conjg(ZE24) + (0,1)*UM12*ZVL12*conjg(Ye22)*conjg(ZE25) + (0,1)*UM12*ZVL13 &
      *conjg(Ye33)*conjg(ZE26))
   G_c1bar_se3_nu1bar = (0,-0.5_default)*((0,-1)*g2*UM11*ZVL11*conjg(ZE31) - (0,1)* &
      g2*UM11*ZVL12*conjg(ZE32) - (0,1)*g2*UM11*ZVL13*conjg(ZE33) + (0,1)*UM12*ZVL11* &
      conjg(Ye11)*conjg(ZE34) + (0,1)*UM12*ZVL12*conjg(Ye22)*conjg(ZE35) + (0,1)*UM12*ZVL13 &
      *conjg(Ye33)*conjg(ZE36))
   G_c1bar_se4_nu1bar = (0,-0.5_default)*((0,-1)*g2*UM11*ZVL11*conjg(ZE41) - (0,1)* &
      g2*UM11*ZVL12*conjg(ZE42) - (0,1)*g2*UM11*ZVL13*conjg(ZE43) + (0,1)*UM12*ZVL11* &
      conjg(Ye11)*conjg(ZE44) + (0,1)*UM12*ZVL12*conjg(Ye22)*conjg(ZE45) + (0,1)*UM12*ZVL13 &
      *conjg(Ye33)*conjg(ZE46))
   G_c1bar_se5_nu1bar = (0,-0.5_default)*((0,-1)*g2*UM11*ZVL11*conjg(ZE51) - (0,1)* &
      g2*UM11*ZVL12*conjg(ZE52) - (0,1)*g2*UM11*ZVL13*conjg(ZE53) + (0,1)*UM12*ZVL11* &
      conjg(Ye11)*conjg(ZE54) + (0,1)*UM12*ZVL12*conjg(Ye22)*conjg(ZE55) + (0,1)*UM12*ZVL13 &
      *conjg(Ye33)*conjg(ZE56))
   G_c1bar_se6_nu1bar = (0,-0.5_default)*((0,-1)*g2*UM11*ZVL11*conjg(ZE61) - (0,1)* &
      g2*UM11*ZVL12*conjg(ZE62) - (0,1)*g2*UM11*ZVL13*conjg(ZE63) + (0,1)*UM12*ZVL11* &
      conjg(Ye11)*conjg(ZE64) + (0,1)*UM12*ZVL12*conjg(Ye22)*conjg(ZE65) + (0,1)*UM12*ZVL13 &
      *conjg(Ye33)*conjg(ZE66))
   G_c1bar_se1_nu2bar = (0,-0.5_default)*((0,-1)*g2*UM11*ZVL21*conjg(ZE11) - (0,1)* &
      g2*UM11*ZVL22*conjg(ZE12) - (0,1)*g2*UM11*ZVL23*conjg(ZE13) + (0,1)*UM12*ZVL21* &
      conjg(Ye11)*conjg(ZE14) + (0,1)*UM12*ZVL22*conjg(Ye22)*conjg(ZE15) + (0,1)*UM12*ZVL23 &
      *conjg(Ye33)*conjg(ZE16))
   G_c1bar_se2_nu2bar = (0,-0.5_default)*((0,-1)*g2*UM11*ZVL21*conjg(ZE21) - (0,1)* &
      g2*UM11*ZVL22*conjg(ZE22) - (0,1)*g2*UM11*ZVL23*conjg(ZE23) + (0,1)*UM12*ZVL21* &
      conjg(Ye11)*conjg(ZE24) + (0,1)*UM12*ZVL22*conjg(Ye22)*conjg(ZE25) + (0,1)*UM12*ZVL23 &
      *conjg(Ye33)*conjg(ZE26))
   G_c1bar_se3_nu2bar = (0,-0.5_default)*((0,-1)*g2*UM11*ZVL21*conjg(ZE31) - (0,1)* &
      g2*UM11*ZVL22*conjg(ZE32) - (0,1)*g2*UM11*ZVL23*conjg(ZE33) + (0,1)*UM12*ZVL21* &
      conjg(Ye11)*conjg(ZE34) + (0,1)*UM12*ZVL22*conjg(Ye22)*conjg(ZE35) + (0,1)*UM12*ZVL23 &
      *conjg(Ye33)*conjg(ZE36))
   G_c1bar_se4_nu2bar = (0,-0.5_default)*((0,-1)*g2*UM11*ZVL21*conjg(ZE41) - (0,1)* &
      g2*UM11*ZVL22*conjg(ZE42) - (0,1)*g2*UM11*ZVL23*conjg(ZE43) + (0,1)*UM12*ZVL21* &
      conjg(Ye11)*conjg(ZE44) + (0,1)*UM12*ZVL22*conjg(Ye22)*conjg(ZE45) + (0,1)*UM12*ZVL23 &
      *conjg(Ye33)*conjg(ZE46))
   G_c1bar_se5_nu2bar = (0,-0.5_default)*((0,-1)*g2*UM11*ZVL21*conjg(ZE51) - (0,1)* &
      g2*UM11*ZVL22*conjg(ZE52) - (0,1)*g2*UM11*ZVL23*conjg(ZE53) + (0,1)*UM12*ZVL21* &
      conjg(Ye11)*conjg(ZE54) + (0,1)*UM12*ZVL22*conjg(Ye22)*conjg(ZE55) + (0,1)*UM12*ZVL23 &
      *conjg(Ye33)*conjg(ZE56))
   G_c1bar_se6_nu2bar = (0,-0.5_default)*((0,-1)*g2*UM11*ZVL21*conjg(ZE61) - (0,1)* &
      g2*UM11*ZVL22*conjg(ZE62) - (0,1)*g2*UM11*ZVL23*conjg(ZE63) + (0,1)*UM12*ZVL21* &
      conjg(Ye11)*conjg(ZE64) + (0,1)*UM12*ZVL22*conjg(Ye22)*conjg(ZE65) + (0,1)*UM12*ZVL23 &
      *conjg(Ye33)*conjg(ZE66))
   G_c1bar_se1_nu3bar = (0,-0.5_default)*((0,-1)*g2*UM11*ZVL31*conjg(ZE11) - (0,1)* &
      g2*UM11*ZVL32*conjg(ZE12) - (0,1)*g2*UM11*ZVL33*conjg(ZE13) + (0,1)*UM12*ZVL31* &
      conjg(Ye11)*conjg(ZE14) + (0,1)*UM12*ZVL32*conjg(Ye22)*conjg(ZE15) + (0,1)*UM12*ZVL33 &
      *conjg(Ye33)*conjg(ZE16))
   G_c1bar_se2_nu3bar = (0,-0.5_default)*((0,-1)*g2*UM11*ZVL31*conjg(ZE21) - (0,1)* &
      g2*UM11*ZVL32*conjg(ZE22) - (0,1)*g2*UM11*ZVL33*conjg(ZE23) + (0,1)*UM12*ZVL31* &
      conjg(Ye11)*conjg(ZE24) + (0,1)*UM12*ZVL32*conjg(Ye22)*conjg(ZE25) + (0,1)*UM12*ZVL33 &
      *conjg(Ye33)*conjg(ZE26))
   G_c1bar_se3_nu3bar = (0,-0.5_default)*((0,-1)*g2*UM11*ZVL31*conjg(ZE31) - (0,1)* &
      g2*UM11*ZVL32*conjg(ZE32) - (0,1)*g2*UM11*ZVL33*conjg(ZE33) + (0,1)*UM12*ZVL31* &
      conjg(Ye11)*conjg(ZE34) + (0,1)*UM12*ZVL32*conjg(Ye22)*conjg(ZE35) + (0,1)*UM12*ZVL33 &
      *conjg(Ye33)*conjg(ZE36))
   G_c1bar_se4_nu3bar = (0,-0.5_default)*((0,-1)*g2*UM11*ZVL31*conjg(ZE41) - (0,1)* &
      g2*UM11*ZVL32*conjg(ZE42) - (0,1)*g2*UM11*ZVL33*conjg(ZE43) + (0,1)*UM12*ZVL31* &
      conjg(Ye11)*conjg(ZE44) + (0,1)*UM12*ZVL32*conjg(Ye22)*conjg(ZE45) + (0,1)*UM12*ZVL33 &
      *conjg(Ye33)*conjg(ZE46))
   G_c1bar_se5_nu3bar = (0,-0.5_default)*((0,-1)*g2*UM11*ZVL31*conjg(ZE51) - (0,1)* &
      g2*UM11*ZVL32*conjg(ZE52) - (0,1)*g2*UM11*ZVL33*conjg(ZE53) + (0,1)*UM12*ZVL31* &
      conjg(Ye11)*conjg(ZE54) + (0,1)*UM12*ZVL32*conjg(Ye22)*conjg(ZE55) + (0,1)*UM12*ZVL33 &
      *conjg(Ye33)*conjg(ZE56))
   G_c1bar_se6_nu3bar = (0,-0.5_default)*((0,-1)*g2*UM11*ZVL31*conjg(ZE61) - (0,1)* &
      g2*UM11*ZVL32*conjg(ZE62) - (0,1)*g2*UM11*ZVL33*conjg(ZE63) + (0,1)*UM12*ZVL31* &
      conjg(Ye11)*conjg(ZE64) + (0,1)*UM12*ZVL32*conjg(Ye22)*conjg(ZE65) + (0,1)*UM12*ZVL33 &
      *conjg(Ye33)*conjg(ZE66))
   G_c2bar_se1_nu1bar = (0,-0.5_default)*((0,-1)*g2*UM21*ZVL11*conjg(ZE11) - (0,1)* &
      g2*UM21*ZVL12*conjg(ZE12) - (0,1)*g2*UM21*ZVL13*conjg(ZE13) + (0,1)*UM22*ZVL11* &
      conjg(Ye11)*conjg(ZE14) + (0,1)*UM22*ZVL12*conjg(Ye22)*conjg(ZE15) + (0,1)*UM22*ZVL13 &
      *conjg(Ye33)*conjg(ZE16))
   G_c2bar_se2_nu1bar = (0,-0.5_default)*((0,-1)*g2*UM21*ZVL11*conjg(ZE21) - (0,1)* &
      g2*UM21*ZVL12*conjg(ZE22) - (0,1)*g2*UM21*ZVL13*conjg(ZE23) + (0,1)*UM22*ZVL11* &
      conjg(Ye11)*conjg(ZE24) + (0,1)*UM22*ZVL12*conjg(Ye22)*conjg(ZE25) + (0,1)*UM22*ZVL13 &
      *conjg(Ye33)*conjg(ZE26))
   G_c2bar_se3_nu1bar = (0,-0.5_default)*((0,-1)*g2*UM21*ZVL11*conjg(ZE31) - (0,1)* &
      g2*UM21*ZVL12*conjg(ZE32) - (0,1)*g2*UM21*ZVL13*conjg(ZE33) + (0,1)*UM22*ZVL11* &
      conjg(Ye11)*conjg(ZE34) + (0,1)*UM22*ZVL12*conjg(Ye22)*conjg(ZE35) + (0,1)*UM22*ZVL13 &
      *conjg(Ye33)*conjg(ZE36))
   G_c2bar_se4_nu1bar = (0,-0.5_default)*((0,-1)*g2*UM21*ZVL11*conjg(ZE41) - (0,1)* &
      g2*UM21*ZVL12*conjg(ZE42) - (0,1)*g2*UM21*ZVL13*conjg(ZE43) + (0,1)*UM22*ZVL11* &
      conjg(Ye11)*conjg(ZE44) + (0,1)*UM22*ZVL12*conjg(Ye22)*conjg(ZE45) + (0,1)*UM22*ZVL13 &
      *conjg(Ye33)*conjg(ZE46))
   G_c2bar_se5_nu1bar = (0,-0.5_default)*((0,-1)*g2*UM21*ZVL11*conjg(ZE51) - (0,1)* &
      g2*UM21*ZVL12*conjg(ZE52) - (0,1)*g2*UM21*ZVL13*conjg(ZE53) + (0,1)*UM22*ZVL11* &
      conjg(Ye11)*conjg(ZE54) + (0,1)*UM22*ZVL12*conjg(Ye22)*conjg(ZE55) + (0,1)*UM22*ZVL13 &
      *conjg(Ye33)*conjg(ZE56))
   G_c2bar_se6_nu1bar = (0,-0.5_default)*((0,-1)*g2*UM21*ZVL11*conjg(ZE61) - (0,1)* &
      g2*UM21*ZVL12*conjg(ZE62) - (0,1)*g2*UM21*ZVL13*conjg(ZE63) + (0,1)*UM22*ZVL11* &
      conjg(Ye11)*conjg(ZE64) + (0,1)*UM22*ZVL12*conjg(Ye22)*conjg(ZE65) + (0,1)*UM22*ZVL13 &
      *conjg(Ye33)*conjg(ZE66))
   G_c2bar_se1_nu2bar = (0,-0.5_default)*((0,-1)*g2*UM21*ZVL21*conjg(ZE11) - (0,1)* &
      g2*UM21*ZVL22*conjg(ZE12) - (0,1)*g2*UM21*ZVL23*conjg(ZE13) + (0,1)*UM22*ZVL21* &
      conjg(Ye11)*conjg(ZE14) + (0,1)*UM22*ZVL22*conjg(Ye22)*conjg(ZE15) + (0,1)*UM22*ZVL23 &
      *conjg(Ye33)*conjg(ZE16))
   G_c2bar_se2_nu2bar = (0,-0.5_default)*((0,-1)*g2*UM21*ZVL21*conjg(ZE21) - (0,1)* &
      g2*UM21*ZVL22*conjg(ZE22) - (0,1)*g2*UM21*ZVL23*conjg(ZE23) + (0,1)*UM22*ZVL21* &
      conjg(Ye11)*conjg(ZE24) + (0,1)*UM22*ZVL22*conjg(Ye22)*conjg(ZE25) + (0,1)*UM22*ZVL23 &
      *conjg(Ye33)*conjg(ZE26))
   G_c2bar_se3_nu2bar = (0,-0.5_default)*((0,-1)*g2*UM21*ZVL21*conjg(ZE31) - (0,1)* &
      g2*UM21*ZVL22*conjg(ZE32) - (0,1)*g2*UM21*ZVL23*conjg(ZE33) + (0,1)*UM22*ZVL21* &
      conjg(Ye11)*conjg(ZE34) + (0,1)*UM22*ZVL22*conjg(Ye22)*conjg(ZE35) + (0,1)*UM22*ZVL23 &
      *conjg(Ye33)*conjg(ZE36))
   G_c2bar_se4_nu2bar = (0,-0.5_default)*((0,-1)*g2*UM21*ZVL21*conjg(ZE41) - (0,1)* &
      g2*UM21*ZVL22*conjg(ZE42) - (0,1)*g2*UM21*ZVL23*conjg(ZE43) + (0,1)*UM22*ZVL21* &
      conjg(Ye11)*conjg(ZE44) + (0,1)*UM22*ZVL22*conjg(Ye22)*conjg(ZE45) + (0,1)*UM22*ZVL23 &
      *conjg(Ye33)*conjg(ZE46))
   G_c2bar_se5_nu2bar = (0,-0.5_default)*((0,-1)*g2*UM21*ZVL21*conjg(ZE51) - (0,1)* &
      g2*UM21*ZVL22*conjg(ZE52) - (0,1)*g2*UM21*ZVL23*conjg(ZE53) + (0,1)*UM22*ZVL21* &
      conjg(Ye11)*conjg(ZE54) + (0,1)*UM22*ZVL22*conjg(Ye22)*conjg(ZE55) + (0,1)*UM22*ZVL23 &
      *conjg(Ye33)*conjg(ZE56))
   G_c2bar_se6_nu2bar = (0,-0.5_default)*((0,-1)*g2*UM21*ZVL21*conjg(ZE61) - (0,1)* &
      g2*UM21*ZVL22*conjg(ZE62) - (0,1)*g2*UM21*ZVL23*conjg(ZE63) + (0,1)*UM22*ZVL21* &
      conjg(Ye11)*conjg(ZE64) + (0,1)*UM22*ZVL22*conjg(Ye22)*conjg(ZE65) + (0,1)*UM22*ZVL23 &
      *conjg(Ye33)*conjg(ZE66))
   G_c2bar_se1_nu3bar = (0,-0.5_default)*((0,-1)*g2*UM21*ZVL31*conjg(ZE11) - (0,1)* &
      g2*UM21*ZVL32*conjg(ZE12) - (0,1)*g2*UM21*ZVL33*conjg(ZE13) + (0,1)*UM22*ZVL31* &
      conjg(Ye11)*conjg(ZE14) + (0,1)*UM22*ZVL32*conjg(Ye22)*conjg(ZE15) + (0,1)*UM22*ZVL33 &
      *conjg(Ye33)*conjg(ZE16))
   G_c2bar_se2_nu3bar = (0,-0.5_default)*((0,-1)*g2*UM21*ZVL31*conjg(ZE21) - (0,1)* &
      g2*UM21*ZVL32*conjg(ZE22) - (0,1)*g2*UM21*ZVL33*conjg(ZE23) + (0,1)*UM22*ZVL31* &
      conjg(Ye11)*conjg(ZE24) + (0,1)*UM22*ZVL32*conjg(Ye22)*conjg(ZE25) + (0,1)*UM22*ZVL33 &
      *conjg(Ye33)*conjg(ZE26))
   G_c2bar_se3_nu3bar = (0,-0.5_default)*((0,-1)*g2*UM21*ZVL31*conjg(ZE31) - (0,1)* &
      g2*UM21*ZVL32*conjg(ZE32) - (0,1)*g2*UM21*ZVL33*conjg(ZE33) + (0,1)*UM22*ZVL31* &
      conjg(Ye11)*conjg(ZE34) + (0,1)*UM22*ZVL32*conjg(Ye22)*conjg(ZE35) + (0,1)*UM22*ZVL33 &
      *conjg(Ye33)*conjg(ZE36))
   G_c2bar_se4_nu3bar = (0,-0.5_default)*((0,-1)*g2*UM21*ZVL31*conjg(ZE41) - (0,1)* &
      g2*UM21*ZVL32*conjg(ZE42) - (0,1)*g2*UM21*ZVL33*conjg(ZE43) + (0,1)*UM22*ZVL31* &
      conjg(Ye11)*conjg(ZE44) + (0,1)*UM22*ZVL32*conjg(Ye22)*conjg(ZE45) + (0,1)*UM22*ZVL33 &
      *conjg(Ye33)*conjg(ZE46))
   G_c2bar_se5_nu3bar = (0,-0.5_default)*((0,-1)*g2*UM21*ZVL31*conjg(ZE51) - (0,1)* &
      g2*UM21*ZVL32*conjg(ZE52) - (0,1)*g2*UM21*ZVL33*conjg(ZE53) + (0,1)*UM22*ZVL31* &
      conjg(Ye11)*conjg(ZE54) + (0,1)*UM22*ZVL32*conjg(Ye22)*conjg(ZE55) + (0,1)*UM22*ZVL33 &
      *conjg(Ye33)*conjg(ZE56))
   G_c2bar_se6_nu3bar = (0,-0.5_default)*((0,-1)*g2*UM21*ZVL31*conjg(ZE61) - (0,1)* &
      g2*UM21*ZVL32*conjg(ZE62) - (0,1)*g2*UM21*ZVL33*conjg(ZE63) + (0,1)*UM22*ZVL31* &
      conjg(Ye11)*conjg(ZE64) + (0,1)*UM22*ZVL32*conjg(Ye22)*conjg(ZE65) + (0,1)*UM22*ZVL33 &
      *conjg(Ye33)*conjg(ZE66))
   G_n1_wmc_c1(1) = (0,-0.5_default)*((0,1)*g2*ZN13*conjg(UM11) + ((0,1)*g2*ZN14* &
      conjg(UM12))/Sqrt (2._default))
   G_n1_wmc_c1(2) = (0,-0.5_default)*((0,1)*g2*UP11*conjg(ZN13) - ((0,1)*g2*UP12* &
      conjg(ZN15))/Sqrt (2._default))
   G_n1_wmc_c2(1) = (0,-0.5_default)*((0,1)*g2*ZN13*conjg(UM21) + ((0,1)*g2*ZN14* &
      conjg(UM22))/Sqrt (2._default))
   G_n1_wmc_c2(2) = (0,-0.5_default)*((0,1)*g2*UP21*conjg(ZN13) - ((0,1)*g2*UP22* &
      conjg(ZN15))/Sqrt (2._default))
   G_n2_wmc_c1(1) = (0,-0.5_default)*((0,1)*g2*ZN23*conjg(UM11) + ((0,1)*g2*ZN24* &
      conjg(UM12))/Sqrt (2._default))
   G_n2_wmc_c1(2) = (0,-0.5_default)*((0,1)*g2*UP11*conjg(ZN23) - ((0,1)*g2*UP12* &
      conjg(ZN25))/Sqrt (2._default))
   G_n2_wmc_c2(1) = (0,-0.5_default)*((0,1)*g2*ZN23*conjg(UM21) + ((0,1)*g2*ZN24* &
      conjg(UM22))/Sqrt (2._default))
   G_n2_wmc_c2(2) = (0,-0.5_default)*((0,1)*g2*UP21*conjg(ZN23) - ((0,1)*g2*UP22* &
      conjg(ZN25))/Sqrt (2._default))
   G_n3_wmc_c1(1) = (0,-0.5_default)*((0,1)*g2*ZN33*conjg(UM11) + ((0,1)*g2*ZN34* &
      conjg(UM12))/Sqrt (2._default))
   G_n3_wmc_c1(2) = (0,-0.5_default)*((0,1)*g2*UP11*conjg(ZN33) - ((0,1)*g2*UP12* &
      conjg(ZN35))/Sqrt (2._default))
   G_n3_wmc_c2(1) = (0,-0.5_default)*((0,1)*g2*ZN33*conjg(UM21) + ((0,1)*g2*ZN34* &
      conjg(UM22))/Sqrt (2._default))
   G_n3_wmc_c2(2) = (0,-0.5_default)*((0,1)*g2*UP21*conjg(ZN33) - ((0,1)*g2*UP22* &
      conjg(ZN35))/Sqrt (2._default))
   G_n4_wmc_c1(1) = (0,-0.5_default)*((0,1)*g2*ZN43*conjg(UM11) + ((0,1)*g2*ZN44* &
      conjg(UM12))/Sqrt (2._default))
   G_n4_wmc_c1(2) = (0,-0.5_default)*((0,1)*g2*UP11*conjg(ZN43) - ((0,1)*g2*UP12* &
      conjg(ZN45))/Sqrt (2._default))
   G_n4_wmc_c2(1) = (0,-0.5_default)*((0,1)*g2*ZN43*conjg(UM21) + ((0,1)*g2*ZN44* &
      conjg(UM22))/Sqrt (2._default))
   G_n4_wmc_c2(2) = (0,-0.5_default)*((0,1)*g2*UP21*conjg(ZN43) - ((0,1)*g2*UP22* &
      conjg(ZN45))/Sqrt (2._default))
   G_n5_wmc_c1(1) = (0,-0.5_default)*((0,1)*g2*ZN53*conjg(UM11) + ((0,1)*g2*ZN54* &
      conjg(UM12))/Sqrt (2._default))
   G_n5_wmc_c1(2) = (0,-0.5_default)*((0,1)*g2*UP11*conjg(ZN53) - ((0,1)*g2*UP12* &
      conjg(ZN55))/Sqrt (2._default))
   G_n5_wmc_c2(1) = (0,-0.5_default)*((0,1)*g2*ZN53*conjg(UM21) + ((0,1)*g2*ZN54* &
      conjg(UM22))/Sqrt (2._default))
   G_n5_wmc_c2(2) = (0,-0.5_default)*((0,1)*g2*UP21*conjg(ZN53) - ((0,1)*g2*UP22* &
      conjg(ZN55))/Sqrt (2._default))
   G_n6_wmc_c1(1) = (0,-0.5_default)*((0,1)*g2*ZN63*conjg(UM11) + ((0,1)*g2*ZN64* &
      conjg(UM12))/Sqrt (2._default))
   G_n6_wmc_c1(2) = (0,-0.5_default)*((0,1)*g2*UP11*conjg(ZN63) - ((0,1)*g2*UP12* &
      conjg(ZN65))/Sqrt (2._default))
   G_n6_wmc_c2(1) = (0,-0.5_default)*((0,1)*g2*ZN63*conjg(UM21) + ((0,1)*g2*ZN64* &
      conjg(UM22))/Sqrt (2._default))
   G_n6_wmc_c2(2) = (0,-0.5_default)*((0,1)*g2*UP21*conjg(ZN63) - ((0,1)*g2*UP22* &
      conjg(ZN65))/Sqrt (2._default))
   G_c1bar_a_1_c1(1) = (0,-0.5_default)*((0,-0.5_default)*g1*UM12*conjg(UM12)*Cos( &
      TW) - (0,1)*g2*UM11*conjg(UM11)*Sin(TW) - (0,0.5_default)*g2*UM12*conjg(UM12)*Sin( &
      TW))
   G_c1bar_a_1_c1(2) = (0,-0.5_default)*((0,-0.5_default)*g1*UP12*conjg(UP12)*Cos( &
      TW) - (0,1)*g2*UP11*conjg(UP11)*Sin(TW) - (0,0.5_default)*g2*UP12*conjg(UP12)*Sin( &
      TW))
   G_c1bar_a_1_c2(1) = (0,-0.5_default)*((0,-0.5_default)*g1*UM12*conjg(UM22)*Cos( &
      TW) - (0,1)*g2*UM11*conjg(UM21)*Sin(TW) - (0,0.5_default)*g2*UM12*conjg(UM22)*Sin( &
      TW))
   G_c1bar_a_1_c2(2) = (0,-0.5_default)*((0,-0.5_default)*g1*UP22*conjg(UP12)*Cos( &
      TW) - (0,1)*g2*UP21*conjg(UP11)*Sin(TW) - (0,0.5_default)*g2*UP22*conjg(UP12)*Sin( &
      TW))
   G_c2bar_a_1_c1(1) = (0,-0.5_default)*((0,-0.5_default)*g1*UM22*conjg(UM12)*Cos( &
      TW) - (0,1)*g2*UM21*conjg(UM11)*Sin(TW) - (0,0.5_default)*g2*UM22*conjg(UM12)*Sin( &
      TW))
   G_c2bar_a_1_c1(2) = (0,-0.5_default)*((0,-0.5_default)*g1*UP12*conjg(UP22)*Cos( &
      TW) - (0,1)*g2*UP11*conjg(UP21)*Sin(TW) - (0,0.5_default)*g2*UP12*conjg(UP22)*Sin( &
      TW))
   G_c2bar_a_1_c2(1) = (0,-0.5_default)*((0,-0.5_default)*g1*UM22*conjg(UM22)*Cos( &
      TW) - (0,1)*g2*UM21*conjg(UM21)*Sin(TW) - (0,0.5_default)*g2*UM22*conjg(UM22)*Sin( &
      TW))
   G_c2bar_a_1_c2(2) = (0,-0.5_default)*((0,-0.5_default)*g1*UP22*conjg(UP22)*Cos( &
      TW) - (0,1)*g2*UP21*conjg(UP21)*Sin(TW) - (0,0.5_default)*g2*UP22*conjg(UP22)*Sin( &
      TW))
   G_c1bar_z_1_c1(1) = (0,-0.5_default)*((0,-1)*g2*UM11*conjg(UM11)*Cos(TW)*Cos(TWp &
      ) - (0,0.5_default)*g2*UM12*conjg(UM12)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g1*UM12* &
      conjg(UM12)*Cos(TWp)*Sin(TW) + (0,1)*gp*QHd*UM12*conjg(UM12)*Sin(TWp))
   G_c1bar_z_1_c1(2) = (0,-0.5_default)*((0,-1)*g2*UP11*conjg(UP11)*Cos(TW)*Cos(TWp &
      ) - (0,0.5_default)*g2*UP12*conjg(UP12)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g1*UP12* &
      conjg(UP12)*Cos(TWp)*Sin(TW) - (0,1)*gp*QHu*UP12*conjg(UP12)*Sin(TWp))
   G_c1bar_z_1_c2(1) = (0,-0.5_default)*((0,-1)*g2*UM11*conjg(UM21)*Cos(TW)*Cos(TWp &
      ) - (0,0.5_default)*g2*UM12*conjg(UM22)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g1*UM12* &
      conjg(UM22)*Cos(TWp)*Sin(TW) + (0,1)*gp*QHd*UM12*conjg(UM22)*Sin(TWp))
   G_c1bar_z_1_c2(2) = (0,-0.5_default)*((0,-1)*g2*UP21*conjg(UP11)*Cos(TW)*Cos(TWp &
      ) - (0,0.5_default)*g2*UP22*conjg(UP12)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g1*UP22* &
      conjg(UP12)*Cos(TWp)*Sin(TW) - (0,1)*gp*QHu*UP22*conjg(UP12)*Sin(TWp))
   G_c2bar_z_1_c1(1) = (0,-0.5_default)*((0,-1)*g2*UM21*conjg(UM11)*Cos(TW)*Cos(TWp &
      ) - (0,0.5_default)*g2*UM22*conjg(UM12)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g1*UM22* &
      conjg(UM12)*Cos(TWp)*Sin(TW) + (0,1)*gp*QHd*UM22*conjg(UM12)*Sin(TWp))
   G_c2bar_z_1_c1(2) = (0,-0.5_default)*((0,-1)*g2*UP11*conjg(UP21)*Cos(TW)*Cos(TWp &
      ) - (0,0.5_default)*g2*UP12*conjg(UP22)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g1*UP12* &
      conjg(UP22)*Cos(TWp)*Sin(TW) - (0,1)*gp*QHu*UP12*conjg(UP22)*Sin(TWp))
   G_c2bar_z_1_c2(1) = (0,-0.5_default)*((0,-1)*g2*UM21*conjg(UM21)*Cos(TW)*Cos(TWp &
      ) - (0,0.5_default)*g2*UM22*conjg(UM22)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g1*UM22* &
      conjg(UM22)*Cos(TWp)*Sin(TW) + (0,1)*gp*QHd*UM22*conjg(UM22)*Sin(TWp))
   G_c2bar_z_1_c2(2) = (0,-0.5_default)*((0,-1)*g2*UP21*conjg(UP21)*Cos(TW)*Cos(TWp &
      ) - (0,0.5_default)*g2*UP22*conjg(UP22)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g1*UP22* &
      conjg(UP22)*Cos(TWp)*Sin(TW) - (0,1)*gp*QHu*UP22*conjg(UP22)*Sin(TWp))
   G_c1bar_zp_1_c1(1) = (0,-0.5_default)*((0,1)*gp*QHd*UM12*conjg(UM12)*Cos(TWp &
      ) + (0,1)*g2*UM11*conjg(UM11)*Cos(TW)*Sin(TWp) + (0,0.5_default)*g2*UM12*conjg(UM12)* &
      Cos(TW)*Sin(TWp) - (0,0.5_default)*g1*UM12*conjg(UM12)*Sin(TW)*Sin(TWp))
   G_c1bar_zp_1_c1(2) = (0,-0.5_default)*((0,-1)*gp*QHu*UP12*conjg(UP12)*Cos(TWp &
      ) + (0,1)*g2*UP11*conjg(UP11)*Cos(TW)*Sin(TWp) + (0,0.5_default)*g2*UP12*conjg(UP12)* &
      Cos(TW)*Sin(TWp) - (0,0.5_default)*g1*UP12*conjg(UP12)*Sin(TW)*Sin(TWp))
   G_c1bar_zp_1_c2(1) = (0,-0.5_default)*((0,1)*gp*QHd*UM12*conjg(UM22)*Cos(TWp &
      ) + (0,1)*g2*UM11*conjg(UM21)*Cos(TW)*Sin(TWp) + (0,0.5_default)*g2*UM12*conjg(UM22)* &
      Cos(TW)*Sin(TWp) - (0,0.5_default)*g1*UM12*conjg(UM22)*Sin(TW)*Sin(TWp))
   G_c1bar_zp_1_c2(2) = (0,-0.5_default)*((0,-1)*gp*QHu*UP22*conjg(UP12)*Cos(TWp &
      ) + (0,1)*g2*UP21*conjg(UP11)*Cos(TW)*Sin(TWp) + (0,0.5_default)*g2*UP22*conjg(UP12)* &
      Cos(TW)*Sin(TWp) - (0,0.5_default)*g1*UP22*conjg(UP12)*Sin(TW)*Sin(TWp))
   G_c2bar_zp_1_c1(1) = (0,-0.5_default)*((0,1)*gp*QHd*UM22*conjg(UM12)*Cos(TWp &
      ) + (0,1)*g2*UM21*conjg(UM11)*Cos(TW)*Sin(TWp) + (0,0.5_default)*g2*UM22*conjg(UM12)* &
      Cos(TW)*Sin(TWp) - (0,0.5_default)*g1*UM22*conjg(UM12)*Sin(TW)*Sin(TWp))
   G_c2bar_zp_1_c1(2) = (0,-0.5_default)*((0,-1)*gp*QHu*UP12*conjg(UP22)*Cos(TWp &
      ) + (0,1)*g2*UP11*conjg(UP21)*Cos(TW)*Sin(TWp) + (0,0.5_default)*g2*UP12*conjg(UP22)* &
      Cos(TW)*Sin(TWp) - (0,0.5_default)*g1*UP12*conjg(UP22)*Sin(TW)*Sin(TWp))
   G_c2bar_zp_1_c2(1) = (0,-0.5_default)*((0,1)*gp*QHd*UM22*conjg(UM22)*Cos(TWp &
      ) + (0,1)*g2*UM21*conjg(UM21)*Cos(TW)*Sin(TWp) + (0,0.5_default)*g2*UM22*conjg(UM22)* &
      Cos(TW)*Sin(TWp) - (0,0.5_default)*g1*UM22*conjg(UM22)*Sin(TW)*Sin(TWp))
   G_c2bar_zp_1_c2(2) = (0,-0.5_default)*((0,-1)*gp*QHu*UP22*conjg(UP22)*Cos(TWp &
      ) + (0,1)*g2*UP21*conjg(UP21)*Cos(TW)*Sin(TWp) + (0,0.5_default)*g2*UP22*conjg(UP22)* &
      Cos(TW)*Sin(TWp) - (0,0.5_default)*g1*UP22*conjg(UP22)*Sin(TW)*Sin(TWp))
   G_n1_z_1_n1(1) = (0,-0.5_default)*((0,0.5_default)*g2*ZN14*conjg(ZN14)*Cos(TW)* &
      Cos(TWp) - (0,0.5_default)*g2*ZN15*conjg(ZN15)*Cos(TW)*Cos(TWp) + (0,0.5_default)* &
      g1*ZN14*conjg(ZN14)*Cos(TWp)*Sin(TW) - (0,0.5_default)*g1*ZN15*conjg(ZN15)*Cos(TWp &
      )*Sin(TW) + (0,1)*gp*QHd*ZN14*conjg(ZN14)*Sin(TWp) + (0,1)*gp*QHu*ZN15*conjg(ZN15 &
      )*Sin(TWp) + (0,1)*gp*Qs*ZN16*conjg(ZN16)*Sin(TWp))
   G_n1_z_1_n1(2) = (0,-0.5_default)*((0,-0.5_default)*g2*ZN14*conjg(ZN14)*Cos(TW)* &
      Cos(TWp) + (0,0.5_default)*g2*ZN15*conjg(ZN15)*Cos(TW)*Cos(TWp) - (0,0.5_default)* &
      g1*ZN14*conjg(ZN14)*Cos(TWp)*Sin(TW) + (0,0.5_default)*g1*ZN15*conjg(ZN15)*Cos(TWp &
      )*Sin(TW) - (0,1)*gp*QHd*ZN14*conjg(ZN14)*Sin(TWp) - (0,1)*gp*QHu*ZN15*conjg(ZN15 &
      )*Sin(TWp) - (0,1)*gp*Qs*ZN16*conjg(ZN16)*Sin(TWp))
   G_n1_z_1_n2(1) = (0,-0.5_default)*((0,0.5_default)*g2*ZN14*conjg(ZN24)*Cos(TW)* &
      Cos(TWp) - (0,0.5_default)*g2*ZN15*conjg(ZN25)*Cos(TW)*Cos(TWp) + (0,0.5_default)* &
      g1*ZN14*conjg(ZN24)*Cos(TWp)*Sin(TW) - (0,0.5_default)*g1*ZN15*conjg(ZN25)*Cos(TWp &
      )*Sin(TW) + (0,1)*gp*QHd*ZN14*conjg(ZN24)*Sin(TWp) + (0,1)*gp*QHu*ZN15*conjg(ZN25 &
      )*Sin(TWp) + (0,1)*gp*Qs*ZN16*conjg(ZN26)*Sin(TWp))
   G_n1_z_1_n2(2) = (0,-0.5_default)*((0,-0.5_default)*g2*ZN24*conjg(ZN14)*Cos(TW)* &
      Cos(TWp) + (0,0.5_default)*g2*ZN25*conjg(ZN15)*Cos(TW)*Cos(TWp) - (0,0.5_default)* &
      g1*ZN24*conjg(ZN14)*Cos(TWp)*Sin(TW) + (0,0.5_default)*g1*ZN25*conjg(ZN15)*Cos(TWp &
      )*Sin(TW) - (0,1)*gp*QHd*ZN24*conjg(ZN14)*Sin(TWp) - (0,1)*gp*QHu*ZN25*conjg(ZN15 &
      )*Sin(TWp) - (0,1)*gp*Qs*ZN26*conjg(ZN16)*Sin(TWp))
   G_n1_z_1_n3(1) = (0,-0.5_default)*((0,0.5_default)*g2*ZN14*conjg(ZN34)*Cos(TW)* &
      Cos(TWp) - (0,0.5_default)*g2*ZN15*conjg(ZN35)*Cos(TW)*Cos(TWp) + (0,0.5_default)* &
      g1*ZN14*conjg(ZN34)*Cos(TWp)*Sin(TW) - (0,0.5_default)*g1*ZN15*conjg(ZN35)*Cos(TWp &
      )*Sin(TW) + (0,1)*gp*QHd*ZN14*conjg(ZN34)*Sin(TWp) + (0,1)*gp*QHu*ZN15*conjg(ZN35 &
      )*Sin(TWp) + (0,1)*gp*Qs*ZN16*conjg(ZN36)*Sin(TWp))
   G_n1_z_1_n3(2) = (0,-0.5_default)*((0,-0.5_default)*g2*ZN34*conjg(ZN14)*Cos(TW)* &
      Cos(TWp) + (0,0.5_default)*g2*ZN35*conjg(ZN15)*Cos(TW)*Cos(TWp) - (0,0.5_default)* &
      g1*ZN34*conjg(ZN14)*Cos(TWp)*Sin(TW) + (0,0.5_default)*g1*ZN35*conjg(ZN15)*Cos(TWp &
      )*Sin(TW) - (0,1)*gp*QHd*ZN34*conjg(ZN14)*Sin(TWp) - (0,1)*gp*QHu*ZN35*conjg(ZN15 &
      )*Sin(TWp) - (0,1)*gp*Qs*ZN36*conjg(ZN16)*Sin(TWp))
   G_n1_z_1_n4(1) = (0,-0.5_default)*((0,0.5_default)*g2*ZN14*conjg(ZN44)*Cos(TW)* &
      Cos(TWp) - (0,0.5_default)*g2*ZN15*conjg(ZN45)*Cos(TW)*Cos(TWp) + (0,0.5_default)* &
      g1*ZN14*conjg(ZN44)*Cos(TWp)*Sin(TW) - (0,0.5_default)*g1*ZN15*conjg(ZN45)*Cos(TWp &
      )*Sin(TW) + (0,1)*gp*QHd*ZN14*conjg(ZN44)*Sin(TWp) + (0,1)*gp*QHu*ZN15*conjg(ZN45 &
      )*Sin(TWp) + (0,1)*gp*Qs*ZN16*conjg(ZN46)*Sin(TWp))
   G_n1_z_1_n4(2) = (0,-0.5_default)*((0,-0.5_default)*g2*ZN44*conjg(ZN14)*Cos(TW)* &
      Cos(TWp) + (0,0.5_default)*g2*ZN45*conjg(ZN15)*Cos(TW)*Cos(TWp) - (0,0.5_default)* &
      g1*ZN44*conjg(ZN14)*Cos(TWp)*Sin(TW) + (0,0.5_default)*g1*ZN45*conjg(ZN15)*Cos(TWp &
      )*Sin(TW) - (0,1)*gp*QHd*ZN44*conjg(ZN14)*Sin(TWp) - (0,1)*gp*QHu*ZN45*conjg(ZN15 &
      )*Sin(TWp) - (0,1)*gp*Qs*ZN46*conjg(ZN16)*Sin(TWp))
   G_n1_z_1_n5(1) = (0,-0.5_default)*((0,0.5_default)*g2*ZN14*conjg(ZN54)*Cos(TW)* &
      Cos(TWp) - (0,0.5_default)*g2*ZN15*conjg(ZN55)*Cos(TW)*Cos(TWp) + (0,0.5_default)* &
      g1*ZN14*conjg(ZN54)*Cos(TWp)*Sin(TW) - (0,0.5_default)*g1*ZN15*conjg(ZN55)*Cos(TWp &
      )*Sin(TW) + (0,1)*gp*QHd*ZN14*conjg(ZN54)*Sin(TWp) + (0,1)*gp*QHu*ZN15*conjg(ZN55 &
      )*Sin(TWp) + (0,1)*gp*Qs*ZN16*conjg(ZN56)*Sin(TWp))
   G_n1_z_1_n5(2) = (0,-0.5_default)*((0,-0.5_default)*g2*ZN54*conjg(ZN14)*Cos(TW)* &
      Cos(TWp) + (0,0.5_default)*g2*ZN55*conjg(ZN15)*Cos(TW)*Cos(TWp) - (0,0.5_default)* &
      g1*ZN54*conjg(ZN14)*Cos(TWp)*Sin(TW) + (0,0.5_default)*g1*ZN55*conjg(ZN15)*Cos(TWp &
      )*Sin(TW) - (0,1)*gp*QHd*ZN54*conjg(ZN14)*Sin(TWp) - (0,1)*gp*QHu*ZN55*conjg(ZN15 &
      )*Sin(TWp) - (0,1)*gp*Qs*ZN56*conjg(ZN16)*Sin(TWp))
   G_n1_z_1_n6(1) = (0,-0.5_default)*((0,0.5_default)*g2*ZN14*conjg(ZN64)*Cos(TW)* &
      Cos(TWp) - (0,0.5_default)*g2*ZN15*conjg(ZN65)*Cos(TW)*Cos(TWp) + (0,0.5_default)* &
      g1*ZN14*conjg(ZN64)*Cos(TWp)*Sin(TW) - (0,0.5_default)*g1*ZN15*conjg(ZN65)*Cos(TWp &
      )*Sin(TW) + (0,1)*gp*QHd*ZN14*conjg(ZN64)*Sin(TWp) + (0,1)*gp*QHu*ZN15*conjg(ZN65 &
      )*Sin(TWp) + (0,1)*gp*Qs*ZN16*conjg(ZN66)*Sin(TWp))
   G_n1_z_1_n6(2) = (0,-0.5_default)*((0,-0.5_default)*g2*ZN64*conjg(ZN14)*Cos(TW)* &
      Cos(TWp) + (0,0.5_default)*g2*ZN65*conjg(ZN15)*Cos(TW)*Cos(TWp) - (0,0.5_default)* &
      g1*ZN64*conjg(ZN14)*Cos(TWp)*Sin(TW) + (0,0.5_default)*g1*ZN65*conjg(ZN15)*Cos(TWp &
      )*Sin(TW) - (0,1)*gp*QHd*ZN64*conjg(ZN14)*Sin(TWp) - (0,1)*gp*QHu*ZN65*conjg(ZN15 &
      )*Sin(TWp) - (0,1)*gp*Qs*ZN66*conjg(ZN16)*Sin(TWp))
   G_n2_z_1_n2(1) = (0,-0.5_default)*((0,0.5_default)*g2*ZN24*conjg(ZN24)*Cos(TW)* &
      Cos(TWp) - (0,0.5_default)*g2*ZN25*conjg(ZN25)*Cos(TW)*Cos(TWp) + (0,0.5_default)* &
      g1*ZN24*conjg(ZN24)*Cos(TWp)*Sin(TW) - (0,0.5_default)*g1*ZN25*conjg(ZN25)*Cos(TWp &
      )*Sin(TW) + (0,1)*gp*QHd*ZN24*conjg(ZN24)*Sin(TWp) + (0,1)*gp*QHu*ZN25*conjg(ZN25 &
      )*Sin(TWp) + (0,1)*gp*Qs*ZN26*conjg(ZN26)*Sin(TWp))
   G_n2_z_1_n2(2) = (0,-0.5_default)*((0,-0.5_default)*g2*ZN24*conjg(ZN24)*Cos(TW)* &
      Cos(TWp) + (0,0.5_default)*g2*ZN25*conjg(ZN25)*Cos(TW)*Cos(TWp) - (0,0.5_default)* &
      g1*ZN24*conjg(ZN24)*Cos(TWp)*Sin(TW) + (0,0.5_default)*g1*ZN25*conjg(ZN25)*Cos(TWp &
      )*Sin(TW) - (0,1)*gp*QHd*ZN24*conjg(ZN24)*Sin(TWp) - (0,1)*gp*QHu*ZN25*conjg(ZN25 &
      )*Sin(TWp) - (0,1)*gp*Qs*ZN26*conjg(ZN26)*Sin(TWp))
   G_n2_z_1_n3(1) = (0,-0.5_default)*((0,0.5_default)*g2*ZN24*conjg(ZN34)*Cos(TW)* &
      Cos(TWp) - (0,0.5_default)*g2*ZN25*conjg(ZN35)*Cos(TW)*Cos(TWp) + (0,0.5_default)* &
      g1*ZN24*conjg(ZN34)*Cos(TWp)*Sin(TW) - (0,0.5_default)*g1*ZN25*conjg(ZN35)*Cos(TWp &
      )*Sin(TW) + (0,1)*gp*QHd*ZN24*conjg(ZN34)*Sin(TWp) + (0,1)*gp*QHu*ZN25*conjg(ZN35 &
      )*Sin(TWp) + (0,1)*gp*Qs*ZN26*conjg(ZN36)*Sin(TWp))
   G_n2_z_1_n3(2) = (0,-0.5_default)*((0,-0.5_default)*g2*ZN34*conjg(ZN24)*Cos(TW)* &
      Cos(TWp) + (0,0.5_default)*g2*ZN35*conjg(ZN25)*Cos(TW)*Cos(TWp) - (0,0.5_default)* &
      g1*ZN34*conjg(ZN24)*Cos(TWp)*Sin(TW) + (0,0.5_default)*g1*ZN35*conjg(ZN25)*Cos(TWp &
      )*Sin(TW) - (0,1)*gp*QHd*ZN34*conjg(ZN24)*Sin(TWp) - (0,1)*gp*QHu*ZN35*conjg(ZN25 &
      )*Sin(TWp) - (0,1)*gp*Qs*ZN36*conjg(ZN26)*Sin(TWp))
end subroutine calc_cpl26

end module parameters_nonumssm_sarah_cpl26