! --------------------------------------------------------------------------------
! Autogenerated by the happy scrappy WHIZARD model file generator on 2/10/2021 , 0:41:44
! WHIZARD interface svn revision info: $Id: WOMathematicaInterface.m 3666 2012-01-14 17:03:09Z cnspeckn $
! Code generated for WHIZARD / O'Mega version 2.4.0
! Model name: nonumssm_sarah
! Gauge: Unitarity
! Maximum number of couplings per FORTRAN module: 150
! --------------------------------------------------------------------------------
! 
! --------------------------------------------------------------------------------

module parameters_nonumssm_sarah_local
use parameters_nonumssm_sarah_global
implicit none
public
save

real(kind=default) :: gp, Qq, Ql1, Ql2, Ql3, QHd, QHu, Qd, Qu, Qe1, Qe2, Qe3, Qs &
   , lam, Tlam, vS, betaH, TWp, aS, aEWinv, Gf, g3, ZP11, ZP12, ZP21, ZP22, ee, TW,  &
   g1, g2, v, vd, vu
complex(kind=default) :: Yd11, Yd12, Yd13, Yd21, Yd22, Yd23, Yd31, Yd32, Yd33,  &
   Td11, Td12, Td13, Td21, Td22, Td23, Td31, Td32, Td33, Ye11, TYe11, Ye22, TYe22, Ye33 &
   , TYe33, Yu11, Yu12, Yu13, Yu21, Yu22, Yu23, Yu31, Yu32, Yu33, Tu11, Tu12, Tu13,  &
   Tu21, Tu22, Tu23, Tu31, Tu32, Tu33, Tdp11, Tdp12, Tdp13, Tdp21, Tdp22, Tdp23, Tdp31 &
   , Tdp32, Tdp33, Tep, Tmup, pG, ZD11, ZD12, ZD13, ZD14, ZD15, ZD16, ZD21, ZD22,  &
   ZD23, ZD24, ZD25, ZD26, ZD31, ZD32, ZD33, ZD34, ZD35, ZD36, ZD41, ZD42, ZD43, ZD44,  &
   ZD45, ZD46, ZD51, ZD52, ZD53, ZD54, ZD55, ZD56, ZD61, ZD62, ZD63, ZD64, ZD65, ZD66,  &
   ZV11, ZV12, ZV13, ZV21, ZV22, ZV23, ZV31, ZV32, ZV33, ZVL11, ZVL12, ZVL13, ZVL21,  &
   ZVL22, ZVL23, ZVL31, ZVL32, ZVL33, ZU11, ZU12, ZU13, ZU14, ZU15, ZU16, ZU21, ZU22,  &
   ZU23, ZU24, ZU25, ZU26, ZU31, ZU32, ZU33, ZU34, ZU35, ZU36, ZU41, ZU42, ZU43, ZU44,  &
   ZU45, ZU46, ZU51, ZU52, ZU53, ZU54, ZU55, ZU56, ZU61, ZU62, ZU63, ZU64, ZU65, ZU66,  &
   ZE11, ZE12, ZE13, ZE14, ZE15, ZE16, ZE21, ZE22, ZE23, ZE24, ZE25, ZE26, ZE31, ZE32,  &
   ZE33, ZE34, ZE35, ZE36, ZE41, ZE42, ZE43, ZE44, ZE45, ZE46, ZE51, ZE52, ZE53, ZE54,  &
   ZE55, ZE56, ZE61, ZE62, ZE63, ZE64, ZE65, ZE66, ZH11, ZH12, ZH13, ZH21, ZH22, ZH23,  &
   ZH31, ZH32, ZH33, ZA11, ZA12, ZA13, ZA21, ZA22, ZA23, ZA31, ZA32, ZA33, ZN11, ZN12,  &
   ZN13, ZN14, ZN15, ZN16, ZN21, ZN22, ZN23, ZN24, ZN25, ZN26, ZN31, ZN32, ZN33, ZN34,  &
   ZN35, ZN36, ZN41, ZN42, ZN43, ZN44, ZN45, ZN46, ZN51, ZN52, ZN53, ZN54, ZN55, ZN56,  &
   ZN61, ZN62, ZN63, ZN64, ZN65, ZN66, UM11, UM12, UM21, UM22, UP11, UP12, UP21, UP22,  &
   ZEL11, ZEL12, ZEL13, ZEL21, ZEL22, ZEL23, ZEL31, ZEL32, ZEL33, ZER11, ZER12, ZER13,  &
   ZER21, ZER22, ZER23, ZER31, ZER32, ZER33, ZDL11, ZDL12, ZDL13, ZDL21, ZDL22, ZDL23,  &
   ZDL31, ZDL32, ZDL33, ZDR11, ZDR12, ZDR13, ZDR21, ZDR22, ZDR23, ZDR31, ZDR32, ZDR33,  &
   ZUL11, ZUL12, ZUL13, ZUL21, ZUL22, ZUL23, ZUL31, ZUL32, ZUL33, ZUR11, ZUR12, ZUR13,  &
   ZUR21, ZUR22, ZUR23, ZUR31, ZUR32, ZUR33

end module parameters_nonumssm_sarah_local