(* --------------------------------------------------------------------------------
   Autogenerated by the happy scrappy WHIZARD model file generator on 2/10/2021 , 0:41:44
   WHIZARD interface svn revision info: $Id: WOMathematicaInterface.m 3666 2012-01-14 17:03:09Z cnspeckn $
   Code generated for WHIZARD / O'Mega version 2.4.0
   Model name: nonumssm_sarah
   Gauge: Unitarity
   Maximum number of couplings per FORTRAN module: 150
   --------------------------------------------------------------------------------
   
   -------------------------------------------------------------------------------- *)

module O =  Omega.Make (Fusion.Mixed23_Majorana) (Targets.Fortran_Majorana)
   (Nonumssm_sarah_mdl.Implementation (struct let gauge = Nonumssm_sarah_mdl.Unitarity let color = true end))

let _ = O.main ()
