(* ----------------------------------------------------------------------------- *) 
(* This model was automatically created by SARAH version4.14.3  *) 
(* SARAH References: arXiv:0806.0538, 0909.2863, 1002.0840, 1207.0906, 1309.7223 *) 
(* (c) Florian Staub, 2013  *) 
(* ----------------------------------------------------------------------------- *) 
(* File created at 16:22 on 21.3.2021  *) 
(* ---------------------------------------------------------------------- *) 
 
 
LoopContributions[PengS2d2nu]={
(* Ah,Fd, Internal:bar[Fd], Propagator: hh*) 
{{Ah,Fd, Internal->bar[Fd], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, Ah][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, Ah][L][i3,i2,i1],coup2R -> Cp[bar[Fd], Fd, Ah][R][i3,i2,i1],coup3L -> Cp[bar[Fd], Fd, hh][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, hh][R][gt2,i3,iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},{mS1 -> M[Ah][i1],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[hh][iProp]}},
(* Chi,Sd, Internal:bar[Fd], Propagator: hh*) 
{{Chi,Sd, Internal->bar[Fd], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Chi, Fd, conj[Sd]][L][i1,gt1,i2],coup1R -> Cp[Chi, Fd, conj[Sd]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Chi, Sd][L][i3,i1,i2],coup2R -> Cp[bar[Fd], Chi, Sd][R][i3,i1,i2],coup3L -> Cp[bar[Fd], Fd, hh][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, hh][R][gt2,i3,iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},{mF1 -> M[Chi][i1],mS1 -> M[Sd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[hh][iProp]}},
(* Glu,Sd, Internal:bar[Fd], Propagator: hh*) 
{{Glu,Sd, Internal->bar[Fd], Propagator ->hh},chargefactor -> 4/3,{coup1L -> Cp[Glu, Fd, conj[Sd]][L][gt1,i2],coup1R -> Cp[Glu, Fd, conj[Sd]][R][gt1,i2],coup2L -> Cp[bar[Fd], Glu, Sd][L][i3,i2],coup2R -> Cp[bar[Fd], Glu, Sd][R][i3,i2],coup3L -> Cp[bar[Fd], Fd, hh][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, hh][R][gt2,i3,iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},{mF1 -> M[Glu],mS1 -> M[Sd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[hh][iProp]}},
(* hh,Fd, Internal:bar[Fd], Propagator: hh*) 
{{hh,Fd, Internal->bar[Fd], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, hh][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, hh][L][i3,i2,i1],coup2R -> Cp[bar[Fd], Fd, hh][R][i3,i2,i1],coup3L -> Cp[bar[Fd], Fd, hh][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, hh][R][gt2,i3,iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},{mS1 -> M[hh][i1],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[hh][iProp]}},
(* VZ,Fd, Internal:bar[Fd], Propagator: hh*) 
{{VZ,Fd, Internal->bar[Fd], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZ][L][i3,i2],coup2R -> Cp[bar[Fd], Fd, VZ][R][i3,i2],coup3L -> Cp[bar[Fd], Fd, hh][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, hh][R][gt2,i3,iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},{mV1 -> M[VZ],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[hh][iProp]}},
(* VZp,Fd, Internal:bar[Fd], Propagator: hh*) 
{{VZp,Fd, Internal->bar[Fd], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZp][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZp][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZp][L][i3,i2],coup2R -> Cp[bar[Fd], Fd, VZp][R][i3,i2],coup3L -> Cp[bar[Fd], Fd, hh][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, hh][R][gt2,i3,iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},{mV1 -> M[VZp],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[hh][iProp]}},
(* bar[Cha],Su, Internal:bar[Fd], Propagator: hh*) 
{{bar[Cha],Su, Internal->bar[Fd], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Cha], Fd, conj[Su]][L][i1,gt1,i2],coup1R -> Cp[bar[Cha], Fd, conj[Su]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Cha, Su][L][i3,i1,i2],coup2R -> Cp[bar[Fd], Cha, Su][R][i3,i1,i2],coup3L -> Cp[bar[Fd], Fd, hh][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, hh][R][gt2,i3,iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},{mF1 -> M[Cha][i1],mS1 -> M[Su][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[hh][iProp]}},
(* bar[Fu],Hpm, Internal:bar[Fd], Propagator: hh*) 
{{bar[Fu],Hpm, Internal->bar[Fd], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, Hpm][L][i3,i1,i2],coup2R -> Cp[bar[Fd], Fu, Hpm][R][i3,i1,i2],coup3L -> Cp[bar[Fd], Fd, hh][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, hh][R][gt2,i3,iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},{mF1 -> M[Fu][i1],mS1 -> M[Hpm][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[hh][iProp]}},
(* bar[Fu],VWm, Internal:bar[Fd], Propagator: hh*) 
{{bar[Fu],VWm, Internal->bar[Fd], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWm][L][i3,i1],coup2R -> Cp[bar[Fd], Fu, VWm][R][i3,i1],coup3L -> Cp[bar[Fd], Fd, hh][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, hh][R][gt2,i3,iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},{mF1 -> M[Fu][i1],mV1 -> M[VWm],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[hh][iProp]}},
(* Fd,Ah, Internal:Fd, Propagator: hh*) 
{{Fd,Ah, Internal->Fd, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fd], Fd, Ah][L][i1,i3,i2],coup2R -> Cp[bar[Fd], Fd, Ah][R][i1,i3,i2],coup1L -> Cp[bar[Fd], Fd, Ah][L][gt2,i1,i2],coup1R -> Cp[bar[Fd], Fd, Ah][R][gt2,i1,i2],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},{mF1 -> M[Fd][i1],mS1 -> M[Ah][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[hh][iProp]}},
(* Sd,Chi, Internal:Fd, Propagator: hh*) 
{{Sd,Chi, Internal->Fd, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWm]][R][i3,gt1,iProp],coup2L -> Cp[Chi, Fd, conj[Sd]][L][i2,i3,i1],coup2R -> Cp[Chi, Fd, conj[Sd]][R][i2,i3,i1],coup1L -> Cp[bar[Fd], Chi, Sd][L][gt2,i2,i1],coup1R -> Cp[bar[Fd], Chi, Sd][R][gt2,i2,i1],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},{mS1 -> M[Sd][i1],mF1 -> M[Chi][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[hh][iProp]}},
(* Sd,Glu, Internal:Fd, Propagator: hh*) 
{{Sd,Glu, Internal->Fd, Propagator ->hh},chargefactor -> 4/3,{coup3L -> Cp[bar[Fu], Fd, conj[VWm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWm]][R][i3,gt1,iProp],coup2L -> Cp[Glu, Fd, conj[Sd]][L][i3,i1],coup2R -> Cp[Glu, Fd, conj[Sd]][R][i3,i1],coup1L -> Cp[bar[Fd], Glu, Sd][L][gt2,i1],coup1R -> Cp[bar[Fd], Glu, Sd][R][gt2,i1],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},{mS1 -> M[Sd][i1],mF1 -> M[Glu],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[hh][iProp]}},
(* Fd,hh, Internal:Fd, Propagator: hh*) 
{{Fd,hh, Internal->Fd, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fd], Fd, hh][L][i1,i3,i2],coup2R -> Cp[bar[Fd], Fd, hh][R][i1,i3,i2],coup1L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i2],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},{mF1 -> M[Fd][i1],mS1 -> M[hh][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[hh][iProp]}},
(* Fd,VZ, Internal:Fd, Propagator: hh*) 
{{Fd,VZ, Internal->Fd, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fd], Fd, VZ][L][i1,i3],coup2R -> Cp[bar[Fd], Fd, VZ][R][i1,i3],coup1L -> Cp[bar[Fd], Fd, VZ][L][gt2,i1],coup1R -> Cp[bar[Fd], Fd, VZ][R][gt2,i1],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},{mF1 -> M[Fd][i1],mV1 -> M[VZ],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[hh][iProp]}},
(* Fd,VZp, Internal:Fd, Propagator: hh*) 
{{Fd,VZp, Internal->Fd, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fd], Fd, VZp][L][i1,i3],coup2R -> Cp[bar[Fd], Fd, VZp][R][i1,i3],coup1L -> Cp[bar[Fd], Fd, VZp][L][gt2,i1],coup1R -> Cp[bar[Fd], Fd, VZp][R][gt2,i1],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},{mF1 -> M[Fd][i1],mV1 -> M[VZp],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[hh][iProp]}},
(* Su,bar[Cha], Internal:Fd, Propagator: hh*) 
{{Su,bar[Cha], Internal->Fd, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Cha], Fd, conj[Su]][L][i2,i3,i1],coup2R -> Cp[bar[Cha], Fd, conj[Su]][R][i2,i3,i1],coup1L -> Cp[bar[Fd], Cha, Su][L][gt2,i2,i1],coup1R -> Cp[bar[Fd], Cha, Su][R][gt2,i2,i1],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},{mS1 -> M[Su][i1],mF1 -> M[Cha][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[hh][iProp]}},
(* Hpm,bar[Fu], Internal:Fd, Propagator: hh*) 
{{Hpm,bar[Fu], Internal->Fd, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i2,i3,i1],coup2R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i2,i3,i1],coup1L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i2,i1],coup1R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i2,i1],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},{mS1 -> M[Hpm][i1],mF1 -> M[Fu][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[hh][iProp]}},
(* VWm,bar[Fu], Internal:Fd, Propagator: hh*) 
{{VWm,bar[Fu], Internal->Fd, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fu], Fd, conj[VWm]][L][i2,i3],coup2R -> Cp[bar[Fu], Fd, conj[VWm]][R][i2,i3],coup1L -> Cp[bar[Fd], Fu, VWm][L][gt2,i2],coup1R -> Cp[bar[Fd], Fu, VWm][R][gt2,i2],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},{mV1 -> M[VWm],mF1 -> M[Fu][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[hh][iProp]}},
(* Ah,Fv, Internal:bar[Fv], Propagator: hh*) 
{{Ah,Fv, Internal->bar[Fv], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, Ah][L][i2,gt3,i1],coup1R -> Cp[bar[Fv], Fv, Ah][R][i2,gt3,i1],coup2L -> Cp[bar[Fv], Fv, Ah][L][i3,i2,i1],coup2R -> Cp[bar[Fv], Fv, Ah][R][i3,i2,i1],coup3L -> Cp[bar[Fv], Fv, hh][L][gt4,i3,iProp],coup3R -> Cp[bar[Fv], Fv, hh][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mS1 -> M[Ah][i1],mF1 -> M[Fv][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[hh][iProp]}},
(* Cha,Se, Internal:bar[Fv], Propagator: hh*) 
{{Cha,Se, Internal->bar[Fv], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Cha, Fv, conj[Se]][L][i1,gt3,i2],coup1R -> Cp[Cha, Fv, conj[Se]][R][i1,gt3,i2],coup2L -> Cp[bar[Cha], bar[Fv], Se][L][i1,i3,i2],coup2R -> Cp[bar[Cha], bar[Fv], Se][R][i1,i3,i2],coup3L -> Cp[bar[Fv], Fv, hh][L][gt4,i3,iProp],coup3R -> Cp[bar[Fv], Fv, hh][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mF1 -> M[Cha][i1],mS1 -> M[Se][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[hh][iProp]}},
(* Chi,Sv, Internal:bar[Fv], Propagator: hh*) 
{{Chi,Sv, Internal->bar[Fv], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Chi, Fv, conj[Sv]][L][i1,gt3,i2],coup1R -> Cp[Chi, Fv, conj[Sv]][R][i1,gt3,i2],coup2L -> Cp[bar[Fv], Chi, Sv][L][i3,i1,i2],coup2R -> Cp[bar[Fv], Chi, Sv][R][i3,i1,i2],coup3L -> Cp[bar[Fv], Fv, hh][L][gt4,i3,iProp],coup3R -> Cp[bar[Fv], Fv, hh][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mF1 -> M[Chi][i1],mS1 -> M[Sv][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[hh][iProp]}},
(* hh,Fv, Internal:bar[Fv], Propagator: hh*) 
{{hh,Fv, Internal->bar[Fv], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, hh][L][i2,gt3,i1],coup1R -> Cp[bar[Fv], Fv, hh][R][i2,gt3,i1],coup2L -> Cp[bar[Fv], Fv, hh][L][i3,i2,i1],coup2R -> Cp[bar[Fv], Fv, hh][R][i3,i2,i1],coup3L -> Cp[bar[Fv], Fv, hh][L][gt4,i3,iProp],coup3R -> Cp[bar[Fv], Fv, hh][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mS1 -> M[hh][i1],mF1 -> M[Fv][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[hh][iProp]}},
(* Hpm,Fe, Internal:bar[Fv], Propagator: hh*) 
{{Hpm,Fe, Internal->bar[Fv], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i2,gt3,i1],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i2,gt3,i1],coup2L -> Cp[bar[Fv], Fe, conj[Hpm]][L][i3,i2,i1],coup2R -> Cp[bar[Fv], Fe, conj[Hpm]][R][i3,i2,i1],coup3L -> Cp[bar[Fv], Fv, hh][L][gt4,i3,iProp],coup3R -> Cp[bar[Fv], Fv, hh][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mS1 -> M[Hpm][i1],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[hh][iProp]}},
(* VWm,Fe, Internal:bar[Fv], Propagator: hh*) 
{{VWm,Fe, Internal->bar[Fv], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWm][L][i2,gt3],coup1R -> Cp[bar[Fe], Fv, VWm][R][i2,gt3],coup2L -> Cp[bar[Fv], Fe, conj[VWm]][L][i3,i2],coup2R -> Cp[bar[Fv], Fe, conj[VWm]][R][i3,i2],coup3L -> Cp[bar[Fv], Fv, hh][L][gt4,i3,iProp],coup3R -> Cp[bar[Fv], Fv, hh][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mV1 -> M[VWm],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[hh][iProp]}},
(* VZ,Fv, Internal:bar[Fv], Propagator: hh*) 
{{VZ,Fv, Internal->bar[Fv], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, VZ][L][i2,gt3],coup1R -> Cp[bar[Fv], Fv, VZ][R][i2,gt3],coup2L -> Cp[bar[Fv], Fv, VZ][L][i3,i2],coup2R -> Cp[bar[Fv], Fv, VZ][R][i3,i2],coup3L -> Cp[bar[Fv], Fv, hh][L][gt4,i3,iProp],coup3R -> Cp[bar[Fv], Fv, hh][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mV1 -> M[VZ],mF1 -> M[Fv][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[hh][iProp]}},
(* VZp,Fv, Internal:bar[Fv], Propagator: hh*) 
{{VZp,Fv, Internal->bar[Fv], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, VZp][L][i2,gt3],coup1R -> Cp[bar[Fv], Fv, VZp][R][i2,gt3],coup2L -> Cp[bar[Fv], Fv, VZp][L][i3,i2],coup2R -> Cp[bar[Fv], Fv, VZp][R][i3,i2],coup3L -> Cp[bar[Fv], Fv, hh][L][gt4,i3,iProp],coup3R -> Cp[bar[Fv], Fv, hh][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mV1 -> M[VZp],mF1 -> M[Fv][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[hh][iProp]}},
(* Fv,Ah, Internal:Fv, Propagator: hh*) 
{{Fv,Ah, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fv], Fv, VZp][L][i3,gt3,iProp],coup3R -> Cp[bar[Fv], Fv, VZp][R][i3,gt3,iProp],coup2L -> Cp[bar[Fv], Fv, Ah][L][i1,i3,i2],coup2R -> Cp[bar[Fv], Fv, Ah][R][i1,i3,i2],coup1L -> Cp[bar[Fv], Fv, Ah][L][gt4,i1,i2],coup1R -> Cp[bar[Fv], Fv, Ah][R][gt4,i1,i2],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mF1 -> M[Fv][i1],mS1 -> M[Ah][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[hh][iProp]}},
(* Se,Cha, Internal:Fv, Propagator: hh*) 
{{Se,Cha, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fv], Fv, VZp][L][i3,gt3,iProp],coup3R -> Cp[bar[Fv], Fv, VZp][R][i3,gt3,iProp],coup2L -> Cp[Cha, Fv, conj[Se]][L][i2,i3,i1],coup2R -> Cp[Cha, Fv, conj[Se]][R][i2,i3,i1],coup1L -> Cp[bar[Cha], bar[Fv], Se][L][i2,gt4,i1],coup1R -> Cp[bar[Cha], bar[Fv], Se][R][i2,gt4,i1],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mS1 -> M[Se][i1],mF1 -> M[Cha][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[hh][iProp]}},
(* Sv,Chi, Internal:Fv, Propagator: hh*) 
{{Sv,Chi, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fv], Fv, VZp][L][i3,gt3,iProp],coup3R -> Cp[bar[Fv], Fv, VZp][R][i3,gt3,iProp],coup2L -> Cp[Chi, Fv, conj[Sv]][L][i2,i3,i1],coup2R -> Cp[Chi, Fv, conj[Sv]][R][i2,i3,i1],coup1L -> Cp[bar[Fv], Chi, Sv][L][gt4,i2,i1],coup1R -> Cp[bar[Fv], Chi, Sv][R][gt4,i2,i1],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mS1 -> M[Sv][i1],mF1 -> M[Chi][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[hh][iProp]}},
(* Fv,hh, Internal:Fv, Propagator: hh*) 
{{Fv,hh, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fv], Fv, VZp][L][i3,gt3,iProp],coup3R -> Cp[bar[Fv], Fv, VZp][R][i3,gt3,iProp],coup2L -> Cp[bar[Fv], Fv, hh][L][i1,i3,i2],coup2R -> Cp[bar[Fv], Fv, hh][R][i1,i3,i2],coup1L -> Cp[bar[Fv], Fv, hh][L][gt4,i1,i2],coup1R -> Cp[bar[Fv], Fv, hh][R][gt4,i1,i2],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mF1 -> M[Fv][i1],mS1 -> M[hh][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[hh][iProp]}},
(* Fe,Hpm, Internal:Fv, Propagator: hh*) 
{{Fe,Hpm, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fv], Fv, VZp][L][i3,gt3,iProp],coup3R -> Cp[bar[Fv], Fv, VZp][R][i3,gt3,iProp],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i1,i3,i2],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i1,i3,i2],coup1L -> Cp[bar[Fv], Fe, conj[Hpm]][L][gt4,i1,i2],coup1R -> Cp[bar[Fv], Fe, conj[Hpm]][R][gt4,i1,i2],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mF1 -> M[Fe][i1],mS1 -> M[Hpm][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[hh][iProp]}},
(* Fe,VWm, Internal:Fv, Propagator: hh*) 
{{Fe,VWm, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fv], Fv, VZp][L][i3,gt3,iProp],coup3R -> Cp[bar[Fv], Fv, VZp][R][i3,gt3,iProp],coup2L -> Cp[bar[Fe], Fv, VWm][L][i1,i3],coup2R -> Cp[bar[Fe], Fv, VWm][R][i1,i3],coup1L -> Cp[bar[Fv], Fe, conj[VWm]][L][gt4,i1],coup1R -> Cp[bar[Fv], Fe, conj[VWm]][R][gt4,i1],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mF1 -> M[Fe][i1],mV1 -> M[VWm],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[hh][iProp]}},
(* Fv,VZ, Internal:Fv, Propagator: hh*) 
{{Fv,VZ, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fv], Fv, VZp][L][i3,gt3,iProp],coup3R -> Cp[bar[Fv], Fv, VZp][R][i3,gt3,iProp],coup2L -> Cp[bar[Fv], Fv, VZ][L][i1,i3],coup2R -> Cp[bar[Fv], Fv, VZ][R][i1,i3],coup1L -> Cp[bar[Fv], Fv, VZ][L][gt4,i1],coup1R -> Cp[bar[Fv], Fv, VZ][R][gt4,i1],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mF1 -> M[Fv][i1],mV1 -> M[VZ],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[hh][iProp]}},
(* Fv,VZp, Internal:Fv, Propagator: hh*) 
{{Fv,VZp, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fv], Fv, VZp][L][i3,gt3,iProp],coup3R -> Cp[bar[Fv], Fv, VZp][R][i3,gt3,iProp],coup2L -> Cp[bar[Fv], Fv, VZp][L][i1,i3],coup2R -> Cp[bar[Fv], Fv, VZp][R][i1,i3],coup1L -> Cp[bar[Fv], Fv, VZp][L][gt4,i1],coup1R -> Cp[bar[Fv], Fv, VZp][R][gt4,i1],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mF1 -> M[Fv][i1],mV1 -> M[VZp],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[hh][iProp]}}
(* Ah,Fd, Internal:bar[Fd], Propagator: Ah*) 
{{Ah,Fd, Internal->bar[Fd], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, Ah][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, Ah][L][i3,i2,i1],coup2R -> Cp[bar[Fd], Fd, Ah][R][i3,i2,i1],coup3L -> Cp[bar[Fd], Fd, Ah][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, Ah][R][gt2,i3,iProp],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},{mS1 -> M[Ah][i1],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[Ah][iProp]}},
(* Chi,Sd, Internal:bar[Fd], Propagator: Ah*) 
{{Chi,Sd, Internal->bar[Fd], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Chi, Fd, conj[Sd]][L][i1,gt1,i2],coup1R -> Cp[Chi, Fd, conj[Sd]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Chi, Sd][L][i3,i1,i2],coup2R -> Cp[bar[Fd], Chi, Sd][R][i3,i1,i2],coup3L -> Cp[bar[Fd], Fd, Ah][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, Ah][R][gt2,i3,iProp],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},{mF1 -> M[Chi][i1],mS1 -> M[Sd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[Ah][iProp]}},
(* Glu,Sd, Internal:bar[Fd], Propagator: Ah*) 
{{Glu,Sd, Internal->bar[Fd], Propagator ->Ah},chargefactor -> 4/3,{coup1L -> Cp[Glu, Fd, conj[Sd]][L][gt1,i2],coup1R -> Cp[Glu, Fd, conj[Sd]][R][gt1,i2],coup2L -> Cp[bar[Fd], Glu, Sd][L][i3,i2],coup2R -> Cp[bar[Fd], Glu, Sd][R][i3,i2],coup3L -> Cp[bar[Fd], Fd, Ah][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, Ah][R][gt2,i3,iProp],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},{mF1 -> M[Glu],mS1 -> M[Sd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[Ah][iProp]}},
(* hh,Fd, Internal:bar[Fd], Propagator: Ah*) 
{{hh,Fd, Internal->bar[Fd], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, hh][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, hh][L][i3,i2,i1],coup2R -> Cp[bar[Fd], Fd, hh][R][i3,i2,i1],coup3L -> Cp[bar[Fd], Fd, Ah][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, Ah][R][gt2,i3,iProp],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},{mS1 -> M[hh][i1],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[Ah][iProp]}},
(* VZ,Fd, Internal:bar[Fd], Propagator: Ah*) 
{{VZ,Fd, Internal->bar[Fd], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZ][L][i3,i2],coup2R -> Cp[bar[Fd], Fd, VZ][R][i3,i2],coup3L -> Cp[bar[Fd], Fd, Ah][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, Ah][R][gt2,i3,iProp],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},{mV1 -> M[VZ],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[Ah][iProp]}},
(* VZp,Fd, Internal:bar[Fd], Propagator: Ah*) 
{{VZp,Fd, Internal->bar[Fd], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZp][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZp][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZp][L][i3,i2],coup2R -> Cp[bar[Fd], Fd, VZp][R][i3,i2],coup3L -> Cp[bar[Fd], Fd, Ah][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, Ah][R][gt2,i3,iProp],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},{mV1 -> M[VZp],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[Ah][iProp]}},
(* bar[Cha],Su, Internal:bar[Fd], Propagator: Ah*) 
{{bar[Cha],Su, Internal->bar[Fd], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Cha], Fd, conj[Su]][L][i1,gt1,i2],coup1R -> Cp[bar[Cha], Fd, conj[Su]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Cha, Su][L][i3,i1,i2],coup2R -> Cp[bar[Fd], Cha, Su][R][i3,i1,i2],coup3L -> Cp[bar[Fd], Fd, Ah][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, Ah][R][gt2,i3,iProp],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},{mF1 -> M[Cha][i1],mS1 -> M[Su][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[Ah][iProp]}},
(* bar[Fu],Hpm, Internal:bar[Fd], Propagator: Ah*) 
{{bar[Fu],Hpm, Internal->bar[Fd], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, Hpm][L][i3,i1,i2],coup2R -> Cp[bar[Fd], Fu, Hpm][R][i3,i1,i2],coup3L -> Cp[bar[Fd], Fd, Ah][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, Ah][R][gt2,i3,iProp],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},{mF1 -> M[Fu][i1],mS1 -> M[Hpm][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[Ah][iProp]}},
(* bar[Fu],VWm, Internal:bar[Fd], Propagator: Ah*) 
{{bar[Fu],VWm, Internal->bar[Fd], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWm][L][i3,i1],coup2R -> Cp[bar[Fd], Fu, VWm][R][i3,i1],coup3L -> Cp[bar[Fd], Fd, Ah][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, Ah][R][gt2,i3,iProp],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},{mF1 -> M[Fu][i1],mV1 -> M[VWm],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[Ah][iProp]}},
(* Fd,Ah, Internal:Fd, Propagator: Ah*) 
{{Fd,Ah, Internal->Fd, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fd], Fd, Ah][L][i1,i3,i2],coup2R -> Cp[bar[Fd], Fd, Ah][R][i1,i3,i2],coup1L -> Cp[bar[Fd], Fd, Ah][L][gt2,i1,i2],coup1R -> Cp[bar[Fd], Fd, Ah][R][gt2,i1,i2],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},{mF1 -> M[Fd][i1],mS1 -> M[Ah][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[Ah][iProp]}},
(* Sd,Chi, Internal:Fd, Propagator: Ah*) 
{{Sd,Chi, Internal->Fd, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWm]][R][i3,gt1,iProp],coup2L -> Cp[Chi, Fd, conj[Sd]][L][i2,i3,i1],coup2R -> Cp[Chi, Fd, conj[Sd]][R][i2,i3,i1],coup1L -> Cp[bar[Fd], Chi, Sd][L][gt2,i2,i1],coup1R -> Cp[bar[Fd], Chi, Sd][R][gt2,i2,i1],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},{mS1 -> M[Sd][i1],mF1 -> M[Chi][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[Ah][iProp]}},
(* Sd,Glu, Internal:Fd, Propagator: Ah*) 
{{Sd,Glu, Internal->Fd, Propagator ->Ah},chargefactor -> 4/3,{coup3L -> Cp[bar[Fu], Fd, conj[VWm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWm]][R][i3,gt1,iProp],coup2L -> Cp[Glu, Fd, conj[Sd]][L][i3,i1],coup2R -> Cp[Glu, Fd, conj[Sd]][R][i3,i1],coup1L -> Cp[bar[Fd], Glu, Sd][L][gt2,i1],coup1R -> Cp[bar[Fd], Glu, Sd][R][gt2,i1],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},{mS1 -> M[Sd][i1],mF1 -> M[Glu],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[Ah][iProp]}},
(* Fd,hh, Internal:Fd, Propagator: Ah*) 
{{Fd,hh, Internal->Fd, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fd], Fd, hh][L][i1,i3,i2],coup2R -> Cp[bar[Fd], Fd, hh][R][i1,i3,i2],coup1L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i2],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},{mF1 -> M[Fd][i1],mS1 -> M[hh][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[Ah][iProp]}},
(* Fd,VZ, Internal:Fd, Propagator: Ah*) 
{{Fd,VZ, Internal->Fd, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fd], Fd, VZ][L][i1,i3],coup2R -> Cp[bar[Fd], Fd, VZ][R][i1,i3],coup1L -> Cp[bar[Fd], Fd, VZ][L][gt2,i1],coup1R -> Cp[bar[Fd], Fd, VZ][R][gt2,i1],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},{mF1 -> M[Fd][i1],mV1 -> M[VZ],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[Ah][iProp]}},
(* Fd,VZp, Internal:Fd, Propagator: Ah*) 
{{Fd,VZp, Internal->Fd, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fd], Fd, VZp][L][i1,i3],coup2R -> Cp[bar[Fd], Fd, VZp][R][i1,i3],coup1L -> Cp[bar[Fd], Fd, VZp][L][gt2,i1],coup1R -> Cp[bar[Fd], Fd, VZp][R][gt2,i1],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},{mF1 -> M[Fd][i1],mV1 -> M[VZp],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[Ah][iProp]}},
(* Su,bar[Cha], Internal:Fd, Propagator: Ah*) 
{{Su,bar[Cha], Internal->Fd, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Cha], Fd, conj[Su]][L][i2,i3,i1],coup2R -> Cp[bar[Cha], Fd, conj[Su]][R][i2,i3,i1],coup1L -> Cp[bar[Fd], Cha, Su][L][gt2,i2,i1],coup1R -> Cp[bar[Fd], Cha, Su][R][gt2,i2,i1],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},{mS1 -> M[Su][i1],mF1 -> M[Cha][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[Ah][iProp]}},
(* Hpm,bar[Fu], Internal:Fd, Propagator: Ah*) 
{{Hpm,bar[Fu], Internal->Fd, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i2,i3,i1],coup2R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i2,i3,i1],coup1L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i2,i1],coup1R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i2,i1],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},{mS1 -> M[Hpm][i1],mF1 -> M[Fu][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[Ah][iProp]}},
(* VWm,bar[Fu], Internal:Fd, Propagator: Ah*) 
{{VWm,bar[Fu], Internal->Fd, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fu], Fd, conj[VWm]][L][i2,i3],coup2R -> Cp[bar[Fu], Fd, conj[VWm]][R][i2,i3],coup1L -> Cp[bar[Fd], Fu, VWm][L][gt2,i2],coup1R -> Cp[bar[Fd], Fu, VWm][R][gt2,i2],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},{mV1 -> M[VWm],mF1 -> M[Fu][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[Ah][iProp]}},
(* Ah,Fv, Internal:bar[Fv], Propagator: Ah*) 
{{Ah,Fv, Internal->bar[Fv], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, Ah][L][i2,gt3,i1],coup1R -> Cp[bar[Fv], Fv, Ah][R][i2,gt3,i1],coup2L -> Cp[bar[Fv], Fv, Ah][L][i3,i2,i1],coup2R -> Cp[bar[Fv], Fv, Ah][R][i3,i2,i1],coup3L -> Cp[bar[Fv], Fv, Ah][L][gt4,i3,iProp],coup3R -> Cp[bar[Fv], Fv, Ah][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mS1 -> M[Ah][i1],mF1 -> M[Fv][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[Ah][iProp]}},
(* Cha,Se, Internal:bar[Fv], Propagator: Ah*) 
{{Cha,Se, Internal->bar[Fv], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Cha, Fv, conj[Se]][L][i1,gt3,i2],coup1R -> Cp[Cha, Fv, conj[Se]][R][i1,gt3,i2],coup2L -> Cp[bar[Cha], bar[Fv], Se][L][i1,i3,i2],coup2R -> Cp[bar[Cha], bar[Fv], Se][R][i1,i3,i2],coup3L -> Cp[bar[Fv], Fv, Ah][L][gt4,i3,iProp],coup3R -> Cp[bar[Fv], Fv, Ah][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mF1 -> M[Cha][i1],mS1 -> M[Se][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[Ah][iProp]}},
(* Chi,Sv, Internal:bar[Fv], Propagator: Ah*) 
{{Chi,Sv, Internal->bar[Fv], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Chi, Fv, conj[Sv]][L][i1,gt3,i2],coup1R -> Cp[Chi, Fv, conj[Sv]][R][i1,gt3,i2],coup2L -> Cp[bar[Fv], Chi, Sv][L][i3,i1,i2],coup2R -> Cp[bar[Fv], Chi, Sv][R][i3,i1,i2],coup3L -> Cp[bar[Fv], Fv, Ah][L][gt4,i3,iProp],coup3R -> Cp[bar[Fv], Fv, Ah][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mF1 -> M[Chi][i1],mS1 -> M[Sv][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[Ah][iProp]}},
(* hh,Fv, Internal:bar[Fv], Propagator: Ah*) 
{{hh,Fv, Internal->bar[Fv], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, hh][L][i2,gt3,i1],coup1R -> Cp[bar[Fv], Fv, hh][R][i2,gt3,i1],coup2L -> Cp[bar[Fv], Fv, hh][L][i3,i2,i1],coup2R -> Cp[bar[Fv], Fv, hh][R][i3,i2,i1],coup3L -> Cp[bar[Fv], Fv, Ah][L][gt4,i3,iProp],coup3R -> Cp[bar[Fv], Fv, Ah][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mS1 -> M[hh][i1],mF1 -> M[Fv][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[Ah][iProp]}},
(* Hpm,Fe, Internal:bar[Fv], Propagator: Ah*) 
{{Hpm,Fe, Internal->bar[Fv], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i2,gt3,i1],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i2,gt3,i1],coup2L -> Cp[bar[Fv], Fe, conj[Hpm]][L][i3,i2,i1],coup2R -> Cp[bar[Fv], Fe, conj[Hpm]][R][i3,i2,i1],coup3L -> Cp[bar[Fv], Fv, Ah][L][gt4,i3,iProp],coup3R -> Cp[bar[Fv], Fv, Ah][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mS1 -> M[Hpm][i1],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[Ah][iProp]}},
(* VWm,Fe, Internal:bar[Fv], Propagator: Ah*) 
{{VWm,Fe, Internal->bar[Fv], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWm][L][i2,gt3],coup1R -> Cp[bar[Fe], Fv, VWm][R][i2,gt3],coup2L -> Cp[bar[Fv], Fe, conj[VWm]][L][i3,i2],coup2R -> Cp[bar[Fv], Fe, conj[VWm]][R][i3,i2],coup3L -> Cp[bar[Fv], Fv, Ah][L][gt4,i3,iProp],coup3R -> Cp[bar[Fv], Fv, Ah][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mV1 -> M[VWm],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[Ah][iProp]}},
(* VZ,Fv, Internal:bar[Fv], Propagator: Ah*) 
{{VZ,Fv, Internal->bar[Fv], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, VZ][L][i2,gt3],coup1R -> Cp[bar[Fv], Fv, VZ][R][i2,gt3],coup2L -> Cp[bar[Fv], Fv, VZ][L][i3,i2],coup2R -> Cp[bar[Fv], Fv, VZ][R][i3,i2],coup3L -> Cp[bar[Fv], Fv, Ah][L][gt4,i3,iProp],coup3R -> Cp[bar[Fv], Fv, Ah][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mV1 -> M[VZ],mF1 -> M[Fv][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[Ah][iProp]}},
(* VZp,Fv, Internal:bar[Fv], Propagator: Ah*) 
{{VZp,Fv, Internal->bar[Fv], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, VZp][L][i2,gt3],coup1R -> Cp[bar[Fv], Fv, VZp][R][i2,gt3],coup2L -> Cp[bar[Fv], Fv, VZp][L][i3,i2],coup2R -> Cp[bar[Fv], Fv, VZp][R][i3,i2],coup3L -> Cp[bar[Fv], Fv, Ah][L][gt4,i3,iProp],coup3R -> Cp[bar[Fv], Fv, Ah][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mV1 -> M[VZp],mF1 -> M[Fv][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[Ah][iProp]}},
(* Fv,Ah, Internal:Fv, Propagator: Ah*) 
{{Fv,Ah, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fv], Fv, VZp][L][i3,gt3,iProp],coup3R -> Cp[bar[Fv], Fv, VZp][R][i3,gt3,iProp],coup2L -> Cp[bar[Fv], Fv, Ah][L][i1,i3,i2],coup2R -> Cp[bar[Fv], Fv, Ah][R][i1,i3,i2],coup1L -> Cp[bar[Fv], Fv, Ah][L][gt4,i1,i2],coup1R -> Cp[bar[Fv], Fv, Ah][R][gt4,i1,i2],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mF1 -> M[Fv][i1],mS1 -> M[Ah][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[Ah][iProp]}},
(* Se,Cha, Internal:Fv, Propagator: Ah*) 
{{Se,Cha, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fv], Fv, VZp][L][i3,gt3,iProp],coup3R -> Cp[bar[Fv], Fv, VZp][R][i3,gt3,iProp],coup2L -> Cp[Cha, Fv, conj[Se]][L][i2,i3,i1],coup2R -> Cp[Cha, Fv, conj[Se]][R][i2,i3,i1],coup1L -> Cp[bar[Cha], bar[Fv], Se][L][i2,gt4,i1],coup1R -> Cp[bar[Cha], bar[Fv], Se][R][i2,gt4,i1],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mS1 -> M[Se][i1],mF1 -> M[Cha][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[Ah][iProp]}},
(* Sv,Chi, Internal:Fv, Propagator: Ah*) 
{{Sv,Chi, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fv], Fv, VZp][L][i3,gt3,iProp],coup3R -> Cp[bar[Fv], Fv, VZp][R][i3,gt3,iProp],coup2L -> Cp[Chi, Fv, conj[Sv]][L][i2,i3,i1],coup2R -> Cp[Chi, Fv, conj[Sv]][R][i2,i3,i1],coup1L -> Cp[bar[Fv], Chi, Sv][L][gt4,i2,i1],coup1R -> Cp[bar[Fv], Chi, Sv][R][gt4,i2,i1],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mS1 -> M[Sv][i1],mF1 -> M[Chi][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[Ah][iProp]}},
(* Fv,hh, Internal:Fv, Propagator: Ah*) 
{{Fv,hh, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fv], Fv, VZp][L][i3,gt3,iProp],coup3R -> Cp[bar[Fv], Fv, VZp][R][i3,gt3,iProp],coup2L -> Cp[bar[Fv], Fv, hh][L][i1,i3,i2],coup2R -> Cp[bar[Fv], Fv, hh][R][i1,i3,i2],coup1L -> Cp[bar[Fv], Fv, hh][L][gt4,i1,i2],coup1R -> Cp[bar[Fv], Fv, hh][R][gt4,i1,i2],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mF1 -> M[Fv][i1],mS1 -> M[hh][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[Ah][iProp]}},
(* Fe,Hpm, Internal:Fv, Propagator: Ah*) 
{{Fe,Hpm, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fv], Fv, VZp][L][i3,gt3,iProp],coup3R -> Cp[bar[Fv], Fv, VZp][R][i3,gt3,iProp],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i1,i3,i2],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i1,i3,i2],coup1L -> Cp[bar[Fv], Fe, conj[Hpm]][L][gt4,i1,i2],coup1R -> Cp[bar[Fv], Fe, conj[Hpm]][R][gt4,i1,i2],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mF1 -> M[Fe][i1],mS1 -> M[Hpm][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[Ah][iProp]}},
(* Fe,VWm, Internal:Fv, Propagator: Ah*) 
{{Fe,VWm, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fv], Fv, VZp][L][i3,gt3,iProp],coup3R -> Cp[bar[Fv], Fv, VZp][R][i3,gt3,iProp],coup2L -> Cp[bar[Fe], Fv, VWm][L][i1,i3],coup2R -> Cp[bar[Fe], Fv, VWm][R][i1,i3],coup1L -> Cp[bar[Fv], Fe, conj[VWm]][L][gt4,i1],coup1R -> Cp[bar[Fv], Fe, conj[VWm]][R][gt4,i1],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mF1 -> M[Fe][i1],mV1 -> M[VWm],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[Ah][iProp]}},
(* Fv,VZ, Internal:Fv, Propagator: Ah*) 
{{Fv,VZ, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fv], Fv, VZp][L][i3,gt3,iProp],coup3R -> Cp[bar[Fv], Fv, VZp][R][i3,gt3,iProp],coup2L -> Cp[bar[Fv], Fv, VZ][L][i1,i3],coup2R -> Cp[bar[Fv], Fv, VZ][R][i1,i3],coup1L -> Cp[bar[Fv], Fv, VZ][L][gt4,i1],coup1R -> Cp[bar[Fv], Fv, VZ][R][gt4,i1],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mF1 -> M[Fv][i1],mV1 -> M[VZ],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[Ah][iProp]}},
(* Fv,VZp, Internal:Fv, Propagator: Ah*) 
{{Fv,VZp, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fv], Fv, VZp][L][i3,gt3,iProp],coup3R -> Cp[bar[Fv], Fv, VZp][R][i3,gt3,iProp],coup2L -> Cp[bar[Fv], Fv, VZp][L][i1,i3],coup2R -> Cp[bar[Fv], Fv, VZp][R][i1,i3],coup1L -> Cp[bar[Fv], Fv, VZp][L][gt4,i1],coup1R -> Cp[bar[Fv], Fv, VZp][R][gt4,i1],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mF1 -> M[Fv][i1],mV1 -> M[VZp],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[Ah][iProp]}}
(* Ah,Fd,Fd, Propagator: hh*) 
{{Ah,Fd,Fd, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, Ah][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, Ah][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Fd, Ah][R][gt2,i3,i1],coup3L -> Cp[bar[Fd], Fd, hh][L][i3,i2,iProp],coup3R -> Cp[bar[Fd], Fd, hh][R][i3,i2,iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* Chi,Sd,Sd, Propagator: hh*) 
{{Chi,Sd,Sd, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Chi, Fd, conj[Sd]][L][i1,gt1,i2],coup1R -> Cp[Chi, Fd, conj[Sd]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Chi, Sd][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Chi, Sd][R][gt2,i1,i3],coup3 -> Cp[hh, Sd, conj[Sd]][iProp,i2,i3],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* Glu,Sd,Sd, Propagator: hh*) 
{{Glu,Sd,Sd, Propagator ->hh},chargefactor -> 4/3,{coup1L -> Cp[Glu, Fd, conj[Sd]][L][gt1,i2],coup1R -> Cp[Glu, Fd, conj[Sd]][R][gt1,i2],coup2L -> Cp[bar[Fd], Glu, Sd][L][gt2,i3],coup2R -> Cp[bar[Fd], Glu, Sd][R][gt2,i3],coup3 -> Cp[hh, Sd, conj[Sd]][iProp,i2,i3],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* hh,Fd,Fd, Propagator: hh*) 
{{hh,Fd,Fd, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, hh][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i3,i1],coup3L -> Cp[bar[Fd], Fd, hh][L][i3,i2,iProp],coup3R -> Cp[bar[Fd], Fd, hh][R][i3,i2,iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* VZ,Fd,Fd, Propagator: hh*) 
{{VZ,Fd,Fd, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZ][L][gt2,i3],coup2R -> Cp[bar[Fd], Fd, VZ][R][gt2,i3],coup3L -> Cp[bar[Fd], Fd, hh][L][i3,i2,iProp],coup3R -> Cp[bar[Fd], Fd, hh][R][i3,i2,iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* VZp,Fd,Fd, Propagator: hh*) 
{{VZp,Fd,Fd, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZp][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZp][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZp][L][gt2,i3],coup2R -> Cp[bar[Fd], Fd, VZp][R][gt2,i3],coup3L -> Cp[bar[Fd], Fd, hh][L][i3,i2,iProp],coup3R -> Cp[bar[Fd], Fd, hh][R][i3,i2,iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Cha],Su,Su, Propagator: hh*) 
{{bar[Cha],Su,Su, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Cha], Fd, conj[Su]][L][i1,gt1,i2],coup1R -> Cp[bar[Cha], Fd, conj[Su]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Cha, Su][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Cha, Su][R][gt2,i1,i3],coup3 -> Cp[hh, Su, conj[Su]][iProp,i2,i3],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fd],Ah,Ah, Propagator: hh*) 
{{bar[Fd],Ah,Ah, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, Ah][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, Ah][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, Ah][R][gt2,i1,i3],coup3 -> Cp[Ah, Ah, hh][i3,i2,iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fd],hh,Ah, Propagator: hh*) 
{{bar[Fd],hh,Ah, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, Ah][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, Ah][R][gt2,i1,i3],coup3 -> Cp[Ah, hh, hh][i3,iProp,i2],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fd],VZ,Ah, Propagator: hh*) 
{{bar[Fd],VZ,Ah, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i1,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i1,gt1],coup2L -> Cp[bar[Fd], Fd, Ah][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, Ah][R][gt2,i1,i3],coup3 -> Cp[Ah, hh, VZ][i3,iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fd],VZp,Ah, Propagator: hh*) 
{{bar[Fd],VZp,Ah, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZp][L][i1,gt1],coup1R -> Cp[bar[Fd], Fd, VZp][R][i1,gt1],coup2L -> Cp[bar[Fd], Fd, Ah][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, Ah][R][gt2,i1,i3],coup3 -> Cp[Ah, hh, VZp][i3,iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fd],Ah,hh, Propagator: hh*) 
{{bar[Fd],Ah,hh, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, Ah][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i3],coup3 -> Cp[Ah, hh, hh][i2,iProp,i3],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fd],hh,hh, Propagator: hh*) 
{{bar[Fd],hh,hh, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i3],coup3 -> Cp[hh, hh, hh][iProp,i3,i2],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fd],Ah,VZ, Propagator: hh*) 
{{bar[Fd],Ah,VZ, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, Ah][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, VZ][L][gt2,i1],coup2R -> Cp[bar[Fd], Fd, VZ][R][gt2,i1],coup3 -> Cp[Ah, hh, VZ][i2,iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fd],VZ,VZ, Propagator: hh*) 
{{bar[Fd],VZ,VZ, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i1,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i1,gt1],coup2L -> Cp[bar[Fd], Fd, VZ][L][gt2,i1],coup2R -> Cp[bar[Fd], Fd, VZ][R][gt2,i1],coup3 -> Cp[hh, VZ, VZ][iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fd],VZp,VZ, Propagator: hh*) 
{{bar[Fd],VZp,VZ, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZp][L][i1,gt1],coup1R -> Cp[bar[Fd], Fd, VZp][R][i1,gt1],coup2L -> Cp[bar[Fd], Fd, VZ][L][gt2,i1],coup2R -> Cp[bar[Fd], Fd, VZ][R][gt2,i1],coup3 -> Cp[hh, VZ, VZp][iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fd],Ah,VZp, Propagator: hh*) 
{{bar[Fd],Ah,VZp, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, Ah][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, VZp][L][gt2,i1],coup2R -> Cp[bar[Fd], Fd, VZp][R][gt2,i1],coup3 -> Cp[Ah, hh, VZp][i2,iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fd],VZ,VZp, Propagator: hh*) 
{{bar[Fd],VZ,VZp, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i1,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i1,gt1],coup2L -> Cp[bar[Fd], Fd, VZp][L][gt2,i1],coup2R -> Cp[bar[Fd], Fd, VZp][R][gt2,i1],coup3 -> Cp[hh, VZ, VZp][iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fd],VZp,VZp, Propagator: hh*) 
{{bar[Fd],VZp,VZp, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZp][L][i1,gt1],coup1R -> Cp[bar[Fd], Fd, VZp][R][i1,gt1],coup2L -> Cp[bar[Fd], Fd, VZp][L][gt2,i1],coup2R -> Cp[bar[Fd], Fd, VZp][R][gt2,i1],coup3 -> Cp[hh, VZp, VZp][iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fu],Hpm,Hpm, Propagator: hh*) 
{{bar[Fu],Hpm,Hpm, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i1,i3],coup3 -> Cp[hh, Hpm, conj[Hpm]][iProp,i2,i3],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fu],VWm,Hpm, Propagator: hh*) 
{{bar[Fu],VWm,Hpm, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i1,i3],coup3 -> Cp[hh, conj[Hpm], VWm][iProp,i3],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fu],Hpm,VWm, Propagator: hh*) 
{{bar[Fu],Hpm,VWm, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, VWm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWm][R][gt2,i1],coup3 -> Cp[hh, Hpm, conj[VWm]][iProp,i2],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fu],VWm,VWm, Propagator: hh*) 
{{bar[Fu],VWm,VWm, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWm][R][gt2,i1],coup3 -> Cp[hh, conj[VWm], VWm][iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* conj[Hpm],Fu,Fu, Propagator: hh*) 
{{conj[Hpm],Fu,Fu, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i2,gt1,i1],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i3,i1],coup3L -> Cp[bar[Fu], Fu, hh][L][i3,i2,iProp],coup3R -> Cp[bar[Fu], Fu, hh][R][i3,i2,iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* conj[Sd],Chi,Chi, Propagator: hh*) 
{{conj[Sd],Chi,Chi, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Chi, Fd, conj[Sd]][L][i2,gt1,i1],coup1R -> Cp[Chi, Fd, conj[Sd]][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Chi, Sd][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Chi, Sd][R][gt2,i3,i1],coup3L -> Cp[Chi, Chi, hh][L][i3,i2,iProp],coup3R -> Cp[Chi, Chi, hh][R][i3,i2,iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* conj[Su],Cha,Cha, Propagator: hh*) 
{{conj[Su],Cha,Cha, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Cha], Fd, conj[Su]][L][i2,gt1,i1],coup1R -> Cp[bar[Cha], Fd, conj[Su]][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Cha, Su][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Cha, Su][R][gt2,i3,i1],coup3L -> Cp[bar[Cha], Cha, hh][L][i3,i2,iProp],coup3R -> Cp[bar[Cha], Cha, hh][R][i3,i2,iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* conj[VWm],Fu,Fu, Propagator: hh*) 
{{conj[VWm],Fu,Fu, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWm]][L][i2,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWm]][R][i2,gt1],coup2L -> Cp[bar[Fd], Fu, VWm][L][gt2,i3],coup2R -> Cp[bar[Fd], Fu, VWm][R][gt2,i3],coup3L -> Cp[bar[Fu], Fu, hh][L][i3,i2,iProp],coup3R -> Cp[bar[Fu], Fu, hh][R][i3,i2,iProp],coup4L -> Cp[bar[Fv], Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* Ah,Fv,Fv, Propagator: hh*) 
{{Ah,Fv,Fv, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, Ah][L][i2,gt3,i1],coup1R -> Cp[bar[Fv], Fv, Ah][R][i2,gt3,i1],coup2L -> Cp[bar[Fv], Fv, Ah][L][gt4,i3,i1],coup2R -> Cp[bar[Fv], Fv, Ah][R][gt4,i3,i1],coup3L -> Cp[bar[Fv], Fv, hh][L][i3,i2,iProp],coup3R -> Cp[bar[Fv], Fv, hh][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* Cha,Se,Se, Propagator: hh*) 
{{Cha,Se,Se, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Cha, Fv, conj[Se]][L][i1,gt3,i2],coup1R -> Cp[Cha, Fv, conj[Se]][R][i1,gt3,i2],coup2L -> Cp[bar[Cha], bar[Fv], Se][L][i1,gt4,i3],coup2R -> Cp[bar[Cha], bar[Fv], Se][R][i1,gt4,i3],coup3 -> Cp[hh, Se, conj[Se]][iProp,i2,i3],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* Chi,Sv,Sv, Propagator: hh*) 
{{Chi,Sv,Sv, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Chi, Fv, conj[Sv]][L][i1,gt3,i2],coup1R -> Cp[Chi, Fv, conj[Sv]][R][i1,gt3,i2],coup2L -> Cp[bar[Fv], Chi, Sv][L][gt4,i1,i3],coup2R -> Cp[bar[Fv], Chi, Sv][R][gt4,i1,i3],coup3 -> Cp[hh, Sv, conj[Sv]][iProp,i2,i3],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* hh,Fv,Fv, Propagator: hh*) 
{{hh,Fv,Fv, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, hh][L][i2,gt3,i1],coup1R -> Cp[bar[Fv], Fv, hh][R][i2,gt3,i1],coup2L -> Cp[bar[Fv], Fv, hh][L][gt4,i3,i1],coup2R -> Cp[bar[Fv], Fv, hh][R][gt4,i3,i1],coup3L -> Cp[bar[Fv], Fv, hh][L][i3,i2,iProp],coup3R -> Cp[bar[Fv], Fv, hh][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* Hpm,Fe,Fe, Propagator: hh*) 
{{Hpm,Fe,Fe, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i2,gt3,i1],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i2,gt3,i1],coup2L -> Cp[bar[Fv], Fe, conj[Hpm]][L][gt4,i3,i1],coup2R -> Cp[bar[Fv], Fe, conj[Hpm]][R][gt4,i3,i1],coup3L -> Cp[bar[Fe], Fe, hh][L][i3,i2,iProp],coup3R -> Cp[bar[Fe], Fe, hh][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* VWm,Fe,Fe, Propagator: hh*) 
{{VWm,Fe,Fe, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWm][L][i2,gt3],coup1R -> Cp[bar[Fe], Fv, VWm][R][i2,gt3],coup2L -> Cp[bar[Fv], Fe, conj[VWm]][L][gt4,i3],coup2R -> Cp[bar[Fv], Fe, conj[VWm]][R][gt4,i3],coup3L -> Cp[bar[Fe], Fe, hh][L][i3,i2,iProp],coup3R -> Cp[bar[Fe], Fe, hh][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* VZ,Fv,Fv, Propagator: hh*) 
{{VZ,Fv,Fv, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, VZ][L][i2,gt3],coup1R -> Cp[bar[Fv], Fv, VZ][R][i2,gt3],coup2L -> Cp[bar[Fv], Fv, VZ][L][gt4,i3],coup2R -> Cp[bar[Fv], Fv, VZ][R][gt4,i3],coup3L -> Cp[bar[Fv], Fv, hh][L][i3,i2,iProp],coup3R -> Cp[bar[Fv], Fv, hh][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* VZp,Fv,Fv, Propagator: hh*) 
{{VZp,Fv,Fv, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, VZp][L][i2,gt3],coup1R -> Cp[bar[Fv], Fv, VZp][R][i2,gt3],coup2L -> Cp[bar[Fv], Fv, VZp][L][gt4,i3],coup2R -> Cp[bar[Fv], Fv, VZp][R][gt4,i3],coup3L -> Cp[bar[Fv], Fv, hh][L][i3,i2,iProp],coup3R -> Cp[bar[Fv], Fv, hh][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fe],conj[Hpm],conj[Hpm], Propagator: hh*) 
{{bar[Fe],conj[Hpm],conj[Hpm], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt3,i2],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt3,i2],coup2L -> Cp[bar[Fv], Fe, conj[Hpm]][L][gt4,i1,i3],coup2R -> Cp[bar[Fv], Fe, conj[Hpm]][R][gt4,i1,i3],coup3 -> Cp[hh, Hpm, conj[Hpm]][iProp,i3,i2],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fe],conj[VWm],conj[Hpm], Propagator: hh*) 
{{bar[Fe],conj[VWm],conj[Hpm], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWm][R][i1,gt3],coup2L -> Cp[bar[Fv], Fe, conj[Hpm]][L][gt4,i1,i3],coup2R -> Cp[bar[Fv], Fe, conj[Hpm]][R][gt4,i1,i3],coup3 -> Cp[hh, Hpm, conj[VWm]][iProp,i3],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fe],conj[Hpm],conj[VWm], Propagator: hh*) 
{{bar[Fe],conj[Hpm],conj[VWm], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt3,i2],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt3,i2],coup2L -> Cp[bar[Fv], Fe, conj[VWm]][L][gt4,i1],coup2R -> Cp[bar[Fv], Fe, conj[VWm]][R][gt4,i1],coup3 -> Cp[hh, conj[Hpm], VWm][iProp,i2],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fe],conj[VWm],conj[VWm], Propagator: hh*) 
{{bar[Fe],conj[VWm],conj[VWm], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWm][R][i1,gt3],coup2L -> Cp[bar[Fv], Fe, conj[VWm]][L][gt4,i1],coup2R -> Cp[bar[Fv], Fe, conj[VWm]][R][gt4,i1],coup3 -> Cp[hh, conj[VWm], VWm][iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fv],Ah,Ah, Propagator: hh*) 
{{bar[Fv],Ah,Ah, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, Ah][L][i1,gt3,i2],coup1R -> Cp[bar[Fv], Fv, Ah][R][i1,gt3,i2],coup2L -> Cp[bar[Fv], Fv, Ah][L][gt4,i1,i3],coup2R -> Cp[bar[Fv], Fv, Ah][R][gt4,i1,i3],coup3 -> Cp[Ah, Ah, hh][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fv],hh,Ah, Propagator: hh*) 
{{bar[Fv],hh,Ah, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, hh][L][i1,gt3,i2],coup1R -> Cp[bar[Fv], Fv, hh][R][i1,gt3,i2],coup2L -> Cp[bar[Fv], Fv, Ah][L][gt4,i1,i3],coup2R -> Cp[bar[Fv], Fv, Ah][R][gt4,i1,i3],coup3 -> Cp[Ah, hh, hh][i3,iProp,i2],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fv],VZ,Ah, Propagator: hh*) 
{{bar[Fv],VZ,Ah, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, VZ][L][i1,gt3],coup1R -> Cp[bar[Fv], Fv, VZ][R][i1,gt3],coup2L -> Cp[bar[Fv], Fv, Ah][L][gt4,i1,i3],coup2R -> Cp[bar[Fv], Fv, Ah][R][gt4,i1,i3],coup3 -> Cp[Ah, hh, VZ][i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fv],VZp,Ah, Propagator: hh*) 
{{bar[Fv],VZp,Ah, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, VZp][L][i1,gt3],coup1R -> Cp[bar[Fv], Fv, VZp][R][i1,gt3],coup2L -> Cp[bar[Fv], Fv, Ah][L][gt4,i1,i3],coup2R -> Cp[bar[Fv], Fv, Ah][R][gt4,i1,i3],coup3 -> Cp[Ah, hh, VZp][i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fv],Ah,hh, Propagator: hh*) 
{{bar[Fv],Ah,hh, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, Ah][L][i1,gt3,i2],coup1R -> Cp[bar[Fv], Fv, Ah][R][i1,gt3,i2],coup2L -> Cp[bar[Fv], Fv, hh][L][gt4,i1,i3],coup2R -> Cp[bar[Fv], Fv, hh][R][gt4,i1,i3],coup3 -> Cp[Ah, hh, hh][i2,iProp,i3],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fv],hh,hh, Propagator: hh*) 
{{bar[Fv],hh,hh, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, hh][L][i1,gt3,i2],coup1R -> Cp[bar[Fv], Fv, hh][R][i1,gt3,i2],coup2L -> Cp[bar[Fv], Fv, hh][L][gt4,i1,i3],coup2R -> Cp[bar[Fv], Fv, hh][R][gt4,i1,i3],coup3 -> Cp[hh, hh, hh][iProp,i3,i2],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fv],Ah,VZ, Propagator: hh*) 
{{bar[Fv],Ah,VZ, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, Ah][L][i1,gt3,i2],coup1R -> Cp[bar[Fv], Fv, Ah][R][i1,gt3,i2],coup2L -> Cp[bar[Fv], Fv, VZ][L][gt4,i1],coup2R -> Cp[bar[Fv], Fv, VZ][R][gt4,i1],coup3 -> Cp[Ah, hh, VZ][i2,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fv],VZ,VZ, Propagator: hh*) 
{{bar[Fv],VZ,VZ, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, VZ][L][i1,gt3],coup1R -> Cp[bar[Fv], Fv, VZ][R][i1,gt3],coup2L -> Cp[bar[Fv], Fv, VZ][L][gt4,i1],coup2R -> Cp[bar[Fv], Fv, VZ][R][gt4,i1],coup3 -> Cp[hh, VZ, VZ][iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fv],VZp,VZ, Propagator: hh*) 
{{bar[Fv],VZp,VZ, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, VZp][L][i1,gt3],coup1R -> Cp[bar[Fv], Fv, VZp][R][i1,gt3],coup2L -> Cp[bar[Fv], Fv, VZ][L][gt4,i1],coup2R -> Cp[bar[Fv], Fv, VZ][R][gt4,i1],coup3 -> Cp[hh, VZ, VZp][iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fv],Ah,VZp, Propagator: hh*) 
{{bar[Fv],Ah,VZp, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, Ah][L][i1,gt3,i2],coup1R -> Cp[bar[Fv], Fv, Ah][R][i1,gt3,i2],coup2L -> Cp[bar[Fv], Fv, VZp][L][gt4,i1],coup2R -> Cp[bar[Fv], Fv, VZp][R][gt4,i1],coup3 -> Cp[Ah, hh, VZp][i2,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fv],VZ,VZp, Propagator: hh*) 
{{bar[Fv],VZ,VZp, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, VZ][L][i1,gt3],coup1R -> Cp[bar[Fv], Fv, VZ][R][i1,gt3],coup2L -> Cp[bar[Fv], Fv, VZp][L][gt4,i1],coup2R -> Cp[bar[Fv], Fv, VZp][R][gt4,i1],coup3 -> Cp[hh, VZ, VZp][iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fv],VZp,VZp, Propagator: hh*) 
{{bar[Fv],VZp,VZp, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, VZp][L][i1,gt3],coup1R -> Cp[bar[Fv], Fv, VZp][R][i1,gt3],coup2L -> Cp[bar[Fv], Fv, VZp][L][gt4,i1],coup2R -> Cp[bar[Fv], Fv, VZp][R][gt4,i1],coup3 -> Cp[hh, VZp, VZp][iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* conj[Se],bar[Cha],bar[Cha], Propagator: hh*) 
{{conj[Se],bar[Cha],bar[Cha], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Cha, Fv, conj[Se]][L][i2,gt3,i1],coup1R -> Cp[Cha, Fv, conj[Se]][R][i2,gt3,i1],coup2L -> Cp[bar[Cha], bar[Fv], Se][L][i3,gt4,i1],coup2R -> Cp[bar[Cha], bar[Fv], Se][R][i3,gt4,i1],coup3L -> Cp[bar[Cha], Cha, hh][L][i2,i3,iProp],coup3R -> Cp[bar[Cha], Cha, hh][R][i2,i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* conj[Sv],Chi,Chi, Propagator: hh*) 
{{conj[Sv],Chi,Chi, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Chi, Fv, conj[Sv]][L][i2,gt3,i1],coup1R -> Cp[Chi, Fv, conj[Sv]][R][i2,gt3,i1],coup2L -> Cp[bar[Fv], Chi, Sv][L][gt4,i3,i1],coup2R -> Cp[bar[Fv], Chi, Sv][R][gt4,i3,i1],coup3L -> Cp[Chi, Chi, hh][L][i3,i2,iProp],coup3R -> Cp[Chi, Chi, hh][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],}
(* Ah,Fd,Fd, Propagator: Ah*) 
{{Ah,Fd,Fd, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, Ah][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, Ah][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Fd, Ah][R][gt2,i3,i1],coup3L -> Cp[bar[Fd], Fd, Ah][L][i3,i2,iProp],coup3R -> Cp[bar[Fd], Fd, Ah][R][i3,i2,iProp],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* Chi,Sd,Sd, Propagator: Ah*) 
{{Chi,Sd,Sd, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Chi, Fd, conj[Sd]][L][i1,gt1,i2],coup1R -> Cp[Chi, Fd, conj[Sd]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Chi, Sd][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Chi, Sd][R][gt2,i1,i3],coup3 -> Cp[Ah, Sd, conj[Sd]][iProp,i2,i3],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* Glu,Sd,Sd, Propagator: Ah*) 
{{Glu,Sd,Sd, Propagator ->Ah},chargefactor -> 4/3,{coup1L -> Cp[Glu, Fd, conj[Sd]][L][gt1,i2],coup1R -> Cp[Glu, Fd, conj[Sd]][R][gt1,i2],coup2L -> Cp[bar[Fd], Glu, Sd][L][gt2,i3],coup2R -> Cp[bar[Fd], Glu, Sd][R][gt2,i3],coup3 -> Cp[Ah, Sd, conj[Sd]][iProp,i2,i3],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* hh,Fd,Fd, Propagator: Ah*) 
{{hh,Fd,Fd, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, hh][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i3,i1],coup3L -> Cp[bar[Fd], Fd, Ah][L][i3,i2,iProp],coup3R -> Cp[bar[Fd], Fd, Ah][R][i3,i2,iProp],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* VZ,Fd,Fd, Propagator: Ah*) 
{{VZ,Fd,Fd, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZ][L][gt2,i3],coup2R -> Cp[bar[Fd], Fd, VZ][R][gt2,i3],coup3L -> Cp[bar[Fd], Fd, Ah][L][i3,i2,iProp],coup3R -> Cp[bar[Fd], Fd, Ah][R][i3,i2,iProp],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* VZp,Fd,Fd, Propagator: Ah*) 
{{VZp,Fd,Fd, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZp][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZp][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZp][L][gt2,i3],coup2R -> Cp[bar[Fd], Fd, VZp][R][gt2,i3],coup3L -> Cp[bar[Fd], Fd, Ah][L][i3,i2,iProp],coup3R -> Cp[bar[Fd], Fd, Ah][R][i3,i2,iProp],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Cha],Su,Su, Propagator: Ah*) 
{{bar[Cha],Su,Su, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Cha], Fd, conj[Su]][L][i1,gt1,i2],coup1R -> Cp[bar[Cha], Fd, conj[Su]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Cha, Su][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Cha, Su][R][gt2,i1,i3],coup3 -> Cp[Ah, Su, conj[Su]][iProp,i2,i3],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Fd],Ah,Ah, Propagator: Ah*) 
{{bar[Fd],Ah,Ah, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, Ah][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, Ah][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, Ah][R][gt2,i1,i3],coup3 -> Cp[Ah, Ah, Ah][iProp,i3,i2],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Fd],hh,Ah, Propagator: Ah*) 
{{bar[Fd],hh,Ah, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, Ah][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, Ah][R][gt2,i1,i3],coup3 -> Cp[Ah, Ah, hh][iProp,i3,i2],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Fd],Ah,hh, Propagator: Ah*) 
{{bar[Fd],Ah,hh, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, Ah][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i3],coup3 -> Cp[Ah, Ah, hh][iProp,i2,i3],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Fd],hh,hh, Propagator: Ah*) 
{{bar[Fd],hh,hh, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i3],coup3 -> Cp[Ah, hh, hh][iProp,i3,i2],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Fd],VZ,hh, Propagator: Ah*) 
{{bar[Fd],VZ,hh, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i1,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i1,gt1],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i3],coup3 -> Cp[Ah, hh, VZ][iProp,i3],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Fd],VZp,hh, Propagator: Ah*) 
{{bar[Fd],VZp,hh, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZp][L][i1,gt1],coup1R -> Cp[bar[Fd], Fd, VZp][R][i1,gt1],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i3],coup3 -> Cp[Ah, hh, VZp][iProp,i3],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Fd],hh,VZ, Propagator: Ah*) 
{{bar[Fd],hh,VZ, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, VZ][L][gt2,i1],coup2R -> Cp[bar[Fd], Fd, VZ][R][gt2,i1],coup3 -> Cp[Ah, hh, VZ][iProp,i2],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Fd],hh,VZp, Propagator: Ah*) 
{{bar[Fd],hh,VZp, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, VZp][L][gt2,i1],coup2R -> Cp[bar[Fd], Fd, VZp][R][gt2,i1],coup3 -> Cp[Ah, hh, VZp][iProp,i2],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Fu],Hpm,Hpm, Propagator: Ah*) 
{{bar[Fu],Hpm,Hpm, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i1,i3],coup3 -> Cp[Ah, Hpm, conj[Hpm]][iProp,i2,i3],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Fu],VWm,Hpm, Propagator: Ah*) 
{{bar[Fu],VWm,Hpm, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i1,i3],coup3 -> Cp[Ah, conj[Hpm], VWm][iProp,i3],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Fu],Hpm,VWm, Propagator: Ah*) 
{{bar[Fu],Hpm,VWm, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, VWm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWm][R][gt2,i1],coup3 -> Cp[Ah, Hpm, conj[VWm]][iProp,i2],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* conj[Hpm],Fu,Fu, Propagator: Ah*) 
{{conj[Hpm],Fu,Fu, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i2,gt1,i1],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i3,i1],coup3L -> Cp[bar[Fu], Fu, Ah][L][i3,i2,iProp],coup3R -> Cp[bar[Fu], Fu, Ah][R][i3,i2,iProp],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* conj[Sd],Chi,Chi, Propagator: Ah*) 
{{conj[Sd],Chi,Chi, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Chi, Fd, conj[Sd]][L][i2,gt1,i1],coup1R -> Cp[Chi, Fd, conj[Sd]][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Chi, Sd][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Chi, Sd][R][gt2,i3,i1],coup3L -> Cp[Chi, Chi, Ah][L][i3,i2,iProp],coup3R -> Cp[Chi, Chi, Ah][R][i3,i2,iProp],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* conj[Su],Cha,Cha, Propagator: Ah*) 
{{conj[Su],Cha,Cha, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Cha], Fd, conj[Su]][L][i2,gt1,i1],coup1R -> Cp[bar[Cha], Fd, conj[Su]][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Cha, Su][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Cha, Su][R][gt2,i3,i1],coup3L -> Cp[bar[Cha], Cha, Ah][L][i3,i2,iProp],coup3R -> Cp[bar[Cha], Cha, Ah][R][i3,i2,iProp],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* conj[VWm],Fu,Fu, Propagator: Ah*) 
{{conj[VWm],Fu,Fu, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWm]][L][i2,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWm]][R][i2,gt1],coup2L -> Cp[bar[Fd], Fu, VWm][L][gt2,i3],coup2R -> Cp[bar[Fd], Fu, VWm][R][gt2,i3],coup3L -> Cp[bar[Fu], Fu, Ah][L][i3,i2,iProp],coup3R -> Cp[bar[Fu], Fu, Ah][R][i3,i2,iProp],coup4L -> Cp[bar[Fv], Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[bar[Fv], Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* Ah,Fv,Fv, Propagator: Ah*) 
{{Ah,Fv,Fv, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, Ah][L][i2,gt3,i1],coup1R -> Cp[bar[Fv], Fv, Ah][R][i2,gt3,i1],coup2L -> Cp[bar[Fv], Fv, Ah][L][gt4,i3,i1],coup2R -> Cp[bar[Fv], Fv, Ah][R][gt4,i3,i1],coup3L -> Cp[bar[Fv], Fv, Ah][L][i3,i2,iProp],coup3R -> Cp[bar[Fv], Fv, Ah][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* Cha,Se,Se, Propagator: Ah*) 
{{Cha,Se,Se, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Cha, Fv, conj[Se]][L][i1,gt3,i2],coup1R -> Cp[Cha, Fv, conj[Se]][R][i1,gt3,i2],coup2L -> Cp[bar[Cha], bar[Fv], Se][L][i1,gt4,i3],coup2R -> Cp[bar[Cha], bar[Fv], Se][R][i1,gt4,i3],coup3 -> Cp[Ah, Se, conj[Se]][iProp,i2,i3],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* Chi,Sv,Sv, Propagator: Ah*) 
{{Chi,Sv,Sv, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Chi, Fv, conj[Sv]][L][i1,gt3,i2],coup1R -> Cp[Chi, Fv, conj[Sv]][R][i1,gt3,i2],coup2L -> Cp[bar[Fv], Chi, Sv][L][gt4,i1,i3],coup2R -> Cp[bar[Fv], Chi, Sv][R][gt4,i1,i3],coup3 -> Cp[Ah, Sv, conj[Sv]][iProp,i2,i3],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* hh,Fv,Fv, Propagator: Ah*) 
{{hh,Fv,Fv, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, hh][L][i2,gt3,i1],coup1R -> Cp[bar[Fv], Fv, hh][R][i2,gt3,i1],coup2L -> Cp[bar[Fv], Fv, hh][L][gt4,i3,i1],coup2R -> Cp[bar[Fv], Fv, hh][R][gt4,i3,i1],coup3L -> Cp[bar[Fv], Fv, Ah][L][i3,i2,iProp],coup3R -> Cp[bar[Fv], Fv, Ah][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* Hpm,Fe,Fe, Propagator: Ah*) 
{{Hpm,Fe,Fe, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i2,gt3,i1],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i2,gt3,i1],coup2L -> Cp[bar[Fv], Fe, conj[Hpm]][L][gt4,i3,i1],coup2R -> Cp[bar[Fv], Fe, conj[Hpm]][R][gt4,i3,i1],coup3L -> Cp[bar[Fe], Fe, Ah][L][i3,i2,iProp],coup3R -> Cp[bar[Fe], Fe, Ah][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* VWm,Fe,Fe, Propagator: Ah*) 
{{VWm,Fe,Fe, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWm][L][i2,gt3],coup1R -> Cp[bar[Fe], Fv, VWm][R][i2,gt3],coup2L -> Cp[bar[Fv], Fe, conj[VWm]][L][gt4,i3],coup2R -> Cp[bar[Fv], Fe, conj[VWm]][R][gt4,i3],coup3L -> Cp[bar[Fe], Fe, Ah][L][i3,i2,iProp],coup3R -> Cp[bar[Fe], Fe, Ah][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* VZ,Fv,Fv, Propagator: Ah*) 
{{VZ,Fv,Fv, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, VZ][L][i2,gt3],coup1R -> Cp[bar[Fv], Fv, VZ][R][i2,gt3],coup2L -> Cp[bar[Fv], Fv, VZ][L][gt4,i3],coup2R -> Cp[bar[Fv], Fv, VZ][R][gt4,i3],coup3L -> Cp[bar[Fv], Fv, Ah][L][i3,i2,iProp],coup3R -> Cp[bar[Fv], Fv, Ah][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* VZp,Fv,Fv, Propagator: Ah*) 
{{VZp,Fv,Fv, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, VZp][L][i2,gt3],coup1R -> Cp[bar[Fv], Fv, VZp][R][i2,gt3],coup2L -> Cp[bar[Fv], Fv, VZp][L][gt4,i3],coup2R -> Cp[bar[Fv], Fv, VZp][R][gt4,i3],coup3L -> Cp[bar[Fv], Fv, Ah][L][i3,i2,iProp],coup3R -> Cp[bar[Fv], Fv, Ah][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* bar[Fe],conj[Hpm],conj[Hpm], Propagator: Ah*) 
{{bar[Fe],conj[Hpm],conj[Hpm], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt3,i2],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt3,i2],coup2L -> Cp[bar[Fv], Fe, conj[Hpm]][L][gt4,i1,i3],coup2R -> Cp[bar[Fv], Fe, conj[Hpm]][R][gt4,i1,i3],coup3 -> Cp[Ah, Hpm, conj[Hpm]][iProp,i3,i2],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* bar[Fe],conj[VWm],conj[Hpm], Propagator: Ah*) 
{{bar[Fe],conj[VWm],conj[Hpm], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWm][R][i1,gt3],coup2L -> Cp[bar[Fv], Fe, conj[Hpm]][L][gt4,i1,i3],coup2R -> Cp[bar[Fv], Fe, conj[Hpm]][R][gt4,i1,i3],coup3 -> Cp[Ah, Hpm, conj[VWm]][iProp,i3],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* bar[Fe],conj[Hpm],conj[VWm], Propagator: Ah*) 
{{bar[Fe],conj[Hpm],conj[VWm], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt3,i2],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt3,i2],coup2L -> Cp[bar[Fv], Fe, conj[VWm]][L][gt4,i1],coup2R -> Cp[bar[Fv], Fe, conj[VWm]][R][gt4,i1],coup3 -> Cp[Ah, conj[Hpm], VWm][iProp,i2],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* bar[Fv],Ah,Ah, Propagator: Ah*) 
{{bar[Fv],Ah,Ah, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, Ah][L][i1,gt3,i2],coup1R -> Cp[bar[Fv], Fv, Ah][R][i1,gt3,i2],coup2L -> Cp[bar[Fv], Fv, Ah][L][gt4,i1,i3],coup2R -> Cp[bar[Fv], Fv, Ah][R][gt4,i1,i3],coup3 -> Cp[Ah, Ah, Ah][iProp,i3,i2],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* bar[Fv],hh,Ah, Propagator: Ah*) 
{{bar[Fv],hh,Ah, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, hh][L][i1,gt3,i2],coup1R -> Cp[bar[Fv], Fv, hh][R][i1,gt3,i2],coup2L -> Cp[bar[Fv], Fv, Ah][L][gt4,i1,i3],coup2R -> Cp[bar[Fv], Fv, Ah][R][gt4,i1,i3],coup3 -> Cp[Ah, Ah, hh][iProp,i3,i2],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* bar[Fv],Ah,hh, Propagator: Ah*) 
{{bar[Fv],Ah,hh, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, Ah][L][i1,gt3,i2],coup1R -> Cp[bar[Fv], Fv, Ah][R][i1,gt3,i2],coup2L -> Cp[bar[Fv], Fv, hh][L][gt4,i1,i3],coup2R -> Cp[bar[Fv], Fv, hh][R][gt4,i1,i3],coup3 -> Cp[Ah, Ah, hh][iProp,i2,i3],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* bar[Fv],hh,hh, Propagator: Ah*) 
{{bar[Fv],hh,hh, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, hh][L][i1,gt3,i2],coup1R -> Cp[bar[Fv], Fv, hh][R][i1,gt3,i2],coup2L -> Cp[bar[Fv], Fv, hh][L][gt4,i1,i3],coup2R -> Cp[bar[Fv], Fv, hh][R][gt4,i1,i3],coup3 -> Cp[Ah, hh, hh][iProp,i3,i2],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* bar[Fv],VZ,hh, Propagator: Ah*) 
{{bar[Fv],VZ,hh, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, VZ][L][i1,gt3],coup1R -> Cp[bar[Fv], Fv, VZ][R][i1,gt3],coup2L -> Cp[bar[Fv], Fv, hh][L][gt4,i1,i3],coup2R -> Cp[bar[Fv], Fv, hh][R][gt4,i1,i3],coup3 -> Cp[Ah, hh, VZ][iProp,i3],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* bar[Fv],VZp,hh, Propagator: Ah*) 
{{bar[Fv],VZp,hh, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, VZp][L][i1,gt3],coup1R -> Cp[bar[Fv], Fv, VZp][R][i1,gt3],coup2L -> Cp[bar[Fv], Fv, hh][L][gt4,i1,i3],coup2R -> Cp[bar[Fv], Fv, hh][R][gt4,i1,i3],coup3 -> Cp[Ah, hh, VZp][iProp,i3],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* bar[Fv],hh,VZ, Propagator: Ah*) 
{{bar[Fv],hh,VZ, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, hh][L][i1,gt3,i2],coup1R -> Cp[bar[Fv], Fv, hh][R][i1,gt3,i2],coup2L -> Cp[bar[Fv], Fv, VZ][L][gt4,i1],coup2R -> Cp[bar[Fv], Fv, VZ][R][gt4,i1],coup3 -> Cp[Ah, hh, VZ][iProp,i2],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* bar[Fv],hh,VZp, Propagator: Ah*) 
{{bar[Fv],hh,VZp, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fv], Fv, hh][L][i1,gt3,i2],coup1R -> Cp[bar[Fv], Fv, hh][R][i1,gt3,i2],coup2L -> Cp[bar[Fv], Fv, VZp][L][gt4,i1],coup2R -> Cp[bar[Fv], Fv, VZp][R][gt4,i1],coup3 -> Cp[Ah, hh, VZp][iProp,i2],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* conj[Se],bar[Cha],bar[Cha], Propagator: Ah*) 
{{conj[Se],bar[Cha],bar[Cha], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Cha, Fv, conj[Se]][L][i2,gt3,i1],coup1R -> Cp[Cha, Fv, conj[Se]][R][i2,gt3,i1],coup2L -> Cp[bar[Cha], bar[Fv], Se][L][i3,gt4,i1],coup2R -> Cp[bar[Cha], bar[Fv], Se][R][i3,gt4,i1],coup3L -> Cp[bar[Cha], Cha, Ah][L][i2,i3,iProp],coup3R -> Cp[bar[Cha], Cha, Ah][R][i2,i3,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* conj[Sv],Chi,Chi, Propagator: Ah*) 
{{conj[Sv],Chi,Chi, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Chi, Fv, conj[Sv]][L][i2,gt3,i1],coup1R -> Cp[Chi, Fv, conj[Sv]][R][i2,gt3,i1],coup2L -> Cp[bar[Fv], Chi, Sv][L][gt4,i3,i1],coup2R -> Cp[bar[Fv], Chi, Sv][R][gt4,i3,i1],coup3L -> Cp[Chi, Chi, Ah][L][i3,i2,iProp],coup3R -> Cp[Chi, Chi, Ah][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],}
};