! --------------------------------------------------------------------------------
! Autogenerated by the happy scrappy WHIZARD model file generator on 2/10/2021 , 0:41:44
! WHIZARD interface svn revision info: $Id: WOMathematicaInterface.m 3666 2012-01-14 17:03:09Z cnspeckn $
! Code generated for WHIZARD / O'Mega version 2.4.0
! Model name: nonumssm_sarah
! Gauge: Unitarity
! Maximum number of couplings per FORTRAN module: 150
! --------------------------------------------------------------------------------
! 
! --------------------------------------------------------------------------------

module parameters_nonumssm_sarah_cpl15
use parameters_nonumssm_sarah_global
use parameters_nonumssm_sarah_local
implicit none

contains

subroutine calc_cpl15
   G_z_1_sd2_sd4c = (0,-1)*((0,0.5_default)*g2*ZD41*conjg(ZD21)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD42*conjg(ZD22)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD43* &
      conjg(ZD23)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD41*conjg(ZD21)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD42*conjg(ZD22)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD43*conjg(ZD23)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD44*conjg(ZD24)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD45* &
      conjg(ZD25)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD46*conjg(ZD26)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD41*conjg(ZD21)*Sin(TWp) - (0,1)*gp*Qq*ZD42*conjg( &
      ZD22)*Sin(TWp) - (0,1)*gp*Qq*ZD43*conjg(ZD23)*Sin(TWp) + (0,1)*gp*Qd*ZD44*conjg(ZD24 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD45*conjg(ZD25)*Sin(TWp) + (0,1)*gp*Qd*ZD46*conjg(ZD26)* &
      Sin(TWp))
   G_z_1_sd2_sd5c = (0,-1)*((0,0.5_default)*g2*ZD51*conjg(ZD21)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD52*conjg(ZD22)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD53* &
      conjg(ZD23)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD51*conjg(ZD21)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD52*conjg(ZD22)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD53*conjg(ZD23)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD54*conjg(ZD24)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD55* &
      conjg(ZD25)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD56*conjg(ZD26)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD51*conjg(ZD21)*Sin(TWp) - (0,1)*gp*Qq*ZD52*conjg( &
      ZD22)*Sin(TWp) - (0,1)*gp*Qq*ZD53*conjg(ZD23)*Sin(TWp) + (0,1)*gp*Qd*ZD54*conjg(ZD24 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD55*conjg(ZD25)*Sin(TWp) + (0,1)*gp*Qd*ZD56*conjg(ZD26)* &
      Sin(TWp))
   G_z_1_sd2_sd6c = (0,-1)*((0,0.5_default)*g2*ZD61*conjg(ZD21)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD62*conjg(ZD22)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD63* &
      conjg(ZD23)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD61*conjg(ZD21)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD62*conjg(ZD22)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD63*conjg(ZD23)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD64*conjg(ZD24)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD65* &
      conjg(ZD25)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD66*conjg(ZD26)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD61*conjg(ZD21)*Sin(TWp) - (0,1)*gp*Qq*ZD62*conjg( &
      ZD22)*Sin(TWp) - (0,1)*gp*Qq*ZD63*conjg(ZD23)*Sin(TWp) + (0,1)*gp*Qd*ZD64*conjg(ZD24 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD65*conjg(ZD25)*Sin(TWp) + (0,1)*gp*Qd*ZD66*conjg(ZD26)* &
      Sin(TWp))
   G_z_1_sd3_sd1c = (0,-1)*((0,0.5_default)*g2*ZD11*conjg(ZD31)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD12*conjg(ZD32)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD13* &
      conjg(ZD33)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD11*conjg(ZD31)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD12*conjg(ZD32)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD13*conjg(ZD33)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD14*conjg(ZD34)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD15* &
      conjg(ZD35)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD16*conjg(ZD36)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD11*conjg(ZD31)*Sin(TWp) - (0,1)*gp*Qq*ZD12*conjg( &
      ZD32)*Sin(TWp) - (0,1)*gp*Qq*ZD13*conjg(ZD33)*Sin(TWp) + (0,1)*gp*Qd*ZD14*conjg(ZD34 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD15*conjg(ZD35)*Sin(TWp) + (0,1)*gp*Qd*ZD16*conjg(ZD36)* &
      Sin(TWp))
   G_z_1_sd3_sd2c = (0,-1)*((0,0.5_default)*g2*ZD21*conjg(ZD31)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD22*conjg(ZD32)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD23* &
      conjg(ZD33)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD21*conjg(ZD31)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD22*conjg(ZD32)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD23*conjg(ZD33)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD24*conjg(ZD34)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD25* &
      conjg(ZD35)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD26*conjg(ZD36)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD21*conjg(ZD31)*Sin(TWp) - (0,1)*gp*Qq*ZD22*conjg( &
      ZD32)*Sin(TWp) - (0,1)*gp*Qq*ZD23*conjg(ZD33)*Sin(TWp) + (0,1)*gp*Qd*ZD24*conjg(ZD34 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD25*conjg(ZD35)*Sin(TWp) + (0,1)*gp*Qd*ZD26*conjg(ZD36)* &
      Sin(TWp))
   G_z_1_sd3_sd3c = (0,-1)*((0,0.5_default)*g2*ZD31*conjg(ZD31)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD32*conjg(ZD32)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD33* &
      conjg(ZD33)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD31*conjg(ZD31)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD32*conjg(ZD32)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD33*conjg(ZD33)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD34*conjg(ZD34)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD35* &
      conjg(ZD35)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD36*conjg(ZD36)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD31*conjg(ZD31)*Sin(TWp) - (0,1)*gp*Qq*ZD32*conjg( &
      ZD32)*Sin(TWp) - (0,1)*gp*Qq*ZD33*conjg(ZD33)*Sin(TWp) + (0,1)*gp*Qd*ZD34*conjg(ZD34 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD35*conjg(ZD35)*Sin(TWp) + (0,1)*gp*Qd*ZD36*conjg(ZD36)* &
      Sin(TWp))
   G_z_1_sd3_sd4c = (0,-1)*((0,0.5_default)*g2*ZD41*conjg(ZD31)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD42*conjg(ZD32)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD43* &
      conjg(ZD33)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD41*conjg(ZD31)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD42*conjg(ZD32)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD43*conjg(ZD33)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD44*conjg(ZD34)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD45* &
      conjg(ZD35)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD46*conjg(ZD36)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD41*conjg(ZD31)*Sin(TWp) - (0,1)*gp*Qq*ZD42*conjg( &
      ZD32)*Sin(TWp) - (0,1)*gp*Qq*ZD43*conjg(ZD33)*Sin(TWp) + (0,1)*gp*Qd*ZD44*conjg(ZD34 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD45*conjg(ZD35)*Sin(TWp) + (0,1)*gp*Qd*ZD46*conjg(ZD36)* &
      Sin(TWp))
   G_z_1_sd3_sd5c = (0,-1)*((0,0.5_default)*g2*ZD51*conjg(ZD31)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD52*conjg(ZD32)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD53* &
      conjg(ZD33)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD51*conjg(ZD31)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD52*conjg(ZD32)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD53*conjg(ZD33)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD54*conjg(ZD34)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD55* &
      conjg(ZD35)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD56*conjg(ZD36)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD51*conjg(ZD31)*Sin(TWp) - (0,1)*gp*Qq*ZD52*conjg( &
      ZD32)*Sin(TWp) - (0,1)*gp*Qq*ZD53*conjg(ZD33)*Sin(TWp) + (0,1)*gp*Qd*ZD54*conjg(ZD34 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD55*conjg(ZD35)*Sin(TWp) + (0,1)*gp*Qd*ZD56*conjg(ZD36)* &
      Sin(TWp))
   G_z_1_sd3_sd6c = (0,-1)*((0,0.5_default)*g2*ZD61*conjg(ZD31)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD62*conjg(ZD32)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD63* &
      conjg(ZD33)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD61*conjg(ZD31)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD62*conjg(ZD32)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD63*conjg(ZD33)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD64*conjg(ZD34)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD65* &
      conjg(ZD35)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD66*conjg(ZD36)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD61*conjg(ZD31)*Sin(TWp) - (0,1)*gp*Qq*ZD62*conjg( &
      ZD32)*Sin(TWp) - (0,1)*gp*Qq*ZD63*conjg(ZD33)*Sin(TWp) + (0,1)*gp*Qd*ZD64*conjg(ZD34 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD65*conjg(ZD35)*Sin(TWp) + (0,1)*gp*Qd*ZD66*conjg(ZD36)* &
      Sin(TWp))
   G_z_1_sd4_sd1c = (0,-1)*((0,0.5_default)*g2*ZD11*conjg(ZD41)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD12*conjg(ZD42)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD13* &
      conjg(ZD43)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD11*conjg(ZD41)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD12*conjg(ZD42)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD13*conjg(ZD43)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD14*conjg(ZD44)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD15* &
      conjg(ZD45)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD16*conjg(ZD46)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD11*conjg(ZD41)*Sin(TWp) - (0,1)*gp*Qq*ZD12*conjg( &
      ZD42)*Sin(TWp) - (0,1)*gp*Qq*ZD13*conjg(ZD43)*Sin(TWp) + (0,1)*gp*Qd*ZD14*conjg(ZD44 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD15*conjg(ZD45)*Sin(TWp) + (0,1)*gp*Qd*ZD16*conjg(ZD46)* &
      Sin(TWp))
   G_z_1_sd4_sd2c = (0,-1)*((0,0.5_default)*g2*ZD21*conjg(ZD41)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD22*conjg(ZD42)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD23* &
      conjg(ZD43)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD21*conjg(ZD41)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD22*conjg(ZD42)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD23*conjg(ZD43)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD24*conjg(ZD44)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD25* &
      conjg(ZD45)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD26*conjg(ZD46)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD21*conjg(ZD41)*Sin(TWp) - (0,1)*gp*Qq*ZD22*conjg( &
      ZD42)*Sin(TWp) - (0,1)*gp*Qq*ZD23*conjg(ZD43)*Sin(TWp) + (0,1)*gp*Qd*ZD24*conjg(ZD44 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD25*conjg(ZD45)*Sin(TWp) + (0,1)*gp*Qd*ZD26*conjg(ZD46)* &
      Sin(TWp))
   G_z_1_sd4_sd3c = (0,-1)*((0,0.5_default)*g2*ZD31*conjg(ZD41)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD32*conjg(ZD42)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD33* &
      conjg(ZD43)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD31*conjg(ZD41)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD32*conjg(ZD42)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD33*conjg(ZD43)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD34*conjg(ZD44)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD35* &
      conjg(ZD45)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD36*conjg(ZD46)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD31*conjg(ZD41)*Sin(TWp) - (0,1)*gp*Qq*ZD32*conjg( &
      ZD42)*Sin(TWp) - (0,1)*gp*Qq*ZD33*conjg(ZD43)*Sin(TWp) + (0,1)*gp*Qd*ZD34*conjg(ZD44 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD35*conjg(ZD45)*Sin(TWp) + (0,1)*gp*Qd*ZD36*conjg(ZD46)* &
      Sin(TWp))
   G_z_1_sd4_sd4c = (0,-1)*((0,0.5_default)*g2*ZD41*conjg(ZD41)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD42*conjg(ZD42)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD43* &
      conjg(ZD43)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD41*conjg(ZD41)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD42*conjg(ZD42)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD43*conjg(ZD43)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD44*conjg(ZD44)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD45* &
      conjg(ZD45)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD46*conjg(ZD46)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD41*conjg(ZD41)*Sin(TWp) - (0,1)*gp*Qq*ZD42*conjg( &
      ZD42)*Sin(TWp) - (0,1)*gp*Qq*ZD43*conjg(ZD43)*Sin(TWp) + (0,1)*gp*Qd*ZD44*conjg(ZD44 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD45*conjg(ZD45)*Sin(TWp) + (0,1)*gp*Qd*ZD46*conjg(ZD46)* &
      Sin(TWp))
   G_z_1_sd4_sd5c = (0,-1)*((0,0.5_default)*g2*ZD51*conjg(ZD41)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD52*conjg(ZD42)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD53* &
      conjg(ZD43)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD51*conjg(ZD41)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD52*conjg(ZD42)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD53*conjg(ZD43)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD54*conjg(ZD44)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD55* &
      conjg(ZD45)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD56*conjg(ZD46)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD51*conjg(ZD41)*Sin(TWp) - (0,1)*gp*Qq*ZD52*conjg( &
      ZD42)*Sin(TWp) - (0,1)*gp*Qq*ZD53*conjg(ZD43)*Sin(TWp) + (0,1)*gp*Qd*ZD54*conjg(ZD44 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD55*conjg(ZD45)*Sin(TWp) + (0,1)*gp*Qd*ZD56*conjg(ZD46)* &
      Sin(TWp))
   G_z_1_sd4_sd6c = (0,-1)*((0,0.5_default)*g2*ZD61*conjg(ZD41)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD62*conjg(ZD42)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD63* &
      conjg(ZD43)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD61*conjg(ZD41)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD62*conjg(ZD42)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD63*conjg(ZD43)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD64*conjg(ZD44)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD65* &
      conjg(ZD45)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD66*conjg(ZD46)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD61*conjg(ZD41)*Sin(TWp) - (0,1)*gp*Qq*ZD62*conjg( &
      ZD42)*Sin(TWp) - (0,1)*gp*Qq*ZD63*conjg(ZD43)*Sin(TWp) + (0,1)*gp*Qd*ZD64*conjg(ZD44 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD65*conjg(ZD45)*Sin(TWp) + (0,1)*gp*Qd*ZD66*conjg(ZD46)* &
      Sin(TWp))
   G_z_1_sd5_sd1c = (0,-1)*((0,0.5_default)*g2*ZD11*conjg(ZD51)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD12*conjg(ZD52)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD13* &
      conjg(ZD53)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD11*conjg(ZD51)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD12*conjg(ZD52)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD13*conjg(ZD53)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD14*conjg(ZD54)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD15* &
      conjg(ZD55)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD16*conjg(ZD56)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD11*conjg(ZD51)*Sin(TWp) - (0,1)*gp*Qq*ZD12*conjg( &
      ZD52)*Sin(TWp) - (0,1)*gp*Qq*ZD13*conjg(ZD53)*Sin(TWp) + (0,1)*gp*Qd*ZD14*conjg(ZD54 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD15*conjg(ZD55)*Sin(TWp) + (0,1)*gp*Qd*ZD16*conjg(ZD56)* &
      Sin(TWp))
   G_z_1_sd5_sd2c = (0,-1)*((0,0.5_default)*g2*ZD21*conjg(ZD51)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD22*conjg(ZD52)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD23* &
      conjg(ZD53)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD21*conjg(ZD51)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD22*conjg(ZD52)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD23*conjg(ZD53)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD24*conjg(ZD54)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD25* &
      conjg(ZD55)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD26*conjg(ZD56)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD21*conjg(ZD51)*Sin(TWp) - (0,1)*gp*Qq*ZD22*conjg( &
      ZD52)*Sin(TWp) - (0,1)*gp*Qq*ZD23*conjg(ZD53)*Sin(TWp) + (0,1)*gp*Qd*ZD24*conjg(ZD54 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD25*conjg(ZD55)*Sin(TWp) + (0,1)*gp*Qd*ZD26*conjg(ZD56)* &
      Sin(TWp))
   G_z_1_sd5_sd3c = (0,-1)*((0,0.5_default)*g2*ZD31*conjg(ZD51)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD32*conjg(ZD52)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD33* &
      conjg(ZD53)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD31*conjg(ZD51)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD32*conjg(ZD52)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD33*conjg(ZD53)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD34*conjg(ZD54)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD35* &
      conjg(ZD55)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD36*conjg(ZD56)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD31*conjg(ZD51)*Sin(TWp) - (0,1)*gp*Qq*ZD32*conjg( &
      ZD52)*Sin(TWp) - (0,1)*gp*Qq*ZD33*conjg(ZD53)*Sin(TWp) + (0,1)*gp*Qd*ZD34*conjg(ZD54 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD35*conjg(ZD55)*Sin(TWp) + (0,1)*gp*Qd*ZD36*conjg(ZD56)* &
      Sin(TWp))
   G_z_1_sd5_sd4c = (0,-1)*((0,0.5_default)*g2*ZD41*conjg(ZD51)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD42*conjg(ZD52)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD43* &
      conjg(ZD53)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD41*conjg(ZD51)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD42*conjg(ZD52)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD43*conjg(ZD53)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD44*conjg(ZD54)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD45* &
      conjg(ZD55)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD46*conjg(ZD56)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD41*conjg(ZD51)*Sin(TWp) - (0,1)*gp*Qq*ZD42*conjg( &
      ZD52)*Sin(TWp) - (0,1)*gp*Qq*ZD43*conjg(ZD53)*Sin(TWp) + (0,1)*gp*Qd*ZD44*conjg(ZD54 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD45*conjg(ZD55)*Sin(TWp) + (0,1)*gp*Qd*ZD46*conjg(ZD56)* &
      Sin(TWp))
   G_z_1_sd5_sd5c = (0,-1)*((0,0.5_default)*g2*ZD51*conjg(ZD51)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD52*conjg(ZD52)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD53* &
      conjg(ZD53)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD51*conjg(ZD51)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD52*conjg(ZD52)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD53*conjg(ZD53)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD54*conjg(ZD54)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD55* &
      conjg(ZD55)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD56*conjg(ZD56)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD51*conjg(ZD51)*Sin(TWp) - (0,1)*gp*Qq*ZD52*conjg( &
      ZD52)*Sin(TWp) - (0,1)*gp*Qq*ZD53*conjg(ZD53)*Sin(TWp) + (0,1)*gp*Qd*ZD54*conjg(ZD54 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD55*conjg(ZD55)*Sin(TWp) + (0,1)*gp*Qd*ZD56*conjg(ZD56)* &
      Sin(TWp))
   G_z_1_sd5_sd6c = (0,-1)*((0,0.5_default)*g2*ZD61*conjg(ZD51)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD62*conjg(ZD52)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD63* &
      conjg(ZD53)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD61*conjg(ZD51)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD62*conjg(ZD52)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD63*conjg(ZD53)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD64*conjg(ZD54)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD65* &
      conjg(ZD55)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD66*conjg(ZD56)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD61*conjg(ZD51)*Sin(TWp) - (0,1)*gp*Qq*ZD62*conjg( &
      ZD52)*Sin(TWp) - (0,1)*gp*Qq*ZD63*conjg(ZD53)*Sin(TWp) + (0,1)*gp*Qd*ZD64*conjg(ZD54 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD65*conjg(ZD55)*Sin(TWp) + (0,1)*gp*Qd*ZD66*conjg(ZD56)* &
      Sin(TWp))
   G_z_1_sd6_sd1c = (0,-1)*((0,0.5_default)*g2*ZD11*conjg(ZD61)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD12*conjg(ZD62)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD13* &
      conjg(ZD63)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD11*conjg(ZD61)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD12*conjg(ZD62)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD13*conjg(ZD63)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD14*conjg(ZD64)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD15* &
      conjg(ZD65)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD16*conjg(ZD66)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD11*conjg(ZD61)*Sin(TWp) - (0,1)*gp*Qq*ZD12*conjg( &
      ZD62)*Sin(TWp) - (0,1)*gp*Qq*ZD13*conjg(ZD63)*Sin(TWp) + (0,1)*gp*Qd*ZD14*conjg(ZD64 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD15*conjg(ZD65)*Sin(TWp) + (0,1)*gp*Qd*ZD16*conjg(ZD66)* &
      Sin(TWp))
   G_z_1_sd6_sd2c = (0,-1)*((0,0.5_default)*g2*ZD21*conjg(ZD61)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD22*conjg(ZD62)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD23* &
      conjg(ZD63)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD21*conjg(ZD61)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD22*conjg(ZD62)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD23*conjg(ZD63)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD24*conjg(ZD64)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD25* &
      conjg(ZD65)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD26*conjg(ZD66)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD21*conjg(ZD61)*Sin(TWp) - (0,1)*gp*Qq*ZD22*conjg( &
      ZD62)*Sin(TWp) - (0,1)*gp*Qq*ZD23*conjg(ZD63)*Sin(TWp) + (0,1)*gp*Qd*ZD24*conjg(ZD64 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD25*conjg(ZD65)*Sin(TWp) + (0,1)*gp*Qd*ZD26*conjg(ZD66)* &
      Sin(TWp))
   G_z_1_sd6_sd3c = (0,-1)*((0,0.5_default)*g2*ZD31*conjg(ZD61)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD32*conjg(ZD62)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD33* &
      conjg(ZD63)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD31*conjg(ZD61)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD32*conjg(ZD62)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD33*conjg(ZD63)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD34*conjg(ZD64)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD35* &
      conjg(ZD65)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD36*conjg(ZD66)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD31*conjg(ZD61)*Sin(TWp) - (0,1)*gp*Qq*ZD32*conjg( &
      ZD62)*Sin(TWp) - (0,1)*gp*Qq*ZD33*conjg(ZD63)*Sin(TWp) + (0,1)*gp*Qd*ZD34*conjg(ZD64 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD35*conjg(ZD65)*Sin(TWp) + (0,1)*gp*Qd*ZD36*conjg(ZD66)* &
      Sin(TWp))
   G_z_1_sd6_sd4c = (0,-1)*((0,0.5_default)*g2*ZD41*conjg(ZD61)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD42*conjg(ZD62)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD43* &
      conjg(ZD63)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD41*conjg(ZD61)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD42*conjg(ZD62)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD43*conjg(ZD63)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD44*conjg(ZD64)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD45* &
      conjg(ZD65)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD46*conjg(ZD66)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD41*conjg(ZD61)*Sin(TWp) - (0,1)*gp*Qq*ZD42*conjg( &
      ZD62)*Sin(TWp) - (0,1)*gp*Qq*ZD43*conjg(ZD63)*Sin(TWp) + (0,1)*gp*Qd*ZD44*conjg(ZD64 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD45*conjg(ZD65)*Sin(TWp) + (0,1)*gp*Qd*ZD46*conjg(ZD66)* &
      Sin(TWp))
   G_z_1_sd6_sd5c = (0,-1)*((0,0.5_default)*g2*ZD51*conjg(ZD61)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD52*conjg(ZD62)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD53* &
      conjg(ZD63)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD51*conjg(ZD61)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD52*conjg(ZD62)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD53*conjg(ZD63)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD54*conjg(ZD64)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD55* &
      conjg(ZD65)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD56*conjg(ZD66)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD51*conjg(ZD61)*Sin(TWp) - (0,1)*gp*Qq*ZD52*conjg( &
      ZD62)*Sin(TWp) - (0,1)*gp*Qq*ZD53*conjg(ZD63)*Sin(TWp) + (0,1)*gp*Qd*ZD54*conjg(ZD64 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD55*conjg(ZD65)*Sin(TWp) + (0,1)*gp*Qd*ZD56*conjg(ZD66)* &
      Sin(TWp))
   G_z_1_sd6_sd6c = (0,-1)*((0,0.5_default)*g2*ZD61*conjg(ZD61)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZD62*conjg(ZD62)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZD63* &
      conjg(ZD63)*Cos(TW)*Cos(TWp) + (0,0.16666666666666666_default)*g1*ZD61*conjg(ZD61)* &
      Cos(TWp)*Sin(TW) + (0,0.16666666666666666_default)*g1*ZD62*conjg(ZD62)*Cos(TWp)*Sin &
      (TW) + (0,0.16666666666666666_default)*g1*ZD63*conjg(ZD63)*Cos(TWp)*Sin(TW) - (0, &
      0.3333333333333333_default)*g1*ZD64*conjg(ZD64)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD65* &
      conjg(ZD65)*Cos(TWp)*Sin(TW) - (0,0.3333333333333333_default)*g1*ZD66*conjg(ZD66)*Cos &
      (TWp)*Sin(TW) - (0,1)*gp*Qq*ZD61*conjg(ZD61)*Sin(TWp) - (0,1)*gp*Qq*ZD62*conjg( &
      ZD62)*Sin(TWp) - (0,1)*gp*Qq*ZD63*conjg(ZD63)*Sin(TWp) + (0,1)*gp*Qd*ZD64*conjg(ZD64 &
      )*Sin(TWp) + (0,1)*gp*Qd*ZD65*conjg(ZD65)*Sin(TWp) + (0,1)*gp*Qd*ZD66*conjg(ZD66)* &
      Sin(TWp))
   G_zp_1_sd1_sd1c = (0,-1)*((0,-1)*gp*Qq*ZD11*conjg(ZD11)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD12*conjg(ZD12)*Cos(TWp) - (0,1)*gp*Qq*ZD13*conjg(ZD13)*Cos(TWp) + (0,1)*gp*Qd*ZD14 &
      *conjg(ZD14)*Cos(TWp) + (0,1)*gp*Qd*ZD15*conjg(ZD15)*Cos(TWp) + (0,1)*gp*Qd*ZD16* &
      conjg(ZD16)*Cos(TWp) - (0,0.5_default)*g2*ZD11*conjg(ZD11)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD12*conjg(ZD12)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD13*conjg(ZD13)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD11*conjg(ZD11)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD12*conjg(ZD12)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD13*conjg(ZD13)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD14* &
      conjg(ZD14)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD15*conjg(ZD15)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD16*conjg(ZD16)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd1_sd2c = (0,-1)*((0,-1)*gp*Qq*ZD21*conjg(ZD11)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD22*conjg(ZD12)*Cos(TWp) - (0,1)*gp*Qq*ZD23*conjg(ZD13)*Cos(TWp) + (0,1)*gp*Qd*ZD24 &
      *conjg(ZD14)*Cos(TWp) + (0,1)*gp*Qd*ZD25*conjg(ZD15)*Cos(TWp) + (0,1)*gp*Qd*ZD26* &
      conjg(ZD16)*Cos(TWp) - (0,0.5_default)*g2*ZD21*conjg(ZD11)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD22*conjg(ZD12)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD23*conjg(ZD13)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD21*conjg(ZD11)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD22*conjg(ZD12)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD23*conjg(ZD13)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD24* &
      conjg(ZD14)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD25*conjg(ZD15)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD26*conjg(ZD16)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd1_sd3c = (0,-1)*((0,-1)*gp*Qq*ZD31*conjg(ZD11)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD32*conjg(ZD12)*Cos(TWp) - (0,1)*gp*Qq*ZD33*conjg(ZD13)*Cos(TWp) + (0,1)*gp*Qd*ZD34 &
      *conjg(ZD14)*Cos(TWp) + (0,1)*gp*Qd*ZD35*conjg(ZD15)*Cos(TWp) + (0,1)*gp*Qd*ZD36* &
      conjg(ZD16)*Cos(TWp) - (0,0.5_default)*g2*ZD31*conjg(ZD11)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD32*conjg(ZD12)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD33*conjg(ZD13)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD31*conjg(ZD11)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD32*conjg(ZD12)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD33*conjg(ZD13)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD34* &
      conjg(ZD14)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD35*conjg(ZD15)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD36*conjg(ZD16)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd1_sd4c = (0,-1)*((0,-1)*gp*Qq*ZD41*conjg(ZD11)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD42*conjg(ZD12)*Cos(TWp) - (0,1)*gp*Qq*ZD43*conjg(ZD13)*Cos(TWp) + (0,1)*gp*Qd*ZD44 &
      *conjg(ZD14)*Cos(TWp) + (0,1)*gp*Qd*ZD45*conjg(ZD15)*Cos(TWp) + (0,1)*gp*Qd*ZD46* &
      conjg(ZD16)*Cos(TWp) - (0,0.5_default)*g2*ZD41*conjg(ZD11)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD42*conjg(ZD12)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD43*conjg(ZD13)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD41*conjg(ZD11)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD42*conjg(ZD12)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD43*conjg(ZD13)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD44* &
      conjg(ZD14)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD45*conjg(ZD15)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD46*conjg(ZD16)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd1_sd5c = (0,-1)*((0,-1)*gp*Qq*ZD51*conjg(ZD11)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD52*conjg(ZD12)*Cos(TWp) - (0,1)*gp*Qq*ZD53*conjg(ZD13)*Cos(TWp) + (0,1)*gp*Qd*ZD54 &
      *conjg(ZD14)*Cos(TWp) + (0,1)*gp*Qd*ZD55*conjg(ZD15)*Cos(TWp) + (0,1)*gp*Qd*ZD56* &
      conjg(ZD16)*Cos(TWp) - (0,0.5_default)*g2*ZD51*conjg(ZD11)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD52*conjg(ZD12)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD53*conjg(ZD13)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD51*conjg(ZD11)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD52*conjg(ZD12)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD53*conjg(ZD13)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD54* &
      conjg(ZD14)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD55*conjg(ZD15)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD56*conjg(ZD16)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd1_sd6c = (0,-1)*((0,-1)*gp*Qq*ZD61*conjg(ZD11)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD62*conjg(ZD12)*Cos(TWp) - (0,1)*gp*Qq*ZD63*conjg(ZD13)*Cos(TWp) + (0,1)*gp*Qd*ZD64 &
      *conjg(ZD14)*Cos(TWp) + (0,1)*gp*Qd*ZD65*conjg(ZD15)*Cos(TWp) + (0,1)*gp*Qd*ZD66* &
      conjg(ZD16)*Cos(TWp) - (0,0.5_default)*g2*ZD61*conjg(ZD11)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD62*conjg(ZD12)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD63*conjg(ZD13)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD61*conjg(ZD11)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD62*conjg(ZD12)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD63*conjg(ZD13)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD64* &
      conjg(ZD14)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD65*conjg(ZD15)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD66*conjg(ZD16)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd2_sd1c = (0,-1)*((0,-1)*gp*Qq*ZD11*conjg(ZD21)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD12*conjg(ZD22)*Cos(TWp) - (0,1)*gp*Qq*ZD13*conjg(ZD23)*Cos(TWp) + (0,1)*gp*Qd*ZD14 &
      *conjg(ZD24)*Cos(TWp) + (0,1)*gp*Qd*ZD15*conjg(ZD25)*Cos(TWp) + (0,1)*gp*Qd*ZD16* &
      conjg(ZD26)*Cos(TWp) - (0,0.5_default)*g2*ZD11*conjg(ZD21)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD12*conjg(ZD22)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD13*conjg(ZD23)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD11*conjg(ZD21)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD12*conjg(ZD22)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD13*conjg(ZD23)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD14* &
      conjg(ZD24)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD15*conjg(ZD25)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD16*conjg(ZD26)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd2_sd2c = (0,-1)*((0,-1)*gp*Qq*ZD21*conjg(ZD21)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD22*conjg(ZD22)*Cos(TWp) - (0,1)*gp*Qq*ZD23*conjg(ZD23)*Cos(TWp) + (0,1)*gp*Qd*ZD24 &
      *conjg(ZD24)*Cos(TWp) + (0,1)*gp*Qd*ZD25*conjg(ZD25)*Cos(TWp) + (0,1)*gp*Qd*ZD26* &
      conjg(ZD26)*Cos(TWp) - (0,0.5_default)*g2*ZD21*conjg(ZD21)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD22*conjg(ZD22)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD23*conjg(ZD23)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD21*conjg(ZD21)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD22*conjg(ZD22)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD23*conjg(ZD23)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD24* &
      conjg(ZD24)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD25*conjg(ZD25)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD26*conjg(ZD26)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd2_sd3c = (0,-1)*((0,-1)*gp*Qq*ZD31*conjg(ZD21)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD32*conjg(ZD22)*Cos(TWp) - (0,1)*gp*Qq*ZD33*conjg(ZD23)*Cos(TWp) + (0,1)*gp*Qd*ZD34 &
      *conjg(ZD24)*Cos(TWp) + (0,1)*gp*Qd*ZD35*conjg(ZD25)*Cos(TWp) + (0,1)*gp*Qd*ZD36* &
      conjg(ZD26)*Cos(TWp) - (0,0.5_default)*g2*ZD31*conjg(ZD21)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD32*conjg(ZD22)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD33*conjg(ZD23)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD31*conjg(ZD21)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD32*conjg(ZD22)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD33*conjg(ZD23)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD34* &
      conjg(ZD24)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD35*conjg(ZD25)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD36*conjg(ZD26)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd2_sd4c = (0,-1)*((0,-1)*gp*Qq*ZD41*conjg(ZD21)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD42*conjg(ZD22)*Cos(TWp) - (0,1)*gp*Qq*ZD43*conjg(ZD23)*Cos(TWp) + (0,1)*gp*Qd*ZD44 &
      *conjg(ZD24)*Cos(TWp) + (0,1)*gp*Qd*ZD45*conjg(ZD25)*Cos(TWp) + (0,1)*gp*Qd*ZD46* &
      conjg(ZD26)*Cos(TWp) - (0,0.5_default)*g2*ZD41*conjg(ZD21)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD42*conjg(ZD22)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD43*conjg(ZD23)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD41*conjg(ZD21)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD42*conjg(ZD22)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD43*conjg(ZD23)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD44* &
      conjg(ZD24)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD45*conjg(ZD25)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD46*conjg(ZD26)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd2_sd5c = (0,-1)*((0,-1)*gp*Qq*ZD51*conjg(ZD21)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD52*conjg(ZD22)*Cos(TWp) - (0,1)*gp*Qq*ZD53*conjg(ZD23)*Cos(TWp) + (0,1)*gp*Qd*ZD54 &
      *conjg(ZD24)*Cos(TWp) + (0,1)*gp*Qd*ZD55*conjg(ZD25)*Cos(TWp) + (0,1)*gp*Qd*ZD56* &
      conjg(ZD26)*Cos(TWp) - (0,0.5_default)*g2*ZD51*conjg(ZD21)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD52*conjg(ZD22)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD53*conjg(ZD23)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD51*conjg(ZD21)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD52*conjg(ZD22)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD53*conjg(ZD23)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD54* &
      conjg(ZD24)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD55*conjg(ZD25)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD56*conjg(ZD26)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd2_sd6c = (0,-1)*((0,-1)*gp*Qq*ZD61*conjg(ZD21)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD62*conjg(ZD22)*Cos(TWp) - (0,1)*gp*Qq*ZD63*conjg(ZD23)*Cos(TWp) + (0,1)*gp*Qd*ZD64 &
      *conjg(ZD24)*Cos(TWp) + (0,1)*gp*Qd*ZD65*conjg(ZD25)*Cos(TWp) + (0,1)*gp*Qd*ZD66* &
      conjg(ZD26)*Cos(TWp) - (0,0.5_default)*g2*ZD61*conjg(ZD21)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD62*conjg(ZD22)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD63*conjg(ZD23)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD61*conjg(ZD21)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD62*conjg(ZD22)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD63*conjg(ZD23)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD64* &
      conjg(ZD24)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD65*conjg(ZD25)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD66*conjg(ZD26)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd3_sd1c = (0,-1)*((0,-1)*gp*Qq*ZD11*conjg(ZD31)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD12*conjg(ZD32)*Cos(TWp) - (0,1)*gp*Qq*ZD13*conjg(ZD33)*Cos(TWp) + (0,1)*gp*Qd*ZD14 &
      *conjg(ZD34)*Cos(TWp) + (0,1)*gp*Qd*ZD15*conjg(ZD35)*Cos(TWp) + (0,1)*gp*Qd*ZD16* &
      conjg(ZD36)*Cos(TWp) - (0,0.5_default)*g2*ZD11*conjg(ZD31)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD12*conjg(ZD32)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD13*conjg(ZD33)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD11*conjg(ZD31)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD12*conjg(ZD32)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD13*conjg(ZD33)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD14* &
      conjg(ZD34)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD15*conjg(ZD35)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD16*conjg(ZD36)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd3_sd2c = (0,-1)*((0,-1)*gp*Qq*ZD21*conjg(ZD31)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD22*conjg(ZD32)*Cos(TWp) - (0,1)*gp*Qq*ZD23*conjg(ZD33)*Cos(TWp) + (0,1)*gp*Qd*ZD24 &
      *conjg(ZD34)*Cos(TWp) + (0,1)*gp*Qd*ZD25*conjg(ZD35)*Cos(TWp) + (0,1)*gp*Qd*ZD26* &
      conjg(ZD36)*Cos(TWp) - (0,0.5_default)*g2*ZD21*conjg(ZD31)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD22*conjg(ZD32)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD23*conjg(ZD33)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD21*conjg(ZD31)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD22*conjg(ZD32)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD23*conjg(ZD33)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD24* &
      conjg(ZD34)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD25*conjg(ZD35)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD26*conjg(ZD36)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd3_sd3c = (0,-1)*((0,-1)*gp*Qq*ZD31*conjg(ZD31)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD32*conjg(ZD32)*Cos(TWp) - (0,1)*gp*Qq*ZD33*conjg(ZD33)*Cos(TWp) + (0,1)*gp*Qd*ZD34 &
      *conjg(ZD34)*Cos(TWp) + (0,1)*gp*Qd*ZD35*conjg(ZD35)*Cos(TWp) + (0,1)*gp*Qd*ZD36* &
      conjg(ZD36)*Cos(TWp) - (0,0.5_default)*g2*ZD31*conjg(ZD31)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD32*conjg(ZD32)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD33*conjg(ZD33)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD31*conjg(ZD31)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD32*conjg(ZD32)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD33*conjg(ZD33)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD34* &
      conjg(ZD34)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD35*conjg(ZD35)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD36*conjg(ZD36)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd3_sd4c = (0,-1)*((0,-1)*gp*Qq*ZD41*conjg(ZD31)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD42*conjg(ZD32)*Cos(TWp) - (0,1)*gp*Qq*ZD43*conjg(ZD33)*Cos(TWp) + (0,1)*gp*Qd*ZD44 &
      *conjg(ZD34)*Cos(TWp) + (0,1)*gp*Qd*ZD45*conjg(ZD35)*Cos(TWp) + (0,1)*gp*Qd*ZD46* &
      conjg(ZD36)*Cos(TWp) - (0,0.5_default)*g2*ZD41*conjg(ZD31)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD42*conjg(ZD32)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD43*conjg(ZD33)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD41*conjg(ZD31)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD42*conjg(ZD32)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD43*conjg(ZD33)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD44* &
      conjg(ZD34)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD45*conjg(ZD35)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD46*conjg(ZD36)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd3_sd5c = (0,-1)*((0,-1)*gp*Qq*ZD51*conjg(ZD31)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD52*conjg(ZD32)*Cos(TWp) - (0,1)*gp*Qq*ZD53*conjg(ZD33)*Cos(TWp) + (0,1)*gp*Qd*ZD54 &
      *conjg(ZD34)*Cos(TWp) + (0,1)*gp*Qd*ZD55*conjg(ZD35)*Cos(TWp) + (0,1)*gp*Qd*ZD56* &
      conjg(ZD36)*Cos(TWp) - (0,0.5_default)*g2*ZD51*conjg(ZD31)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD52*conjg(ZD32)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD53*conjg(ZD33)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD51*conjg(ZD31)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD52*conjg(ZD32)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD53*conjg(ZD33)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD54* &
      conjg(ZD34)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD55*conjg(ZD35)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD56*conjg(ZD36)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd3_sd6c = (0,-1)*((0,-1)*gp*Qq*ZD61*conjg(ZD31)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD62*conjg(ZD32)*Cos(TWp) - (0,1)*gp*Qq*ZD63*conjg(ZD33)*Cos(TWp) + (0,1)*gp*Qd*ZD64 &
      *conjg(ZD34)*Cos(TWp) + (0,1)*gp*Qd*ZD65*conjg(ZD35)*Cos(TWp) + (0,1)*gp*Qd*ZD66* &
      conjg(ZD36)*Cos(TWp) - (0,0.5_default)*g2*ZD61*conjg(ZD31)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD62*conjg(ZD32)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD63*conjg(ZD33)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD61*conjg(ZD31)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD62*conjg(ZD32)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD63*conjg(ZD33)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD64* &
      conjg(ZD34)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD65*conjg(ZD35)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD66*conjg(ZD36)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd4_sd1c = (0,-1)*((0,-1)*gp*Qq*ZD11*conjg(ZD41)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD12*conjg(ZD42)*Cos(TWp) - (0,1)*gp*Qq*ZD13*conjg(ZD43)*Cos(TWp) + (0,1)*gp*Qd*ZD14 &
      *conjg(ZD44)*Cos(TWp) + (0,1)*gp*Qd*ZD15*conjg(ZD45)*Cos(TWp) + (0,1)*gp*Qd*ZD16* &
      conjg(ZD46)*Cos(TWp) - (0,0.5_default)*g2*ZD11*conjg(ZD41)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD12*conjg(ZD42)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD13*conjg(ZD43)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD11*conjg(ZD41)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD12*conjg(ZD42)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD13*conjg(ZD43)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD14* &
      conjg(ZD44)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD15*conjg(ZD45)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD16*conjg(ZD46)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd4_sd2c = (0,-1)*((0,-1)*gp*Qq*ZD21*conjg(ZD41)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD22*conjg(ZD42)*Cos(TWp) - (0,1)*gp*Qq*ZD23*conjg(ZD43)*Cos(TWp) + (0,1)*gp*Qd*ZD24 &
      *conjg(ZD44)*Cos(TWp) + (0,1)*gp*Qd*ZD25*conjg(ZD45)*Cos(TWp) + (0,1)*gp*Qd*ZD26* &
      conjg(ZD46)*Cos(TWp) - (0,0.5_default)*g2*ZD21*conjg(ZD41)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD22*conjg(ZD42)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD23*conjg(ZD43)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD21*conjg(ZD41)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD22*conjg(ZD42)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD23*conjg(ZD43)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD24* &
      conjg(ZD44)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD25*conjg(ZD45)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD26*conjg(ZD46)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd4_sd3c = (0,-1)*((0,-1)*gp*Qq*ZD31*conjg(ZD41)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD32*conjg(ZD42)*Cos(TWp) - (0,1)*gp*Qq*ZD33*conjg(ZD43)*Cos(TWp) + (0,1)*gp*Qd*ZD34 &
      *conjg(ZD44)*Cos(TWp) + (0,1)*gp*Qd*ZD35*conjg(ZD45)*Cos(TWp) + (0,1)*gp*Qd*ZD36* &
      conjg(ZD46)*Cos(TWp) - (0,0.5_default)*g2*ZD31*conjg(ZD41)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD32*conjg(ZD42)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD33*conjg(ZD43)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD31*conjg(ZD41)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD32*conjg(ZD42)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD33*conjg(ZD43)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD34* &
      conjg(ZD44)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD35*conjg(ZD45)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD36*conjg(ZD46)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd4_sd4c = (0,-1)*((0,-1)*gp*Qq*ZD41*conjg(ZD41)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD42*conjg(ZD42)*Cos(TWp) - (0,1)*gp*Qq*ZD43*conjg(ZD43)*Cos(TWp) + (0,1)*gp*Qd*ZD44 &
      *conjg(ZD44)*Cos(TWp) + (0,1)*gp*Qd*ZD45*conjg(ZD45)*Cos(TWp) + (0,1)*gp*Qd*ZD46* &
      conjg(ZD46)*Cos(TWp) - (0,0.5_default)*g2*ZD41*conjg(ZD41)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD42*conjg(ZD42)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD43*conjg(ZD43)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD41*conjg(ZD41)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD42*conjg(ZD42)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD43*conjg(ZD43)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD44* &
      conjg(ZD44)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD45*conjg(ZD45)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD46*conjg(ZD46)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd4_sd5c = (0,-1)*((0,-1)*gp*Qq*ZD51*conjg(ZD41)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD52*conjg(ZD42)*Cos(TWp) - (0,1)*gp*Qq*ZD53*conjg(ZD43)*Cos(TWp) + (0,1)*gp*Qd*ZD54 &
      *conjg(ZD44)*Cos(TWp) + (0,1)*gp*Qd*ZD55*conjg(ZD45)*Cos(TWp) + (0,1)*gp*Qd*ZD56* &
      conjg(ZD46)*Cos(TWp) - (0,0.5_default)*g2*ZD51*conjg(ZD41)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD52*conjg(ZD42)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD53*conjg(ZD43)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD51*conjg(ZD41)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD52*conjg(ZD42)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD53*conjg(ZD43)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD54* &
      conjg(ZD44)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD55*conjg(ZD45)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD56*conjg(ZD46)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd4_sd6c = (0,-1)*((0,-1)*gp*Qq*ZD61*conjg(ZD41)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD62*conjg(ZD42)*Cos(TWp) - (0,1)*gp*Qq*ZD63*conjg(ZD43)*Cos(TWp) + (0,1)*gp*Qd*ZD64 &
      *conjg(ZD44)*Cos(TWp) + (0,1)*gp*Qd*ZD65*conjg(ZD45)*Cos(TWp) + (0,1)*gp*Qd*ZD66* &
      conjg(ZD46)*Cos(TWp) - (0,0.5_default)*g2*ZD61*conjg(ZD41)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD62*conjg(ZD42)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD63*conjg(ZD43)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD61*conjg(ZD41)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD62*conjg(ZD42)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD63*conjg(ZD43)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD64* &
      conjg(ZD44)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD65*conjg(ZD45)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD66*conjg(ZD46)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd5_sd1c = (0,-1)*((0,-1)*gp*Qq*ZD11*conjg(ZD51)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD12*conjg(ZD52)*Cos(TWp) - (0,1)*gp*Qq*ZD13*conjg(ZD53)*Cos(TWp) + (0,1)*gp*Qd*ZD14 &
      *conjg(ZD54)*Cos(TWp) + (0,1)*gp*Qd*ZD15*conjg(ZD55)*Cos(TWp) + (0,1)*gp*Qd*ZD16* &
      conjg(ZD56)*Cos(TWp) - (0,0.5_default)*g2*ZD11*conjg(ZD51)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD12*conjg(ZD52)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD13*conjg(ZD53)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD11*conjg(ZD51)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD12*conjg(ZD52)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD13*conjg(ZD53)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD14* &
      conjg(ZD54)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD15*conjg(ZD55)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD16*conjg(ZD56)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd5_sd2c = (0,-1)*((0,-1)*gp*Qq*ZD21*conjg(ZD51)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD22*conjg(ZD52)*Cos(TWp) - (0,1)*gp*Qq*ZD23*conjg(ZD53)*Cos(TWp) + (0,1)*gp*Qd*ZD24 &
      *conjg(ZD54)*Cos(TWp) + (0,1)*gp*Qd*ZD25*conjg(ZD55)*Cos(TWp) + (0,1)*gp*Qd*ZD26* &
      conjg(ZD56)*Cos(TWp) - (0,0.5_default)*g2*ZD21*conjg(ZD51)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD22*conjg(ZD52)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD23*conjg(ZD53)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD21*conjg(ZD51)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD22*conjg(ZD52)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD23*conjg(ZD53)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD24* &
      conjg(ZD54)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD25*conjg(ZD55)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD26*conjg(ZD56)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd5_sd3c = (0,-1)*((0,-1)*gp*Qq*ZD31*conjg(ZD51)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD32*conjg(ZD52)*Cos(TWp) - (0,1)*gp*Qq*ZD33*conjg(ZD53)*Cos(TWp) + (0,1)*gp*Qd*ZD34 &
      *conjg(ZD54)*Cos(TWp) + (0,1)*gp*Qd*ZD35*conjg(ZD55)*Cos(TWp) + (0,1)*gp*Qd*ZD36* &
      conjg(ZD56)*Cos(TWp) - (0,0.5_default)*g2*ZD31*conjg(ZD51)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD32*conjg(ZD52)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD33*conjg(ZD53)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD31*conjg(ZD51)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD32*conjg(ZD52)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD33*conjg(ZD53)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD34* &
      conjg(ZD54)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD35*conjg(ZD55)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD36*conjg(ZD56)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd5_sd4c = (0,-1)*((0,-1)*gp*Qq*ZD41*conjg(ZD51)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD42*conjg(ZD52)*Cos(TWp) - (0,1)*gp*Qq*ZD43*conjg(ZD53)*Cos(TWp) + (0,1)*gp*Qd*ZD44 &
      *conjg(ZD54)*Cos(TWp) + (0,1)*gp*Qd*ZD45*conjg(ZD55)*Cos(TWp) + (0,1)*gp*Qd*ZD46* &
      conjg(ZD56)*Cos(TWp) - (0,0.5_default)*g2*ZD41*conjg(ZD51)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD42*conjg(ZD52)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD43*conjg(ZD53)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD41*conjg(ZD51)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD42*conjg(ZD52)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD43*conjg(ZD53)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD44* &
      conjg(ZD54)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD45*conjg(ZD55)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD46*conjg(ZD56)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd5_sd5c = (0,-1)*((0,-1)*gp*Qq*ZD51*conjg(ZD51)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD52*conjg(ZD52)*Cos(TWp) - (0,1)*gp*Qq*ZD53*conjg(ZD53)*Cos(TWp) + (0,1)*gp*Qd*ZD54 &
      *conjg(ZD54)*Cos(TWp) + (0,1)*gp*Qd*ZD55*conjg(ZD55)*Cos(TWp) + (0,1)*gp*Qd*ZD56* &
      conjg(ZD56)*Cos(TWp) - (0,0.5_default)*g2*ZD51*conjg(ZD51)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD52*conjg(ZD52)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD53*conjg(ZD53)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD51*conjg(ZD51)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD52*conjg(ZD52)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD53*conjg(ZD53)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD54* &
      conjg(ZD54)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD55*conjg(ZD55)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD56*conjg(ZD56)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd5_sd6c = (0,-1)*((0,-1)*gp*Qq*ZD61*conjg(ZD51)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD62*conjg(ZD52)*Cos(TWp) - (0,1)*gp*Qq*ZD63*conjg(ZD53)*Cos(TWp) + (0,1)*gp*Qd*ZD64 &
      *conjg(ZD54)*Cos(TWp) + (0,1)*gp*Qd*ZD65*conjg(ZD55)*Cos(TWp) + (0,1)*gp*Qd*ZD66* &
      conjg(ZD56)*Cos(TWp) - (0,0.5_default)*g2*ZD61*conjg(ZD51)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD62*conjg(ZD52)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD63*conjg(ZD53)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD61*conjg(ZD51)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD62*conjg(ZD52)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD63*conjg(ZD53)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD64* &
      conjg(ZD54)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD65*conjg(ZD55)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD66*conjg(ZD56)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd6_sd1c = (0,-1)*((0,-1)*gp*Qq*ZD11*conjg(ZD61)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD12*conjg(ZD62)*Cos(TWp) - (0,1)*gp*Qq*ZD13*conjg(ZD63)*Cos(TWp) + (0,1)*gp*Qd*ZD14 &
      *conjg(ZD64)*Cos(TWp) + (0,1)*gp*Qd*ZD15*conjg(ZD65)*Cos(TWp) + (0,1)*gp*Qd*ZD16* &
      conjg(ZD66)*Cos(TWp) - (0,0.5_default)*g2*ZD11*conjg(ZD61)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD12*conjg(ZD62)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD13*conjg(ZD63)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD11*conjg(ZD61)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD12*conjg(ZD62)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD13*conjg(ZD63)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD14* &
      conjg(ZD64)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD15*conjg(ZD65)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD16*conjg(ZD66)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd6_sd2c = (0,-1)*((0,-1)*gp*Qq*ZD21*conjg(ZD61)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD22*conjg(ZD62)*Cos(TWp) - (0,1)*gp*Qq*ZD23*conjg(ZD63)*Cos(TWp) + (0,1)*gp*Qd*ZD24 &
      *conjg(ZD64)*Cos(TWp) + (0,1)*gp*Qd*ZD25*conjg(ZD65)*Cos(TWp) + (0,1)*gp*Qd*ZD26* &
      conjg(ZD66)*Cos(TWp) - (0,0.5_default)*g2*ZD21*conjg(ZD61)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD22*conjg(ZD62)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD23*conjg(ZD63)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD21*conjg(ZD61)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD22*conjg(ZD62)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD23*conjg(ZD63)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD24* &
      conjg(ZD64)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD25*conjg(ZD65)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD26*conjg(ZD66)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd6_sd3c = (0,-1)*((0,-1)*gp*Qq*ZD31*conjg(ZD61)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD32*conjg(ZD62)*Cos(TWp) - (0,1)*gp*Qq*ZD33*conjg(ZD63)*Cos(TWp) + (0,1)*gp*Qd*ZD34 &
      *conjg(ZD64)*Cos(TWp) + (0,1)*gp*Qd*ZD35*conjg(ZD65)*Cos(TWp) + (0,1)*gp*Qd*ZD36* &
      conjg(ZD66)*Cos(TWp) - (0,0.5_default)*g2*ZD31*conjg(ZD61)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD32*conjg(ZD62)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD33*conjg(ZD63)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD31*conjg(ZD61)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD32*conjg(ZD62)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD33*conjg(ZD63)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD34* &
      conjg(ZD64)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD35*conjg(ZD65)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD36*conjg(ZD66)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd6_sd4c = (0,-1)*((0,-1)*gp*Qq*ZD41*conjg(ZD61)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD42*conjg(ZD62)*Cos(TWp) - (0,1)*gp*Qq*ZD43*conjg(ZD63)*Cos(TWp) + (0,1)*gp*Qd*ZD44 &
      *conjg(ZD64)*Cos(TWp) + (0,1)*gp*Qd*ZD45*conjg(ZD65)*Cos(TWp) + (0,1)*gp*Qd*ZD46* &
      conjg(ZD66)*Cos(TWp) - (0,0.5_default)*g2*ZD41*conjg(ZD61)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD42*conjg(ZD62)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD43*conjg(ZD63)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD41*conjg(ZD61)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD42*conjg(ZD62)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD43*conjg(ZD63)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD44* &
      conjg(ZD64)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD45*conjg(ZD65)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD46*conjg(ZD66)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd6_sd5c = (0,-1)*((0,-1)*gp*Qq*ZD51*conjg(ZD61)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD52*conjg(ZD62)*Cos(TWp) - (0,1)*gp*Qq*ZD53*conjg(ZD63)*Cos(TWp) + (0,1)*gp*Qd*ZD54 &
      *conjg(ZD64)*Cos(TWp) + (0,1)*gp*Qd*ZD55*conjg(ZD65)*Cos(TWp) + (0,1)*gp*Qd*ZD56* &
      conjg(ZD66)*Cos(TWp) - (0,0.5_default)*g2*ZD51*conjg(ZD61)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD52*conjg(ZD62)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD53*conjg(ZD63)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD51*conjg(ZD61)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD52*conjg(ZD62)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD53*conjg(ZD63)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD54* &
      conjg(ZD64)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD55*conjg(ZD65)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD56*conjg(ZD66)*Sin(TW)*Sin( &
      TWp))
   G_zp_1_sd6_sd6c = (0,-1)*((0,-1)*gp*Qq*ZD61*conjg(ZD61)*Cos(TWp) - (0,1)*gp*Qq* &
      ZD62*conjg(ZD62)*Cos(TWp) - (0,1)*gp*Qq*ZD63*conjg(ZD63)*Cos(TWp) + (0,1)*gp*Qd*ZD64 &
      *conjg(ZD64)*Cos(TWp) + (0,1)*gp*Qd*ZD65*conjg(ZD65)*Cos(TWp) + (0,1)*gp*Qd*ZD66* &
      conjg(ZD66)*Cos(TWp) - (0,0.5_default)*g2*ZD61*conjg(ZD61)*Cos(TW)*Sin(TWp) - (0, &
      0.5_default)*g2*ZD62*conjg(ZD62)*Cos(TW)*Sin(TWp) - (0,0.5_default)*g2*ZD63*conjg(ZD63)*Cos &
      (TW)*Sin(TWp) - (0,0.16666666666666666_default)*g1*ZD61*conjg(ZD61)*Sin(TW)*Sin( &
      TWp) - (0,0.16666666666666666_default)*g1*ZD62*conjg(ZD62)*Sin(TW)*Sin(TWp) - (0, &
      0.16666666666666666_default)*g1*ZD63*conjg(ZD63)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD64* &
      conjg(ZD64)*Sin(TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD65*conjg(ZD65)*Sin &
      (TW)*Sin(TWp) + (0,0.3333333333333333_default)*g1*ZD66*conjg(ZD66)*Sin(TW)*Sin( &
      TWp))
   G_wmc_sd1_su1c = (0,-1)*(((0,-1)*g2*ZU11*conjg(ZD11))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU12*conjg(ZD12))/Sqrt (2._default) - ((0,1)*g2*ZU13*conjg(ZD13))/Sqrt ( &
      2._default))
   G_wmc_sd1_su2c = (0,-1)*(((0,-1)*g2*ZU21*conjg(ZD11))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU22*conjg(ZD12))/Sqrt (2._default) - ((0,1)*g2*ZU23*conjg(ZD13))/Sqrt ( &
      2._default))
   G_wmc_sd1_su3c = (0,-1)*(((0,-1)*g2*ZU31*conjg(ZD11))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU32*conjg(ZD12))/Sqrt (2._default) - ((0,1)*g2*ZU33*conjg(ZD13))/Sqrt ( &
      2._default))
   G_wmc_sd1_su4c = (0,-1)*(((0,-1)*g2*ZU41*conjg(ZD11))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU42*conjg(ZD12))/Sqrt (2._default) - ((0,1)*g2*ZU43*conjg(ZD13))/Sqrt ( &
      2._default))
   G_wmc_sd1_su5c = (0,-1)*(((0,-1)*g2*ZU51*conjg(ZD11))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU52*conjg(ZD12))/Sqrt (2._default) - ((0,1)*g2*ZU53*conjg(ZD13))/Sqrt ( &
      2._default))
   G_wmc_sd1_su6c = (0,-1)*(((0,-1)*g2*ZU61*conjg(ZD11))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU62*conjg(ZD12))/Sqrt (2._default) - ((0,1)*g2*ZU63*conjg(ZD13))/Sqrt ( &
      2._default))
   G_wmc_sd2_su1c = (0,-1)*(((0,-1)*g2*ZU11*conjg(ZD21))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU12*conjg(ZD22))/Sqrt (2._default) - ((0,1)*g2*ZU13*conjg(ZD23))/Sqrt ( &
      2._default))
   G_wmc_sd2_su2c = (0,-1)*(((0,-1)*g2*ZU21*conjg(ZD21))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU22*conjg(ZD22))/Sqrt (2._default) - ((0,1)*g2*ZU23*conjg(ZD23))/Sqrt ( &
      2._default))
   G_wmc_sd2_su3c = (0,-1)*(((0,-1)*g2*ZU31*conjg(ZD21))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU32*conjg(ZD22))/Sqrt (2._default) - ((0,1)*g2*ZU33*conjg(ZD23))/Sqrt ( &
      2._default))
   G_wmc_sd2_su4c = (0,-1)*(((0,-1)*g2*ZU41*conjg(ZD21))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU42*conjg(ZD22))/Sqrt (2._default) - ((0,1)*g2*ZU43*conjg(ZD23))/Sqrt ( &
      2._default))
   G_wmc_sd2_su5c = (0,-1)*(((0,-1)*g2*ZU51*conjg(ZD21))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU52*conjg(ZD22))/Sqrt (2._default) - ((0,1)*g2*ZU53*conjg(ZD23))/Sqrt ( &
      2._default))
   G_wmc_sd2_su6c = (0,-1)*(((0,-1)*g2*ZU61*conjg(ZD21))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU62*conjg(ZD22))/Sqrt (2._default) - ((0,1)*g2*ZU63*conjg(ZD23))/Sqrt ( &
      2._default))
   G_wmc_sd3_su1c = (0,-1)*(((0,-1)*g2*ZU11*conjg(ZD31))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU12*conjg(ZD32))/Sqrt (2._default) - ((0,1)*g2*ZU13*conjg(ZD33))/Sqrt ( &
      2._default))
   G_wmc_sd3_su2c = (0,-1)*(((0,-1)*g2*ZU21*conjg(ZD31))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU22*conjg(ZD32))/Sqrt (2._default) - ((0,1)*g2*ZU23*conjg(ZD33))/Sqrt ( &
      2._default))
   G_wmc_sd3_su3c = (0,-1)*(((0,-1)*g2*ZU31*conjg(ZD31))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU32*conjg(ZD32))/Sqrt (2._default) - ((0,1)*g2*ZU33*conjg(ZD33))/Sqrt ( &
      2._default))
   G_wmc_sd3_su4c = (0,-1)*(((0,-1)*g2*ZU41*conjg(ZD31))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU42*conjg(ZD32))/Sqrt (2._default) - ((0,1)*g2*ZU43*conjg(ZD33))/Sqrt ( &
      2._default))
   G_wmc_sd3_su5c = (0,-1)*(((0,-1)*g2*ZU51*conjg(ZD31))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU52*conjg(ZD32))/Sqrt (2._default) - ((0,1)*g2*ZU53*conjg(ZD33))/Sqrt ( &
      2._default))
   G_wmc_sd3_su6c = (0,-1)*(((0,-1)*g2*ZU61*conjg(ZD31))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU62*conjg(ZD32))/Sqrt (2._default) - ((0,1)*g2*ZU63*conjg(ZD33))/Sqrt ( &
      2._default))
   G_wmc_sd4_su1c = (0,-1)*(((0,-1)*g2*ZU11*conjg(ZD41))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU12*conjg(ZD42))/Sqrt (2._default) - ((0,1)*g2*ZU13*conjg(ZD43))/Sqrt ( &
      2._default))
   G_wmc_sd4_su2c = (0,-1)*(((0,-1)*g2*ZU21*conjg(ZD41))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU22*conjg(ZD42))/Sqrt (2._default) - ((0,1)*g2*ZU23*conjg(ZD43))/Sqrt ( &
      2._default))
   G_wmc_sd4_su3c = (0,-1)*(((0,-1)*g2*ZU31*conjg(ZD41))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU32*conjg(ZD42))/Sqrt (2._default) - ((0,1)*g2*ZU33*conjg(ZD43))/Sqrt ( &
      2._default))
   G_wmc_sd4_su4c = (0,-1)*(((0,-1)*g2*ZU41*conjg(ZD41))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU42*conjg(ZD42))/Sqrt (2._default) - ((0,1)*g2*ZU43*conjg(ZD43))/Sqrt ( &
      2._default))
   G_wmc_sd4_su5c = (0,-1)*(((0,-1)*g2*ZU51*conjg(ZD41))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU52*conjg(ZD42))/Sqrt (2._default) - ((0,1)*g2*ZU53*conjg(ZD43))/Sqrt ( &
      2._default))
   G_wmc_sd4_su6c = (0,-1)*(((0,-1)*g2*ZU61*conjg(ZD41))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU62*conjg(ZD42))/Sqrt (2._default) - ((0,1)*g2*ZU63*conjg(ZD43))/Sqrt ( &
      2._default))
   G_wmc_sd5_su1c = (0,-1)*(((0,-1)*g2*ZU11*conjg(ZD51))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU12*conjg(ZD52))/Sqrt (2._default) - ((0,1)*g2*ZU13*conjg(ZD53))/Sqrt ( &
      2._default))
   G_wmc_sd5_su2c = (0,-1)*(((0,-1)*g2*ZU21*conjg(ZD51))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU22*conjg(ZD52))/Sqrt (2._default) - ((0,1)*g2*ZU23*conjg(ZD53))/Sqrt ( &
      2._default))
   G_wmc_sd5_su3c = (0,-1)*(((0,-1)*g2*ZU31*conjg(ZD51))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU32*conjg(ZD52))/Sqrt (2._default) - ((0,1)*g2*ZU33*conjg(ZD53))/Sqrt ( &
      2._default))
   G_wmc_sd5_su4c = (0,-1)*(((0,-1)*g2*ZU41*conjg(ZD51))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU42*conjg(ZD52))/Sqrt (2._default) - ((0,1)*g2*ZU43*conjg(ZD53))/Sqrt ( &
      2._default))
   G_wmc_sd5_su5c = (0,-1)*(((0,-1)*g2*ZU51*conjg(ZD51))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU52*conjg(ZD52))/Sqrt (2._default) - ((0,1)*g2*ZU53*conjg(ZD53))/Sqrt ( &
      2._default))
   G_wmc_sd5_su6c = (0,-1)*(((0,-1)*g2*ZU61*conjg(ZD51))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU62*conjg(ZD52))/Sqrt (2._default) - ((0,1)*g2*ZU63*conjg(ZD53))/Sqrt ( &
      2._default))
   G_wmc_sd6_su1c = (0,-1)*(((0,-1)*g2*ZU11*conjg(ZD61))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU12*conjg(ZD62))/Sqrt (2._default) - ((0,1)*g2*ZU13*conjg(ZD63))/Sqrt ( &
      2._default))
   G_wmc_sd6_su2c = (0,-1)*(((0,-1)*g2*ZU21*conjg(ZD61))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU22*conjg(ZD62))/Sqrt (2._default) - ((0,1)*g2*ZU23*conjg(ZD63))/Sqrt ( &
      2._default))
   G_wmc_sd6_su3c = (0,-1)*(((0,-1)*g2*ZU31*conjg(ZD61))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU32*conjg(ZD62))/Sqrt (2._default) - ((0,1)*g2*ZU33*conjg(ZD63))/Sqrt ( &
      2._default))
   G_wmc_sd6_su4c = (0,-1)*(((0,-1)*g2*ZU41*conjg(ZD61))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU42*conjg(ZD62))/Sqrt (2._default) - ((0,1)*g2*ZU43*conjg(ZD63))/Sqrt ( &
      2._default))
   G_wmc_sd6_su5c = (0,-1)*(((0,-1)*g2*ZU51*conjg(ZD61))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU52*conjg(ZD62))/Sqrt (2._default) - ((0,1)*g2*ZU53*conjg(ZD63))/Sqrt ( &
      2._default))
   G_wmc_sd6_su6c = (0,-1)*(((0,-1)*g2*ZU61*conjg(ZD61))/Sqrt (2._default) - ((0,1 &
      )*g2*ZU62*conjg(ZD62))/Sqrt (2._default) - ((0,1)*g2*ZU63*conjg(ZD63))/Sqrt ( &
      2._default))
   G_a_1_se1_se1c = (0,-1)*((0,0.5_default)*g1*ZE11*conjg(ZE11)*Cos(TW) + (0, &
      0.5_default)*g1*ZE12*conjg(ZE12)*Cos(TW) + (0,0.5_default)*g1*ZE13*conjg(ZE13)*Cos(TW) + (0 &
      ,1)*g1*ZE14*conjg(ZE14)*Cos(TW) + (0,1)*g1*ZE15*conjg(ZE15)*Cos(TW) + (0,1)*g1* &
      ZE16*conjg(ZE16)*Cos(TW) + (0,0.5_default)*g2*ZE11*conjg(ZE11)*Sin(TW) + (0, &
      0.5_default)*g2*ZE12*conjg(ZE12)*Sin(TW) + (0,0.5_default)*g2*ZE13*conjg(ZE13)*Sin(TW))
   G_a_1_se1_se2c = (0,-1)*((0,0.5_default)*g1*ZE21*conjg(ZE11)*Cos(TW) + (0, &
      0.5_default)*g1*ZE22*conjg(ZE12)*Cos(TW) + (0,0.5_default)*g1*ZE23*conjg(ZE13)*Cos(TW) + (0 &
      ,1)*g1*ZE24*conjg(ZE14)*Cos(TW) + (0,1)*g1*ZE25*conjg(ZE15)*Cos(TW) + (0,1)*g1* &
      ZE26*conjg(ZE16)*Cos(TW) + (0,0.5_default)*g2*ZE21*conjg(ZE11)*Sin(TW) + (0, &
      0.5_default)*g2*ZE22*conjg(ZE12)*Sin(TW) + (0,0.5_default)*g2*ZE23*conjg(ZE13)*Sin(TW))
   G_a_1_se1_se3c = (0,-1)*((0,0.5_default)*g1*ZE31*conjg(ZE11)*Cos(TW) + (0, &
      0.5_default)*g1*ZE32*conjg(ZE12)*Cos(TW) + (0,0.5_default)*g1*ZE33*conjg(ZE13)*Cos(TW) + (0 &
      ,1)*g1*ZE34*conjg(ZE14)*Cos(TW) + (0,1)*g1*ZE35*conjg(ZE15)*Cos(TW) + (0,1)*g1* &
      ZE36*conjg(ZE16)*Cos(TW) + (0,0.5_default)*g2*ZE31*conjg(ZE11)*Sin(TW) + (0, &
      0.5_default)*g2*ZE32*conjg(ZE12)*Sin(TW) + (0,0.5_default)*g2*ZE33*conjg(ZE13)*Sin(TW))
   G_a_1_se1_se4c = (0,-1)*((0,0.5_default)*g1*ZE41*conjg(ZE11)*Cos(TW) + (0, &
      0.5_default)*g1*ZE42*conjg(ZE12)*Cos(TW) + (0,0.5_default)*g1*ZE43*conjg(ZE13)*Cos(TW) + (0 &
      ,1)*g1*ZE44*conjg(ZE14)*Cos(TW) + (0,1)*g1*ZE45*conjg(ZE15)*Cos(TW) + (0,1)*g1* &
      ZE46*conjg(ZE16)*Cos(TW) + (0,0.5_default)*g2*ZE41*conjg(ZE11)*Sin(TW) + (0, &
      0.5_default)*g2*ZE42*conjg(ZE12)*Sin(TW) + (0,0.5_default)*g2*ZE43*conjg(ZE13)*Sin(TW))
   G_a_1_se1_se5c = (0,-1)*((0,0.5_default)*g1*ZE51*conjg(ZE11)*Cos(TW) + (0, &
      0.5_default)*g1*ZE52*conjg(ZE12)*Cos(TW) + (0,0.5_default)*g1*ZE53*conjg(ZE13)*Cos(TW) + (0 &
      ,1)*g1*ZE54*conjg(ZE14)*Cos(TW) + (0,1)*g1*ZE55*conjg(ZE15)*Cos(TW) + (0,1)*g1* &
      ZE56*conjg(ZE16)*Cos(TW) + (0,0.5_default)*g2*ZE51*conjg(ZE11)*Sin(TW) + (0, &
      0.5_default)*g2*ZE52*conjg(ZE12)*Sin(TW) + (0,0.5_default)*g2*ZE53*conjg(ZE13)*Sin(TW))
   G_a_1_se1_se6c = (0,-1)*((0,0.5_default)*g1*ZE61*conjg(ZE11)*Cos(TW) + (0, &
      0.5_default)*g1*ZE62*conjg(ZE12)*Cos(TW) + (0,0.5_default)*g1*ZE63*conjg(ZE13)*Cos(TW) + (0 &
      ,1)*g1*ZE64*conjg(ZE14)*Cos(TW) + (0,1)*g1*ZE65*conjg(ZE15)*Cos(TW) + (0,1)*g1* &
      ZE66*conjg(ZE16)*Cos(TW) + (0,0.5_default)*g2*ZE61*conjg(ZE11)*Sin(TW) + (0, &
      0.5_default)*g2*ZE62*conjg(ZE12)*Sin(TW) + (0,0.5_default)*g2*ZE63*conjg(ZE13)*Sin(TW))
   G_a_1_se2_se1c = (0,-1)*((0,0.5_default)*g1*ZE11*conjg(ZE21)*Cos(TW) + (0, &
      0.5_default)*g1*ZE12*conjg(ZE22)*Cos(TW) + (0,0.5_default)*g1*ZE13*conjg(ZE23)*Cos(TW) + (0 &
      ,1)*g1*ZE14*conjg(ZE24)*Cos(TW) + (0,1)*g1*ZE15*conjg(ZE25)*Cos(TW) + (0,1)*g1* &
      ZE16*conjg(ZE26)*Cos(TW) + (0,0.5_default)*g2*ZE11*conjg(ZE21)*Sin(TW) + (0, &
      0.5_default)*g2*ZE12*conjg(ZE22)*Sin(TW) + (0,0.5_default)*g2*ZE13*conjg(ZE23)*Sin(TW))
   G_a_1_se2_se2c = (0,-1)*((0,0.5_default)*g1*ZE21*conjg(ZE21)*Cos(TW) + (0, &
      0.5_default)*g1*ZE22*conjg(ZE22)*Cos(TW) + (0,0.5_default)*g1*ZE23*conjg(ZE23)*Cos(TW) + (0 &
      ,1)*g1*ZE24*conjg(ZE24)*Cos(TW) + (0,1)*g1*ZE25*conjg(ZE25)*Cos(TW) + (0,1)*g1* &
      ZE26*conjg(ZE26)*Cos(TW) + (0,0.5_default)*g2*ZE21*conjg(ZE21)*Sin(TW) + (0, &
      0.5_default)*g2*ZE22*conjg(ZE22)*Sin(TW) + (0,0.5_default)*g2*ZE23*conjg(ZE23)*Sin(TW))
   G_a_1_se2_se3c = (0,-1)*((0,0.5_default)*g1*ZE31*conjg(ZE21)*Cos(TW) + (0, &
      0.5_default)*g1*ZE32*conjg(ZE22)*Cos(TW) + (0,0.5_default)*g1*ZE33*conjg(ZE23)*Cos(TW) + (0 &
      ,1)*g1*ZE34*conjg(ZE24)*Cos(TW) + (0,1)*g1*ZE35*conjg(ZE25)*Cos(TW) + (0,1)*g1* &
      ZE36*conjg(ZE26)*Cos(TW) + (0,0.5_default)*g2*ZE31*conjg(ZE21)*Sin(TW) + (0, &
      0.5_default)*g2*ZE32*conjg(ZE22)*Sin(TW) + (0,0.5_default)*g2*ZE33*conjg(ZE23)*Sin(TW))
   G_a_1_se2_se4c = (0,-1)*((0,0.5_default)*g1*ZE41*conjg(ZE21)*Cos(TW) + (0, &
      0.5_default)*g1*ZE42*conjg(ZE22)*Cos(TW) + (0,0.5_default)*g1*ZE43*conjg(ZE23)*Cos(TW) + (0 &
      ,1)*g1*ZE44*conjg(ZE24)*Cos(TW) + (0,1)*g1*ZE45*conjg(ZE25)*Cos(TW) + (0,1)*g1* &
      ZE46*conjg(ZE26)*Cos(TW) + (0,0.5_default)*g2*ZE41*conjg(ZE21)*Sin(TW) + (0, &
      0.5_default)*g2*ZE42*conjg(ZE22)*Sin(TW) + (0,0.5_default)*g2*ZE43*conjg(ZE23)*Sin(TW))
   G_a_1_se2_se5c = (0,-1)*((0,0.5_default)*g1*ZE51*conjg(ZE21)*Cos(TW) + (0, &
      0.5_default)*g1*ZE52*conjg(ZE22)*Cos(TW) + (0,0.5_default)*g1*ZE53*conjg(ZE23)*Cos(TW) + (0 &
      ,1)*g1*ZE54*conjg(ZE24)*Cos(TW) + (0,1)*g1*ZE55*conjg(ZE25)*Cos(TW) + (0,1)*g1* &
      ZE56*conjg(ZE26)*Cos(TW) + (0,0.5_default)*g2*ZE51*conjg(ZE21)*Sin(TW) + (0, &
      0.5_default)*g2*ZE52*conjg(ZE22)*Sin(TW) + (0,0.5_default)*g2*ZE53*conjg(ZE23)*Sin(TW))
   G_a_1_se2_se6c = (0,-1)*((0,0.5_default)*g1*ZE61*conjg(ZE21)*Cos(TW) + (0, &
      0.5_default)*g1*ZE62*conjg(ZE22)*Cos(TW) + (0,0.5_default)*g1*ZE63*conjg(ZE23)*Cos(TW) + (0 &
      ,1)*g1*ZE64*conjg(ZE24)*Cos(TW) + (0,1)*g1*ZE65*conjg(ZE25)*Cos(TW) + (0,1)*g1* &
      ZE66*conjg(ZE26)*Cos(TW) + (0,0.5_default)*g2*ZE61*conjg(ZE21)*Sin(TW) + (0, &
      0.5_default)*g2*ZE62*conjg(ZE22)*Sin(TW) + (0,0.5_default)*g2*ZE63*conjg(ZE23)*Sin(TW))
   G_a_1_se3_se1c = (0,-1)*((0,0.5_default)*g1*ZE11*conjg(ZE31)*Cos(TW) + (0, &
      0.5_default)*g1*ZE12*conjg(ZE32)*Cos(TW) + (0,0.5_default)*g1*ZE13*conjg(ZE33)*Cos(TW) + (0 &
      ,1)*g1*ZE14*conjg(ZE34)*Cos(TW) + (0,1)*g1*ZE15*conjg(ZE35)*Cos(TW) + (0,1)*g1* &
      ZE16*conjg(ZE36)*Cos(TW) + (0,0.5_default)*g2*ZE11*conjg(ZE31)*Sin(TW) + (0, &
      0.5_default)*g2*ZE12*conjg(ZE32)*Sin(TW) + (0,0.5_default)*g2*ZE13*conjg(ZE33)*Sin(TW))
   G_a_1_se3_se2c = (0,-1)*((0,0.5_default)*g1*ZE21*conjg(ZE31)*Cos(TW) + (0, &
      0.5_default)*g1*ZE22*conjg(ZE32)*Cos(TW) + (0,0.5_default)*g1*ZE23*conjg(ZE33)*Cos(TW) + (0 &
      ,1)*g1*ZE24*conjg(ZE34)*Cos(TW) + (0,1)*g1*ZE25*conjg(ZE35)*Cos(TW) + (0,1)*g1* &
      ZE26*conjg(ZE36)*Cos(TW) + (0,0.5_default)*g2*ZE21*conjg(ZE31)*Sin(TW) + (0, &
      0.5_default)*g2*ZE22*conjg(ZE32)*Sin(TW) + (0,0.5_default)*g2*ZE23*conjg(ZE33)*Sin(TW))
   G_a_1_se3_se3c = (0,-1)*((0,0.5_default)*g1*ZE31*conjg(ZE31)*Cos(TW) + (0, &
      0.5_default)*g1*ZE32*conjg(ZE32)*Cos(TW) + (0,0.5_default)*g1*ZE33*conjg(ZE33)*Cos(TW) + (0 &
      ,1)*g1*ZE34*conjg(ZE34)*Cos(TW) + (0,1)*g1*ZE35*conjg(ZE35)*Cos(TW) + (0,1)*g1* &
      ZE36*conjg(ZE36)*Cos(TW) + (0,0.5_default)*g2*ZE31*conjg(ZE31)*Sin(TW) + (0, &
      0.5_default)*g2*ZE32*conjg(ZE32)*Sin(TW) + (0,0.5_default)*g2*ZE33*conjg(ZE33)*Sin(TW))
   G_a_1_se3_se4c = (0,-1)*((0,0.5_default)*g1*ZE41*conjg(ZE31)*Cos(TW) + (0, &
      0.5_default)*g1*ZE42*conjg(ZE32)*Cos(TW) + (0,0.5_default)*g1*ZE43*conjg(ZE33)*Cos(TW) + (0 &
      ,1)*g1*ZE44*conjg(ZE34)*Cos(TW) + (0,1)*g1*ZE45*conjg(ZE35)*Cos(TW) + (0,1)*g1* &
      ZE46*conjg(ZE36)*Cos(TW) + (0,0.5_default)*g2*ZE41*conjg(ZE31)*Sin(TW) + (0, &
      0.5_default)*g2*ZE42*conjg(ZE32)*Sin(TW) + (0,0.5_default)*g2*ZE43*conjg(ZE33)*Sin(TW))
   G_a_1_se3_se5c = (0,-1)*((0,0.5_default)*g1*ZE51*conjg(ZE31)*Cos(TW) + (0, &
      0.5_default)*g1*ZE52*conjg(ZE32)*Cos(TW) + (0,0.5_default)*g1*ZE53*conjg(ZE33)*Cos(TW) + (0 &
      ,1)*g1*ZE54*conjg(ZE34)*Cos(TW) + (0,1)*g1*ZE55*conjg(ZE35)*Cos(TW) + (0,1)*g1* &
      ZE56*conjg(ZE36)*Cos(TW) + (0,0.5_default)*g2*ZE51*conjg(ZE31)*Sin(TW) + (0, &
      0.5_default)*g2*ZE52*conjg(ZE32)*Sin(TW) + (0,0.5_default)*g2*ZE53*conjg(ZE33)*Sin(TW))
   G_a_1_se3_se6c = (0,-1)*((0,0.5_default)*g1*ZE61*conjg(ZE31)*Cos(TW) + (0, &
      0.5_default)*g1*ZE62*conjg(ZE32)*Cos(TW) + (0,0.5_default)*g1*ZE63*conjg(ZE33)*Cos(TW) + (0 &
      ,1)*g1*ZE64*conjg(ZE34)*Cos(TW) + (0,1)*g1*ZE65*conjg(ZE35)*Cos(TW) + (0,1)*g1* &
      ZE66*conjg(ZE36)*Cos(TW) + (0,0.5_default)*g2*ZE61*conjg(ZE31)*Sin(TW) + (0, &
      0.5_default)*g2*ZE62*conjg(ZE32)*Sin(TW) + (0,0.5_default)*g2*ZE63*conjg(ZE33)*Sin(TW))
   G_a_1_se4_se1c = (0,-1)*((0,0.5_default)*g1*ZE11*conjg(ZE41)*Cos(TW) + (0, &
      0.5_default)*g1*ZE12*conjg(ZE42)*Cos(TW) + (0,0.5_default)*g1*ZE13*conjg(ZE43)*Cos(TW) + (0 &
      ,1)*g1*ZE14*conjg(ZE44)*Cos(TW) + (0,1)*g1*ZE15*conjg(ZE45)*Cos(TW) + (0,1)*g1* &
      ZE16*conjg(ZE46)*Cos(TW) + (0,0.5_default)*g2*ZE11*conjg(ZE41)*Sin(TW) + (0, &
      0.5_default)*g2*ZE12*conjg(ZE42)*Sin(TW) + (0,0.5_default)*g2*ZE13*conjg(ZE43)*Sin(TW))
   G_a_1_se4_se2c = (0,-1)*((0,0.5_default)*g1*ZE21*conjg(ZE41)*Cos(TW) + (0, &
      0.5_default)*g1*ZE22*conjg(ZE42)*Cos(TW) + (0,0.5_default)*g1*ZE23*conjg(ZE43)*Cos(TW) + (0 &
      ,1)*g1*ZE24*conjg(ZE44)*Cos(TW) + (0,1)*g1*ZE25*conjg(ZE45)*Cos(TW) + (0,1)*g1* &
      ZE26*conjg(ZE46)*Cos(TW) + (0,0.5_default)*g2*ZE21*conjg(ZE41)*Sin(TW) + (0, &
      0.5_default)*g2*ZE22*conjg(ZE42)*Sin(TW) + (0,0.5_default)*g2*ZE23*conjg(ZE43)*Sin(TW))
   G_a_1_se4_se3c = (0,-1)*((0,0.5_default)*g1*ZE31*conjg(ZE41)*Cos(TW) + (0, &
      0.5_default)*g1*ZE32*conjg(ZE42)*Cos(TW) + (0,0.5_default)*g1*ZE33*conjg(ZE43)*Cos(TW) + (0 &
      ,1)*g1*ZE34*conjg(ZE44)*Cos(TW) + (0,1)*g1*ZE35*conjg(ZE45)*Cos(TW) + (0,1)*g1* &
      ZE36*conjg(ZE46)*Cos(TW) + (0,0.5_default)*g2*ZE31*conjg(ZE41)*Sin(TW) + (0, &
      0.5_default)*g2*ZE32*conjg(ZE42)*Sin(TW) + (0,0.5_default)*g2*ZE33*conjg(ZE43)*Sin(TW))
   G_a_1_se4_se4c = (0,-1)*((0,0.5_default)*g1*ZE41*conjg(ZE41)*Cos(TW) + (0, &
      0.5_default)*g1*ZE42*conjg(ZE42)*Cos(TW) + (0,0.5_default)*g1*ZE43*conjg(ZE43)*Cos(TW) + (0 &
      ,1)*g1*ZE44*conjg(ZE44)*Cos(TW) + (0,1)*g1*ZE45*conjg(ZE45)*Cos(TW) + (0,1)*g1* &
      ZE46*conjg(ZE46)*Cos(TW) + (0,0.5_default)*g2*ZE41*conjg(ZE41)*Sin(TW) + (0, &
      0.5_default)*g2*ZE42*conjg(ZE42)*Sin(TW) + (0,0.5_default)*g2*ZE43*conjg(ZE43)*Sin(TW))
   G_a_1_se4_se5c = (0,-1)*((0,0.5_default)*g1*ZE51*conjg(ZE41)*Cos(TW) + (0, &
      0.5_default)*g1*ZE52*conjg(ZE42)*Cos(TW) + (0,0.5_default)*g1*ZE53*conjg(ZE43)*Cos(TW) + (0 &
      ,1)*g1*ZE54*conjg(ZE44)*Cos(TW) + (0,1)*g1*ZE55*conjg(ZE45)*Cos(TW) + (0,1)*g1* &
      ZE56*conjg(ZE46)*Cos(TW) + (0,0.5_default)*g2*ZE51*conjg(ZE41)*Sin(TW) + (0, &
      0.5_default)*g2*ZE52*conjg(ZE42)*Sin(TW) + (0,0.5_default)*g2*ZE53*conjg(ZE43)*Sin(TW))
   G_a_1_se4_se6c = (0,-1)*((0,0.5_default)*g1*ZE61*conjg(ZE41)*Cos(TW) + (0, &
      0.5_default)*g1*ZE62*conjg(ZE42)*Cos(TW) + (0,0.5_default)*g1*ZE63*conjg(ZE43)*Cos(TW) + (0 &
      ,1)*g1*ZE64*conjg(ZE44)*Cos(TW) + (0,1)*g1*ZE65*conjg(ZE45)*Cos(TW) + (0,1)*g1* &
      ZE66*conjg(ZE46)*Cos(TW) + (0,0.5_default)*g2*ZE61*conjg(ZE41)*Sin(TW) + (0, &
      0.5_default)*g2*ZE62*conjg(ZE42)*Sin(TW) + (0,0.5_default)*g2*ZE63*conjg(ZE43)*Sin(TW))
   G_a_1_se5_se1c = (0,-1)*((0,0.5_default)*g1*ZE11*conjg(ZE51)*Cos(TW) + (0, &
      0.5_default)*g1*ZE12*conjg(ZE52)*Cos(TW) + (0,0.5_default)*g1*ZE13*conjg(ZE53)*Cos(TW) + (0 &
      ,1)*g1*ZE14*conjg(ZE54)*Cos(TW) + (0,1)*g1*ZE15*conjg(ZE55)*Cos(TW) + (0,1)*g1* &
      ZE16*conjg(ZE56)*Cos(TW) + (0,0.5_default)*g2*ZE11*conjg(ZE51)*Sin(TW) + (0, &
      0.5_default)*g2*ZE12*conjg(ZE52)*Sin(TW) + (0,0.5_default)*g2*ZE13*conjg(ZE53)*Sin(TW))
   G_a_1_se5_se2c = (0,-1)*((0,0.5_default)*g1*ZE21*conjg(ZE51)*Cos(TW) + (0, &
      0.5_default)*g1*ZE22*conjg(ZE52)*Cos(TW) + (0,0.5_default)*g1*ZE23*conjg(ZE53)*Cos(TW) + (0 &
      ,1)*g1*ZE24*conjg(ZE54)*Cos(TW) + (0,1)*g1*ZE25*conjg(ZE55)*Cos(TW) + (0,1)*g1* &
      ZE26*conjg(ZE56)*Cos(TW) + (0,0.5_default)*g2*ZE21*conjg(ZE51)*Sin(TW) + (0, &
      0.5_default)*g2*ZE22*conjg(ZE52)*Sin(TW) + (0,0.5_default)*g2*ZE23*conjg(ZE53)*Sin(TW))
   G_a_1_se5_se3c = (0,-1)*((0,0.5_default)*g1*ZE31*conjg(ZE51)*Cos(TW) + (0, &
      0.5_default)*g1*ZE32*conjg(ZE52)*Cos(TW) + (0,0.5_default)*g1*ZE33*conjg(ZE53)*Cos(TW) + (0 &
      ,1)*g1*ZE34*conjg(ZE54)*Cos(TW) + (0,1)*g1*ZE35*conjg(ZE55)*Cos(TW) + (0,1)*g1* &
      ZE36*conjg(ZE56)*Cos(TW) + (0,0.5_default)*g2*ZE31*conjg(ZE51)*Sin(TW) + (0, &
      0.5_default)*g2*ZE32*conjg(ZE52)*Sin(TW) + (0,0.5_default)*g2*ZE33*conjg(ZE53)*Sin(TW))
   G_a_1_se5_se4c = (0,-1)*((0,0.5_default)*g1*ZE41*conjg(ZE51)*Cos(TW) + (0, &
      0.5_default)*g1*ZE42*conjg(ZE52)*Cos(TW) + (0,0.5_default)*g1*ZE43*conjg(ZE53)*Cos(TW) + (0 &
      ,1)*g1*ZE44*conjg(ZE54)*Cos(TW) + (0,1)*g1*ZE45*conjg(ZE55)*Cos(TW) + (0,1)*g1* &
      ZE46*conjg(ZE56)*Cos(TW) + (0,0.5_default)*g2*ZE41*conjg(ZE51)*Sin(TW) + (0, &
      0.5_default)*g2*ZE42*conjg(ZE52)*Sin(TW) + (0,0.5_default)*g2*ZE43*conjg(ZE53)*Sin(TW))
   G_a_1_se5_se5c = (0,-1)*((0,0.5_default)*g1*ZE51*conjg(ZE51)*Cos(TW) + (0, &
      0.5_default)*g1*ZE52*conjg(ZE52)*Cos(TW) + (0,0.5_default)*g1*ZE53*conjg(ZE53)*Cos(TW) + (0 &
      ,1)*g1*ZE54*conjg(ZE54)*Cos(TW) + (0,1)*g1*ZE55*conjg(ZE55)*Cos(TW) + (0,1)*g1* &
      ZE56*conjg(ZE56)*Cos(TW) + (0,0.5_default)*g2*ZE51*conjg(ZE51)*Sin(TW) + (0, &
      0.5_default)*g2*ZE52*conjg(ZE52)*Sin(TW) + (0,0.5_default)*g2*ZE53*conjg(ZE53)*Sin(TW))
   G_a_1_se5_se6c = (0,-1)*((0,0.5_default)*g1*ZE61*conjg(ZE51)*Cos(TW) + (0, &
      0.5_default)*g1*ZE62*conjg(ZE52)*Cos(TW) + (0,0.5_default)*g1*ZE63*conjg(ZE53)*Cos(TW) + (0 &
      ,1)*g1*ZE64*conjg(ZE54)*Cos(TW) + (0,1)*g1*ZE65*conjg(ZE55)*Cos(TW) + (0,1)*g1* &
      ZE66*conjg(ZE56)*Cos(TW) + (0,0.5_default)*g2*ZE61*conjg(ZE51)*Sin(TW) + (0, &
      0.5_default)*g2*ZE62*conjg(ZE52)*Sin(TW) + (0,0.5_default)*g2*ZE63*conjg(ZE53)*Sin(TW))
   G_a_1_se6_se1c = (0,-1)*((0,0.5_default)*g1*ZE11*conjg(ZE61)*Cos(TW) + (0, &
      0.5_default)*g1*ZE12*conjg(ZE62)*Cos(TW) + (0,0.5_default)*g1*ZE13*conjg(ZE63)*Cos(TW) + (0 &
      ,1)*g1*ZE14*conjg(ZE64)*Cos(TW) + (0,1)*g1*ZE15*conjg(ZE65)*Cos(TW) + (0,1)*g1* &
      ZE16*conjg(ZE66)*Cos(TW) + (0,0.5_default)*g2*ZE11*conjg(ZE61)*Sin(TW) + (0, &
      0.5_default)*g2*ZE12*conjg(ZE62)*Sin(TW) + (0,0.5_default)*g2*ZE13*conjg(ZE63)*Sin(TW))
   G_a_1_se6_se2c = (0,-1)*((0,0.5_default)*g1*ZE21*conjg(ZE61)*Cos(TW) + (0, &
      0.5_default)*g1*ZE22*conjg(ZE62)*Cos(TW) + (0,0.5_default)*g1*ZE23*conjg(ZE63)*Cos(TW) + (0 &
      ,1)*g1*ZE24*conjg(ZE64)*Cos(TW) + (0,1)*g1*ZE25*conjg(ZE65)*Cos(TW) + (0,1)*g1* &
      ZE26*conjg(ZE66)*Cos(TW) + (0,0.5_default)*g2*ZE21*conjg(ZE61)*Sin(TW) + (0, &
      0.5_default)*g2*ZE22*conjg(ZE62)*Sin(TW) + (0,0.5_default)*g2*ZE23*conjg(ZE63)*Sin(TW))
   G_a_1_se6_se3c = (0,-1)*((0,0.5_default)*g1*ZE31*conjg(ZE61)*Cos(TW) + (0, &
      0.5_default)*g1*ZE32*conjg(ZE62)*Cos(TW) + (0,0.5_default)*g1*ZE33*conjg(ZE63)*Cos(TW) + (0 &
      ,1)*g1*ZE34*conjg(ZE64)*Cos(TW) + (0,1)*g1*ZE35*conjg(ZE65)*Cos(TW) + (0,1)*g1* &
      ZE36*conjg(ZE66)*Cos(TW) + (0,0.5_default)*g2*ZE31*conjg(ZE61)*Sin(TW) + (0, &
      0.5_default)*g2*ZE32*conjg(ZE62)*Sin(TW) + (0,0.5_default)*g2*ZE33*conjg(ZE63)*Sin(TW))
   G_a_1_se6_se4c = (0,-1)*((0,0.5_default)*g1*ZE41*conjg(ZE61)*Cos(TW) + (0, &
      0.5_default)*g1*ZE42*conjg(ZE62)*Cos(TW) + (0,0.5_default)*g1*ZE43*conjg(ZE63)*Cos(TW) + (0 &
      ,1)*g1*ZE44*conjg(ZE64)*Cos(TW) + (0,1)*g1*ZE45*conjg(ZE65)*Cos(TW) + (0,1)*g1* &
      ZE46*conjg(ZE66)*Cos(TW) + (0,0.5_default)*g2*ZE41*conjg(ZE61)*Sin(TW) + (0, &
      0.5_default)*g2*ZE42*conjg(ZE62)*Sin(TW) + (0,0.5_default)*g2*ZE43*conjg(ZE63)*Sin(TW))
   G_a_1_se6_se5c = (0,-1)*((0,0.5_default)*g1*ZE51*conjg(ZE61)*Cos(TW) + (0, &
      0.5_default)*g1*ZE52*conjg(ZE62)*Cos(TW) + (0,0.5_default)*g1*ZE53*conjg(ZE63)*Cos(TW) + (0 &
      ,1)*g1*ZE54*conjg(ZE64)*Cos(TW) + (0,1)*g1*ZE55*conjg(ZE65)*Cos(TW) + (0,1)*g1* &
      ZE56*conjg(ZE66)*Cos(TW) + (0,0.5_default)*g2*ZE51*conjg(ZE61)*Sin(TW) + (0, &
      0.5_default)*g2*ZE52*conjg(ZE62)*Sin(TW) + (0,0.5_default)*g2*ZE53*conjg(ZE63)*Sin(TW))
   G_a_1_se6_se6c = (0,-1)*((0,0.5_default)*g1*ZE61*conjg(ZE61)*Cos(TW) + (0, &
      0.5_default)*g1*ZE62*conjg(ZE62)*Cos(TW) + (0,0.5_default)*g1*ZE63*conjg(ZE63)*Cos(TW) + (0 &
      ,1)*g1*ZE64*conjg(ZE64)*Cos(TW) + (0,1)*g1*ZE65*conjg(ZE65)*Cos(TW) + (0,1)*g1* &
      ZE66*conjg(ZE66)*Cos(TW) + (0,0.5_default)*g2*ZE61*conjg(ZE61)*Sin(TW) + (0, &
      0.5_default)*g2*ZE62*conjg(ZE62)*Sin(TW) + (0,0.5_default)*g2*ZE63*conjg(ZE63)*Sin(TW))
   G_z_1_se1_se1c = (0,-1)*((0,0.5_default)*g2*ZE11*conjg(ZE11)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZE12*conjg(ZE12)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZE13* &
      conjg(ZE13)*Cos(TW)*Cos(TWp) - (0,0.5_default)*g1*ZE11*conjg(ZE11)*Cos(TWp)*Sin(TW &
      ) - (0,0.5_default)*g1*ZE12*conjg(ZE12)*Cos(TWp)*Sin(TW) - (0,0.5_default)*g1*ZE13* &
      conjg(ZE13)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE14*conjg(ZE14)*Cos(TWp)*Sin(TW) - (0,1)*g1* &
      ZE15*conjg(ZE15)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE16*conjg(ZE16)*Cos(TWp)*Sin(TW) - (0, &
      1)*gp*Ql1*ZE11*conjg(ZE11)*Sin(TWp) - (0,1)*gp*Ql2*ZE12*conjg(ZE12)*Sin(TWp) - (0 &
      ,1)*gp*Ql3*ZE13*conjg(ZE13)*Sin(TWp) + (0,1)*gp*Qe1*ZE14*conjg(ZE14)*Sin(TWp) + ( &
      0,1)*gp*Qe2*ZE15*conjg(ZE15)*Sin(TWp) + (0,1)*gp*Qe3*ZE16*conjg(ZE16)*Sin(TWp))
   G_z_1_se1_se2c = (0,-1)*((0,0.5_default)*g2*ZE21*conjg(ZE11)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZE22*conjg(ZE12)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZE23* &
      conjg(ZE13)*Cos(TW)*Cos(TWp) - (0,0.5_default)*g1*ZE21*conjg(ZE11)*Cos(TWp)*Sin(TW &
      ) - (0,0.5_default)*g1*ZE22*conjg(ZE12)*Cos(TWp)*Sin(TW) - (0,0.5_default)*g1*ZE23* &
      conjg(ZE13)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE24*conjg(ZE14)*Cos(TWp)*Sin(TW) - (0,1)*g1* &
      ZE25*conjg(ZE15)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE26*conjg(ZE16)*Cos(TWp)*Sin(TW) - (0, &
      1)*gp*Ql1*ZE21*conjg(ZE11)*Sin(TWp) - (0,1)*gp*Ql2*ZE22*conjg(ZE12)*Sin(TWp) - (0 &
      ,1)*gp*Ql3*ZE23*conjg(ZE13)*Sin(TWp) + (0,1)*gp*Qe1*ZE24*conjg(ZE14)*Sin(TWp) + ( &
      0,1)*gp*Qe2*ZE25*conjg(ZE15)*Sin(TWp) + (0,1)*gp*Qe3*ZE26*conjg(ZE16)*Sin(TWp))
   G_z_1_se1_se3c = (0,-1)*((0,0.5_default)*g2*ZE31*conjg(ZE11)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZE32*conjg(ZE12)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZE33* &
      conjg(ZE13)*Cos(TW)*Cos(TWp) - (0,0.5_default)*g1*ZE31*conjg(ZE11)*Cos(TWp)*Sin(TW &
      ) - (0,0.5_default)*g1*ZE32*conjg(ZE12)*Cos(TWp)*Sin(TW) - (0,0.5_default)*g1*ZE33* &
      conjg(ZE13)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE34*conjg(ZE14)*Cos(TWp)*Sin(TW) - (0,1)*g1* &
      ZE35*conjg(ZE15)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE36*conjg(ZE16)*Cos(TWp)*Sin(TW) - (0, &
      1)*gp*Ql1*ZE31*conjg(ZE11)*Sin(TWp) - (0,1)*gp*Ql2*ZE32*conjg(ZE12)*Sin(TWp) - (0 &
      ,1)*gp*Ql3*ZE33*conjg(ZE13)*Sin(TWp) + (0,1)*gp*Qe1*ZE34*conjg(ZE14)*Sin(TWp) + ( &
      0,1)*gp*Qe2*ZE35*conjg(ZE15)*Sin(TWp) + (0,1)*gp*Qe3*ZE36*conjg(ZE16)*Sin(TWp))
   G_z_1_se1_se4c = (0,-1)*((0,0.5_default)*g2*ZE41*conjg(ZE11)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZE42*conjg(ZE12)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZE43* &
      conjg(ZE13)*Cos(TW)*Cos(TWp) - (0,0.5_default)*g1*ZE41*conjg(ZE11)*Cos(TWp)*Sin(TW &
      ) - (0,0.5_default)*g1*ZE42*conjg(ZE12)*Cos(TWp)*Sin(TW) - (0,0.5_default)*g1*ZE43* &
      conjg(ZE13)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE44*conjg(ZE14)*Cos(TWp)*Sin(TW) - (0,1)*g1* &
      ZE45*conjg(ZE15)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE46*conjg(ZE16)*Cos(TWp)*Sin(TW) - (0, &
      1)*gp*Ql1*ZE41*conjg(ZE11)*Sin(TWp) - (0,1)*gp*Ql2*ZE42*conjg(ZE12)*Sin(TWp) - (0 &
      ,1)*gp*Ql3*ZE43*conjg(ZE13)*Sin(TWp) + (0,1)*gp*Qe1*ZE44*conjg(ZE14)*Sin(TWp) + ( &
      0,1)*gp*Qe2*ZE45*conjg(ZE15)*Sin(TWp) + (0,1)*gp*Qe3*ZE46*conjg(ZE16)*Sin(TWp))
   G_z_1_se1_se5c = (0,-1)*((0,0.5_default)*g2*ZE51*conjg(ZE11)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZE52*conjg(ZE12)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZE53* &
      conjg(ZE13)*Cos(TW)*Cos(TWp) - (0,0.5_default)*g1*ZE51*conjg(ZE11)*Cos(TWp)*Sin(TW &
      ) - (0,0.5_default)*g1*ZE52*conjg(ZE12)*Cos(TWp)*Sin(TW) - (0,0.5_default)*g1*ZE53* &
      conjg(ZE13)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE54*conjg(ZE14)*Cos(TWp)*Sin(TW) - (0,1)*g1* &
      ZE55*conjg(ZE15)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE56*conjg(ZE16)*Cos(TWp)*Sin(TW) - (0, &
      1)*gp*Ql1*ZE51*conjg(ZE11)*Sin(TWp) - (0,1)*gp*Ql2*ZE52*conjg(ZE12)*Sin(TWp) - (0 &
      ,1)*gp*Ql3*ZE53*conjg(ZE13)*Sin(TWp) + (0,1)*gp*Qe1*ZE54*conjg(ZE14)*Sin(TWp) + ( &
      0,1)*gp*Qe2*ZE55*conjg(ZE15)*Sin(TWp) + (0,1)*gp*Qe3*ZE56*conjg(ZE16)*Sin(TWp))
   G_z_1_se1_se6c = (0,-1)*((0,0.5_default)*g2*ZE61*conjg(ZE11)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZE62*conjg(ZE12)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZE63* &
      conjg(ZE13)*Cos(TW)*Cos(TWp) - (0,0.5_default)*g1*ZE61*conjg(ZE11)*Cos(TWp)*Sin(TW &
      ) - (0,0.5_default)*g1*ZE62*conjg(ZE12)*Cos(TWp)*Sin(TW) - (0,0.5_default)*g1*ZE63* &
      conjg(ZE13)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE64*conjg(ZE14)*Cos(TWp)*Sin(TW) - (0,1)*g1* &
      ZE65*conjg(ZE15)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE66*conjg(ZE16)*Cos(TWp)*Sin(TW) - (0, &
      1)*gp*Ql1*ZE61*conjg(ZE11)*Sin(TWp) - (0,1)*gp*Ql2*ZE62*conjg(ZE12)*Sin(TWp) - (0 &
      ,1)*gp*Ql3*ZE63*conjg(ZE13)*Sin(TWp) + (0,1)*gp*Qe1*ZE64*conjg(ZE14)*Sin(TWp) + ( &
      0,1)*gp*Qe2*ZE65*conjg(ZE15)*Sin(TWp) + (0,1)*gp*Qe3*ZE66*conjg(ZE16)*Sin(TWp))
   G_z_1_se2_se1c = (0,-1)*((0,0.5_default)*g2*ZE11*conjg(ZE21)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZE12*conjg(ZE22)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZE13* &
      conjg(ZE23)*Cos(TW)*Cos(TWp) - (0,0.5_default)*g1*ZE11*conjg(ZE21)*Cos(TWp)*Sin(TW &
      ) - (0,0.5_default)*g1*ZE12*conjg(ZE22)*Cos(TWp)*Sin(TW) - (0,0.5_default)*g1*ZE13* &
      conjg(ZE23)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE14*conjg(ZE24)*Cos(TWp)*Sin(TW) - (0,1)*g1* &
      ZE15*conjg(ZE25)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE16*conjg(ZE26)*Cos(TWp)*Sin(TW) - (0, &
      1)*gp*Ql1*ZE11*conjg(ZE21)*Sin(TWp) - (0,1)*gp*Ql2*ZE12*conjg(ZE22)*Sin(TWp) - (0 &
      ,1)*gp*Ql3*ZE13*conjg(ZE23)*Sin(TWp) + (0,1)*gp*Qe1*ZE14*conjg(ZE24)*Sin(TWp) + ( &
      0,1)*gp*Qe2*ZE15*conjg(ZE25)*Sin(TWp) + (0,1)*gp*Qe3*ZE16*conjg(ZE26)*Sin(TWp))
   G_z_1_se2_se2c = (0,-1)*((0,0.5_default)*g2*ZE21*conjg(ZE21)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZE22*conjg(ZE22)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZE23* &
      conjg(ZE23)*Cos(TW)*Cos(TWp) - (0,0.5_default)*g1*ZE21*conjg(ZE21)*Cos(TWp)*Sin(TW &
      ) - (0,0.5_default)*g1*ZE22*conjg(ZE22)*Cos(TWp)*Sin(TW) - (0,0.5_default)*g1*ZE23* &
      conjg(ZE23)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE24*conjg(ZE24)*Cos(TWp)*Sin(TW) - (0,1)*g1* &
      ZE25*conjg(ZE25)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE26*conjg(ZE26)*Cos(TWp)*Sin(TW) - (0, &
      1)*gp*Ql1*ZE21*conjg(ZE21)*Sin(TWp) - (0,1)*gp*Ql2*ZE22*conjg(ZE22)*Sin(TWp) - (0 &
      ,1)*gp*Ql3*ZE23*conjg(ZE23)*Sin(TWp) + (0,1)*gp*Qe1*ZE24*conjg(ZE24)*Sin(TWp) + ( &
      0,1)*gp*Qe2*ZE25*conjg(ZE25)*Sin(TWp) + (0,1)*gp*Qe3*ZE26*conjg(ZE26)*Sin(TWp))
   G_z_1_se2_se3c = (0,-1)*((0,0.5_default)*g2*ZE31*conjg(ZE21)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZE32*conjg(ZE22)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZE33* &
      conjg(ZE23)*Cos(TW)*Cos(TWp) - (0,0.5_default)*g1*ZE31*conjg(ZE21)*Cos(TWp)*Sin(TW &
      ) - (0,0.5_default)*g1*ZE32*conjg(ZE22)*Cos(TWp)*Sin(TW) - (0,0.5_default)*g1*ZE33* &
      conjg(ZE23)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE34*conjg(ZE24)*Cos(TWp)*Sin(TW) - (0,1)*g1* &
      ZE35*conjg(ZE25)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE36*conjg(ZE26)*Cos(TWp)*Sin(TW) - (0, &
      1)*gp*Ql1*ZE31*conjg(ZE21)*Sin(TWp) - (0,1)*gp*Ql2*ZE32*conjg(ZE22)*Sin(TWp) - (0 &
      ,1)*gp*Ql3*ZE33*conjg(ZE23)*Sin(TWp) + (0,1)*gp*Qe1*ZE34*conjg(ZE24)*Sin(TWp) + ( &
      0,1)*gp*Qe2*ZE35*conjg(ZE25)*Sin(TWp) + (0,1)*gp*Qe3*ZE36*conjg(ZE26)*Sin(TWp))
   G_z_1_se2_se4c = (0,-1)*((0,0.5_default)*g2*ZE41*conjg(ZE21)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZE42*conjg(ZE22)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZE43* &
      conjg(ZE23)*Cos(TW)*Cos(TWp) - (0,0.5_default)*g1*ZE41*conjg(ZE21)*Cos(TWp)*Sin(TW &
      ) - (0,0.5_default)*g1*ZE42*conjg(ZE22)*Cos(TWp)*Sin(TW) - (0,0.5_default)*g1*ZE43* &
      conjg(ZE23)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE44*conjg(ZE24)*Cos(TWp)*Sin(TW) - (0,1)*g1* &
      ZE45*conjg(ZE25)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE46*conjg(ZE26)*Cos(TWp)*Sin(TW) - (0, &
      1)*gp*Ql1*ZE41*conjg(ZE21)*Sin(TWp) - (0,1)*gp*Ql2*ZE42*conjg(ZE22)*Sin(TWp) - (0 &
      ,1)*gp*Ql3*ZE43*conjg(ZE23)*Sin(TWp) + (0,1)*gp*Qe1*ZE44*conjg(ZE24)*Sin(TWp) + ( &
      0,1)*gp*Qe2*ZE45*conjg(ZE25)*Sin(TWp) + (0,1)*gp*Qe3*ZE46*conjg(ZE26)*Sin(TWp))
   G_z_1_se2_se5c = (0,-1)*((0,0.5_default)*g2*ZE51*conjg(ZE21)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZE52*conjg(ZE22)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZE53* &
      conjg(ZE23)*Cos(TW)*Cos(TWp) - (0,0.5_default)*g1*ZE51*conjg(ZE21)*Cos(TWp)*Sin(TW &
      ) - (0,0.5_default)*g1*ZE52*conjg(ZE22)*Cos(TWp)*Sin(TW) - (0,0.5_default)*g1*ZE53* &
      conjg(ZE23)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE54*conjg(ZE24)*Cos(TWp)*Sin(TW) - (0,1)*g1* &
      ZE55*conjg(ZE25)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE56*conjg(ZE26)*Cos(TWp)*Sin(TW) - (0, &
      1)*gp*Ql1*ZE51*conjg(ZE21)*Sin(TWp) - (0,1)*gp*Ql2*ZE52*conjg(ZE22)*Sin(TWp) - (0 &
      ,1)*gp*Ql3*ZE53*conjg(ZE23)*Sin(TWp) + (0,1)*gp*Qe1*ZE54*conjg(ZE24)*Sin(TWp) + ( &
      0,1)*gp*Qe2*ZE55*conjg(ZE25)*Sin(TWp) + (0,1)*gp*Qe3*ZE56*conjg(ZE26)*Sin(TWp))
   G_z_1_se2_se6c = (0,-1)*((0,0.5_default)*g2*ZE61*conjg(ZE21)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZE62*conjg(ZE22)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZE63* &
      conjg(ZE23)*Cos(TW)*Cos(TWp) - (0,0.5_default)*g1*ZE61*conjg(ZE21)*Cos(TWp)*Sin(TW &
      ) - (0,0.5_default)*g1*ZE62*conjg(ZE22)*Cos(TWp)*Sin(TW) - (0,0.5_default)*g1*ZE63* &
      conjg(ZE23)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE64*conjg(ZE24)*Cos(TWp)*Sin(TW) - (0,1)*g1* &
      ZE65*conjg(ZE25)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE66*conjg(ZE26)*Cos(TWp)*Sin(TW) - (0, &
      1)*gp*Ql1*ZE61*conjg(ZE21)*Sin(TWp) - (0,1)*gp*Ql2*ZE62*conjg(ZE22)*Sin(TWp) - (0 &
      ,1)*gp*Ql3*ZE63*conjg(ZE23)*Sin(TWp) + (0,1)*gp*Qe1*ZE64*conjg(ZE24)*Sin(TWp) + ( &
      0,1)*gp*Qe2*ZE65*conjg(ZE25)*Sin(TWp) + (0,1)*gp*Qe3*ZE66*conjg(ZE26)*Sin(TWp))
   G_z_1_se3_se1c = (0,-1)*((0,0.5_default)*g2*ZE11*conjg(ZE31)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZE12*conjg(ZE32)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZE13* &
      conjg(ZE33)*Cos(TW)*Cos(TWp) - (0,0.5_default)*g1*ZE11*conjg(ZE31)*Cos(TWp)*Sin(TW &
      ) - (0,0.5_default)*g1*ZE12*conjg(ZE32)*Cos(TWp)*Sin(TW) - (0,0.5_default)*g1*ZE13* &
      conjg(ZE33)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE14*conjg(ZE34)*Cos(TWp)*Sin(TW) - (0,1)*g1* &
      ZE15*conjg(ZE35)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE16*conjg(ZE36)*Cos(TWp)*Sin(TW) - (0, &
      1)*gp*Ql1*ZE11*conjg(ZE31)*Sin(TWp) - (0,1)*gp*Ql2*ZE12*conjg(ZE32)*Sin(TWp) - (0 &
      ,1)*gp*Ql3*ZE13*conjg(ZE33)*Sin(TWp) + (0,1)*gp*Qe1*ZE14*conjg(ZE34)*Sin(TWp) + ( &
      0,1)*gp*Qe2*ZE15*conjg(ZE35)*Sin(TWp) + (0,1)*gp*Qe3*ZE16*conjg(ZE36)*Sin(TWp))
   G_z_1_se3_se2c = (0,-1)*((0,0.5_default)*g2*ZE21*conjg(ZE31)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZE22*conjg(ZE32)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZE23* &
      conjg(ZE33)*Cos(TW)*Cos(TWp) - (0,0.5_default)*g1*ZE21*conjg(ZE31)*Cos(TWp)*Sin(TW &
      ) - (0,0.5_default)*g1*ZE22*conjg(ZE32)*Cos(TWp)*Sin(TW) - (0,0.5_default)*g1*ZE23* &
      conjg(ZE33)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE24*conjg(ZE34)*Cos(TWp)*Sin(TW) - (0,1)*g1* &
      ZE25*conjg(ZE35)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE26*conjg(ZE36)*Cos(TWp)*Sin(TW) - (0, &
      1)*gp*Ql1*ZE21*conjg(ZE31)*Sin(TWp) - (0,1)*gp*Ql2*ZE22*conjg(ZE32)*Sin(TWp) - (0 &
      ,1)*gp*Ql3*ZE23*conjg(ZE33)*Sin(TWp) + (0,1)*gp*Qe1*ZE24*conjg(ZE34)*Sin(TWp) + ( &
      0,1)*gp*Qe2*ZE25*conjg(ZE35)*Sin(TWp) + (0,1)*gp*Qe3*ZE26*conjg(ZE36)*Sin(TWp))
   G_z_1_se3_se3c = (0,-1)*((0,0.5_default)*g2*ZE31*conjg(ZE31)*Cos(TW)*Cos(TWp &
      ) + (0,0.5_default)*g2*ZE32*conjg(ZE32)*Cos(TW)*Cos(TWp) + (0,0.5_default)*g2*ZE33* &
      conjg(ZE33)*Cos(TW)*Cos(TWp) - (0,0.5_default)*g1*ZE31*conjg(ZE31)*Cos(TWp)*Sin(TW &
      ) - (0,0.5_default)*g1*ZE32*conjg(ZE32)*Cos(TWp)*Sin(TW) - (0,0.5_default)*g1*ZE33* &
      conjg(ZE33)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE34*conjg(ZE34)*Cos(TWp)*Sin(TW) - (0,1)*g1* &
      ZE35*conjg(ZE35)*Cos(TWp)*Sin(TW) - (0,1)*g1*ZE36*conjg(ZE36)*Cos(TWp)*Sin(TW) - (0, &
      1)*gp*Ql1*ZE31*conjg(ZE31)*Sin(TWp) - (0,1)*gp*Ql2*ZE32*conjg(ZE32)*Sin(TWp) - (0 &
      ,1)*gp*Ql3*ZE33*conjg(ZE33)*Sin(TWp) + (0,1)*gp*Qe1*ZE34*conjg(ZE34)*Sin(TWp) + ( &
      0,1)*gp*Qe2*ZE35*conjg(ZE35)*Sin(TWp) + (0,1)*gp*Qe3*ZE36*conjg(ZE36)*Sin(TWp))
end subroutine calc_cpl15

end module parameters_nonumssm_sarah_cpl15