! --------------------------------------------------------------------------------
! Autogenerated by the happy scrappy WHIZARD model file generator on 2/10/2021 , 0:41:44
! WHIZARD interface svn revision info: $Id: WOMathematicaInterface.m 3666 2012-01-14 17:03:09Z cnspeckn $
! Code generated for WHIZARD / O'Mega version 2.4.0
! Model name: nonumssm_sarah
! Gauge: Unitarity
! Maximum number of couplings per FORTRAN module: 150
! --------------------------------------------------------------------------------
! 
! --------------------------------------------------------------------------------

module parameters_nonumssm_sarah_cpl28
use parameters_nonumssm_sarah_global
use parameters_nonumssm_sarah_local
implicit none

contains

subroutine calc_cpl28
end subroutine calc_cpl28

end module parameters_nonumssm_sarah_cpl28