#!/bin/bash
#SBATCH --time=12:00:00          # walltime
#SBATCH --mem-per-cpu=40000

module load python/2.7.14
module load numpy/1.16.4
module load pandas/0.22.0
module load scipy/1.0.0

python run_Micromegas.py
#python runMicroForXSEC.py
